using Uno.UI.SourceGenerators.Mixins;

namespace Uno.UI.SourceGenerators.Tests.MixinGeneratorTests;

[TestClass]
public class Given_MixinGenerators
{
	[TestMethod]
	public void DependencyPropertyMixin_ContainsExpectedClasses()
	{
		var output = DependencyPropertyMixinGenerator.Generate();

		output.Should().Contain("#if UNO_MIXIN_GENERATION");
		output.Should().Contain("#endif // UNO_MIXIN_GENERATION");
		output.Should().Contain("partial class Control");
		output.Should().Contain("partial class Popup");
		output.Should().Contain("partial class SelectorItem");
		output.Should().Contain("partial class ComboBox");
		output.Should().Contain("partial class ListViewBase");
	}

	[TestMethod]
	public void DependencyPropertyMixin_ContainsExpectedProperties()
	{
		var output = DependencyPropertyMixinGenerator.Generate();

		output.Should().Contain("BackgroundSizingProperty");
		output.Should().Contain("HorizontalContentAlignmentProperty");
		output.Should().Contain("VerticalContentAlignmentProperty");
		output.Should().Contain("IsOpenProperty");
		output.Should().Contain("IsSelectedProperty");
		output.Should().Contain("PlaceholderTextProperty");
	}

	[TestMethod]
	public void DependencyPropertyMixin_ContainsNamespaces()
	{
		var output = DependencyPropertyMixinGenerator.Generate();

		output.Should().Contain("namespace Microsoft.UI.Xaml.Controls");
		output.Should().Contain("namespace Microsoft.UI.Xaml.Controls.Primitives");
		output.Should().Contain("namespace Uno.UI.Controls.Legacy");
	}

	[TestMethod]
	public void DependencyPropertyMixin_HeaderInsideMixinGuard()
	{
		var output = DependencyPropertyMixinGenerator.Generate();

		var ifIndex = output.IndexOf("#if UNO_MIXIN_GENERATION");
		var headerIndex = output.IndexOf("// <auto-generated>");

		ifIndex.Should().BeGreaterThanOrEqualTo(0);
		headerIndex.Should().BeGreaterThan(ifIndex, "Header should be inside #if UNO_MIXIN_GENERATION block");
	}

	[TestMethod]
	public void DependencyPropertyMixin_GeneratesPropertyChangedCallbacks()
	{
		var output = DependencyPropertyMixinGenerator.Generate();

		output.Should().Contain("OnBackgroundSizingChanged");
		output.Should().Contain("OnBackgroundSizingChangedPartial");
		output.Should().Contain("OnBackgroundSizingChangedPartialNative");
	}

	[TestMethod]
	public void DependencyPropertyMixin_GeneratesFrameworkPropertyMetadata()
	{
		var output = DependencyPropertyMixinGenerator.Generate();

		output.Should().Contain("new FrameworkPropertyMetadata(");
		output.Should().Contain("FrameworkPropertyMetadataOptions.AffectsArrange");
		output.Should().Contain("FrameworkPropertyMetadataOptions.ValueDoesNotInheritDataContext");
	}

	[TestMethod]
	public void AndroidMixin_ContainsExpectedContent()
	{
		var output = FrameworkElementAndroidMixinGenerator.GenerateFrameworkElementMixins();

		output.Should().Contain("#if UNO_MIXIN_GENERATION && __ANDROID__");
		output.Should().Contain("partial class FrameworkElement");
		output.Should().Contain("IFrameworkElement");
	}

	[TestMethod]
	public void UIKitMixin_ContainsExpectedContent()
	{
		var output = FrameworkElementUIKitMixinGenerator.GenerateFrameworkElementMixins();

		output.Should().Contain("#if UNO_MIXIN_GENERATION && __APPLE_UIKIT__");
		output.Should().Contain("partial class FrameworkElement");
		output.Should().Contain("IFrameworkElement");
	}

	[TestMethod]
	public void BaseActivityCallbacks_ContainsExpectedContent()
	{
		var output = BaseActivityCallbacksGenerator.Generate();

		output.Should().Contain("#if UNO_MIXIN_GENERATION && __ANDROID__");
		output.Should().Contain("partial class BaseActivity");
		output.Should().Contain("IBaseActivityEvents");
		output.Should().Contain("EventHandler");
	}

	[TestMethod]
	public void BaseActivityCallbacks_GeneratesOverrideMethods()
	{
		var output = BaseActivityCallbacksGenerator.Generate();

		output.Should().Contain("override void OnCreate");
		output.Should().Contain("override void OnResume");
		output.Should().Contain("override void OnPause");
		output.Should().Contain("override void OnDestroy");
	}
}
