// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.

// DO NOT EDIT! This file was generated by CustomTasks.DependencyPropertyCodeGen

// Imported in uno on 2021/03/21 from commit 307bd99682cccaa128483036b764c0b7c862d666
// https://github.com/microsoft/microsoft-ui-xaml/blob/307bd99682cccaa128483036b764c0b7c862d666/dev/Generated/SwipeControl.properties.cpp

namespace Microsoft.UI.Xaml.Controls
{
	public partial class SwipeControl
	{
		//public:

		//SwipeControlProperties();

		//void BottomItems(winrt.SwipeItems & value);

		//winrt.SwipeItems BottomItems();

		//void LeftItems(winrt.SwipeItems & value);

		//winrt.SwipeItems LeftItems();

		//void RightItems(winrt.SwipeItems & value);

		//winrt.SwipeItems RightItems();

		//void TopItems(winrt.SwipeItems & value);

		//winrt.SwipeItems TopItems();

		//static winrt.DependencyProperty BottomItemsProperty() { return s_BottomItemsProperty; }

		//static winrt.DependencyProperty LeftItemsProperty() { return s_LeftItemsProperty; }

		//static winrt.DependencyProperty RightItemsProperty() { return s_RightItemsProperty; }

		//static winrt.DependencyProperty TopItemsProperty() { return s_TopItemsProperty; }

		//static GlobalDependencyProperty s_BottomItemsProperty;
		//static GlobalDependencyProperty s_LeftItemsProperty;
		//static GlobalDependencyProperty s_RightItemsProperty;
		//static GlobalDependencyProperty s_TopItemsProperty;

		//static void EnsureProperties();

		//static void ClearProperties();

		//static void OnBottomItemsPropertyChanged(
		//	winrt.DependencyObject & sender,

		//winrt.DependencyPropertyChangedEventArgs & args);

		//static void OnLeftItemsPropertyChanged(
		//	winrt.DependencyObject & sender,

		//winrt.DependencyPropertyChangedEventArgs & args);

		//static void OnRightItemsPropertyChanged(
		//	winrt.DependencyObject & sender,

		//winrt.DependencyPropertyChangedEventArgs & args);

		//static void OnTopItemsPropertyChanged(
		//	winrt.DependencyObject & sender,

		//winrt.DependencyPropertyChangedEventArgs & args);
	}
}
