// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.

// DO NOT EDIT! This file was generated by CustomTasks.DependencyPropertyCodeGen

// Imported in uno on 2021/03/21 from commit 307bd99682cccaa128483036b764c0b7c862d666
// https://github.com/microsoft/microsoft-ui-xaml/blob/307bd99682cccaa128483036b764c0b7c862d666/dev/Generated/SwipeItem.properties.h

using Windows.Foundation;

namespace Microsoft.UI.Xaml.Controls
{
	public partial class SwipeItem
	{
		//public:

		//SwipeItemProperties();

		//void Background(winrt.Brush & value);

		//winrt.Brush Background();

		//void BehaviorOnInvoked(winrt.SwipeBehaviorOnInvoked & value);

		//winrt.SwipeBehaviorOnInvoked BehaviorOnInvoked();

		//void Command(winrt.ICommand & value);

		//winrt.ICommand Command();

		//void CommandParameter(winrt.DependencyObject & value);

		//winrt.DependencyObject CommandParameter();

		//void Foreground(winrt.Brush & value);

		//winrt.Brush Foreground();

		//void IconSource(winrt.IconSource & value);

		//winrt.IconSource IconSource();

		//void Text(winrt.string & value);
		//winrt.string Text();

		//static winrt.DependencyProperty BackgroundProperty() { return s_BackgroundProperty; }

		//static winrt.DependencyProperty BehaviorOnInvokedProperty() { return s_BehaviorOnInvokedProperty; }

		//static winrt.DependencyProperty CommandProperty() { return s_CommandProperty; }

		//static winrt.DependencyProperty CommandParameterProperty() { return s_CommandParameterProperty; }

		//static winrt.DependencyProperty ForegroundProperty() { return s_ForegroundProperty; }

		//static winrt.DependencyProperty IconSourceProperty() { return s_IconSourceProperty; }

		//static winrt.DependencyProperty TextProperty() { return s_TextProperty; }

		//static GlobalDependencyProperty s_BackgroundProperty;
		//static GlobalDependencyProperty s_BehaviorOnInvokedProperty;
		//static GlobalDependencyProperty s_CommandProperty;
		//static GlobalDependencyProperty s_CommandParameterProperty;
		//static GlobalDependencyProperty s_ForegroundProperty;
		//static GlobalDependencyProperty s_IconSourceProperty;
		//static GlobalDependencyProperty s_TextProperty;

		//winrt.event_token Invoked(winrt.TypedEventHandler<winrt.SwipeItem, winrt.SwipeItemInvokedEventArgs> & value);

		//void Invoked(winrt.event_token & token);

		private event TypedEventHandler<SwipeItem, SwipeItemInvokedEventArgs> m_invokedEventSource;

		//static void EnsureProperties();

		//static void ClearProperties();

		//static void OnBackgroundPropertyChanged(
		//	winrt.DependencyObject & sender,

		//winrt.DependencyPropertyChangedEventArgs & args);

		//static void OnBehaviorOnInvokedPropertyChanged(
		//	winrt.DependencyObject & sender,

		//winrt.DependencyPropertyChangedEventArgs & args);

		//static void OnCommandPropertyChanged(
		//	winrt.DependencyObject & sender,

		//winrt.DependencyPropertyChangedEventArgs & args);

		//static void OnCommandParameterPropertyChanged(
		//	winrt.DependencyObject & sender,

		//winrt.DependencyPropertyChangedEventArgs & args);

		//static void OnForegroundPropertyChanged(
		//	winrt.DependencyObject & sender,

		//winrt.DependencyPropertyChangedEventArgs & args);

		//static void OnIconSourcePropertyChanged(
		//	winrt.DependencyObject & sender,

		//winrt.DependencyPropertyChangedEventArgs & args);

		//static void OnTextPropertyChanged(
		//	winrt.DependencyObject & sender,

		//winrt.DependencyPropertyChangedEventArgs & args);
	};
}
