using System;
using System.Collections.Generic;

namespace Windows.UI.Shell.Tasks;

/// <summary>
/// Represents the task content shown in the UI that is displayed on hover
/// over the app's taskbar icon.
/// </summary>
public sealed class AppTaskContent
{
	private readonly List<(string Text, Uri ActionUri)> _buttons = new();
	private string _question;
	private string _textInputPlaceholder;
	private string _textInputActionUriTemplate;

	internal AppTaskContentKind Kind { get; private set; }
	internal string[] CompletedSteps { get; private set; }
	internal string ExecutingStep { get; private set; }
	internal Uri ImageUri { get; private set; }
	internal string TextSummary { get; private set; }
	internal AppTaskResultAsset[] GeneratedAssets { get; private set; }
	internal IReadOnlyList<(string Text, Uri ActionUri)> Buttons => _buttons;
	internal string Question => _question;
	internal string TextInputPlaceholder => _textInputPlaceholder;
	internal string TextInputActionUriTemplate => _textInputActionUriTemplate;

	private AppTaskContent()
	{
	}

	/// <summary>
	/// Gets the maximum number of buttons that can be added to the task content.
	/// </summary>
	public static uint MaxButtons => 3;

	/// <summary>
	/// Builds a sequence of steps being executed by the app task to display in the UI.
	/// </summary>
	/// <param name="completedSteps">An array of strings that describe the task steps that have been completed.</param>
	/// <param name="executingStep">A string that describes the step that the task is currently working on.</param>
	/// <returns>An instance of <see cref="AppTaskContent"/> with the created sequence of steps.</returns>
	public static AppTaskContent CreateSequenceOfSteps(string[] completedSteps, string executingStep)
	{
		return new AppTaskContent
		{
			Kind = AppTaskContentKind.SequenceOfSteps,
			CompletedSteps = completedSteps ?? throw new ArgumentNullException(nameof(completedSteps)),
			ExecutingStep = executingStep ?? throw new ArgumentNullException(nameof(executingStep)),
		};
	}

	/// <summary>
	/// Creates a thumbnail preview of the task output for tasks that create images.
	/// </summary>
	/// <param name="imageUri">The path to the image preview.</param>
	/// <param name="executingStep">A string that describes the step that the task is currently working on.</param>
	/// <returns>An instance of <see cref="AppTaskContent"/> with the created image preview and step.</returns>
	public static AppTaskContent CreatePreviewThumbnail(Uri imageUri, string executingStep)
	{
		return new AppTaskContent
		{
			Kind = AppTaskContentKind.PreviewThumbnail,
			ImageUri = imageUri ?? throw new ArgumentNullException(nameof(imageUri)),
			ExecutingStep = executingStep ?? throw new ArgumentNullException(nameof(executingStep)),
		};
	}

	/// <summary>
	/// Creates a text summary of the task results.
	/// </summary>
	/// <param name="text">Text that describes the result of the task.</param>
	/// <returns>An instance of <see cref="AppTaskContent"/> that contains the text description of the task results.</returns>
	public static AppTaskContent CreateTextSummaryResult(string text)
	{
		return new AppTaskContent
		{
			Kind = AppTaskContentKind.TextSummary,
			TextSummary = text ?? throw new ArgumentNullException(nameof(text)),
		};
	}

	/// <summary>
	/// Creates a display of assets generated by the app task.
	/// </summary>
	/// <param name="assets">An array of <see cref="AppTaskResultAsset"/> objects that describe the assets generated by the task.</param>
	/// <returns>An instance of <see cref="AppTaskContent"/> with the created assets.</returns>
	public static AppTaskContent CreateGeneratedAssetsResult(AppTaskResultAsset[] assets)
	{
		return new AppTaskContent
		{
			Kind = AppTaskContentKind.GeneratedAssets,
			GeneratedAssets = assets ?? throw new ArgumentNullException(nameof(assets)),
		};
	}

	/// <summary>
	/// Adds a button to the content of the app task UI.
	/// </summary>
	/// <param name="text">The button label.</param>
	/// <param name="actionUri">The path to an app action using an app-defined deep link URI scheme.</param>
	public void AddButton(string text, Uri actionUri)
	{
		if (_buttons.Count >= MaxButtons)
		{
			throw new InvalidOperationException($"Cannot add more than {MaxButtons} buttons.");
		}

		_buttons.Add((
			text ?? throw new ArgumentNullException(nameof(text)),
			actionUri ?? throw new ArgumentNullException(nameof(actionUri))));
	}

	/// <summary>
	/// Adds a text box to the app task UI that lets the user provide text input.
	/// </summary>
	/// <param name="placeholderText">The placeholder text shown in the text box.</param>
	/// <param name="actionUriTemplate">An app-defined deep link URI with a placeholder that is replaced by the user's input.</param>
	public void SetTextInput(string placeholderText, string actionUriTemplate)
	{
		_textInputPlaceholder = placeholderText ?? throw new ArgumentNullException(nameof(placeholderText));
		_textInputActionUriTemplate = actionUriTemplate ?? throw new ArgumentNullException(nameof(actionUriTemplate));
	}

	/// <summary>
	/// Adds text to the app task UI that lets you ask the user a question.
	/// </summary>
	/// <param name="question">The question that requires a user's response.</param>
	public void SetQuestion(string question)
	{
		_question = question ?? throw new ArgumentNullException(nameof(question));
	}
}
