// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// WinSDK Reference windows.ui.shell.tasks.idl, Windows SDK 10.0.26100.7705, commit 1bfb76d

#nullable enable
#pragma warning disable CS8305

using System;
using System.Collections.Generic;
using System.Linq;
using Windows.Foundation.Metadata;

namespace Windows.UI.Shell.Tasks;

/// <summary>
/// Represents the content displayed for an app task in the Windows Shell UI.
/// Use this class to create different visual representations of task progress and results.
/// </summary>
[ContractVersion(typeof(AppTaskContract), 65536U)]
[Experimental]
[MarshalingBehavior(MarshalingType.Agile)]
[Threading(ThreadingModel.Both)]
public sealed class AppTaskContent
{
	private const uint WindowsMaxButtons = 2;

	private readonly object _gate = new();
	private readonly List<AppTaskButtonSnapshot> _buttons = new();
	private readonly AppTaskContentKind _kind;
	private readonly string[] _completedSteps;
	private readonly string _executingStep;
	private readonly Uri? _imageUri;
	private readonly string _textSummary;
	private readonly AppTaskResultAssetSnapshot[] _generatedAssets;
	private string _question = string.Empty;
	private string _textInputPlaceholder = string.Empty;
	private string _textInputActionUriTemplate = string.Empty;
	private bool _hasTextInput;

	private AppTaskContent(
		AppTaskContentKind kind,
		string[]? completedSteps = null,
		string? executingStep = null,
		Uri? imageUri = null,
		string? textSummary = null,
		AppTaskResultAssetSnapshot[]? generatedAssets = null)
	{
		_kind = kind;
		_completedSteps = completedSteps ?? Array.Empty<string>();
		_executingStep = executingStep ?? string.Empty;
		_imageUri = imageUri;
		_textSummary = textSummary ?? string.Empty;
		_generatedAssets = generatedAssets ?? Array.Empty<AppTaskResultAssetSnapshot>();
	}

	/// <summary>
	/// Gets the maximum number of buttons that can be added to task content.
	/// </summary>
	public static uint MaxButtons => WindowsMaxButtons;

	/// <summary>
	/// Creates task content that displays a sequence of steps showing task progress.
	/// </summary>
	/// <param name="completedSteps">The sequence of steps that have already been completed.</param>
	/// <param name="executingStep">The step that is currently executing. This value is required.</param>
	/// <returns>Task content that displays the specified sequence of steps.</returns>
	public static AppTaskContent CreateSequenceOfSteps(string[] completedSteps, string executingStep)
	{
		AppTaskValidation.RequireNonEmpty(executingStep, nameof(executingStep));

		return new(
			AppTaskContentKind.SequenceOfSteps,
			completedSteps: completedSteps is null
				? Array.Empty<string>()
				: completedSteps.Select(static step => step ?? string.Empty).ToArray(),
			executingStep: executingStep);
	}

	/// <summary>
	/// Creates task content that displays a preview thumbnail of the task output.
	/// </summary>
	/// <param name="imageUri">The URI of the preview thumbnail.</param>
	/// <param name="executingStep">The step that is currently executing.</param>
	/// <returns>Task content that displays the specified preview thumbnail.</returns>
	public static AppTaskContent CreatePreviewThumbnail(Uri imageUri, string executingStep) =>
		new(
			AppTaskContentKind.PreviewThumbnail,
			executingStep: executingStep ?? string.Empty,
			imageUri: AppTaskValidation.RequireAbsoluteUri(imageUri, nameof(imageUri)));

	/// <summary>
	/// Creates task content that displays a text summary of the task result.
	/// </summary>
	/// <param name="text">The text summary to display. This value is required.</param>
	/// <returns>Task content that displays the specified text summary.</returns>
	public static AppTaskContent CreateTextSummaryResult(string text)
	{
		AppTaskValidation.RequireNonEmpty(text, nameof(text));
		return new(AppTaskContentKind.TextSummary, textSummary: text);
	}

	/// <summary>
	/// Creates task content that displays a collection of assets generated by the task.
	/// </summary>
	/// <param name="assets">The assets generated by the task.</param>
	/// <returns>Task content that displays the specified generated assets.</returns>
	public static AppTaskContent CreateGeneratedAssetsResult(AppTaskResultAsset[] assets)
	{
		ArgumentNullException.ThrowIfNull(assets);

		if (assets.Any(static asset => asset is null))
		{
			throw new ArgumentException("Generated assets cannot contain null values.", nameof(assets));
		}

		return new(
			AppTaskContentKind.GeneratedAssets,
			generatedAssets: assets.Select(static asset => asset.CreateSnapshot()).ToArray());
	}

	/// <summary>
	/// Adds a button to the task content that the user can click to take an action.
	/// </summary>
	/// <param name="text">The text displayed on the button.</param>
	/// <param name="actionUri">The URI launched when the user clicks the button.</param>
	/// <exception cref="ArgumentException">
	/// <see cref="MaxButtons"/> buttons have already been added, or <paramref name="actionUri"/> is not absolute.
	/// </exception>
	public void AddButton(string text, Uri actionUri)
	{
		AppTaskValidation.RequireAbsoluteUri(actionUri, nameof(actionUri));

		lock (_gate)
		{
			if (_buttons.Count >= MaxButtons)
			{
				throw new ArgumentException($"Task content supports at most {MaxButtons} buttons.");
			}

			_buttons.Add(new(text ?? string.Empty, actionUri));
		}
	}

	/// <summary>
	/// Sets up a text input field for the user to provide a free-form text response.
	/// </summary>
	/// <param name="placeholderText">The placeholder text displayed in the input field to guide the user.</param>
	/// <param name="actionUriTemplate">
	/// A URI template string. Any <c>{userTextInput}</c> occurrence is replaced with the user's escaped input text when submitted.
	/// </param>
	/// <exception cref="ArgumentException">A text input has already been set on this content.</exception>
	public void SetTextInput(string placeholderText, string actionUriTemplate)
	{
		lock (_gate)
		{
			if (_hasTextInput)
			{
				throw new ArgumentException("A text input has already been set on this task content.");
			}

			_hasTextInput = true;
			_textInputPlaceholder = placeholderText ?? string.Empty;
			_textInputActionUriTemplate = actionUriTemplate ?? string.Empty;
		}
	}

	/// <summary>
	/// Sets a question to display to the user when the task needs attention.
	/// </summary>
	/// <param name="question">The question to display.</param>
	public void SetQuestion(string question)
	{
		lock (_gate)
		{
			_question = question ?? string.Empty;
		}
	}

	internal AppTaskContentSnapshot CreateSnapshot()
	{
		lock (_gate)
		{
			return new(
				_kind,
				(string[])_completedSteps.Clone(),
				_executingStep,
				_imageUri,
				_textSummary,
				(AppTaskResultAssetSnapshot[])_generatedAssets.Clone(),
				_buttons.ToArray(),
				_question,
				_textInputPlaceholder,
				_textInputActionUriTemplate);
		}
	}
}
