// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// WinSDK Reference windows.ui.shell.tasks.idl, Windows SDK 10.0.26100.7705, commit 1bfb76d

#nullable enable
#pragma warning disable CS8305

using System;
using Windows.Foundation.Metadata;

namespace Windows.UI.Shell.Tasks;

/// <summary>
/// Represents an asset produced by a completed task, such as a file or other generated content.
/// </summary>
[ContractVersion(typeof(AppTaskContract), 65536U)]
[Experimental]
[MarshalingBehavior(MarshalingType.Agile)]
[Threading(ThreadingModel.Both)]
public sealed class AppTaskResultAsset
{
	private readonly string _name;
	private readonly string _context;
	private readonly Uri _iconUri;
	private readonly Uri _assetUri;

	/// <summary>
	/// Creates a new instance of <see cref="AppTaskResultAsset"/> with the specified parameters.
	/// </summary>
	/// <param name="name">The name of the generated asset.</param>
	/// <param name="context">A description of the task context.</param>
	/// <param name="iconUri">The URI of the icon that represents the asset.</param>
	/// <param name="assetUri">The URI of the asset generated by the task.</param>
	public AppTaskResultAsset(string name, string context, Uri iconUri, Uri assetUri)
	{
		_name = name ?? throw new ArgumentNullException(nameof(name));
		_context = context ?? throw new ArgumentNullException(nameof(context));
		_iconUri = AppTaskValidation.RequireAbsoluteUri(iconUri, nameof(iconUri));
		_assetUri = AppTaskValidation.RequireAbsoluteUri(assetUri, nameof(assetUri));
	}

	internal AppTaskResultAssetSnapshot CreateSnapshot() => new(_name, _context, _iconUri, _assetUri);
}
