#nullable enable

namespace Uno.UI.SourceGenerators.XamlGenerator;

/// <summary>
/// Emits the code-behind source text for a XAML file that has no developer-authored code-behind.
/// </summary>
internal static class XamlCodeBehindEmitter
{
	/// <summary>
	/// Generates a code-behind partial class source string for the given XAML class info.
	/// </summary>
	public static string Emit(XamlClassInfo classInfo)
	{
		return $@"// <auto-generated>
// This file was auto-generated by Uno.UI.SourceGenerators.
// Do not edit this file manually.
// </auto-generated>

namespace {classInfo.Namespace}
{{
	public partial class {classInfo.ClassName} : {classInfo.BaseTypeFullName}
	{{
		public {classInfo.ClassName}()
		{{
			this.InitializeComponent();
		}}
	}}
}}
";
	}

	/// <summary>
	/// Returns the hint name for a generated code-behind source file.
	/// </summary>
	public static string GetHintName(XamlClassInfo classInfo)
		=> $"{classInfo.FullClassName}.codebehind.g.cs";
}
