#nullable enable

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;
using Uno.Roslyn;
using Uno.UI.SourceGenerators.Helpers;
using Uno.DevTools.Telemetry;

namespace Uno.UI.SourceGenerators.XamlGenerator
{
	[Generator]
	public partial class XamlCodeGenerator : IIncrementalGenerator
	{
		public void Initialize(IncrementalGeneratorInitializationContext context)
		{
			//var process = Process.GetCurrentProcess().ProcessName;
			//if (process.IndexOf("VBCSCompiler", StringComparison.OrdinalIgnoreCase) is not -1
			//	|| process.IndexOf("csc", StringComparison.OrdinalIgnoreCase) is not -1)
			//{
			//	Debugger.Launch();
			//}

			RegisterLocalizationResources(context);

			var additionalFilesProvider = context.AdditionalTextsProvider.Collect();

			var combined = context.CompilationProvider
				.Combine(additionalFilesProvider)
				.Combine(context.AnalyzerConfigOptionsProvider);

			context.RegisterSourceOutput(combined, static (spc, data) =>
			{
				var ((compilation, additionalFiles), optionsProvider) = data;

				if (!IsValidPlatform(compilation))
				{
					return;
				}

				var sourceContext = XamlSourceContext.FromIncrementalInputs(
					compilation: compilation,
					cancellationToken: spc.CancellationToken,
					additionalFiles: additionalFiles,
					optionsProvider: optionsProvider,
					reportDiagnostic: spc.ReportDiagnostic,
					addSource: spc.AddSource);

				var isDesignTimeBuild = IsDesignTimeBuild(optionsProvider);
				var gen = new XamlCodeGeneration(sourceContext, isDesignTimeBuild);
				var generatedTrees = gen.Generate();

				foreach (var tree in generatedTrees)
				{
					spc.AddSource(tree.Key, tree.Value);
				}

				DumpXamlSourceGeneratorState(sourceContext, generatedTrees);
			});
		}

		/// <summary>
		/// Wires the LocalizationResources output as its own pipeline node so the
		/// AssemblyMetadata("UnoHasLocalizationResources", ...) attribute is only
		/// recomputed when a PRIResource AdditionalText (or the platform-validity
		/// of the compilation) actually changes.
		/// </summary>
		private static void RegisterLocalizationResources(IncrementalGeneratorInitializationContext context)
		{
			var priResourceFiles = context.AdditionalTextsProvider
				.Combine(context.AnalyzerConfigOptionsProvider)
				.Select(static (pair, ct) =>
				{
					var (file, optionsProvider) = pair;
					var options = optionsProvider.GetOptions(file);
					return options.TryGetValue("build_metadata.AdditionalFiles.SourceItemGroup", out var group)
						&& group == "PRIResource"
						? file
						: null;
				})
				.Where(static file => file is not null)
				.Select(static (file, ct) => HasAnyResourceEntries(file!, ct))
				.Collect();

			var localizationProvider = priResourceFiles
				.Select(static (results, _) => results.Any(static r => r))
				.Combine(context.CompilationProvider.Select(static (c, _) => IsValidPlatform(c)));

			context.RegisterSourceOutput(localizationProvider, static (spc, data) =>
			{
				var (hasResources, isValidPlatform) = data;
				if (!isValidPlatform)
				{
					return;
				}

				spc.AddSource(
					"LocalizationResources",
					$"""
					// <auto-generated />
					[assembly: global::System.Reflection.AssemblyMetadata("UnoHasLocalizationResources", "{hasResources.ToString(System.Globalization.CultureInfo.InvariantCulture)}")]
					""");
			});
		}

		private static bool HasAnyResourceEntries(AdditionalText file, System.Threading.CancellationToken ct)
		{
			try
			{
				if (file.GetText(ct) is not { } sourceText)
				{
					return false;
				}

				var doc = new System.Xml.XmlDocument();
				doc.LoadXml(sourceText.ToString());
				return doc.SelectNodes("/root/data") is { Count: > 0 };
			}
			catch
			{
				// Mirrors XamlCodeGeneration.BuildLocalResourceDetails: malformed PRIResource files are
				// reported there during ResourceDetailsCollection construction; here we just refuse
				// to claim "has resources" so the LocalizationResources attribute stays false.
				return false;
			}
		}

		private static bool IsValidPlatform(Compilation compilation)
			=> compilation.Options.OutputKind != OutputKind.WindowsRuntimeApplication
				&& compilation.Options.OutputKind != OutputKind.WindowsRuntimeMetadata;

		private static bool IsDesignTimeBuild(AnalyzerConfigOptionsProvider optionsProvider)
		{
			optionsProvider.GlobalOptions.TryGetValue("build_property.BuildingProject", out var buildingProject);
			optionsProvider.GlobalOptions.TryGetValue("build_property.DesignTimeBuild", out var designTimeBuild);

			return string.Equals(buildingProject, "false", StringComparison.OrdinalIgnoreCase)
				|| string.Equals(designTimeBuild, "true", StringComparison.OrdinalIgnoreCase);
		}
	}
}
