#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.CodeAnalysis.Text;
using Uno.Extensions;
using Uno.UI.SourceGenerators.Helpers;
using Uno.UI.SourceGenerators.Utils;

namespace Uno.UI.SourceGenerators.XamlGenerator;

partial class XamlCodeGeneration
{
	private SourceText? GenerateEmbeddedXamlSources(XamlFileDefinition[] files)
	{
		var interestingFiles = new SortedSet<XamlFileDefinition>();

		foreach (var file in files)
		{
			if (file.Content.Length > 0)
			{
				interestingFiles.Add(file);
			}
		}

		if (interestingFiles.Count == 0)
		{
			return null;
		}

		const string embeddedXamlSourcesClassName = "EmbeddedXamlSourcesProvider";
		var writer = new IndentedStringBuilder();

		writer.AppendLineIndented("#nullable enable");
		writer.AppendLineIndented("// <autogenerated />");
		AnalyzerSuppressionsGenerator.Generate(writer, _analyzerSuppressions);

		writer.AppendLineIndented("#pragma warning disable // Disable all warnings for this generated file");
		writer.AppendLine();
		writer.AppendLineIndented("// Register an embedded sources provider for Hot Reload");
		writer.AppendLineInvariantIndented("[assembly: global::System.Reflection.AssemblyMetadata(\"Uno.HotDesign.HotReloadEmbeddedXamlSourceFilesProvider\", \"{0}.__Sources__.{1}\")]", _defaultNamespace, embeddedXamlSourcesClassName);
		writer.AppendLineIndented("// Register a metadata update handler so the cached XAML sources are invalidated when hot reload applies new IL for the GetSources_N() method bodies.");
		writer.AppendLineInvariantIndented("[assembly: global::System.Reflection.Metadata.MetadataUpdateHandlerAttribute(typeof({0}.__Sources__.{1}.HotReloadMetadataUpdateHandler))]", _defaultNamespace, embeddedXamlSourcesClassName);
		writer.AppendLine();
		writer.AppendLineInvariantIndented("namespace {0}.__Sources__;", _defaultNamespace);
		writer.AppendLine();

		// Compute the checksum of all the files by hashing the content of the files, separated by a null character
		var filesListHash = HashBuilder.Build(string.Join("\0", interestingFiles.Select(f => f.FilePath)));

		writer.AppendLineIndented("/// <summary>");
		writer.AppendLineIndented("/// Provides access to the embedded XAML sources");
		writer.AppendLineIndented("/// </summary>");
		writer.AppendLineIndented("/// <remarks>");
		writer.AppendLineIndented("/// This class is used to provide the embedded XAML sources to the Hot Reload engine.");
		writer.AppendLineIndented("/// This is not intended to be used directly by application code.");
		writer.AppendLineIndented("/// WON'T BE GENERATED ON RELEASE BUILDS");
		writer.AppendLineIndented("/// </remarks>");
		using (writer.BlockInvariant("internal static class {0}", embeddedXamlSourcesClassName))
		{
			writer.AppendLineIndented("// key=absolute file path");
			writer.AppendLineIndented("private static global::System.Collections.Generic.IDictionary<string, (string ActualPath, global::System.Func<(string Hash, string Payload)> Getter)>? _XamlSources;");
			writer.AppendLine();
			writer.AppendLineIndented("// hash of all the paths");
			writer.AppendLineIndented("private static volatile string? _filesListHash;");
			writer.AppendLine();
			writer.AppendLineIndented("// get the current value of the update counter");
			writer.AppendLineIndented("private static volatile uint _updateCounter;");
			writer.AppendLine();
			writer.AppendLineIndented("private static readonly global::System.Text.Encoding _utf8 = global::System.Text.Encoding.UTF8;");
			writer.AppendLine();
			writer.AppendLineIndented("// The content of this method only changes when the file list changes");
			using (writer.BlockInvariant("private static global::System.Collections.Generic.IDictionary<string, (string ActualPath, global::System.Func<(string Hash, string Payload)> Getter)> EnsureInitialize()"))
			{
				writer.AppendLineInvariantIndented("const string currentListHash = \"{0}\"; // that's the hash of all the paths, used to detect changes in the file list following a HR operation", filesListHash);
				writer.AppendLine();
				writer.AppendLineIndented("// Determine if the sources have been updated or not initialized yet");
				writer.AppendLineIndented("var previousHashList = _XamlSources;");
				writer.AppendLineIndented("var needsUpdate = previousHashList is null || _filesListHash != currentListHash;");
				writer.AppendLine();
				using (writer.BlockInvariant("if (needsUpdate)"))
				{
					writer.AppendLineInvariantIndented("var xamlSources = new global::System.Collections.Generic.Dictionary<string, (string ActualPath, global::System.Func<(string Hash, string Payload)> Getter)>({0}, global::System.StringComparer.OrdinalIgnoreCase);", interestingFiles.Count);
					writer.AppendLine();
					writer.AppendLineIndented("// Use method groups to avoid closure allocation and ensure no lambda is created, to allow proper HR support");
					foreach (var f in interestingFiles)
					{
						writer.AppendLineInvariantIndented("xamlSources[NormalizePath(@\"{0}\")] = (NormalizePath(@\"{0}\"), GetSources_{1});", f.FilePath, f.UniqueID);
					}
					writer.AppendLine();
					using (writer.BlockInvariant("if (global::System.Threading.Interlocked.CompareExchange(ref _XamlSources, xamlSources, previousHashList) == previousHashList)"))
					{
						writer.AppendLineIndented("// The sources were updated successfully (no other thread modified them concurrently)");
						writer.AppendLineIndented("_filesListHash = currentListHash;");
						writer.AppendLineIndented("_updateCounter++;");
					}
				}
				writer.AppendLine();
				writer.AppendLineIndented("return _XamlSources;");
			}
			writer.AppendLine();
			writer.AppendLineIndented("/// <summary>");
			writer.AppendLineIndented("/// Gets the current update counter, used to detect changes in the sources.");
			writer.AppendLineIndented("/// </summary>");
			writer.AppendLineIndented("/// <remarks>");
			writer.AppendLineIndented("/// This counter is incremented each time a Hot Reload sources update is detected.");
			writer.AppendLineIndented("/// </remarks>");
			using (writer.BlockInvariant("public static uint UpdateCounter"))
			{
				using (writer.BlockInvariant("get"))
				{
					writer.AppendLineIndented("EnsureInitialize();");
					writer.AppendLineIndented("return _updateCounter;");
				}
			}
			writer.AppendLine();
			writer.AppendLineIndented("public static global::System.Collections.Generic.IReadOnlyList<string> GetXamlFilesList() => [.. EnsureInitialize().Keys];");

			writer.AppendLine();
			using (writer.BlockInvariant("public static string? GetNormalizedFileName(string path)"))
			{
				writer.AppendLineIndented("// Will return the normalized path if the file exists, or null if it doesn't.");
				writer.AppendLineIndented("// (the returned value will be constant for the file and can be used in a dictionary using an ordinal comparer)");
				writer.AppendLineIndented("var normalizedPath = NormalizePath(path);");
				writer.AppendLineIndented("return EnsureInitialize().TryGetValue(normalizedPath, out var entry) ? entry.ActualPath : null;");
			}

			writer.AppendLine();
			using (writer.BlockInvariant("public static (string ActualPath, string Hash, string Payload)? GetXamlFile(string path)"))
			{
				writer.AppendLineIndented("var normalizedPath = NormalizePath(path);");
				using (writer.BlockInvariant("if (EnsureInitialize().TryGetValue(normalizedPath, out var entry))"))
				{
					writer.AppendLineIndented("// Hot reload workaround: the IL for the baked GetSources_N() delegates is not updated when a .xaml file is edited at runtime");
					writer.AppendLineIndented("// (the XAML source generator does not re-run during WatchHotReloadService delta emission). Read the file from disk when available");
					writer.AppendLineIndented("// so Hot Design's property editor observes the user's current XAML. Fall back to the baked payload if the file is absent.");
					using (writer.BlockInvariant("try"))
					{
						using (writer.BlockInvariant("if (global::System.IO.File.Exists(entry.ActualPath))"))
						{
							writer.AppendLineIndented("var diskContent = global::System.IO.File.ReadAllText(entry.ActualPath);");
							writer.AppendLineIndented("var diskHash = ComputeContentHash(diskContent);");
							writer.AppendLineIndented("global::System.Console.WriteLine($\"[HD-Diag] GetXamlFile: read from disk path={entry.ActualPath} len={diskContent.Length} hash={diskHash}\");");
							writer.AppendLineIndented("return (entry.ActualPath, diskHash, diskContent);");
						}
					}
					writer.AppendLineIndented("catch (global::System.Exception ex)");
					using (writer.BlockInvariant(""))
					{
						writer.AppendLineIndented("global::System.Console.WriteLine($\"[HD-Diag] GetXamlFile: disk read failed path={entry.ActualPath} error={ex.Message}; falling back to baked payload\");");
					}
					writer.AppendLine();
					writer.AppendLineIndented("var sources = entry.Getter();");
					writer.AppendLineIndented("return (entry.ActualPath, sources.Hash, sources.Payload);");
				}
				writer.AppendLineIndented("return null;");
			}

			writer.AppendLine();
			writer.AppendLineIndented(@"private static string NormalizePath(string path) => path.Replace('\\', '/');");

			writer.AppendLine();
			using (writer.BlockInvariant("private static string ComputeContentHash(string content)"))
			{
				writer.AppendLineIndented("// Stable hex hash of UTF-8 bytes. Consumers (Hot Design) treat the hash opaquely; only stability and content-sensitivity matter.");
				writer.AppendLineIndented("using var sha = global::System.Security.Cryptography.SHA1.Create();");
				writer.AppendLineIndented("var bytes = _utf8.GetBytes(content);");
				writer.AppendLineIndented("var hashBytes = sha.ComputeHash(bytes);");
				writer.AppendLineIndented("var sb = new global::System.Text.StringBuilder(hashBytes.Length * 2);");
				using (writer.BlockInvariant("for (var i = 0; i < hashBytes.Length; i++)"))
				{
					writer.AppendLineIndented("sb.Append(hashBytes[i].ToString(\"x2\", global::System.Globalization.CultureInfo.InvariantCulture));");
				}
				writer.AppendLineIndented("return sb.ToString();");
			}

			writer.AppendLine();
			writer.AppendLineIndented("/// <summary>");
			writer.AppendLineIndented("/// Metadata update handler discovered by <see cref=\"global::System.Reflection.Metadata.MetadataUpdateHandlerAttribute\"/>.");
			writer.AppendLineIndented("/// Invalidates the cached <c>_XamlSources</c> dictionary and bumps <c>_updateCounter</c> when hot reload applies metadata deltas,");
			writer.AppendLineIndented("/// so the next call to <c>EnsureInitialize</c> rebuilds the dictionary and re-invokes the freshly-updated <c>GetSources_N</c> method bodies.");
			writer.AppendLineIndented("/// </summary>");
			using (writer.BlockInvariant("internal static class HotReloadMetadataUpdateHandler"))
			{
				using (writer.BlockInvariant("public static void ClearCache(global::System.Type[]? types)"))
				{
					writer.AppendLineIndented("global::System.Console.WriteLine($\"[HD-Diag] EmbeddedXamlSourcesProvider.HotReloadMetadataUpdateHandler.ClearCache invoked, types={types?.Length ?? 0}\");");
					writer.AppendLineIndented("// Dropping _XamlSources forces the next EnsureInitialize call to rebuild the dictionary using the updated method-group references to GetSources_N(), which may now carry new IL.");
					writer.AppendLineIndented("_XamlSources = null;");
					writer.AppendLineIndented("_filesListHash = null;");
					writer.AppendLineIndented("unchecked { _updateCounter++; }");
				}
				writer.AppendLine();
				using (writer.BlockInvariant("public static void UpdateApplication(global::System.Type[]? types)"))
				{
					writer.AppendLineIndented("global::System.Console.WriteLine($\"[HD-Diag] EmbeddedXamlSourcesProvider.HotReloadMetadataUpdateHandler.UpdateApplication invoked, types={types?.Length ?? 0}\");");
					writer.AppendLineIndented("// Called after metadata deltas are applied. ClearCache already invalidated our state; this method is present so the runtime recognizes the handler even in delta-ordering scenarios.");
					writer.AppendLineIndented("_XamlSources = null;");
					writer.AppendLineIndented("_filesListHash = null;");
					writer.AppendLineIndented("unchecked { _updateCounter++; }");
				}
			}

			foreach (var f in interestingFiles)
			{
				writer.AppendLine();
				writer.AppendLineInvariantIndented("#region Sources for {0}", f.FilePath);

				var rawStringDelimiter = GetRawStringDelimiter(f.Content.AsSpan());

				using (writer.BlockInvariant("private static (string hash, string payload) GetSources_{0}()", f.UniqueID))
				{
					writer.AppendLineIndented("return (");
					using (writer.Indent())
					{
						writer.AppendLineInvariantIndented("\"{0}\", // hash", f.Checksum);
						writer.AppendLineInvariantIndented("_utf8.GetString({0}", rawStringDelimiter);
						writer.AppendMultiLineIndented(f.Content);
						writer.AppendLineInvariantIndented("{0}u8)); // Stored as UTF8 to minimize impact on assembly size / limitations", rawStringDelimiter);
					}
				}
				writer.AppendLineIndented("#endregion");
			}
		}

		return new StringBuilderBasedSourceText(writer.Builder);
	}

	private static string GetRawStringDelimiter(ReadOnlySpan<char> content)
	{
		var nbQuotes = 3; // Minimum triple quotes

		var i = 0;
		while (i < content.Length)
		{
			// Find the next occurrence of a quote
			var nextQuote = content.Slice(i).IndexOf('"');
			if (nextQuote == -1)
			{
				break; // No more quotes to process
			}

			i += nextQuote; // Move to the found quote

			var start = i;
			while (i + 1 < content.Length && content[i + 1] == '"')
			{
				i++;
			}

			var count = i - start + 1 + 1; // +1 for the zero-based index, +1 for the number of quotes required for escaping
			if (count > nbQuotes)
			{
				nbQuotes = count;
			}

			i++; // Move to the next character after the quote sequence
		}

		return nbQuotes == 3
			? "\"\"\"" // No need to escape, use triple quotes
			: new string('"', nbQuotes);
	}
}
