# https://github.com/actions/labeler

area/automation:
  - src/SamplesApp/*
  - src/SamplesApp/**/*
  - src/Uno.UI.Tests/*
  - src/Uno.UI.Tests/**/*
  - src/Uno.UI.Wasm.Tests/*
  - src/Uno.UI.Wasm.Tests/**/*

area/build:
  - build/*
  - build/**/*
  - '**/*.yml'
  - src/Uno.UI.TestComparer/*
  - src/Uno.UI.TestComparer/**/*

area/code-generation:
  - src/SourceGenerators/*
  - src/SourceGenerators/**/*

kind/documentation:
  - README.*
  - doc/**
  - '**/*.md'
  - '**/*.MD'
  - '**/*.txt'

area/skia ✏️:
  - '**/*.skia.cs'
  - src/Uno.UI.Runtime.Skia.Gtk/*
  - src/Uno.UI.Runtime.Skia.Gtk/**/*
  - src/Uno.UI.Runtime.Skia.Linux.FrameBuffer/*
  - src/Uno.UI.Runtime.Skia.Linux.FrameBuffer/**/*
  - src/Uno.UI.Runtime.Skia.Tizen/*
  - src/Uno.UI.Runtime.Skia.Tizen/**/*
  - src/Uno.UI.Runtime.Skia.Wpf/*
  - src/Uno.UI.Runtime.Skia.Wpf/**/*
  - src/Uno.UI.Runtime.Skia.Android/*
  - src/Uno.UI.Runtime.Skia.Android/**/*
  - src/Uno.UI.Runtime.Skia.AppleUIKit/*
  - src/Uno.UI.Runtime.Skia.AppleUIKit/**/*
  - src/Uno.UI.XamlHost.Skia.Wpf/**/*
  - src/Uno.UI.XamlHost.Skia.Wpf/**/*

area/solution-templates:
  - src/SolutionTemplate/*
  - src/SolutionTemplate/**/*
  - src/UnoItemTemplate/*
  - src/UnoItemTemplate/**/*

area/sdk:
  - src/Uno.Sdk/*

platform/android 🤖:
  - src/Uno.UI.BindingHelper.Android/*
  - src/Uno.UI.BindingHelper.Android/**/*
  - '**/*.Android.cs'
  - '**/*.Xamarin.cs'
  - src/Uno.UI.Runtime.Skia.Android/*
  - src/Uno.UI.Runtime.Skia.Android/**/*
  
platform/wasm 🌐:
  - '**/*.wasm.cs'
  - src/Uno.UI.Wasm/*
  - src/Uno.UI.Wasm/**/*
  - src/Uno.Foundation.Runtime.WebAssembly/*
  - src/Uno.Foundation.Runtime.WebAssembly/**/*
  - src/Uno.UI.Runtime.WebAssembly/*
  - src/Uno.UI.Runtime.WebAssembly/**/*
  - src/Uno.UI.Runtime.Skia.WebAssembly.Browser/*
  - src/Uno.UI.Runtime.Skia.WebAssembly.Browser/**/*

platform/ios 🍎:
  - '**/*.iOS.cs'
  - '**/*.UIKit.cs'
  - '**/*.iOSmacOS.cs'
  - '**/*.Apple.cs'
  - '**/*.Xamarin.cs'
  - src/Uno.UI.Runtime.Skia.AppleUIKit/*
  - src/Uno.UI.Runtime.Skia.AppleUIKit/**/*

platform/macos 🍏:
  - '**/*.macOS.cs'
  - '**/*.iOSmacOS.cs'
  - '**/*.Apple.cs'
  - '**/*.Xamarin.cs'
  - src/Uno.UI.Runtime.Skia.MacOS/*
  - src/Uno.UI.Runtime.Skia.MacOS/**/*

platform/x11 🐧:
  - src/Uno.UI.Runtime.Skia.X11/*
  - src/Uno.UI.Runtime.Skia.X11/**/*

platform/wpf 🪟:
  - src/Uno.UI.Runtime.Skia.Wpf/*
  - src/Uno.UI.Runtime.Skia.Wpf/**/*