image:
  file: build/gitpod/.gitpod.Dockerfile

ports:
  # Default port for the SampleApp
  - port: 8000
    onOpen: open-preview

tasks:
  # Mitigation for https://github.com/gitpod-io/gitpod/issues/6460 
  - name: Postinstall .NET and dev certificates
    init: |
      mkdir -p $DOTNET_ROOT && curl -fsSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel $DOTNET_VERSION --install-dir $DOTNET_ROOT 
      mkdir -p $DOTNET_ROOT && curl -fsSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --version 7.0.302 --install-dir $DOTNET_ROOT 
      dotnet dev-certs https 
      build/gitpod/build-skia.sh
      build/gitpod/build-wasm.sh

  - name: SampleApp Static Files Server
    before: export NUGET_PACKAGES=/workspace/.nuget
    openMode: tab-after
    command: echo "once you've built the sources run build/gitpod/serve-sampleapp-wasm.sh"

  - name: Build
    before: export NUGET_PACKAGES=/workspace/.nuget
    command: echo -e "Follow the guide here https://github.com/unoplatform/uno/tree/master/doc/articles/features/working-with-gitpod.md" && echo && echo "Build Uno with build/gitpod/build-wasm.sh"
    openMode: tab-after

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: false
