phases:
- phase: VS_Latest
  variables:
    CombinedConfiguration: Release|Any CPU
    CI_Build: true

  steps:
  - checkout: self
    clean: true
    
  - task: GitVersion@3
    # Ignore gitversion for forks, until this is fixed:
    # https://developercommunity.visualstudio.com/content/problem/284991/public-vsts-previouw-cant-set-build-number-of-pr-b.html
    condition: eq(variables['System.PullRequest.IsFork'], 'False')
    inputs:
      updateAssemblyInfo: false

  - task: NuGetToolInstaller@0
    inputs:
      versionSpec: 4.7.0
      checkLatest: false

  - task: NuGetCommand@2
    inputs:
      command: restore
      solution: src/Uno.UI.sln
      selectOrConfig: select
      includeNuGetOrg: true
      verbosityRestore: Normal

  - task: MSBuild@1
    inputs:
      solution: Build/Uno.UI.proj
      msbuildLocationMethod: version
      msbuildVersion: latest
      msbuildArchitecture: x86
      msbuildArguments: /p:CheckExclusions=True "/p:CombinedConfiguration=$(CombinedConfiguration)" /nodeReuse:true /detailedsummary /m:16 /nr:false #/bl:$(build.artifactstagingdirectory)\build.binlog
      clean: false
      maximumCpuCount: true
      restoreNugetPackages: false
      logProjectEvents: false
      createLogFile: false
      
  - task: VSTest@2
    inputs:
      testAssemblyVer2: |
        **\*test*.dll
        !**\obj\**
        !**\*Wasm.Test*.dll
        !**\*.RuntimeTests.dll
      vstestLocationMethod: version
      vsTestVersion: latest
      testSelector: testAssemblies

  - task: CopyFiles@2
    inputs:
      SourceFolder: $(build.sourcesdirectory)/Build
      Contents: '*.nupkg'
      TargetFolder: $(build.artifactstagingdirectory)\vslatest
      CleanTargetFolder: false
      OverWrite: false
      flattenFolders: false

  - task: CopyFiles@2
    inputs:
      SourceFolder: $(build.sourcesdirectory)\src\SamplesApp\SamplesApp.Wasm\bin\Release\netstandard2.0\dist
      Contents: '**\*.*'
      TargetFolder: $(build.artifactstagingdirectory)\sampleapp-wasm
      CleanTargetFolder: false
      OverWrite: false
      flattenFolders: false

  - task: PowerShell@2
    displayName: Authenticode Sign Packages
    inputs:
      filePath: build/Sign-Package.ps1
    env:
      SignClientUser: $(SignClientUser)
      SignClientSecret: $(SignClientSecret)
      SignPackageName: "Uno Platform"
      SignPackageDescription: "The Uno Platform"
      ArtifactDirectory: $(build.artifactstagingdirectory)\vslatest
    condition: and(succeeded(), not(eq(variables['build.reason'], 'PullRequest')), not(eq(variables['SignClientSecret'], '')), not(eq(variables['SignClientUser'], '')))

  - task: PublishBuildArtifacts@1
    # https://developercommunity.visualstudio.com/content/problem/284991/public-vsts-previouw-cant-set-build-number-of-pr-b.html
    condition: eq(variables['System.PullRequest.IsFork'], 'False')
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      ArtifactName: NugetPackages
      ArtifactType: Container

# Disabled until VS4Mac is updated to 7.7 or later.
#- phase: macOS
#  variables:
#    NUGET_PACKAGES: $(Agent.WorkFolder)\.nuget
#    NUGET_HTTP_CACHE_PATH: $(Agent.WorkFolder)\.nuget-http-cache
#    CombinedConfiguration: Release|Any CPU
#    CI_Build: true
#    SourceLinkEnabled: false
#
#  queue:
#    name: Hosted macOS
#
#  steps:
#  - checkout: self
#    clean: true
#
#  - task: NuGetToolInstaller@0
#    inputs:
#      versionSpec: 4.7.0
#      checkLatest: false
#
#  - task: NuGetCommand@2
#    inputs:
#      command: restore
#      solution: src/Uno.UI-vs4mac.sln
#      selectOrConfig: select
#      includeNuGetOrg: true
#      verbosityRestore: Normal
#
#  - task: MSBuild@1
#    inputs:
#      solution: Build/Uno.UI.proj
#      msbuildLocationMethod: version
#      msbuildVersion: latest
#      msbuildArchitecture: x86
#      msbuildArguments: /r /p:CheckExclusions=True "/p:CombinedConfiguration=$(CombinedConfiguration)" /detailedsummary /bl:$(build.artifactstagingdirectory)/build-macos.binlog
#      clean: false
#      maximumCpuCount: true
#      restoreNugetPackages: false
#      logProjectEvents: false
#      createLogFile: false
#
#  - task: PublishBuildArtifacts@1
#    # https://developercommunity.visualstudio.com/content/problem/284991/public-vsts-previouw-cant-set-build-number-of-pr-b.html
#    condition: eq(variables['System.PullRequest.IsFork'], 'False')
#    inputs:
#      PathtoPublish: $(build.artifactstagingdirectory)
#      ArtifactName: uno-macos-artifacts
#      ArtifactType: Container

- phase: Documentation
  variables:
    NUGET_PACKAGES: $(Agent.WorkFolder)\.nuget
    NUGET_HTTP_CACHE_PATH: $(Agent.WorkFolder)\.nuget-http-cache
    CombinedConfiguration: Release|Any CPU
    CI_Build: true

  steps:
  - checkout: self
    clean: true
    
  - task: GitVersion@3
    # Ignore gitversion for forks, until this is fixed:
    # https://developercommunity.visualstudio.com/content/problem/284991/public-vsts-previouw-cant-set-build-number-of-pr-b.html
    condition: eq(variables['System.PullRequest.IsFork'], 'False')
    inputs:
      updateAssemblyInfo: false

  - task: NuGetToolInstaller@0
    inputs:
      versionSpec: 4.9.1
      checkLatest: false

  - task: NuGetCommand@2
    inputs:
      command: restore
      solution: src/Uno.UI.sln
      selectOrConfig: select
      includeNuGetOrg: true
      verbosityRestore: Normal

  - task: MSBuild@1
    inputs:
      solution: Build/Uno.UI.proj
      msbuildLocationMethod: version
      msbuildVersion: latest
      msbuildArchitecture: x86
      msbuildArguments: /t:GenerateDoc /p:CheckExclusions=True "/p:CombinedConfiguration=$(CombinedConfiguration)" /detailedsummary
      clean: false
      maximumCpuCount: true
      restoreNugetPackages: false
      logProjectEvents: false
      createLogFile: false

  - task: PublishBuildArtifacts@1
    # https://developercommunity.visualstudio.com/content/problem/284991/public-vsts-previouw-cant-set-build-number-of-pr-b.html
    condition: eq(variables['System.PullRequest.IsFork'], 'False')
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      ArtifactName: NugetPackages
      ArtifactType: Container
