trigger:
  branches:
    include:
      - master
      - release/beta/*
      - release/stable/*
      - feature/*
      - legacy/*
      
  paths:
    include:
    - '/'
    exclude:
    - .dependabot/
    - .github/
    # don't trigger the CI if only docs files are changed
    - doc/*
    - '**/*.md'
    - '*.md'
    - 'build/cSpell.json'
    - 'build/.markdownlint.json'
    
pr: 
  branches:
    include:
      - master
      - release/beta/*
      - release/stable/*
      - feature/*
      - legacy/*
      
  paths:
    include:
    - '/'
    exclude:
    - .dependabot/
    - .github/
    # don't trigger the CI if only docs files are changed
    - doc/*
    - '**/*.md'
    - '*.md'
    - 'build/cSpell.json'
    - 'build/.markdownlint.json'

resources:
  containers:
  - container: nv-bionic-wasm
    image: unoplatform/wasm-build:3.0
    # Ensures that Chromium has enough room to avoid net::ERR_INSUFFICIENT_RESOURCES errors
    options: "--shm-size=2gb"

variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  windows2019HostedVMImage: 'windows-2019'
  windows2022HostedVMImage: 'windows-2022'
  windowsScaledPool: 'Windows2022-20250720-1'
  linuxVMImage: 'ubuntu-22.04'
  linuxScaledPool: 'Ubuntu2204-20230918'
  macOSVMImage: 'macOS-15'
  macOSVMImage_UITests: 'macOS-14'
  xCodeRoot: '/Applications/Xcode_16.4.app'
  xCodeRoot_iOS_UITests: '/Applications/Xcode_15.3.app'

  # Offline validation to improve build performance
  NUGET_CERT_REVOCATION_MODE: offline

  # https://github.com/microsoft/azure-pipelines-tasks/issues/11864
  #enable_package_cache: true

  enable_dotnet_cache: true
  enable_emsdk_cache: true
  GlobalUnoCheckVersion: '1.33.0-dev.7'

stages:
- template: build/ci/.azure-devops-stages.yml
