trigger:
  branches:
    include:
      - master
      - release/beta/*
      - release/stable/*
      - feature/*

pr: 
  branches:
    include:
      - master
      - release/beta/*
      - release/stable/*
      - feature/*
      
  paths:
    include:
    - '/'
    exclude:
    - .dependabot/
    - .github/
    - '*.md'
    - .all-contributorsrc

resources:
  containers:
  - container: nv-bionic-wasm
    image: unoplatform/wasm-build:3.0

variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  windows2019HostedVMImage: 'windows-2019'
  windows2022HostedVMImage: 'windows-2022'
  windowsScaledPool: 'Windows2022-20211130'
  linuxVMImage: 'ubuntu-latest'
  macOSVMImage: 'macOS-11'
  macOSVMImage_UITests: 'macOS-10.15'
  xCodeRoot: '/Applications/Xcode_13.1.app'
  XamarinSDKVersion: 6_12_7
  xCodeRoot_iOS_UITests: '/Applications/Xcode_11.5.app'
  XamarinSDKVersion_iOS_UITests: 6_10_0

jobs:
- template: build/ci/.azure-devops-commitsar.yml
  parameters:
    vmImage: '$(linuxVMImage)'

- template: build/ci/.azure-devops-pipeline-validations.yml
  parameters:
    vmImage: '$(linuxVMImage)'

- template: build/ci/.azure-devops-package-generic.yml
  parameters:
    poolName: '$(windowsScaledPool)'

- template: build/ci/.azure-devops-package-net6-win.yml
  parameters:
    poolName: '$(windowsScaledPool)'

- template: build/ci/.azure-devops-package.yml
  parameters:
    poolName: '$(windowsScaledPool)'

- template: build/ci/.azure-devops-project-template-tests.yml
  parameters:
    vmImageWindows: '$(windows2022HostedVMImage)'
    vmImageLinux: '$(linuxVMImage)'

- template: build/ci/.azure-devops-uap.yml
  parameters:
    vmImage: '$(windows2022HostedVMImage)'

- template: build/ci/.azure-devops-unit-tests.yml
  parameters:
    vmImage: '$(windows2022HostedVMImage)'

- template: build/ci/.azure-devops-skia-tests.yml
  parameters:
    vmImage: '$(windows2022HostedVMImage)'
    vmMacImage: '$(macOSVMImage)'
    poolName: '$(windows2022HostedVMImage)'

- template: build/ci/.azure-devops-docs.yml
  parameters:
    vmImage: '$(windows2022HostedVMImage)'

- template: build/ci/.azure-devops-samplesapp-uitests-build.yml
  parameters:
    vmImage: '$(windows2022HostedVMImage)'

- template: build/ci/.azure-devops-wasm-uitests.yml
  parameters:
    vmImage: '$(linuxVMImage)'

- template: build/ci/.azure-devops-wasm-cs9-preview-validation.yml
  parameters:
    vmImage: '$(linuxVMImage)'

- template: build/ci/.azure-devops-macos.yml
  parameters:
    vmImage: '$(macOSVMImage)'
    xCodeRoot: '$(xCodeRoot)'
    XamarinSDKVersion: '$(XamarinSDKVersion)'

- template: build/ci/.azure-devops-android-tests.yml
  parameters:
    vmWindowsImage: '$(windows2019HostedVMImage)'
    vmMacOSImage: '$(macOSVMImage)'
    xCodeRoot: '$(xCodeRoot)'
    XamarinSDKVersion: '$(XamarinSDKVersion)'

- template: build/ci/.azure-devops-ios-tests.yml
  parameters:
    vmImage: '$(macOSVMImage)'
    vmImageTest: '$(macOSVMImage_UITests)'
    xCodeRootBuild: '$(xCodeRoot)'
    XamarinSDKVersionBuild: '$(XamarinSDKVersion)'
    xCodeRootTest: '$(xCodeRoot_iOS_UITests)'
    XamarinSDKVersionTest: '$(XamarinSDKVersion_iOS_UITests)'

- template: build/ci/.azure-devops-screenshot-compare.yml
  parameters:
    vmImage: '$(windows2022HostedVMImage)'

- template: build/ci/.azure-devops-vs2022-vsix.yml
  parameters:
    vmImage: '$(windows2022HostedVMImage)'
