trigger:
  branches:
    include:
      - master
      - release/beta/*
      - release/stable/*
      - feature/*
      - legacy/*

pr: 
  branches:
    include:
      - master
      - release/beta/*
      - release/stable/*
      - feature/*
      - legacy/*

variables:
  windowsScaledPool: 'Windows2022-20241021-1'
  linuxVMImage: 'ubuntu-22.04'

  enable_dotnet_cache: true
  enable_emsdk_cache: true
  GlobalUnoCheckVersion: '1.31.0-dev.12'

stages:
- template: build/ci/.azure-devops-stages-docs.yml
