trigger:
  branches:
    include:
      - master
      - release/beta/*
      - release/stable/*

pr: 
  branches:
    include:
      - master
      - release/beta/*
      - release/stable/*
      
resources:
  containers:
  - container: nv-bionic-wasm
    image: nventive/wasm-build:1.5

jobs:
- template: .azure-devops-windows.yml

# Disabled because not packaged
#- template: .azure-devops-docs.yml
#- template: .azure-devops-wasm-uitests.yml
#- template: .azure-devops-macos.yml
#- template: .azure-devops-android-tests.yml
#- template: .azure-devops-ios-tests.yml


