trigger:
  branches:
    include:
      - master
      - release/beta/*
      - release/stable/*
      - feature/*

pr: 
  branches:
    include:
      - master
      - release/beta/*
      - release/stable/*
      - feature/*

variables:
  windows2022HostedVMImage: 'windows-2022'
  linuxVMImage: 'ubuntu-latest'

jobs:
- template: build/ci/.azure-devops-commitsar.yml
  parameters:
    vmImage: '$(linuxVMImage)'

- template: build/ci/.azure-devops-pipeline-validations.yml
  parameters:
    vmImage: '$(linuxVMImage)'

- template: build/ci/.azure-devops-docs.yml
  parameters:
    vmImage: '$(windows2022HostedVMImage)'
