// <auto-generated>
#pragma warning disable 108 // new keyword hiding
#pragma warning disable 114 // new keyword hiding
namespace Microsoft.UI.Input
{
#if false
	public enum NonClientRegionKind
	{
		Close = 0,
		Maximize = 1,
		Minimize = 2,
		Icon = 3,
		Caption = 4,
		TopBorder = 5,
		LeftBorder = 6,
		BottomBorder = 7,
		RightBorder = 8,
		Passthrough = 9,
	}
#endif
}
