//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uno.UI.Tests.ResourceLoader.Strings.en {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Uno.UI.Tests.ResourceLoader.Strings.en.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App70-en.
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        internal static string button2Convert__using_Uno_UI_Tests_Windows_UI_Xaml_Markup_XUidTests_Controls_When_XUid_And_AttachedProperty_And_Conversion_KeyboardShortcutManager_VirtualKey {
            get {
                return ResourceManager.GetString("button2Convert.[using:Uno.UI.Tests.Windows_UI_Xaml_Markup.XUidTests.Controls]When" +
                        "_XUid_And_AttachedProperty_And_Conversion_KeyboardShortcutManager.VirtualKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text in &apos;en&apos;.
        /// </summary>
        internal static string Given_ResourceLoader_When_LocalizedResource {
            get {
                return ResourceManager.GetString("Given_ResourceLoader.When_LocalizedResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localized value.
        /// </summary>
        internal static string OpenVideosButton__using_Windows_UI_Xaml_Controls_ToolTipService_ToolTip {
            get {
                return ResourceManager.GetString("OpenVideosButton.[using:Windows.UI.Xaml.Controls]ToolTipService.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TestEmptyConverterText_ValueIfNotNull {
            get {
                return ResourceManager.GetString("TestEmptyConverterText.ValueIfNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        internal static string TestEmptyConverterText_ValueIfNull {
            get {
                return ResourceManager.GetString("TestEmptyConverterText.ValueIfNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TestEmptyResource {
            get {
                return ResourceManager.GetString("TestEmptyResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header in &apos;en&apos;.
        /// </summary>
        internal static string ThemeRadioButtons_Header {
            get {
                return ResourceManager.GetString("ThemeRadioButtons.Header", resourceCulture);
            }
        }
    }
}
