name: Q&A
description: Ask the community for help
body:

  - type: textarea
    id: question
    attributes:
      label: Describe your issue
      description: |
        - Explain your problem in the most specific way. Provide any relevant error logs, full stack traces of exceptions, browser logs, etc...
        - If you have a build error, [make sure to attach a binlog](https://aka.platform.uno/msbuild-troubleshoot)

  - type: textarea
    id: repro-steps
    attributes:
      label: Provide repro steps and sample
      description: |
        - Attach a [**minimal repro project**](https://aka.platform.uno/uno-repro-sample) and provide detailed **steps to reproduce**.
        - Make sure to attach the zip file to this discussion (you can use drag and drop of the zip file).

  - type: textarea
    id: nuget-versions
    attributes:
      label: NuGet package version(s)

  - type: checkboxes
    id: renderer
    attributes:
      label: Renderer
      multiple: true
      options:

        - Skia
        - Native

  - type: dropdown
    id: platforms
    attributes:
      label: Affected platforms
      multiple: true
      options:        
        - WebAssembly
        - Android
        - iOS
        - Desktop (Windows)
        - Desktop (macOS)
        - Desktop (X11)
        - Desktop (Linux Framebuffer)
        - Windows App SDK
        - Build tasks

  - type: dropdown
    id: ide
    attributes:
      label: IDE
      multiple: true
      options:
        - Visual Studio 2022
        - Visual Studio Code
        - Rider Windows
        - Rider macOS
        - Rider Linux
