namespace Microsoft.UI.Xaml.Input;

partial class StandardUICommand
{
	private const string TEXT_COMMAND_LABEL_CUT = nameof(TEXT_COMMAND_LABEL_CUT);
	private const string TEXT_COMMAND_LABEL_COPY = nameof(TEXT_COMMAND_LABEL_COPY);
	private const string TEXT_COMMAND_LABEL_PASTE = nameof(TEXT_COMMAND_LABEL_PASTE);
	private const string TEXT_COMMAND_LABEL_SELECTALL = nameof(TEXT_COMMAND_LABEL_SELECTALL);
	private const string TEXT_COMMAND_LABEL_DELETE = nameof(TEXT_COMMAND_LABEL_DELETE);
	private const string TEXT_COMMAND_LABEL_SHARE = nameof(TEXT_COMMAND_LABEL_SHARE);
	private const string TEXT_COMMAND_LABEL_SAVE = nameof(TEXT_COMMAND_LABEL_SAVE);
	private const string TEXT_COMMAND_LABEL_OPEN = nameof(TEXT_COMMAND_LABEL_OPEN);
	private const string TEXT_COMMAND_LABEL_CLOSE = nameof(TEXT_COMMAND_LABEL_CLOSE);
	private const string TEXT_COMMAND_LABEL_PAUSE = nameof(TEXT_COMMAND_LABEL_PAUSE);
	private const string TEXT_COMMAND_LABEL_PLAY = nameof(TEXT_COMMAND_LABEL_PLAY);
	private const string TEXT_COMMAND_LABEL_STOP = nameof(TEXT_COMMAND_LABEL_STOP);
	private const string TEXT_COMMAND_LABEL_FORWARD = nameof(TEXT_COMMAND_LABEL_FORWARD);
	private const string TEXT_COMMAND_LABEL_BACKWARD = nameof(TEXT_COMMAND_LABEL_BACKWARD);
	private const string TEXT_COMMAND_LABEL_UNDO = nameof(TEXT_COMMAND_LABEL_UNDO);
	private const string TEXT_COMMAND_LABEL_REDO = nameof(TEXT_COMMAND_LABEL_REDO);

	private const string TEXT_COMMAND_DESCRIPTION_CUT = nameof(TEXT_COMMAND_DESCRIPTION_CUT);
	private const string TEXT_COMMAND_DESCRIPTION_COPY = nameof(TEXT_COMMAND_DESCRIPTION_COPY);
	private const string TEXT_COMMAND_DESCRIPTION_PASTE = nameof(TEXT_COMMAND_DESCRIPTION_PASTE);
	private const string TEXT_COMMAND_DESCRIPTION_SELECTALL = nameof(TEXT_COMMAND_DESCRIPTION_SELECTALL);
	private const string TEXT_COMMAND_DESCRIPTION_DELETE = nameof(TEXT_COMMAND_DESCRIPTION_DELETE);
	private const string TEXT_COMMAND_DESCRIPTION_SHARE = nameof(TEXT_COMMAND_DESCRIPTION_SHARE);
	private const string TEXT_COMMAND_DESCRIPTION_SAVE = nameof(TEXT_COMMAND_DESCRIPTION_SAVE);
	private const string TEXT_COMMAND_DESCRIPTION_OPEN = nameof(TEXT_COMMAND_DESCRIPTION_OPEN);
	private const string TEXT_COMMAND_DESCRIPTION_CLOSE = nameof(TEXT_COMMAND_DESCRIPTION_CLOSE);
	private const string TEXT_COMMAND_DESCRIPTION_PAUSE = nameof(TEXT_COMMAND_DESCRIPTION_PAUSE);
	private const string TEXT_COMMAND_DESCRIPTION_PLAY = nameof(TEXT_COMMAND_DESCRIPTION_PLAY);
	private const string TEXT_COMMAND_DESCRIPTION_STOP = nameof(TEXT_COMMAND_DESCRIPTION_STOP);
	private const string TEXT_COMMAND_DESCRIPTION_FORWARD = nameof(TEXT_COMMAND_DESCRIPTION_FORWARD);
	private const string TEXT_COMMAND_DESCRIPTION_BACKWARD = nameof(TEXT_COMMAND_DESCRIPTION_BACKWARD);
	private const string TEXT_COMMAND_DESCRIPTION_UNDO = nameof(TEXT_COMMAND_DESCRIPTION_UNDO);
	private const string TEXT_COMMAND_DESCRIPTION_REDO = nameof(TEXT_COMMAND_DESCRIPTION_REDO);

	private const string TEXT_COMMAND_KEYBOARDACCELERATORKEY_CUT = nameof(TEXT_COMMAND_KEYBOARDACCELERATORKEY_CUT);
	private const string TEXT_COMMAND_KEYBOARDACCELERATORKEY_COPY = nameof(TEXT_COMMAND_KEYBOARDACCELERATORKEY_COPY);
	private const string TEXT_COMMAND_KEYBOARDACCELERATORKEY_PASTE = nameof(TEXT_COMMAND_KEYBOARDACCELERATORKEY_PASTE);
	private const string TEXT_COMMAND_KEYBOARDACCELERATORKEY_SELECTALL = nameof(TEXT_COMMAND_KEYBOARDACCELERATORKEY_SELECTALL);
	private const string TEXT_COMMAND_KEYBOARDACCELERATORKEY_SAVE = nameof(TEXT_COMMAND_KEYBOARDACCELERATORKEY_SAVE);
	private const string TEXT_COMMAND_KEYBOARDACCELERATORKEY_OPEN = nameof(TEXT_COMMAND_KEYBOARDACCELERATORKEY_OPEN);
	private const string TEXT_COMMAND_KEYBOARDACCELERATORKEY_CLOSE = nameof(TEXT_COMMAND_KEYBOARDACCELERATORKEY_CLOSE);
	private const string TEXT_COMMAND_KEYBOARDACCELERATORKEY_UNDO = nameof(TEXT_COMMAND_KEYBOARDACCELERATORKEY_UNDO);
	private const string TEXT_COMMAND_KEYBOARDACCELERATORKEY_REDO = nameof(TEXT_COMMAND_KEYBOARDACCELERATORKEY_REDO);
}
