using System.Diagnostics.CodeAnalysis;

// Legacy code that predates EnforceExtendedAnalyzerRules. Suppressed per type so new generators and analyzers stay checked.
[assembly: SuppressMessage("MicrosoftCodeAnalysisCompatibility", "RS1042:Implementations of this interface are not allowed", Justification = "Legacy ISourceGenerator, not yet migrated to IIncrementalGenerator.", Scope = "type", Target = "~T:Uno.UI.SourceGenerators.TSBindings.TSBindingsGenerator")]
[assembly: SuppressMessage("MicrosoftCodeAnalysisCorrectness", "RS1035:Do not use APIs banned for analyzers", Justification = "Legacy ISourceGenerator that writes the TypeScript bindings to disk by design.", Scope = "type", Target = "~T:Uno.UI.SourceGenerators.TSBindings.TSBindingsGenerator")]
[assembly: SuppressMessage("MicrosoftCodeAnalysisCorrectness", "RS1035:Do not use APIs banned for analyzers", Justification = "Shared ISourceGenerator helper, also compiled into Uno.UI.SourceGenerators.", Scope = "type", Target = "~T:Uno.Roslyn.GeneratorExecutionContextExtensions")]
[assembly: SuppressMessage("MicrosoftCodeAnalysisCorrectness", "RS1035:Do not use APIs banned for analyzers", Justification = "Shared ISourceGenerator helper, also compiled into Uno.UI.SourceGenerators.", Scope = "type", Target = "~T:Uno.Roslyn.MSBuildItem")]
[assembly: SuppressMessage("MicrosoftCodeAnalysisCorrectness", "RS1035:Do not use APIs banned for analyzers", Justification = "Shared ISourceGenerator helper, also compiled into Uno.UI.SourceGenerators.", Scope = "type", Target = "~T:Uno.UI.SourceGenerators.Helpers.PlatformHelper")]
[assembly: SuppressMessage("MicrosoftCodeAnalysisCorrectness", "RS1035:Do not use APIs banned for analyzers", Justification = "Shared Roslyn ObjectPool sizes itself from Environment.ProcessorCount.", Scope = "member", Target = "~M:Microsoft.CodeAnalysis.PooledObjects.ObjectPool`1.#ctor(Microsoft.CodeAnalysis.PooledObjects.ObjectPool{`0}.Factory)")]

// RS1038 fires on every compiler extension because BoxingCodeFixProvider needs Workspaces. None of these use Workspaces APIs, and csc never loads the code fix.
[assembly: SuppressMessage("MicrosoftCodeAnalysisCorrectness", "RS1038:Compiler extensions should be implemented in assemblies with compiler-provided references", Justification = "Uses no Workspaces API.", Scope = "type", Target = "~T:Uno.UI.SourceGenerators.Internal.BoxingDiagnosticAnalyzer")]
[assembly: SuppressMessage("MicrosoftCodeAnalysisCorrectness", "RS1038:Compiler extensions should be implemented in assemblies with compiler-provided references", Justification = "Uses no Workspaces API.", Scope = "type", Target = "~T:Uno.UI.SourceGenerators.Internal.ObservableVectorAnalyzer")]
[assembly: SuppressMessage("MicrosoftCodeAnalysisCorrectness", "RS1038:Compiler extensions should be implemented in assemblies with compiler-provided references", Justification = "Uses no Workspaces API.", Scope = "type", Target = "~T:Uno.UI.SourceGenerators.DependencyObject.DependencyPropertyGenerator")]
[assembly: SuppressMessage("MicrosoftCodeAnalysisCorrectness", "RS1038:Compiler extensions should be implemented in assemblies with compiler-provided references", Justification = "Uses no Workspaces API.", Scope = "type", Target = "~T:Uno.UI.SourceGenerators.Mixins.DependencyPropertyMixinGenerator")]
[assembly: SuppressMessage("MicrosoftCodeAnalysisCorrectness", "RS1038:Compiler extensions should be implemented in assemblies with compiler-provided references", Justification = "Uses no Workspaces API.", Scope = "type", Target = "~T:Uno.UI.SourceGenerators.TSBindings.TSBindingsGenerator")]
