<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>$(NetSkiaPreviousAndCurrent)</TargetFrameworks>
	</PropertyGroup>

	<Import Project="../targetframework-override.props"/>

	<PropertyGroup>
		<AssemblyName>Uno.UI.Extras</AssemblyName>
		<RootNamespace>Uno.UI.Extras</RootNamespace>
		<DefaultLanguage>en-US</DefaultLanguage>

		<ProduceReferenceAssembly>false</ProduceReferenceAssembly>
		<Deterministic>true</Deterministic>

		<UnoRuntimeFlavor>Generic</UnoRuntimeFlavor>
		<PlatformItemsBasePath>.\</PlatformItemsBasePath>

		<UnoXamlResourcesTrimming>true</UnoXamlResourcesTrimming>

		<UseCommonOverridePackage>true</UseCommonOverridePackage>
		<CommonOverridePackageId>Uno.UI</CommonOverridePackageId>
	</PropertyGroup>

	<ItemGroup>
		<Compile Include="..\Uno.UI\Behaviors\VisibleBoundsPadding.cs" Link="VisibleBoundsPadding.cs" />
	</ItemGroup>

	<PropertyGroup>
		<UnoUIMSBuildTasksPath>$(MSBuildThisFileDirectory)..\SourceGenerators\Uno.UI.Tasks\bin\$(Configuration)_Shadow</UnoUIMSBuildTasksPath>
	</PropertyGroup>

	<ItemGroup>
		<EmbeddedResource Include="LinkerDefinition.net6.0.xml">
			<LogicalName>$(AssemblyName).xml</LogicalName>
		</EmbeddedResource>
	</ItemGroup>

	<Import Project="..\SourceGenerators\Uno.UI.Tasks\Content\Uno.UI.Tasks.targets" Condition="'$(SkipUnoResourceGeneration)' == '' " />

	<ItemGroup>
		<ProjectReference Include="..\Uno.UI\Uno.UI.csproj">
		</ProjectReference>
		<ProjectReference Include="..\Uno.WinRT\Uno.WinRT.Reference.csproj">
		</ProjectReference>
		<ProjectReference Include="..\Uno.Foundation\Uno.Foundation.Reference.csproj">
		</ProjectReference>
	</ItemGroup>

	<!-- Override existing target, this project cannot be published -->
	<Target Name="Publish" />

	<Import Project="..\SourceGenerators\Uno.UI.SourceGenerators\Content\Uno.UI.SourceGenerators.props" />

</Project>
