namespace Windows.UI.Xaml.Automation.Peers;

/// <summary>
/// Specifies the control type that is exposed to the Microsoft UI Automation client. Used by GetAutomationControlType.
/// </summary>
public enum AutomationControlType
{
	Button = 0,
	Calendar = 1,
	CheckBox = 2,
	ComboBox = 3,
	Edit = 4,
	Hyperlink = 5,
	Image = 6,
	ListItem = 7,
	List = 8,
	Menu = 9,
	MenuBar = 10,
	MenuItem = 11,
	ProgressBar = 12,
	RadioButton = 13,
	ScrollBar = 14,
	Slider = 15,
	Spinner = 16,
	StatusBar = 17,
	Tab = 18,
	TabItem = 19,
	Text = 20,
	ToolBar = 21,
	ToolTip = 22,
	Tree = 23,
	TreeItem = 24,
	Custom = 25,
	Group = 26,
	Thumb = 27,
	DataGrid = 28,
	DataItem = 29,
	Document = 30,
	SplitButton = 31,
	Window = 32,
	Pane = 33,
	Header = 34,
	HeaderItem = 35,
	Table = 36,
	TitleBar = 37,
	Separator = 38,
	SemanticZoom = 39,
	AppBar = 40,
}
