using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Testing;
using Microsoft.CodeAnalysis.Text;
using System.Text;
using Uno.UI.SourceGenerators.Tests.Verifiers;
using Uno.UI.SourceGenerators.XamlGenerator;

namespace Uno.UI.SourceGenerators.Tests.XamlCodeBehindGeneratorTests;

using Verify = CSharpIncrementalSourceGeneratorVerifier<XamlCodeBehindGenerator>;

[TestClass]
public class XamlCodeBehindGeneratorTests
{
	/// <summary>
	/// Minimal WinUI type stubs needed to compile generated code-behind.
	/// </summary>
	private const string WinUIStubs = """
		namespace Microsoft.UI.Xaml.Controls
		{
			public class Page { public void InitializeComponent() { } }
			public class UserControl { public void InitializeComponent() { } }
			public class ContentDialog { public void InitializeComponent() { } }
		}
		namespace Microsoft.UI.Xaml
		{
			public class Window { public void InitializeComponent() { } }
			public class Application { public void InitializeComponent() { } }
			public class ResourceDictionary { }
		}
		""";

	private const string SimplePageXaml = """
		<Page x:Class="MyApp.MainPage"
		      xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
		      xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
		    <TextBlock Text="Hello" />
		</Page>
		""";

	private const string UserControlXaml = """
		<UserControl x:Class="MyApp.Controls.MyUserControl"
		             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
		             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
		    <TextBlock Text="Hello" />
		</UserControl>
		""";

	private const string WindowXaml = """
		<Window x:Class="MyApp.MainWindow"
		        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
		        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
		</Window>
		""";

	private const string ContentDialogXaml = """
		<ContentDialog x:Class="MyApp.Dialogs.MyDialog"
		               xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
		               xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
		</ContentDialog>
		""";

	private const string NoXClassXaml = """
		<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
		                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
		</ResourceDictionary>
		""";

	private const string ApplicationXaml = """
		<Application x:Class="MyApp.App"
		             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
		             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
		</Application>
		""";

	private const string MalformedXClassXaml = """
		<Page x:Class="MainPageWithoutNamespace"
		      xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
		      xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
		</Page>
		""";

	private static Verify.Test CreateTest(
		string xamlContent,
		string xamlFileName = "MainPage.xaml",
		string? sourceItemGroup = "Page",
		string? perFileGenerateCodeBehind = null,
		string? globalGenerateCodeBehind = null,
		string? existingCodeBehind = null)
	{
		var test = new Verify.Test();

		// Always include WinUI stubs so generated code compiles
		test.TestState.Sources.Add(WinUIStubs);

		// Build global config with build properties and per-file metadata
		var configBuilder = new StringBuilder();
		configBuilder.AppendLine("is_global = true");

		if (globalGenerateCodeBehind is not null)
		{
			configBuilder.AppendLine($"build_property.UnoGenerateCodeBehind = {globalGenerateCodeBehind}");
		}

		configBuilder.AppendLine();

		if (sourceItemGroup is not null)
		{
			configBuilder.AppendLine($"[C:/Project/0/{xamlFileName}]");
			configBuilder.AppendLine($"build_metadata.AdditionalFiles.SourceItemGroup = {sourceItemGroup}");

			if (perFileGenerateCodeBehind is not null)
			{
				configBuilder.AppendLine($"build_metadata.AdditionalFiles.UnoGenerateCodeBehind = {perFileGenerateCodeBehind}");
			}
		}

		test.TestState.AnalyzerConfigFiles.Add(("/.globalconfig", configBuilder.ToString()));
		test.TestState.AdditionalFiles.Add(($"C:/Project/0/{xamlFileName}", xamlContent));

		if (existingCodeBehind is not null)
		{
			test.TestState.Sources.Add(existingCodeBehind);
		}

		return test;
	}

	// T015: XAML with x:Class and no code-behind generates correct partial class
	[TestMethod]
	public async Task XamlWithXClass_NoCodeBehind_GeneratesPartialClass()
	{
		var test = CreateTest(SimplePageXaml);
		test.TestState.GeneratedSources.Add(
			(typeof(XamlCodeBehindGenerator), "MyApp.MainPage.codebehind.g.cs", SourceText.From("""
				// <auto-generated>
				// This file was auto-generated by Uno.UI.SourceGenerators.
				// Do not edit this file manually.
				// </auto-generated>

				namespace MyApp
				{
					partial class MainPage : Microsoft.UI.Xaml.Controls.Page
					{
						public MainPage()
						{
							this.InitializeComponent();
						}
					}
				}

				""", Encoding.UTF8)));
		await test.RunAsync();
	}

	// T016: XAML with x:Class and existing code-behind produces no generated output
	[TestMethod]
	public async Task XamlWithXClass_ExistingCodeBehind_NoOutput()
	{
		var existingCodeBehind = """
			namespace MyApp
			{
				public partial class MainPage : Microsoft.UI.Xaml.Controls.Page
				{
					public MainPage()
					{
						this.InitializeComponent();
					}
				}
			}
			""";

		var test = CreateTest(SimplePageXaml, existingCodeBehind: existingCodeBehind);
		// No generated sources expected
		await test.RunAsync();
	}

	// T017: XAML with x:Class where class exists in non-conventional file
	[TestMethod]
	public async Task XamlWithXClass_ClassInNonConventionalFile_NoOutput()
	{
		// The class is defined but not in a .xaml.cs file
		var existingClass = """
			namespace MyApp
			{
				public partial class MainPage : Microsoft.UI.Xaml.Controls.Page
				{
					public MainPage()
					{
						this.InitializeComponent();
					}
				}
			}
			""";

		var test = CreateTest(SimplePageXaml, existingCodeBehind: existingClass);
		// No generated sources expected - class exists in compilation
		await test.RunAsync();
	}

	// T018: XAML with no x:Class produces no generated output
	[TestMethod]
	public async Task XamlWithNoXClass_NoOutput()
	{
		var test = CreateTest(NoXClassXaml, xamlFileName: "Styles.xaml");
		// No generated sources expected
		await test.RunAsync();
	}

	// T019: Malformed x:Class emits UNOB0001 diagnostic
	[TestMethod]
	public async Task MalformedXClass_EmitsDiagnostic()
	{
		var test = CreateTest(MalformedXClassXaml);
		test.TestState.ExpectedDiagnostics.Add(
			new DiagnosticResult("UNOB0001", DiagnosticSeverity.Warning));
		await test.RunAsync();
	}

	// T020: Correct base type resolution for different root elements
	[TestMethod]
	public async Task UserControl_CorrectBaseType()
	{
		var test = CreateTest(UserControlXaml, xamlFileName: "MyUserControl.xaml");
		test.TestState.GeneratedSources.Add(
			(typeof(XamlCodeBehindGenerator), "MyApp.Controls.MyUserControl.codebehind.g.cs", SourceText.From("""
				// <auto-generated>
				// This file was auto-generated by Uno.UI.SourceGenerators.
				// Do not edit this file manually.
				// </auto-generated>

				namespace MyApp.Controls
				{
					partial class MyUserControl : Microsoft.UI.Xaml.Controls.UserControl
					{
						public MyUserControl()
						{
							this.InitializeComponent();
						}
					}
				}

				""", Encoding.UTF8)));
		await test.RunAsync();
	}

	[TestMethod]
	public async Task Window_CorrectBaseType()
	{
		var test = CreateTest(WindowXaml, xamlFileName: "MainWindow.xaml");
		test.TestState.GeneratedSources.Add(
			(typeof(XamlCodeBehindGenerator), "MyApp.MainWindow.codebehind.g.cs", SourceText.From("""
				// <auto-generated>
				// This file was auto-generated by Uno.UI.SourceGenerators.
				// Do not edit this file manually.
				// </auto-generated>

				namespace MyApp
				{
					partial class MainWindow : Microsoft.UI.Xaml.Window
					{
						public MainWindow()
						{
							this.InitializeComponent();
						}
					}
				}

				""", Encoding.UTF8)));
		await test.RunAsync();
	}

	[TestMethod]
	public async Task ContentDialog_CorrectBaseType()
	{
		var test = CreateTest(ContentDialogXaml, xamlFileName: "MyDialog.xaml");
		test.TestState.GeneratedSources.Add(
			(typeof(XamlCodeBehindGenerator), "MyApp.Dialogs.MyDialog.codebehind.g.cs", SourceText.From("""
				// <auto-generated>
				// This file was auto-generated by Uno.UI.SourceGenerators.
				// Do not edit this file manually.
				// </auto-generated>

				namespace MyApp.Dialogs
				{
					partial class MyDialog : Microsoft.UI.Xaml.Controls.ContentDialog
					{
						public MyDialog()
						{
							this.InitializeComponent();
						}
					}
				}

				""", Encoding.UTF8)));
		await test.RunAsync();
	}

	// T031: ApplicationDefinition (App.xaml) generates correct code-behind
	[TestMethod]
	public async Task ApplicationDefinition_CorrectBaseType()
	{
		var test = CreateTest(ApplicationXaml, xamlFileName: "App.xaml", sourceItemGroup: "ApplicationDefinition");
		test.TestState.GeneratedSources.Add(
			(typeof(XamlCodeBehindGenerator), "MyApp.App.codebehind.g.cs", SourceText.From("""
				// <auto-generated>
				// This file was auto-generated by Uno.UI.SourceGenerators.
				// Do not edit this file manually.
				// </auto-generated>

				namespace MyApp
				{
					partial class App : Microsoft.UI.Xaml.Application
					{
						public App()
						{
							this.InitializeComponent();
						}
					}
				}

				""", Encoding.UTF8)));
		await test.RunAsync();
	}

	// T032: Existing code-behind means no generation (backward compat)
	[TestMethod]
	public async Task ExistingCodeBehind_BackwardCompatible_NoNewOutput()
	{
		var existingCodeBehind = """
			namespace MyApp
			{
				public partial class MainPage : Microsoft.UI.Xaml.Controls.Page
				{
					public MainPage()
					{
						this.InitializeComponent();
					}
					public void CustomMethod() { }
				}
			}
			""";

		var test = CreateTest(SimplePageXaml, existingCodeBehind: existingCodeBehind);
		// No generated sources expected - existing code-behind preserved
		await test.RunAsync();
	}

	// T025: UnoGenerateCodeBehind=false suppresses generation
	[TestMethod]
	public async Task GlobalDisabled_NoOutput()
	{
		var test = CreateTest(SimplePageXaml, globalGenerateCodeBehind: "false");
		// No generated sources expected
		await test.RunAsync();
	}

	// T026: Per-file GenerateCodeBehind=false overrides global true
	[TestMethod]
	public async Task PerFileDisabled_OverridesGlobalTrue()
	{
		var test = CreateTest(SimplePageXaml, perFileGenerateCodeBehind: "false", globalGenerateCodeBehind: "true");
		// No generated sources expected
		await test.RunAsync();
	}

	// T033: Output parity - standalone emitter produces expected format
	[TestMethod]
	public void CrossPathOutputParity_EmitterProducesCorrectFormat()
	{
		var info = new XamlClassInfo(
			FullClassName: "MyApp.MainPage",
			Namespace: "MyApp",
			ClassName: "MainPage",
			RootElementName: "Page",
			RootElementNamespace: "http://schemas.microsoft.com/winfx/2006/xaml/presentation",
			BaseTypeFullName: "Microsoft.UI.Xaml.Controls.Page");

		var output = XamlCodeBehindEmitter.Emit(info);
		Assert.IsTrue(output.Contains("partial class MainPage : Microsoft.UI.Xaml.Controls.Page"));
		Assert.IsTrue(output.Contains("this.InitializeComponent()"));
		Assert.IsTrue(output.Contains("namespace MyApp"));
		Assert.IsTrue(output.Contains("// <auto-generated>"));

		var hintName = XamlCodeBehindEmitter.GetHintName(info);
		Assert.AreEqual("MyApp.MainPage.codebehind.g.cs", hintName);
	}

	// T035: Files without valid SourceItemGroup are skipped
	[TestMethod]
	public async Task NonPageSourceItemGroup_NoOutput()
	{
		var test = CreateTest(SimplePageXaml, sourceItemGroup: null);
		// No generated sources expected - no SourceItemGroup metadata
		await test.RunAsync();
	}

	// T027: Per-file GenerateCodeBehind=true overrides global false
	[TestMethod]
	public async Task PerFileEnabled_OverridesGlobalFalse()
	{
		var test = CreateTest(SimplePageXaml, perFileGenerateCodeBehind: "true", globalGenerateCodeBehind: "false");
		test.TestState.GeneratedSources.Add(
			(typeof(XamlCodeBehindGenerator), "MyApp.MainPage.codebehind.g.cs", SourceText.From("""
				// <auto-generated>
				// This file was auto-generated by Uno.UI.SourceGenerators.
				// Do not edit this file manually.
				// </auto-generated>

				namespace MyApp
				{
					partial class MainPage : Microsoft.UI.Xaml.Controls.Page
					{
						public MainPage()
						{
							this.InitializeComponent();
						}
					}
				}

				""", Encoding.UTF8)));
		await test.RunAsync();
	}
}
