// <auto-generated>
#pragma warning disable 108 // new keyword hiding
#pragma warning disable 114 // new keyword hiding
using System;
using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Automation;
using Microsoft.UI.Xaml.Controls;

namespace Microsoft.UI.Xaml.Automation.Peers;

public partial class ListViewBaseHeaderItemAutomationPeer : FrameworkElementAutomationPeer
{
	protected ListViewBaseHeaderItemAutomationPeer(ListViewBaseHeaderItem owner) : base(owner)
	{
		ArgumentNullException.ThrowIfNull(owner);
	}

	protected override string GetClassNameCore() => nameof(ListViewBaseHeaderItem);

	protected override AutomationControlType GetAutomationControlTypeCore()
		=> AutomationControlType.Group;

	internal ItemsControlAutomationPeer? GetParentItemsControlAutomationPeer()
	{
		if (Owner is not ListViewBaseHeaderItem header)
		{
			return null;
		}

		var parentControl = ItemsControl.ItemsControlFromItemContainer(header);
		if (parentControl is FrameworkElement element)
		{
			return FrameworkElementAutomationPeer.FromElement(element) as ItemsControlAutomationPeer
				?? FrameworkElementAutomationPeer.CreatePeerForElement(element) as ItemsControlAutomationPeer;
		}

		return null;
	}
}
