// <auto-generated>
#pragma warning disable 108 // new keyword hiding
#pragma warning disable 114 // new keyword hiding
using System;
using Microsoft.UI.Xaml.Automation;
using Microsoft.UI.Xaml.Controls;

namespace Microsoft.UI.Xaml.Automation.Peers;

public partial class MenuBarAutomationPeer : FrameworkElementAutomationPeer
{
	public MenuBarAutomationPeer(MenuBar owner) : base(owner)
	{
		ArgumentNullException.ThrowIfNull(owner);
	}

	protected override AutomationControlType GetAutomationControlTypeCore()
		=> AutomationControlType.MenuBar;

	protected override string GetClassNameCore()
		=> nameof(MenuBar);
}
