// <auto-generated>
#pragma warning disable 108 // new keyword hiding
#pragma warning disable 114 // new keyword hiding
using System;
using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Automation;
using Microsoft.UI.Xaml.Automation.Provider;
using Microsoft.UI.Xaml.Controls;

namespace Microsoft.UI.Xaml.Automation.Peers;

/// <summary>
/// Exposes TreeViewItem data types to Microsoft UI Automation.
/// </summary>
public partial class TreeViewItemDataAutomationPeer : ItemAutomationPeer, IExpandCollapseProvider
{
	private const string ElementNotEnabledMessage = "Element not enabled";

	/// <summary>
	/// Initializes a new instance of the TreeViewItemDataAutomationPeer class.
	/// </summary>
	/// <param name="item">The TreeView item.</param>
	/// <param name="parent">The parent automation peer.</param>
	public TreeViewItemDataAutomationPeer(object item, TreeViewListAutomationPeer parent)
		: base(item, parent)
	{
	}

	public ExpandCollapseState ExpandCollapseState
	{
		get
		{
			var peer = GetTreeViewItemAutomationPeer();
			return peer?.ExpandCollapseState ?? throw new InvalidOperationException(ElementNotEnabledMessage);
		}
	}

	public void Collapse()
	{
		var peer = GetTreeViewItemAutomationPeer();
		if (peer == null)
		{
			throw new InvalidOperationException(ElementNotEnabledMessage);
		}

		peer.Collapse();
	}

	public void Expand()
	{
		var peer = GetTreeViewItemAutomationPeer();
		if (peer == null)
		{
			throw new InvalidOperationException(ElementNotEnabledMessage);
		}

		peer.Expand();
	}

	protected override object GetPatternCore(PatternInterface patternInterface)
	{
		if (patternInterface == PatternInterface.ExpandCollapse)
		{
			return this;
		}

		return base.GetPatternCore(patternInterface);
	}

	private TreeViewItemAutomationPeer? GetTreeViewItemAutomationPeer()
	{
		var containerPeer = GetContainerPeer() as TreeViewItemAutomationPeer;
		if (containerPeer != null)
		{
			return containerPeer;
		}

		var itemsControl = ItemsControlAutomationPeer?.Owner as ItemsControl;
		var container = itemsControl?.ContainerFromItem(Item) as UIElement;
		if (container != null)
		{
			return FrameworkElementAutomationPeer.CreatePeerForElement(container) as TreeViewItemAutomationPeer
				?? container.GetOrCreateAutomationPeer() as TreeViewItemAutomationPeer;
		}

		return null;
	}
}
