#if __SKIA__
﻿//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//       Command:
//           LottieGen -Language CSharp -Public -WinUIVersion 3.0 -InputFile HamburgerArrow.json
//       
//       Input file:
//           HamburgerArrow.json (6209 bytes created 18:59+02:00 Jul 3 2026)
//       
//       LottieGen source:
//           http://aka.ms/Lottie
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ____________________________________
// |       Object stats       | Count |
// |__________________________|_______|
// | All CompositionObjects   |    60 |
// |--------------------------+-------|
// | Expression animators     |     1 |
// | KeyFrame animators       |     7 |
// | Reference parameters     |     1 |
// | Expression operations    |     0 |
// |--------------------------+-------|
// | Animated brushes         |     - |
// | Animated gradient stops  |     - |
// | ExpressionAnimations     |     1 |
// | PathKeyFrameAnimations   |     - |
// |--------------------------+-------|
// | ContainerVisuals         |     1 |
// | ShapeVisuals             |     1 |
// |--------------------------+-------|
// | ContainerShapes          |     1 |
// | CompositionSpriteShapes  |     3 |
// |--------------------------+-------|
// | Brushes                  |     1 |
// | Gradient stops           |     - |
// | CompositionVisualSurface |     - |
// ------------------------------------
using Microsoft.Graphics;
using Microsoft.Graphics.Canvas.Geometry;
using Microsoft.UI.Composition;
using System;
using System.Collections.Generic;
using System.Numerics;
using Windows.UI;

namespace AnimatedVisuals
{
    // Frame rate:  30 fps
    // Frame count: 180
    // Duration:    6000.0 mS
    public sealed class HamburgerArrow
        : Microsoft.UI.Xaml.Controls.IAnimatedVisualSource
        , Microsoft.UI.Xaml.Controls.IAnimatedVisualSource2
    {
        // Animation duration: 6.000 seconds.
        internal const long c_durationTicks = 60000000;

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor)
        {
            object ignored = null;
            return TryCreateAnimatedVisual(compositor, out ignored);
        }

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor, out object diagnostics)
        {
            diagnostics = null;

            var res = 
                new HamburgerArrow_AnimatedVisual(
                    compositor
                    );
                res.CreateAnimations();
                return res;
        }

        /// <summary>
        /// Gets the number of frames in the animation.
        /// </summary>
        public double FrameCount => 180d;

        /// <summary>
        /// Gets the frame rate of the animation.
        /// </summary>
        public double Framerate => 30d;

        /// <summary>
        /// Gets the duration of the animation.
        /// </summary>
        public TimeSpan Duration => TimeSpan.FromTicks(60000000);

        /// <summary>
        /// Converts a zero-based frame number to the corresponding progress value denoting the
        /// start of the frame.
        /// </summary>
        public double FrameToProgress(double frameNumber)
        {
            return frameNumber / 180d;
        }

        /// <summary>
        /// Returns a map from marker names to corresponding progress values.
        /// </summary>
        public IReadOnlyDictionary<string, double> Markers =>
            new Dictionary<string, double>
            {
            };

        /// <summary>
        /// Sets the color property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetColorProperty(string propertyName, Color value)
        {
        }

        /// <summary>
        /// Sets the scalar property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetScalarProperty(string propertyName, double value)
        {
        }

        sealed class HamburgerArrow_AnimatedVisual
            : Microsoft.UI.Xaml.Controls.IAnimatedVisual
            , Microsoft.UI.Xaml.Controls.IAnimatedVisual2
        {
            const long c_durationTicks = 60000000;
            readonly Compositor _c;
            readonly ExpressionAnimation _reusableExpressionAnimation;
            AnimationController _animationController_0;
            CompositionColorBrush _colorBrush_AlmostDarkSlateBlue_FF6628B2;
            CompositionContainerShape _containerShape;
            CompositionPathGeometry _pathGeometry_0;
            CompositionPathGeometry _pathGeometry_2;
            CompositionSpriteShape _spriteShape_0;
            CompositionSpriteShape _spriteShape_2;
            ContainerVisual _root;
            CubicBezierEasingFunction _cubicBezierEasingFunction_0;
            CubicBezierEasingFunction _cubicBezierEasingFunction_1;
            CubicBezierEasingFunction _cubicBezierEasingFunction_2;
            CubicBezierEasingFunction _cubicBezierEasingFunction_3;
            ScalarKeyFrameAnimation _trimStartScalarAnimation_0_to_0;
            StepEasingFunction _holdThenStepEasingFunction;
            StepEasingFunction _stepThenHoldEasingFunction;

            void BindProperty(
                CompositionObject target,
                string animatedPropertyName,
                string expression,
                string referenceParameterName,
                CompositionObject referencedObject)
            {
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = expression;
                _reusableExpressionAnimation.SetReferenceParameter(referenceParameterName, referencedObject);
                target.StartAnimation(animatedPropertyName, _reusableExpressionAnimation);
            }

            ScalarKeyFrameAnimation CreateScalarKeyFrameAnimation(float initialProgress, float initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateScalarKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            Vector2KeyFrameAnimation CreateVector2KeyFrameAnimation(float initialProgress, Vector2 initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateVector2KeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            CompositionSpriteShape CreateSpriteShape(CompositionGeometry geometry, Matrix3x2 transformMatrix)
            {
                var result = _c.CreateSpriteShape(geometry);
                result.TransformMatrix = transformMatrix;
                return result;
            }

            AnimationController AnimationController_0()
            {
                if (_animationController_0 != null) { return _animationController_0; }
                var result = _animationController_0 = _c.CreateAnimationController();
                result.Pause();
                BindProperty(_animationController_0, "Progress", "_.Progress", "_", _root);
                return result;
            }

            // - - - - Layer aggregator
            // - - Transforms: A3
            CanvasGeometry Geometry_0()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.BeginFigure(new Vector2(-34F, -23.5F));
                    builder.AddLine(new Vector2(35F, -23.5F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Layer aggregator
            // - - Transforms: A2 Offset:<59.5, 60.625>
            CanvasGeometry Geometry_1()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.BeginFigure(new Vector2(-34F, 0F));
                    builder.AddLine(new Vector2(35F, 0F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Layer aggregator
            // - - Transforms: A1
            CanvasGeometry Geometry_2()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.BeginFigure(new Vector2(-34F, 22.25F));
                    builder.AddLine(new Vector2(35F, 22.25F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CompositionColorBrush ColorBrush_AlmostDarkSlateBlue_FF6628B2()
            {
                return (_colorBrush_AlmostDarkSlateBlue_FF6628B2 == null)
                    ? _colorBrush_AlmostDarkSlateBlue_FF6628B2 = _c.CreateColorBrush(Color.FromArgb(0xFF, 0x66, 0x28, 0xB2))
                    : _colorBrush_AlmostDarkSlateBlue_FF6628B2;
            }

            // Layer aggregator
            CompositionContainerShape ContainerShape()
            {
                if (_containerShape != null) { return _containerShape; }
                var result = _containerShape = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(60F, 60F);
                result.Offset = new Vector2(140.5F, 89.375F);
                var shapes = result.Shapes;
                // Transforms: A3
                shapes.Add(SpriteShape_0());
                // Transforms: A2 Offset:<59.5, 60.625>
                shapes.Add(SpriteShape_1());
                // Transforms: A1
                shapes.Add(SpriteShape_2());
                return result;
            }

            // - - Layer aggregator
            // Transforms: A3
            CompositionPathGeometry PathGeometry_0()
            {
                if (_pathGeometry_0 != null) { return _pathGeometry_0; }
                var result = _pathGeometry_0 = _c.CreatePathGeometry(new CompositionPath(Geometry_0()));
                return result;
            }

            // - - Layer aggregator
            // Transforms: A2 Offset:<59.5, 60.625>
            CompositionPathGeometry PathGeometry_1()
            {
                return _c.CreatePathGeometry(new CompositionPath(Geometry_1()));
            }

            // - - Layer aggregator
            // Transforms: A1
            CompositionPathGeometry PathGeometry_2()
            {
                if (_pathGeometry_2 != null) { return _pathGeometry_2; }
                var result = _pathGeometry_2 = _c.CreatePathGeometry(new CompositionPath(Geometry_2()));
                return result;
            }

            // - Layer aggregator
            // Path 1
            CompositionSpriteShape SpriteShape_0()
            {
                if (_spriteShape_0 != null) { return _spriteShape_0; }
                var result = _spriteShape_0 = _c.CreateSpriteShape(PathGeometry_0());
                result.CenterPoint = new Vector2(35F, -23.5F);
                result.StrokeBrush = ColorBrush_AlmostDarkSlateBlue_FF6628B2();
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 10F;
                return result;
            }

            // - Layer aggregator
            // Path 1
            CompositionSpriteShape SpriteShape_1()
            {
                // Offset:<59.5, 60.625>
                var result = CreateSpriteShape(PathGeometry_1(), new Matrix3x2(1F, 0F, 0F, 1F, 59.5F, 60.625F));;
                result.StrokeBrush = ColorBrush_AlmostDarkSlateBlue_FF6628B2();
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 10F;
                return result;
            }

            // - Layer aggregator
            // Path 1
            CompositionSpriteShape SpriteShape_2()
            {
                if (_spriteShape_2 != null) { return _spriteShape_2; }
                var result = _spriteShape_2 = _c.CreateSpriteShape(PathGeometry_2());
                result.CenterPoint = new Vector2(35F, 22.25F);
                result.StrokeBrush = ColorBrush_AlmostDarkSlateBlue_FF6628B2();
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 10F;
                return result;
            }

            // The root of the composition.
            ContainerVisual Root()
            {
                if (_root != null) { return _root; }
                var result = _root = _c.CreateContainerVisual();
                var propertySet = result.Properties;
                propertySet.InsertScalar("Progress", 0F);
                // Layer aggregator
                result.Children.InsertAtTop(ShapeVisual_0());
                return result;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_0()
            {
                return (_cubicBezierEasingFunction_0 == null)
                    ? _cubicBezierEasingFunction_0 = _c.CreateCubicBezierEasingFunction(new Vector2(0.634000003F, 0F), new Vector2(0.560000002F, 1F))
                    : _cubicBezierEasingFunction_0;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_1()
            {
                return (_cubicBezierEasingFunction_1 == null)
                    ? _cubicBezierEasingFunction_1 = _c.CreateCubicBezierEasingFunction(new Vector2(0.166999996F, 0.166999996F), new Vector2(0.833000004F, 0.833000004F))
                    : _cubicBezierEasingFunction_1;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_2()
            {
                return (_cubicBezierEasingFunction_2 == null)
                    ? _cubicBezierEasingFunction_2 = _c.CreateCubicBezierEasingFunction(new Vector2(0.600000024F, 0F), new Vector2(0.340999991F, 1F))
                    : _cubicBezierEasingFunction_2;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_3()
            {
                return (_cubicBezierEasingFunction_3 == null)
                    ? _cubicBezierEasingFunction_3 = _c.CreateCubicBezierEasingFunction(new Vector2(0.166999996F, 0.166999996F), new Vector2(0F, 0F))
                    : _cubicBezierEasingFunction_3;
            }

            // - - Layer aggregator
            // Transforms: A3
            // Rotation
            ScalarKeyFrameAnimation RotationAngleInDegreesScalarAnimation_0_to_0_0()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 0F, StepThenHoldEasingFunction());
                // Frame 19.
                result.InsertKeyFrame(0.105555557F, 0F, HoldThenStepEasingFunction());
                // Frame 33.
                result.InsertKeyFrame(0.183333337F, 45F, CubicBezierEasingFunction_0());
                // Frame 116.
                result.InsertKeyFrame(0.644444466F, 45F, CubicBezierEasingFunction_1());
                // Frame 134.
                result.InsertKeyFrame(0.74444443F, 0F, CubicBezierEasingFunction_2());
                return result;
            }

            // - - Layer aggregator
            // Transforms: A1
            // Rotation
            ScalarKeyFrameAnimation RotationAngleInDegreesScalarAnimation_0_to_0_1()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 0F, StepThenHoldEasingFunction());
                // Frame 19.
                result.InsertKeyFrame(0.105555557F, 0F, HoldThenStepEasingFunction());
                // Frame 33.
                result.InsertKeyFrame(0.183333337F, -45F, CubicBezierEasingFunction_0());
                // Frame 116.
                result.InsertKeyFrame(0.644444466F, -45F, CubicBezierEasingFunction_1());
                // Frame 134.
                result.InsertKeyFrame(0.74444443F, 0F, CubicBezierEasingFunction_2());
                return result;
            }

            // - Layer aggregator
            // Rotation
            ScalarKeyFrameAnimation RotationAngleInDegreesScalarAnimation_0_to_360()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 0F, StepThenHoldEasingFunction());
                // Frame 19.
                result.InsertKeyFrame(0.105555557F, 0F, HoldThenStepEasingFunction());
                // Frame 33.
                result.InsertKeyFrame(0.183333337F, 190.699997F, CubicBezierEasingFunction_0());
                // Frame 40.5.
                result.InsertKeyFrame(0.224999994F, 176.100006F, _c.CreateCubicBezierEasingFunction(new Vector2(0.398000002F, 0F), new Vector2(0.561999977F, 1F)));
                // Frame 55.
                result.InsertKeyFrame(0.305555552F, 181.800003F, _c.CreateCubicBezierEasingFunction(new Vector2(0.310000002F, 0F), new Vector2(0.684000015F, 1F)));
                // Frame 71.
                result.InsertKeyFrame(0.394444436F, 180F, _c.CreateCubicBezierEasingFunction(new Vector2(0.437999994F, 0F), new Vector2(0.684000015F, 1F)));
                // Frame 111.
                result.InsertKeyFrame(0.616666675F, 180F, _c.CreateCubicBezierEasingFunction(new Vector2(0.38499999F, 0.38499999F), new Vector2(0.73299998F, 0.73299998F)));
                // Frame 116.
                result.InsertKeyFrame(0.644444466F, 167.899994F, _c.CreateCubicBezierEasingFunction(new Vector2(0.405999988F, 0F), new Vector2(0.0920000002F, 1F)));
                // Frame 134.
                result.InsertKeyFrame(0.74444443F, 363F, CubicBezierEasingFunction_2());
                // Frame 141.
                result.InsertKeyFrame(0.783333361F, 360F, _c.CreateCubicBezierEasingFunction(new Vector2(0.166999996F, 0F), new Vector2(0.462000012F, 1F)));
                return result;
            }

            // TrimStart
            ScalarKeyFrameAnimation TrimStartScalarAnimation_0_to_0()
            {
                // Frame 0.
                if (_trimStartScalarAnimation_0_to_0 != null) { return _trimStartScalarAnimation_0_to_0; }
                var result = _trimStartScalarAnimation_0_to_0 = CreateScalarKeyFrameAnimation(0F, 0F, StepThenHoldEasingFunction());
                // Frame 19.
                result.InsertKeyFrame(0.105555557F, 0F, HoldThenStepEasingFunction());
                // Frame 33.
                result.InsertKeyFrame(0.183333337F, 0.25999999F, CubicBezierEasingFunction_0());
                // Frame 116.
                result.InsertKeyFrame(0.644444466F, 0.25999999F, CubicBezierEasingFunction_1());
                // Frame 134.
                result.InsertKeyFrame(0.74444443F, 0F, CubicBezierEasingFunction_2());
                return result;
            }

            // Layer aggregator
            ShapeVisual ShapeVisual_0()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(400F, 300F);
                result.Shapes.Add(ContainerShape());
                return result;
            }

            StepEasingFunction HoldThenStepEasingFunction()
            {
                if (_holdThenStepEasingFunction != null) { return _holdThenStepEasingFunction; }
                var result = _holdThenStepEasingFunction = _c.CreateStepEasingFunction();
                result.IsFinalStepSingleFrame = true;
                return result;
            }

            StepEasingFunction StepThenHoldEasingFunction()
            {
                if (_stepThenHoldEasingFunction != null) { return _stepThenHoldEasingFunction; }
                var result = _stepThenHoldEasingFunction = _c.CreateStepEasingFunction();
                result.IsInitialStepSingleFrame = true;
                return result;
            }

            // - - Layer aggregator
            // Transforms: A3
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_0()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(59.5F, 60.625F), StepThenHoldEasingFunction());
                // Frame 19.
                result.InsertKeyFrame(0.105555557F, new Vector2(59.5F, 60.625F), HoldThenStepEasingFunction());
                // Frame 33.
                result.InsertKeyFrame(0.183333337F, new Vector2(61.2000008F, 87.5449982F), CubicBezierEasingFunction_0());
                // Frame 116.
                result.InsertKeyFrame(0.644444466F, new Vector2(61.2000008F, 87.5449982F), CubicBezierEasingFunction_3());
                // Frame 134.
                result.InsertKeyFrame(0.74444443F, new Vector2(59.5F, 60.625F), CubicBezierEasingFunction_2());
                return result;
            }

            // - - Layer aggregator
            // Transforms: A1
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_1()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(59.5F, 60.625F), StepThenHoldEasingFunction());
                // Frame 19.
                result.InsertKeyFrame(0.105555557F, new Vector2(59.5F, 60.625F), HoldThenStepEasingFunction());
                // Frame 33.
                result.InsertKeyFrame(0.183333337F, new Vector2(61.2000008F, 34.8050003F), CubicBezierEasingFunction_0());
                // Frame 116.
                result.InsertKeyFrame(0.644444466F, new Vector2(61.2000008F, 34.8050003F), CubicBezierEasingFunction_3());
                // Frame 134.
                result.InsertKeyFrame(0.74444443F, new Vector2(59.5F, 60.625F), CubicBezierEasingFunction_2());
                return result;
            }

            internal HamburgerArrow_AnimatedVisual(
                Compositor compositor
                )
            {
                _c = compositor;
                _reusableExpressionAnimation = compositor.CreateExpressionAnimation();
                Root();
            }

            public Visual RootVisual => _root;
            public TimeSpan Duration => TimeSpan.FromTicks(c_durationTicks);
            public Vector2 Size => new Vector2(400F, 300F);
            void IDisposable.Dispose() => _root?.Dispose();

            public void CreateAnimations()
            {
                _containerShape.StartAnimation("RotationAngleInDegrees", RotationAngleInDegreesScalarAnimation_0_to_360(), AnimationController_0());
                _pathGeometry_0.StartAnimation("TrimStart", TrimStartScalarAnimation_0_to_0(), AnimationController_0());
                _pathGeometry_2.StartAnimation("TrimStart", TrimStartScalarAnimation_0_to_0(), AnimationController_0());
                _spriteShape_0.StartAnimation("RotationAngleInDegrees", RotationAngleInDegreesScalarAnimation_0_to_0_0(), AnimationController_0());
                _spriteShape_0.StartAnimation("Offset", OffsetVector2Animation_0(), AnimationController_0());
                _spriteShape_2.StartAnimation("RotationAngleInDegrees", RotationAngleInDegreesScalarAnimation_0_to_0_1(), AnimationController_0());
                _spriteShape_2.StartAnimation("Offset", OffsetVector2Animation_1(), AnimationController_0());
            }

            public void DestroyAnimations()
            {
                _containerShape.StopAnimation("RotationAngleInDegrees");
                _pathGeometry_0.StopAnimation("TrimStart");
                _pathGeometry_2.StopAnimation("TrimStart");
                _spriteShape_0.StopAnimation("RotationAngleInDegrees");
                _spriteShape_0.StopAnimation("Offset");
                _spriteShape_2.StopAnimation("RotationAngleInDegrees");
                _spriteShape_2.StopAnimation("Offset");
            }

        }
    }
}
#endif
