using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Uno.UI.RemoteControl.HotReload.Messages;

/// <summary>
/// Represents a configuration message sent from the client to the server to initialize and configure hot reload functionality.
/// This record provides the necessary project information, MSBuild properties, and hot reload capabilities required by the server
/// to enable and manage hot reload operations during development.
/// </summary>
/// <param name="ProjectPath">The path to the project being configured for hot reload.</param>
/// <param name="MetadataUpdateCapabilities">Array of metadata update capabilities supported by the application.</param>
/// <param name="MSBuildPropertiesRaw">Raw MSBuild properties in base64-encoded format.</param>
/// <param name="EnableMetadataUpdates">Instructs the dev-server to observe the project for changes (on file system) and emit metadata updates.</param>
/// <param name="EnableHotReloadThruDebugger">
/// Instructs the dev-server to send metadata updates to the debugger (i.e. through the IDE channel)
/// instead of sending them directly to the app (using the AssemblyDeltaReload message through the App channel).
/// </param>
/// <param name="HotReloadInfoPath">Path of the HotReloadInfo file generated by the HotReloadInfoTask.</param>
public record ConfigureServer(
	string ProjectPath,
	string[] MetadataUpdateCapabilities,
	string[] MSBuildPropertiesRaw,
	string? HotReloadInfoPath,
	bool EnableMetadataUpdates,
	bool EnableHotReloadThruDebugger)
	: IMessage
{
	public const string Name = nameof(ConfigureServer);

	private Dictionary<string, string>? _msbuildProperties;

	public string Scope => WellKnownScopes.HotReload;

	string IMessage.Name => Name;

	public Dictionary<string, string> MSBuildProperties => _msbuildProperties ??= ParseMSBuildProperties(MSBuildPropertiesRaw);

	public static Dictionary<string, string> ParseMSBuildProperties(string[] rawMSBuildProperties)
		=> rawMSBuildProperties
			.Select(property => property.Split('=', 2))
			.Where(tokens => tokens.Length == 2)
			.ToDictionary(
				tokens => tokens[0],
				tokens => Encoding.UTF8.GetString(Convert.FromBase64String(tokens[1])));
}
