using System.Collections.Immutable;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis.Testing;
using Microsoft.CodeAnalysis.Text;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Uno.UI.SourceGenerators.ImplementedRoutedEvents;
using Uno.UI.SourceGenerators.Tests.Verifiers;

namespace Uno.UI.SourceGenerators.Tests.ImplementedRoutedEventsGeneratorTests
{
	using Verify = CSharpSourceGeneratorVerifier<ImplementedRoutedEventsGenerator>;

	[TestClass]
	public class Given_ImplementedRoutedEventsGenerator
	{
		private static readonly ReferenceAssemblies s_defaultWithUno = ReferenceAssemblies.Default.AddPackages(
			ImmutableArray.Create(new PackageIdentity("Uno.UI", "4.2.6"))); // UPDATE with a version that has a Control.GetImplementedRoutedEvents available.

		// TODO: Remove and use s_defaultWithUno when we have a version with Control.GetImplementedRoutedEvents available.
		private const string Stub = @"
namespace Windows.UI.Xaml
{
	public class RoutedEventArgs
	{
	}
	public sealed class DragEventArgs : RoutedEventArgs
	{
	}

	public partial class UIElement
	{		
	}

	public partial class FrameworkElement : UIElement
	{
	}
}
namespace Uno.UI.Xaml
{
	public static class UIElementGeneratedProxy
	{
		public static global::Uno.UI.Xaml.RoutedEventFlag RegisterImplementedRoutedEvents(global::System.Type type, global::Uno.UI.Xaml.RoutedEventFlag routedEventFlags)
		{
			return routedEventFlags;
		}
	}
}
namespace Windows.UI.Xaml.Controls
{
	public partial class Control : Windows.UI.Xaml.FrameworkElement
	{
	}
}
namespace Windows.UI.Xaml.Input
{
	public sealed class PointerRoutedEventArgs : RoutedEventArgs
	{
	}
	public sealed class ManipulationStartingRoutedEventArgs : RoutedEventArgs
	{
	}
	public sealed class ManipulationStartedRoutedEventArgs : RoutedEventArgs
	{
	}
	public sealed class ManipulationDeltaRoutedEventArgs : RoutedEventArgs
	{
	}
	public sealed class ManipulationInertiaStartingRoutedEventArgs : RoutedEventArgs
	{
	}
	public sealed class ManipulationCompletedRoutedEventArgs : RoutedEventArgs
	{
	}
	public sealed class TappedRoutedEventArgs : RoutedEventArgs
	{
	}
	public sealed class DoubleTappedRoutedEventArgs : RoutedEventArgs
	{
	}
	public sealed class RightTappedRoutedEventArgs : RoutedEventArgs
	{
	}
	public sealed class HoldingRoutedEventArgs : RoutedEventArgs
	{
	}
	public sealed class KeyRoutedEventArgs : RoutedEventArgs
	{
	}
}";

		private readonly GeneratedFile _uiElementGeneratedFile = new GeneratedFile(
			@"Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.ImplementedRoutedEvents.ImplementedRoutedEventsGenerator\Windows.UI.Xaml.UIElement_ImplementedRoutedEvents.g.cs",
			@"// <auto-generated>
namespace Windows.UI.Xaml
{
	partial class UIElement
	{
		[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
		private static global::Uno.UI.Xaml.RoutedEventFlag __uno_ImplementedRoutedEvents = global::Uno.UI.Xaml.UIElementGeneratedProxy.RegisterImplementedRoutedEvents(
		typeof(UIElement), 
		global::Uno.UI.Xaml.RoutedEventFlag.None
		);
	}
}
");

		private readonly GeneratedFile _frameworkElementGeneratedFile = new GeneratedFile(
			@"Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.ImplementedRoutedEvents.ImplementedRoutedEventsGenerator\Windows.UI.Xaml.FrameworkElement_ImplementedRoutedEvents.g.cs",
			@"// <auto-generated>
namespace Windows.UI.Xaml
{
	partial class FrameworkElement
	{
		[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
		private static global::Uno.UI.Xaml.RoutedEventFlag __uno_ImplementedRoutedEvents = global::Uno.UI.Xaml.UIElementGeneratedProxy.RegisterImplementedRoutedEvents(
		typeof(FrameworkElement), 
		global::Uno.UI.Xaml.RoutedEventFlag.None
		);
	}
}
");

		private readonly GeneratedFile _controlGeneratedFile = new GeneratedFile(
			@"Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.ImplementedRoutedEvents.ImplementedRoutedEventsGenerator\Windows.UI.Xaml.Controls.Control_ImplementedRoutedEvents.g.cs",
			@"// <auto-generated>
namespace Windows.UI.Xaml.Controls
{
	partial class Control
	{
		[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
		private static global::Uno.UI.Xaml.RoutedEventFlag __uno_ImplementedRoutedEvents = global::Uno.UI.Xaml.UIElementGeneratedProxy.RegisterImplementedRoutedEvents(
		typeof(Control), 
		global::Uno.UI.Xaml.RoutedEventFlag.None
		);
	}
}
");

		private string _routedEventFlagSource;

		[TestInitialize]
		public void Initialize()
		{
			LoadRoutedEventFlagSource();
		}

		private void LoadRoutedEventFlagSource()
		{
			using var stream = typeof(ImplementedRoutedEventsGeneratorTests).Assembly.GetManifestResourceStream("Uno.UI.SourceGenerators.net6.Tests.RoutedEventFlag.cs");
			using var reader = new StreamReader(stream);
			_routedEventFlagSource = reader.ReadToEnd();
		}

		private async Task TestGeneratorAsync(string inputSource, params GeneratedFile[] generatedFiles)
		{
			var test = new Verify.Test
			{
				ReferenceAssemblies = s_defaultWithUno,
				TestState =
				{
					Sources = { Stub, _routedEventFlagSource, inputSource },
				},
			};
			test.TestState.GeneratedSources.AddRange(generatedFiles.Select(f => (f.Path, f.Source)));
			await test.RunAsync();
		}

		[TestMethod]
		public async Task Given_NonGeneric_Control_In_Global_Namespace()
		{
			const string inputSource = @"
using Windows.UI.Xaml.Controls;

public partial class MyAwesomeControl : Control
{
}
";
			const string expectedCode = @"// <auto-generated>
partial class MyAwesomeControl
{
	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
	private static global::Uno.UI.Xaml.RoutedEventFlag __uno_ImplementedRoutedEvents = global::Uno.UI.Xaml.UIElementGeneratedProxy.RegisterImplementedRoutedEvents(
	typeof(MyAwesomeControl), 
	global::Uno.UI.Xaml.RoutedEventFlag.None
	);
}
";
			await TestGeneratorAsync(
				inputSource,
				_controlGeneratedFile,
				_uiElementGeneratedFile,
				_frameworkElementGeneratedFile,
				new GeneratedFile(
					@"Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.ImplementedRoutedEvents.ImplementedRoutedEventsGenerator\MyAwesomeControl_ImplementedRoutedEvents.g.cs",
					expectedCode));
		}

		[TestMethod]
		public async Task Given_Generic_Control_In_Global_Namespace()
		{
			const string inputSource = @"
using Windows.UI.Xaml.Controls;

public partial class MyAwesomeControl<T> : Control
{
}
";
			const string expectedCode = @"// <auto-generated>
partial class MyAwesomeControl<T>
{
	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
	private static global::Uno.UI.Xaml.RoutedEventFlag __uno_ImplementedRoutedEvents = global::Uno.UI.Xaml.UIElementGeneratedProxy.RegisterImplementedRoutedEvents(
	typeof(MyAwesomeControl<T>), 
	global::Uno.UI.Xaml.RoutedEventFlag.None
	);
}
";
			await TestGeneratorAsync(
				inputSource,
				_controlGeneratedFile,
				_uiElementGeneratedFile,
				_frameworkElementGeneratedFile,
				new GeneratedFile(
					@"Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.ImplementedRoutedEvents.ImplementedRoutedEventsGenerator\MyAwesomeControl-1[MyAwesomeControl-1.T]_ImplementedRoutedEvents.g.cs",
					expectedCode));
		}

		[TestMethod]
		public async Task Given_Generic_Control_In_Non_Global_Namespace()
		{
			const string inputSource = @"
using Windows.UI.Xaml.Controls;

namespace MyControls
{
	public partial class MyAwesomeControl<T> : Control
	{
	}
}
";
			const string expectedCode = @"// <auto-generated>
namespace MyControls
{
	partial class MyAwesomeControl<T>
	{
		[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
		private static global::Uno.UI.Xaml.RoutedEventFlag __uno_ImplementedRoutedEvents = global::Uno.UI.Xaml.UIElementGeneratedProxy.RegisterImplementedRoutedEvents(
		typeof(MyAwesomeControl<T>), 
		global::Uno.UI.Xaml.RoutedEventFlag.None
		);
	}
}
";
			await TestGeneratorAsync(
				inputSource,
				_controlGeneratedFile,
				_uiElementGeneratedFile,
				_frameworkElementGeneratedFile,
				new GeneratedFile(
					@"Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.ImplementedRoutedEvents.ImplementedRoutedEventsGenerator\MyControls.MyAwesomeControl-1[MyControls.MyAwesomeControl-1.T]_ImplementedRoutedEvents.g.cs",
					expectedCode));
		}
	}

	public class GeneratedFile
	{
		public GeneratedFile(string path, string source)
		{
			Path = path;
			Source = SourceText.From(source, Encoding.UTF8);
		}

		public string Path { get; set; }

		public SourceText Source { get; set; }
	}
}
