name: "📖 Documentation Request"
description: "Request an enhancement to the Uno documentation ✨"
labels: [kind/consumer-experience, kind/documentation, triage/untriaged, difficulty/tbd]
body:
  - type: markdown
    attributes:
      value: |
        Please only use this template for submitting documentation requests. 🙏

  - type: textarea
    id: docs-request-description
    attributes:
      label: "What would you like clarification on? 🤔"
      description: "Provide a clear and detailed explanation of what aspect of the documentation you would like to see improved or clarified 📝"
    validations:
      required: true

  - type: dropdown
    id: docs-request-concern
    attributes:
      label: "Concern 📚"
      description: "Choose the category that best describes your concern from the provided options or leave blank if none is applicable 🏷️"
      multiple: false
      options:        
        - "Usage in industry 🏭"
        - "Clarification of capabilities 💡"
        - "Getting started with Uno 🚀"
        - "Developing with Uno 🛠️"
        - "Contributing to the Uno project 🤝"
        - "Publishing your application 🌍"
        - "Support 🆘"

  - type: checkboxes
    id: docs-request-renderer
    attributes:
      label: "Renderer 🎨"
      description: "Select the renderer you are using. Your application is using Skia if you find `SkiaRenderer` in your `.csproj` project file."
      options:
        - label: "Skia"
        - label: "Native"

  - type: dropdown
    id: docs-request-platforms
    attributes:
      label: "Affected platforms 📱💻🖥️"
      description: "Select the platforms for which the requested documentation is relevant 🌍"
      multiple: true
      options:
        - "All platforms 🌍"
        - "WebAssembly"
        - "Android"
        - "iOS"
        - "Desktop (Windows)"
        - "Desktop (macOS)"
        - "Desktop (X11)"
        - "Desktop (Linux Framebuffer)"
        - "Windows App SDK"
        - "Build tasks"

  - type: textarea
    id: docs-request-additional-info
    attributes:
      label: "Any feedback? 💬"
      description: "Feel free to offer any additional feedback that could help us better understand the problem or potential solution 💡"
