name: Samples Issue
description: Report an issue with the Uno samples
labels: [kind/contributor-experience, kind/documentation, triage/untriaged, difficulty/tbd]
body:
  - type: markdown
    attributes:
      value: |
        Please only use this template for reporting issues with the samples where the fix isn't straightforward. We greatly appreciate it when people send in pull requests with fixes. If any friction, apart from knowledge, is preventing you from doing so, please let us know below. 

  - type: input
    id: samples-issue-location
    attributes:
      label: On which page?
      description: Specify the sample page or section where you've identified an issue
      placeholder: ex. Windows.Devices/Accelerometer
    validations:
      required: true

  - type: textarea
    id: samples-issue-description
    attributes:
      label: What's wrong?
      description: Provide a detailed description of what you believe is incorrect, unclear, or needs improvement
    validations:
      required: true

  - type: textarea
    id: samples-issue-additional-info
    attributes:
      label: Any feedback?
      description: Feel free to offer any additional feedback that could help us better understand the problem or potential solution
