name: Samples Request
description: Request an enhancement to the Uno samples
labels: [kind/contributor-experience, kind/documentation, triage/untriaged, difficulty/tbd]
body:
  - type: markdown
    attributes:
      value: |
        Please only use this template for submitting samples requests. 

  - type: textarea
    id: samples-request-description
    attributes:
      label: What would you like to be added
      description: Provide a clear and detailed explanation of what aspect of our samples you would like to see improved and tell us why you think it is needed
    validations:
      required: true

  - type: dropdown
    id: samples-request-platforms
    attributes:
      label: Affected platforms
      multiple: true
      description: Select the platforms for which your request is relevant
      options:        
        - WebAssembly
        - Android
        - iOS
        - macOS (AppKit)
        - Mac Catalyst
        - Skia (WPF)
        - Skia (GTK on Linux/macOS/Windows)
        - Skia (Linux Framebuffer)
        - Windows

  - type: textarea
    id: samples-request-additional-info
    attributes:
      label: Any feedback?
      description: Feel free to offer any additional feedback that could help us better understand the problem or potential solution
