name: "🏆 Success Story"
description: "If you are using Uno Platform in production, we would love to hear about it! 🎉"
labels: [kind/consumer-experience, kind/documentation, triage/untriaged]
body:
  - type: markdown
    attributes:
      value: |
        **STOP ⛔ -- PLEASE READ!**

        We 💖 to hear about how, where and what you're doing with Uno Platform. Sharing this information is one of the kindest things you can do in open-source and the maintainers love hearing about success stories. Instead of raising a new GitHub issue could you please comment in the existing thread? 📝

        [Uno in Production](https://github.com/unoplatform/uno/discussions/5012) 

        If you're feeling extra generous, how about writing a blog post and then letting us know about it? That way, we can retweet it. 🐦

        Thank you! 🙏

  - type: textarea
    id: success-story-text
    attributes:
      label: "What is your success story? 🏅"
      description: "If you still want to use GitHub Issues for sharing your Success story, you can do so below. 📣"
