name: "🆘 Support Request"
description: "Request help or support for Uno Platform 🙋‍♂️🙋‍♀️"
labels: [kind/support, triage/untriaged]
body:
  - type: markdown
    attributes:
      value: |
        Need help? You're in the right place! 💡

        Please use this template to request support or help with Uno Platform. For general questions, you can also check out our [GitHub Discussions](https://github.com/unoplatform/uno/discussions) or [documentation](https://platform.uno/docs/). 📚

  - type: textarea
    id: support-description
    attributes:
      label: "Describe your issue or question 📝"
      description: "Please provide as much detail as possible so we can best assist you. Include error messages, steps to reproduce, and any relevant context. 🛠️"
    validations:
      required: true

  - type: dropdown
    id: support-platforms
    attributes:
      label: "For which platforms 📱💻🖥️"
      description: "Select the platforms your support requested is related to 🌍"
      multiple: true
      options:
        - "All platforms 🌍"
        - "WebAssembly"
        - "Android"
        - "iOS"
        - "Desktop (Windows)"
        - "Desktop (macOS)"
        - "Desktop (X11)"
        - "Desktop (Linux Framebuffer)"
        - "Windows App SDK"
        - "Build tasks"

  - type: textarea
    id: support-additional-info
    attributes:
      label: "Anything else we need to know? 💬"
      description: "Feel free to offer any additional information that could help us better understand your issue or question 💡"
