#pragma warning disable 108 // new keyword hiding
#pragma warning disable 114 // new keyword hiding
namespace Windows.UI.Xaml.Controls.Primitives
{
#pragma warning disable CA1822 // Mark members as static
	// TODO: Should this be deleted and have it auto-generated by UWPSyncGenerator?
	[global::Uno.NotImplemented]
	public partial class ToggleSwitchTemplateSettings : global::Windows.UI.Xaml.DependencyObject
	{
		[global::Uno.NotImplemented]
		public  double CurtainCurrentToOffOffset
		{
			get
			{
				global::Windows.Foundation.Metadata.ApiInformation.TryRaiseNotImplemented("Windows.UI.Xaml.Controls.Primitives.ToggleSwitchTemplateSettings", "CurtainCurrentToOffOffset");
				return 0;
			}
		}

		[global::Uno.NotImplemented]
		public double CurtainCurrentToOnOffset
		{
			get
			{
				global::Windows.Foundation.Metadata.ApiInformation.TryRaiseNotImplemented("Windows.UI.Xaml.Controls.Primitives.ToggleSwitchTemplateSettings", "CurtainCurrentToOnOffset");
				return 0;
			}
		}

		[global::Uno.NotImplemented]
		public double CurtainOffToOnOffset
		{
			get
			{
				global::Windows.Foundation.Metadata.ApiInformation.TryRaiseNotImplemented("Windows.UI.Xaml.Controls.Primitives.ToggleSwitchTemplateSettings", "CurtainOffToOnOffset");
				return 0;
			}
		}

		[global::Uno.NotImplemented]
		public double CurtainOnToOffOffset
		{
			get
			{
				global::Windows.Foundation.Metadata.ApiInformation.TryRaiseNotImplemented("Windows.UI.Xaml.Controls.Primitives.ToggleSwitchTemplateSettings", "CurtainOnToOffOffset");
				return 0;
			}
		}

		[global::Uno.NotImplemented]
		public double KnobCurrentToOffOffset
		{
			get
			{
				global::Windows.Foundation.Metadata.ApiInformation.TryRaiseNotImplemented("Windows.UI.Xaml.Controls.Primitives.ToggleSwitchTemplateSettings", "KnobCurrentToOffOffset");
				return 0;
			}
		}

		[global::Uno.NotImplemented]
		public double KnobCurrentToOnOffset
		{
			get
			{
				global::Windows.Foundation.Metadata.ApiInformation.TryRaiseNotImplemented("Windows.UI.Xaml.Controls.Primitives.ToggleSwitchTemplateSettings", "KnobCurrentToOnOffset");
				return 0;
			}
		}

		[global::Uno.NotImplemented]
		public double KnobOffToOnOffset
		{
			get
			{
				global::Windows.Foundation.Metadata.ApiInformation.TryRaiseNotImplemented("Windows.UI.Xaml.Controls.Primitives.ToggleSwitchTemplateSettings", "KnobOffToOnOffset");
				return 0;
			}
		}

		[global::Uno.NotImplemented]
		public double KnobOnToOffOffset
		{
			get
			{
				global::Windows.Foundation.Metadata.ApiInformation.TryRaiseNotImplemented("Windows.UI.Xaml.Controls.Primitives.ToggleSwitchTemplateSettings", "KnobOnToOffOffset");
				return 0;
			}
		}
	}
}
