// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.

// DO NOT EDIT! This file was generated by CustomTasks.DependencyPropertyCodeGen

namespace Windows.UI.Xaml.Controls
{
	public partial class SwipeItems
	{
		//public:

		//SwipeItemsProperties();

		//void Mode(winrt.SwipeMode & value);

		//winrt.SwipeMode Mode();

		//static winrt.DependencyProperty ModeProperty() { return s_ModeProperty; }

		//static GlobalDependencyProperty s_ModeProperty;

		//static void EnsureProperties();

		//static void ClearProperties();

		//static void OnModePropertyChanged(
		//	winrt.DependencyObject & sender,

		//winrt.DependencyPropertyChangedEventArgs & args);
	}
}
