<?xml version="1.0" encoding="utf-8" ?>
<Project>
	<ItemGroup>
		<Page Remove="$(MSBuildThisFileDirectory)Windows\UI\Xaml\Media\RevealBrushes\**" />
		<Compile Remove="$(MSBuildThisFileDirectory)Windows\UI\Xaml\Media\RevealBrushes\**" />
		<None Include="$(MSBuildThisFileDirectory)Windows\UI\Xaml\Media\RevealBrushes\**"
		      Link="Windows\UI\Xaml\Media\RevealBrushes\%(RecursiveDir)%(Filename)%(Extension)" />

		<Page Remove="$(MSBuildThisFileDirectory)Windows\Phone\**" />
		<Compile Remove="$(MSBuildThisFileDirectory)Windows\Phone\**" />
		<None Include="$(MSBuildThisFileDirectory)Windows\Phone\**"
		      Link="Windows\Phone\%(RecursiveDir)%(Filename)%(Extension)" />

		<Page Remove="$(MSBuildThisFileDirectory)Windows\UI\Xaml\Controls\Repeater\FlowLayout_Simple.xaml" />
		<Compile Remove="$(MSBuildThisFileDirectory)Windows\UI\Xaml\Controls\Repeater\FlowLayout_Simple.xaml.cs" />
		<None Include="$(MSBuildThisFileDirectory)Windows\UI\Xaml\Controls\Repeater\FlowLayout_Simple.xaml"
		      Link="Windows\UI\Xaml\Controls\Repeater\FlowLayout_Simple.xaml" />
		<None Include="$(MSBuildThisFileDirectory)Windows\UI\Xaml\Controls\Repeater\FlowLayout_Simple.xaml.cs"
		      Link="Windows\UI\Xaml\Controls\Repeater\FlowLayout_Simple.xaml.cs" />

		<Page Remove="$(MSBuildThisFileDirectory)Microsoft\UI\Xaml\Controls\PagerControlTests\**" />
		<Compile Remove="$(MSBuildThisFileDirectory)Microsoft\UI\Xaml\Controls\PagerControlTests\**" />
		<None Include="$(MSBuildThisFileDirectory)Microsoft\UI\Xaml\Controls\PagerControlTests\**"
		      Link="Microsoft\UI\Xaml\Controls\PagerControlTests\%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>

	<ItemGroup Condition="'$(UseWinUI)'=='true'">
		<Page Remove="$(MSBuildThisFileDirectory)Windows\UI\Xaml\Controls\WebView\**" />
		<Compile Remove="$(MSBuildThisFileDirectory)Windows\UI\Xaml\Controls\WebView\**" />
		<None Include="$(MSBuildThisFileDirectory)Windows\UI\Xaml\Controls\WebView\**"
		      Link="Windows\UI\Xaml\Controls\WebView\%(RecursiveDir)%(Filename)%(Extension)" />

		<!-- Some samples rely on internal types -->
		<Page Remove="$(MSBuildThisFileDirectory)Microsoft\UI\Xaml\Controls\ScrollViewTests\**" />
		<Compile Remove="$(MSBuildThisFileDirectory)Microsoft\UI\Xaml\Controls\ScrollViewTests\**" />
		<None Include="$(MSBuildThisFileDirectory)Microsoft\UI\Xaml\Controls\ScrollViewTests\**"
		      Link="Microsoft\UI\Xaml\Controls\ScrollViewTests\%(RecursiveDir)%(Filename)%(Extension)" />
		<Page Remove="$(MSBuildThisFileDirectory)Microsoft\UI\Xaml\Controls\ItemsViewTests\**" />
		<Compile Remove="$(MSBuildThisFileDirectory)Microsoft\UI\Xaml\Controls\ItemsViewTests\**" />
		<None Include="$(MSBuildThisFileDirectory)Microsoft\UI\Xaml\Controls\ItemsViewTests\**"
		      Link="Microsoft\UI\Xaml\Controls\ItemsViewTests\%(RecursiveDir)%(Filename)%(Extension)" />
		<Page Remove="$(MSBuildThisFileDirectory)Microsoft\UI\Xaml\Controls\SelectorBarTests\**" />
		<Compile Remove="$(MSBuildThisFileDirectory)Microsoft\UI\Xaml\Controls\SelectorBarTests\**" />
		<None Include="$(MSBuildThisFileDirectory)Microsoft\UI\Xaml\Controls\SelectorBarTests\**"
		      Link="Microsoft\UI\Xaml\Controls\SelectorBarTests\%(RecursiveDir)%(Filename)%(Extension)" />

		<Page Remove="$(MSBuildThisFileDirectory)Microsoft\UI\Xaml\Controls\WebView2Tests\**" />
		<Compile Remove="$(MSBuildThisFileDirectory)Microsoft\UI\Xaml\Controls\WebView2Tests\**" />
		<None Include="$(MSBuildThisFileDirectory)Microsoft\UI\Xaml\Controls\WebView2Tests\**"
		      Link="Microsoft\UI\Xaml\Controls\WebView2Tests\%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>
</Project>
