<#
    import_external_docs_test.ps1 [-NoFetch]

    -NoFetch   : Skip the import of external repositories. Useful for testing or authoring.
                 The default is to import the external repositories from the main branch.
#>

param(
    [Alias('NF')]
    [switch] $NoFetch
)

Write-Host 'Updating docfx tool...' -ForegroundColor Black -BackgroundColor Green
# Intentionally pinned to match the CI docs build toolchain (build/Uno.UI.Build.csproj)
# so local validation reproduces doc generation behavior consistently.
dotnet tool update --global docfx --version 2.73.2 --allow-downgrade

# Older or newer local versions can cause template behavior differences.
# Verify the actual resolved version and force-install the pinned toolchain when needed.
# A Homebrew or other system-wide install may shadow the dotnet tool, so prefer
# the dotnet tool path explicitly when it exists.
$dotnetToolDocfx = Join-Path $env:HOME '.dotnet/tools/docfx'
if (Test-Path $dotnetToolDocfx) {
    $script:DocfxCmd = $dotnetToolDocfx
} else {
    $script:DocfxCmd = 'docfx'
}
$docfxVersionOutput = (& $script:DocfxCmd --version | Select-Object -First 1).Trim()
if ($docfxVersionOutput -notlike '2.73.2*') {
    Write-Host "DocFX version '$docfxVersionOutput' does not match required 2.73.2. Reinstalling pinned version..." -ForegroundColor Black -BackgroundColor DarkYellow
    dotnet tool uninstall --global docfx | Out-Null
    dotnet tool install --global docfx --version 2.73.2
    $docfxVersionOutput = (& $script:DocfxCmd --version | Select-Object -First 1).Trim()
    if ($docfxVersionOutput -notlike '2.73.2*') {
        Write-Error "Failed to install DocFX 2.73.2. Resolved version: $docfxVersionOutput"
        exit 1
    }
}

Write-Host 'Updating dotnet-serve tool...' -ForegroundColor Black -BackgroundColor Green
dotnet tool update --global dotnet-serve

if (-not $NoFetch) {
    $external_docs = @{
        "uno.wasm.bootstrap" = "main"
        "uno.themes"         = "master"
        "uno.toolkit.ui"     = "main"
        "uno.check"          = "main"
        "uno.xamlmerge.task" = "main"
        "figma-docs"         = "main"
        "uno.resizetizer"    = "main"
        "uno.uitest"         = "master"
        "uno.extensions"     = "main"
        "workshops"          = "master"
        "uno.samples"        = "master"
        "uno.chefs"          = "main"
        "hd-docs"            = "main"
    }

    Write-Host 'Importing external repositories...' -ForegroundColor Black -BackgroundColor Green
    ./import_external_docs $external_docs
} else {
    Write-Host '-nofetch option specified. Skipping the import of external repositories.' -ForegroundColor Black -BackgroundColor DarkRed
}

# Generate the documentation
$implementedTocDir = Join-Path $PSScriptRoot "articles/implemented"
$implementedTocPath = Join-Path $implementedTocDir "toc.yml"
$implementedViewsPath = Join-Path $PSScriptRoot "articles/implemented-views.md"

if (-not (Test-Path $implementedTocPath)) {
    Write-Host 'Missing generated implemented TOC. Creating local placeholder for DocFX.' -ForegroundColor Black -BackgroundColor DarkYellow
    New-Item -ItemType Directory -Force -Path $implementedTocDir | Out-Null
    Set-Content -Path $implementedTocPath -Value @"
# Generated by Uno.UWPSyncGenerator (DocGenerator.cs)
- name: Placeholder
"@
}

if (-not (Test-Path $implementedViewsPath)) {
    Write-Host 'Missing generated implemented views page. Creating local placeholder for DocFX.' -ForegroundColor Black -BackgroundColor DarkYellow
    Set-Content -Path $implementedViewsPath -Value @"
# Implemented Views

This page is generated during CI builds by Uno.UWPSyncGenerator.
"@
}

& $script:DocfxCmd

if ($LASTEXITCODE -ne 0) {
    throw "DocFX generation failed with exit code $LASTEXITCODE."
}

$algoliaCheckFile = Join-Path $PSScriptRoot "_site/articles/intro.html"
if (-not (Test-Path $algoliaCheckFile)) {
    throw "Algolia verification failed: generated file not found at $algoliaCheckFile"
}

$algoliaHtml = Get-Content -Raw -Path $algoliaCheckFile
if ($algoliaHtml -notmatch "@docsearch/js@3" -or $algoliaHtml -notmatch "docsearch\s*\(") {
    throw "Algolia verification failed: expected DocSearch script and initializer were not found in generated output."
}

Write-Host 'Algolia DocSearch wiring verified in generated docs output.' -ForegroundColor Black -BackgroundColor Green

# Serve it
dotnet-serve --open-browser:_site/articles/intro.html
