<Project>
	<PropertyGroup>
		<IsIOS>true</IsIOS>
		<SupportedOSPlatformVersion Condition=" $(SupportedOSPlatformVersion) == '' ">15.0</SupportedOSPlatformVersion>

		<EnableDefaultiOSItems Condition="$(EnableDefaultiOSItems) == ''">false</EnableDefaultiOSItems>

		<IsMSALSupported>true</IsMSALSupported>
	</PropertyGroup>

	<Import Project="$(MSBuildThisFileDirectory)Uno.SingleProject.iOS.targets" Condition=" $(_IsUnoSingleProjectAndLegacy) == 'true' " />
</Project>
