//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     LottieGen version: 7.0.2+gebbbdfc697
// </auto-generated>
//------------------------------------------------------------------------------
// MUX Reference AnimatedAcceptVisualSource.cpp, commit 5f9e85113

using System;
using System.Collections.Generic;
using System.Numerics;
using Microsoft.UI.Composition;
using Microsoft.UI.Xaml.Controls;
using Color = Windows.UI.Color;

namespace Microsoft.UI.Xaml.Controls.AnimatedVisuals;

partial class AnimatedAcceptVisualSource
{
	private static Vector4 ColorAsVector4(Color color)
	{
		return new Vector4((float)color.R, (float)color.G, (float)color.B, (float)color.A);
	}

	private CompositionPropertySet EnsureThemeProperties(Compositor compositor)
	{
		if (_themeProperties == null)
		{
			_themeProperties = compositor.CreatePropertySet();
			_themeProperties.InsertVector4("Foreground", ColorAsVector4(_themeForeground));
		}

		return _themeProperties;
	}

	/// <summary>
	/// Gets or sets the color used for the check (accept) icon's foreground stroke.
	/// </summary>
	/// <value>The foreground <see cref="Color"/>. The default is <c>#FF000000</c> (opaque black).</value>
	public Color Foreground
	{
		get => _themeForeground;
		set
		{
			_themeForeground = value;
			if (_themeProperties != null)
			{
				_themeProperties.InsertVector4("Foreground", ColorAsVector4(_themeForeground));
			}
		}
	}

	public IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor)
	{
		object diagnostics = null;
		return TryCreateAnimatedVisual(compositor, out diagnostics);
	}

	public IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor, out object diagnostics)
	{
		_ = EnsureThemeProperties(compositor);
		diagnostics = null;

		if (AnimatedAcceptVisualSource_AnimatedVisual.IsRuntimeCompatible())
		{
			return new AnimatedAcceptVisualSource_AnimatedVisual(
				compositor,
				_themeProperties!);
		}

		return null;
	}

	/// <summary>Gets the number of frames in the animation.</summary>
	public double FrameCount => 160.0;

	/// <summary>Gets the framerate of the animation in frames-per-second.</summary>
	public double Framerate => 60.0;

	/// <summary>Gets the duration of the animation.</summary>
	public TimeSpan Duration => new TimeSpan(26666666L);

	public double FrameToProgress(double frameNumber)
	{
		return frameNumber / 160.0;
	}

	public IReadOnlyDictionary<string, double> Markers => s_markers;

	private static readonly IReadOnlyDictionary<string, double> s_markers = new Dictionary<string, double>
	{
		{ "NormalOnToNormalOff_Start", 0.0 },
		{ "NormalOnToNormalOff_End", 0.0253125 },
		{ "NormalOnToPointerOverOn_Start", 0.0315625 },
		{ "NormalOnToPointerOverOn_End", 0.0565625 },
		{ "NormalOnToPressedOn_Start", 0.0628125 },
		{ "NormalOnToPressedOn_End", 0.0878125 },
		{ "NormalOffToNormalOn_Start", 0.0940625 },
		{ "NormalOffToNormalOn_End", 0.2128125 },
		{ "NormalOffToPointerOverOff_Start", 0.2190625 },
		{ "NormalOffToPointerOverOff_End", 0.2440625 },
		{ "NormalOffToPressedOff_Start", 0.2503125 },
		{ "NormalOffToPressedOff_End", 0.2753125 },
		{ "PointerOverOnToPointerOverOff_Start", 0.2815625 },
		{ "PointerOverOnToPointerOverOff_End", 0.3065625 },
		{ "PointerOverOnToNormalOn_Start", 0.3128125 },
		{ "PointerOverOnToNormalOn_End", 0.3378125 },
		{ "PointerOverOnToPressedOn_Start", 0.3440625 },
		{ "PointerOverOnToPressedOn_End", 0.3690625 },
		{ "PointerOverOffToPointerOverOn_Start", 0.3753125 },
		{ "PointerOverOffToPointerOverOn_End", 0.4940625 },
		{ "PointerOverOffToNormalOff_Start", 0.5003125 },
		{ "PointerOverOffToNormalOff_End", 0.5253125 },
		{ "PointerOverOffToPressedOff_Start", 0.5315625 },
		{ "PointerOverOffToPressedOff_End", 0.5565625 },
		{ "PressedOnToPressedOff_Start", 0.5628125 },
		{ "PressedOnToPressedOff_End", 0.5878125 },
		{ "PressedOnToPointerOverOff_Start", 0.5940625 },
		{ "PressedOnToPointerOverOff_End", 0.6190625 },
		{ "PressedOnToNormalOff_Start", 0.6253125 },
		{ "PressedOnToNormalOff_End", 0.6503125 },
		{ "PressedOffToPressedOn_Start", 0.6565625 },
		{ "PressedOffToPressedOn_End", 0.7128125 },
		{ "PressedOffToPointerOverOn_Start", 0.7190625 },
		{ "PressedOffToPointerOverOn_End", 0.8378125 },
		{ "PressedOffToNormalOn_Start", 0.8440625 },
		{ "PressedOffToNormalOn_End", 0.9628125 },
		{ "NormalIndeterminate", 0.9690625 },
		{ "PointerOverIndeterminate", 0.9815625 },
		{ "PressedIndeterminate", 0.9940625 },
	};

	public void SetColorProperty(string propertyName, Color value)
	{
		if (propertyName == "Foreground")
		{
			_themeForeground = value;
		}
		else
		{
			return;
		}

		if (_themeProperties != null)
		{
			_themeProperties.InsertVector4(propertyName, ColorAsVector4(value));
		}
	}

	public void SetScalarProperty(string propertyName, double value)
	{
	}
}
