//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     LottieGen version: 7.1.0+ge1fa92580f
// </auto-generated>
//------------------------------------------------------------------------------
// MUX Reference AnimatedBackVisualSource.cpp (nested AnimatedBackVisualSource_AnimatedVisual class), commit 5f9e85113

// ____________________________________
// |       Object stats       | Count |
// |__________________________|_______|
// | All CompositionObjects   |    89 |
// |--------------------------+-------|
// | Expression animators     |    12 |
// | KeyFrame animators       |     9 |
// | Reference parameters     |    12 |
// | Expression operations    |     4 |
// |--------------------------+-------|
// | Animated brushes         |     1 |
// | Animated gradient stops  |     - |
// | ExpressionAnimations     |     2 |
// | PathKeyFrameAnimations   |     - |
// |--------------------------+-------|
// | ContainerVisuals         |     3 |
// | ShapeVisuals             |     2 |
// |--------------------------+-------|
// | ContainerShapes          |     1 |
// | CompositionSpriteShapes  |     6 |
// |--------------------------+-------|
// | Brushes                  |     1 |
// | Gradient stops           |     - |
// | CompositionVisualSurface |     - |
// ------------------------------------

using System;
using System.Numerics;
using Microsoft.Graphics.Canvas.Geometry;
using Microsoft.UI.Composition;
using Microsoft.UI.Xaml.Controls;
using Windows.Foundation;
using Windows.Foundation.Metadata;

namespace Microsoft.UI.Xaml.Controls.AnimatedVisuals;

/// <summary>
/// The IAnimatedVisual implementation that builds the back-icon composition tree and drives
/// its property animations. Keep in lock-step with AnimatedBackVisualSource.cpp (the nested
/// AnimatedBackVisualSource_AnimatedVisual struct in WinUI).
/// </summary>
internal sealed class AnimatedBackVisualSource_AnimatedVisual : IAnimatedVisual
{
	private const long c_durationTicks = 13333333L;

	private readonly Compositor _c;
	private readonly ExpressionAnimation _reusableExpressionAnimation;
	private readonly CompositionPropertySet _themeProperties;

	private CompositionColorBrush _themeColor_Foreground;
	private CompositionPathGeometry _pathGeometry_0;
	private CompositionPathGeometry _pathGeometry_1;
	private CompositionPathGeometry _pathGeometry_2;
	private ContainerVisual _root;
	private CubicBezierEasingFunction _cubicBezierEasingFunction_0;
	private CubicBezierEasingFunction _cubicBezierEasingFunction_1;
	private CubicBezierEasingFunction _cubicBezierEasingFunction_2;
	private CubicBezierEasingFunction _cubicBezierEasingFunction_3;
	private CubicBezierEasingFunction _cubicBezierEasingFunction_4;
	private ExpressionAnimation _rootProgress;
	private InsetClip _insetClip_0;
	private StepEasingFunction _holdThenStepEasingFunction;
	private StepEasingFunction _stepThenHoldEasingFunction;

	private static void StartProgressBoundAnimation(
		CompositionObject target,
		string animatedPropertyName,
		CompositionAnimation animation,
		ExpressionAnimation controllerProgressExpression)
	{
		target.StartAnimation(animatedPropertyName, animation);
		var controller = target.TryGetAnimationController(animatedPropertyName);
		controller.Pause();
		controller.StartAnimation("Progress", controllerProgressExpression);
	}

	private void BindProperty(
		CompositionObject target,
		string animatedPropertyName,
		string expression,
		string referenceParameterName,
		CompositionObject referencedObject)
	{
		_reusableExpressionAnimation.ClearAllParameters();
		_reusableExpressionAnimation.Expression = expression;
		_reusableExpressionAnimation.SetReferenceParameter(referenceParameterName, referencedObject);
		target.StartAnimation(animatedPropertyName, _reusableExpressionAnimation);
	}

	private BooleanKeyFrameAnimation CreateBooleanKeyFrameAnimation(float initialProgress, bool initialValue)
	{
		var result = _c.CreateBooleanKeyFrameAnimation();
		result.Duration = new TimeSpan(c_durationTicks);
		result.InsertKeyFrame(initialProgress, initialValue);
		return result;
	}

	private ScalarKeyFrameAnimation CreateScalarKeyFrameAnimation(float initialProgress, float initialValue, CompositionEasingFunction initialEasingFunction)
	{
		var result = _c.CreateScalarKeyFrameAnimation();
		result.Duration = new TimeSpan(c_durationTicks);
		result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
		return result;
	}

	private Vector2KeyFrameAnimation CreateVector2KeyFrameAnimation(float initialProgress, Vector2 initialValue, CompositionEasingFunction initialEasingFunction)
	{
		var result = _c.CreateVector2KeyFrameAnimation();
		result.Duration = new TimeSpan(c_durationTicks);
		result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
		return result;
	}

	private CompositionSpriteShape CreateSpriteShape(CompositionGeometry geometry, Matrix3x2 transformMatrix, CompositionBrush fillBrush)
	{
		var result = _c.CreateSpriteShape(geometry);
		result.TransformMatrix = transformMatrix;
		result.FillBrush = fillBrush;
		return result;
	}

	// PreComp layer: Controls - 03 - Back - 02 - NormalToPressed Controls - 03 - Back -
	// 04 - PointerOverToPressed  Controls - 03 - Back - 05 - PressedToNormal Controls -
	// 03 - Back - 06 - PressedToPointerOver
	private BooleanKeyFrameAnimation IsVisibleBooleanAnimation_0()
	{
		// Frame 10.
		var result = CreateBooleanKeyFrameAnimation(0.125F, true);
		return result;
	}

	// PreComp layer: Controls - 03 - Back - 01 - NormalToPointerOver Controls - 03 - Back
	// - 03 - PointerOverToNormal
	private BooleanKeyFrameAnimation IsVisibleBooleanAnimation_1()
	{
		// Frame 30.
		var result = CreateBooleanKeyFrameAnimation(0.375F, false);
		return result;
	}

	private CanvasGeometry Geometry_0()
	{
		var builder = new CanvasPathBuilder(null);
		builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
		builder.BeginFigure(new Vector2(7.5F, 0.499000013F));
		builder.AddCubicBezier(new Vector2(7.77600002F, 0.499000013F), new Vector2(8.0F, 0.275000006F), new Vector2(8.0F, -0.00100000005F));
		builder.AddCubicBezier(new Vector2(8.0F, -0.27700001F), new Vector2(7.77600002F, -0.500999987F), new Vector2(7.5F, -0.500999987F));
		builder.AddLine(new Vector2(7.5F, 0.499000013F));
		builder.EndFigure(CanvasFigureLoop.Closed);
		return CanvasGeometry.CreatePath(builder);
	}

	private CanvasGeometry Geometry_1()
	{
		var builder = new CanvasPathBuilder(null);
		builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
		builder.BeginFigure(new Vector2(-5.33400011F, 0.495000005F));
		builder.AddLine(new Vector2(7.5F, 0.499000013F));
		builder.AddLine(new Vector2(7.5F, -0.500999987F));
		builder.AddLine(new Vector2(-5.33099985F, -0.504999995F));
		builder.AddLine(new Vector2(-5.33400011F, 0.495000005F));
		builder.EndFigure(CanvasFigureLoop.Closed);
		return CanvasGeometry.CreatePath(builder);
	}

	private CanvasGeometry Geometry_2()
	{
		var builder = new CanvasPathBuilder(null);
		builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
		builder.BeginFigure(new Vector2(-0.837000012F, 6.86800003F));
		builder.AddCubicBezier(new Vector2(-0.633000016F, 7.0539999F), new Vector2(-0.317000002F, 7.03999996F), new Vector2(-0.130999997F, 6.83599997F));
		builder.AddCubicBezier(new Vector2(0.0549999997F, 6.63199997F), new Vector2(0.0410000011F, 6.31500006F), new Vector2(-0.163000003F, 6.12900019F));
		builder.AddLine(new Vector2(-6.33099985F, 0.499000013F));
		builder.AddLine(new Vector2(-5.32800007F, 0.488999993F));
		builder.AddLine(new Vector2(-5.32800007F, -0.510999978F));
		builder.AddLine(new Vector2(-6.32800007F, -0.500999987F));
		builder.AddLine(new Vector2(-0.163000003F, -6.12900019F));
		builder.AddCubicBezier(new Vector2(0.0410000011F, -6.31500006F), new Vector2(0.0549999997F, -6.63199997F), new Vector2(-0.130999997F, -6.83599997F));
		builder.AddCubicBezier(new Vector2(-0.317000002F, -7.03999996F), new Vector2(-0.633000016F, -7.0539999F), new Vector2(-0.837000012F, -6.86800003F));
		builder.AddLine(new Vector2(-7.75299978F, -0.55400002F));
		builder.AddCubicBezier(new Vector2(-7.89300013F, -0.425999999F), new Vector2(-7.97300005F, -0.257999986F), new Vector2(-7.99300003F, -0.0850000009F));
		builder.AddCubicBezier(new Vector2(-7.99800014F, -0.0579999983F), new Vector2(-8.0F, -0.0299999993F), new Vector2(-8.0F, -0.00100000005F));
		builder.AddCubicBezier(new Vector2(-8.0F, 0.0260000005F), new Vector2(-7.99800014F, 0.0520000011F), new Vector2(-7.99399996F, 0.0780000016F));
		builder.AddCubicBezier(new Vector2(-7.97599983F, 0.254000008F), new Vector2(-7.89499998F, 0.423999995F), new Vector2(-7.75299978F, 0.55400002F));
		builder.AddLine(new Vector2(-0.837000012F, 6.86800003F));
		builder.EndFigure(CanvasFigureLoop.Closed);
		return CanvasGeometry.CreatePath(builder);
	}

	// Color bound to theme property value: Foreground
	private CompositionColorBrush ThemeColor_Foreground()
	{
		var result = _themeColor_Foreground = _c.CreateColorBrush();
		BindProperty(result, "Color", "ColorRGB(_theme.Foreground.W,_theme.Foreground.X,_theme.Foreground.Y,_theme.Foreground.Z)", "_theme", _themeProperties);
		return result;
	}

	// - PreComp layer: Controls - 03 - Back - 02 - NormalToPressed Controls - 03 - Back -
	// 04 - PointerOverToPressed  Controls - 03 - Back - 05 - PressedToNormal Controls -
	// 03 - Back - 06 - PressedToPointerOver
	// Opacity for layer: Controls - 03 - Back - 02 - NormalToPressed Controls - 03 - Back
	// - 04 - PointerOverToPressed  Controls - 03 - Back - 05 - PressedToNormal Controls -
	// 03 - Back - 06 - PressedToPointerOver
	// Layer: Round Cap 2 Round Cap 2 Round Cap 2 Round Cap 2
	private CompositionContainerShape ContainerShape()
	{
		var result = _c.CreateContainerShape();
		var shapes = result.Shapes;
		// Transforms: Round Cap 2 Round Cap 2 Round Cap 2 Round Cap 2 Scale:2.25,2.25
		shapes.Add(SpriteShape_0());
		// Transforms: Stem 2 Stem 2 Stem 2 Stem 2
		shapes.Add(SpriteShape_1());
		StartProgressBoundAnimation(result, "Offset", OffsetVector2Animation_0(), _rootProgress);
		return result;
	}

	private CompositionPathGeometry PathGeometry_0()
	{
		return _pathGeometry_0 = _c.CreatePathGeometry(new CompositionPath(Geometry_0()));
	}

	private CompositionPathGeometry PathGeometry_1()
	{
		return _pathGeometry_1 = _c.CreatePathGeometry(new CompositionPath(Geometry_1()));
	}

	private CompositionPathGeometry PathGeometry_2()
	{
		return _pathGeometry_2 = _c.CreatePathGeometry(new CompositionPath(Geometry_2()));
	}

	// - - PreComp layer: Controls - 03 - Back - 02 - NormalToPressed Controls - 03 - Back
	// - 04 - PointerOverToPressed  Controls - 03 - Back - 05 - PressedToNormal Controls -
	// 03 - Back - 06 - PressedToPointerOver
	// - Opacity for layer: Controls - 03 - Back - 02 - NormalToPressed Controls - 03 -
	// Back - 04 - PointerOverToPressed  Controls - 03 - Back - 05 - PressedToNormal
	// Controls - 03 - Back - 06 - PressedToPointerOver
	// Layer: Round Cap 2 Round Cap 2 Round Cap 2 Round Cap 2
	// Path 1 Path 1 Path 1 Path 1
	private CompositionSpriteShape SpriteShape_0()
	{
		// Scale:<2.25, 2.25>
		var geometry = PathGeometry_0();
		var result = CreateSpriteShape(geometry, new Matrix3x2(2.25F, 0.0F, 0.0F, 2.25F, 0.0F, 0.0F), ThemeColor_Foreground());
		return result;
	}

	// - - PreComp layer: Controls - 03 - Back - 02 - NormalToPressed Controls - 03 - Back
	// - 04 - PointerOverToPressed  Controls - 03 - Back - 05 - PressedToNormal Controls -
	// 03 - Back - 06 - PressedToPointerOver
	// - Opacity for layer: Controls - 03 - Back - 02 - NormalToPressed Controls - 03 -
	// Back - 04 - PointerOverToPressed  Controls - 03 - Back - 05 - PressedToNormal
	// Controls - 03 - Back - 06 - PressedToPointerOver
	// Layer: Round Cap 2 Round Cap 2 Round Cap 2 Round Cap 2
	// Path 1 Path 1 Path 1 Path 1
	private CompositionSpriteShape SpriteShape_1()
	{
		var result = _c.CreateSpriteShape(PathGeometry_1());
		result.CenterPoint = new Vector2(7.5F, -0.00300000003F);
		result.Offset = new Vector2(9.375F, -0.00400000019F);
		result.FillBrush = _themeColor_Foreground;
		StartProgressBoundAnimation(result, "Scale.X", ScaleXScalarAnimation_2p25_to_2p25(), RootProgress());
		StartProgressBoundAnimation(result, "Scale.Y", ScaleYScalarAnimation_2p25_to_2p25(), _rootProgress);
		return result;
	}

	// - PreComp layer: Controls - 03 - Back - 02 - NormalToPressed Controls - 03 - Back -
	// 04 - PointerOverToPressed  Controls - 03 - Back - 05 - PressedToNormal Controls -
	// 03 - Back - 06 - PressedToPointerOver
	// Opacity for layer: Controls - 03 - Back - 02 - NormalToPressed Controls - 03 - Back
	// - 04 - PointerOverToPressed  Controls - 03 - Back - 05 - PressedToNormal Controls -
	// 03 - Back - 06 - PressedToPointerOver
	// Path 1 Path 1 Path 1 Path 1
	private CompositionSpriteShape SpriteShape_2()
	{
		var result = _c.CreateSpriteShape(PathGeometry_2());
		result.Scale = new Vector2(2.25F, 2.25F);
		result.FillBrush = _themeColor_Foreground;
		StartProgressBoundAnimation(result, "Offset", OffsetVector2Animation_1(), _rootProgress);
		return result;
	}

	// - PreComp layer: Controls - 03 - Back - 01 - NormalToPointerOver Controls - 03 -
	// Back - 03 - PointerOverToNormal
	// Opacity for layer: Controls - 03 - Back - 01 - NormalToPointerOver Controls - 03 -
	// Back - 03 - PointerOverToNormal
	// Path 1 Path 1
	private CompositionSpriteShape SpriteShape_3()
	{
		// Offset:<24, 24>, Scale:<2.25, 2.25>
		var geometry = _pathGeometry_0;
		var result = CreateSpriteShape(geometry, new Matrix3x2(2.25F, 0.0F, 0.0F, 2.25F, 24.0F, 24.0F), _themeColor_Foreground);
		return result;
	}

	// - PreComp layer: Controls - 03 - Back - 01 - NormalToPointerOver Controls - 03 -
	// Back - 03 - PointerOverToNormal
	// Opacity for layer: Controls - 03 - Back - 01 - NormalToPointerOver Controls - 03 -
	// Back - 03 - PointerOverToNormal
	// Path 1 Path 1
	private CompositionSpriteShape SpriteShape_4()
	{
		// Offset:<24, 23.99975>, Scale:<2.25, 2.25>
		var geometry = _pathGeometry_1;
		var result = CreateSpriteShape(geometry, new Matrix3x2(2.25F, 0.0F, 0.0F, 2.25F, 24.0F, 23.9997501F), _themeColor_Foreground);
		return result;
	}

	// - PreComp layer: Controls - 03 - Back - 01 - NormalToPointerOver Controls - 03 -
	// Back - 03 - PointerOverToNormal
	// Opacity for layer: Controls - 03 - Back - 01 - NormalToPointerOver Controls - 03 -
	// Back - 03 - PointerOverToNormal
	// Path 1 Path 1
	private CompositionSpriteShape SpriteShape_5()
	{
		// Offset:<24, 24>, Scale:<2.25, 2.25>
		var geometry = _pathGeometry_2;
		var result = CreateSpriteShape(geometry, new Matrix3x2(2.25F, 0.0F, 0.0F, 2.25F, 24.0F, 24.0F), _themeColor_Foreground);
		return result;
	}

	// PreComp layer: Controls - 03 - Back - 02 - NormalToPressed Controls - 03 - Back -
	// 04 - PointerOverToPressed  Controls - 03 - Back - 05 - PressedToNormal Controls -
	// 03 - Back - 06 - PressedToPointerOver
	private ContainerVisual ContainerVisual_0()
	{
		var result = _c.CreateContainerVisual();
		result.Clip = InsetClip_0();
		result.IsVisible = false;
		result.Size = new Vector2(48.0F, 48.0F);
		// Scale:<1, 1> — Identity matrix.
		// Note: the WinUI-generated source applies a malformed 4x4 here with zeros on M22/M33.
		// In WinUI's column-major DComp pipeline that ends up being interpreted as identity for
		// 2D content; in Skia's row-major Matrix4x4 it would collapse the layer entirely. We
		// substitute identity which is the intended behavior.
		result.TransformMatrix = Matrix4x4.Identity;
		// Opacity for layer: Controls - 03 - Back - 02 - NormalToPressed Controls - 03 - Back
		// - 04 - PointerOverToPressed  Controls - 03 - Back - 05 - PressedToNormal Controls -
		// 03 - Back - 06 - PressedToPointerOver
		result.Children.InsertAtTop(ShapeVisual_0());
		StartProgressBoundAnimation(result, "Opacity", OpacityScalarAnimation_1_to_1_0(), _rootProgress);
		StartProgressBoundAnimation(result, "IsVisible", IsVisibleBooleanAnimation_0(), _rootProgress);
		return result;
	}

	// PreComp layer: Controls - 03 - Back - 01 - NormalToPointerOver Controls - 03 - Back
	// - 03 - PointerOverToNormal
	private ContainerVisual ContainerVisual_1()
	{
		var result = _c.CreateContainerVisual();
		result.Clip = _insetClip_0;
		result.Size = new Vector2(48.0F, 48.0F);
		// Scale:<1, 1>
		// TODO Uno: see ContainerVisual_0 for context on the matrix diagonals.
		result.TransformMatrix = new Matrix4x4(
			1.0F, 0.0F, 0.0F, 0.0F,
			0.0F, 1.0F, 0.0F, 0.0F,
			0.0F, 0.0F, 0.0F, 0.0F,
			0.0F, 0.0F, 0.0F, 1.0F);
		// Opacity for layer: Controls - 03 - Back - 01 - NormalToPointerOver Controls - 03 -
		// Back - 03 - PointerOverToNormal
		result.Children.InsertAtTop(ShapeVisual_1());
		StartProgressBoundAnimation(result, "Opacity", OpacityScalarAnimation_1_to_1_1(), _rootProgress);
		StartProgressBoundAnimation(result, "IsVisible", IsVisibleBooleanAnimation_1(), _rootProgress);
		return result;
	}

	// The root of the composition.
	private ContainerVisual Root()
	{
		var result = _root = _c.CreateContainerVisual();
		var propertySet = result.Properties;
		propertySet.InsertScalar("Progress", 0.0F);
		propertySet.InsertScalar("t0", 0.0F);
		var children = result.Children;
		// PreComp layer: Controls - 03 - Back - 02 - NormalToPressed Controls - 03 - Back -
		// 04 - PointerOverToPressed  Controls - 03 - Back - 05 - PressedToNormal Controls -
		// 03 - Back - 06 - PressedToPointerOver
		children.InsertAtTop(ContainerVisual_0());
		// PreComp layer: Controls - 03 - Back - 01 - NormalToPointerOver Controls - 03 - Back
		// - 03 - PointerOverToNormal
		children.InsertAtTop(ContainerVisual_1());
		StartProgressBoundAnimation(propertySet, "t0", t0ScalarAnimation_0_to_1(), _rootProgress);
		return result;
	}

	private CubicBezierEasingFunction CubicBezierEasingFunction_0()
	{
		return _cubicBezierEasingFunction_0 = _c.CreateCubicBezierEasingFunction(new Vector2(0.166999996F, 0.166999996F), new Vector2(0.0F, 1.0F));
	}

	private CubicBezierEasingFunction CubicBezierEasingFunction_1()
	{
		return _cubicBezierEasingFunction_1 = _c.CreateCubicBezierEasingFunction(new Vector2(0.550000012F, 0.0F), new Vector2(0.75F, 1.0F));
	}

	private CubicBezierEasingFunction CubicBezierEasingFunction_2()
	{
		return _cubicBezierEasingFunction_2 = _c.CreateCubicBezierEasingFunction(new Vector2(0.349999994F, 0.0F), new Vector2(0.0F, 1.0F));
	}

	private CubicBezierEasingFunction CubicBezierEasingFunction_3()
	{
		return _cubicBezierEasingFunction_3 = _c.CreateCubicBezierEasingFunction(new Vector2(0.166999996F, 0.0F), new Vector2(0.0F, 1.0F));
	}

	private CubicBezierEasingFunction CubicBezierEasingFunction_4()
	{
		return _cubicBezierEasingFunction_4 = _c.CreateCubicBezierEasingFunction(new Vector2(0.850000024F, 0.0F), new Vector2(0.75F, 1.0F));
	}

	private ExpressionAnimation RootProgress()
	{
		var result = _rootProgress = _c.CreateExpressionAnimation("_.Progress");
		result.SetReferenceParameter("_", _root);
		return result;
	}

	private InsetClip InsetClip_0()
	{
		var result = _insetClip_0 = _c.CreateInsetClip();
		return result;
	}

	// PreComp layer: Controls - 03 - Back - 02 - NormalToPressed Controls - 03 - Back -
	// 04 - PointerOverToPressed  Controls - 03 - Back - 05 - PressedToNormal Controls -
	// 03 - Back - 06 - PressedToPointerOver
	// Layer opacity animation
	private ScalarKeyFrameAnimation OpacityScalarAnimation_1_to_1_0()
	{
		// Frame 0.
		var result = CreateScalarKeyFrameAnimation(0.0F, 1.0F, _stepThenHoldEasingFunction);
		// Frame 10.
		result.InsertKeyFrame(0.125F, 1.0F, _holdThenStepEasingFunction);
		// Frame 20.
		result.InsertKeyFrame(0.25F, 0.0F, _holdThenStepEasingFunction);
		// Frame 30.
		result.InsertKeyFrame(0.375F, 1.0F, _holdThenStepEasingFunction);
		return result;
	}

	// PreComp layer: Controls - 03 - Back - 01 - NormalToPointerOver Controls - 03 - Back
	// - 03 - PointerOverToNormal
	// Layer opacity animation
	private ScalarKeyFrameAnimation OpacityScalarAnimation_1_to_1_1()
	{
		// Frame 0.
		var result = CreateScalarKeyFrameAnimation(0.0F, 1.0F, _holdThenStepEasingFunction);
		// Frame 10.
		result.InsertKeyFrame(0.125F, 0.0F, _holdThenStepEasingFunction);
		// Frame 20.
		result.InsertKeyFrame(0.25F, 1.0F, _holdThenStepEasingFunction);
		return result;
	}

	// - - - PreComp layer: Controls - 03 - Back - 02 - NormalToPressed Controls - 03 -
	// Back - 04 - PointerOverToPressed  Controls - 03 - Back - 05 - PressedToNormal
	// Controls - 03 - Back - 06 - PressedToPointerOver
	// - - Opacity for layer: Controls - 03 - Back - 02 - NormalToPressed Controls - 03 -
	// Back - 04 - PointerOverToPressed  Controls - 03 - Back - 05 - PressedToNormal
	// Controls - 03 - Back - 06 - PressedToPointerOver
	// - Layer: Round Cap 2 Round Cap 2 Round Cap 2 Round Cap 2
	// Transforms: Stem 2 Stem 2 Stem 2 Stem 2
	// Scale
	private ScalarKeyFrameAnimation ScaleXScalarAnimation_2p25_to_2p25()
	{
		// Frame 0.
		var result = CreateScalarKeyFrameAnimation(0.0F, 2.25F, StepThenHoldEasingFunction());
		// Frame 10.
		result.InsertKeyFrame(0.125F, 2.25F, HoldThenStepEasingFunction());
		// Frame 19.
		result.InsertKeyFrame(0.237499997F, 1.62211001F, CubicBezierEasingFunction_0());
		// Frame 30.
		result.InsertKeyFrame(0.375F, 2.25F, _holdThenStepEasingFunction);
		// Frame 39.
		result.InsertKeyFrame(0.487500012F, 1.62211001F, _cubicBezierEasingFunction_0);
		// Frame 40.
		result.InsertKeyFrame(0.5F, 1.62211001F, _holdThenStepEasingFunction);
		// Frame 50.
		result.InsertKeyFrame(0.625F, 2.26947999F, CubicBezierEasingFunction_1());
		// Frame 59.
		result.InsertKeyFrame(0.737500012F, 2.25F, CubicBezierEasingFunction_2());
		// Frame 60.
		result.InsertKeyFrame(0.75F, 1.62211001F, _holdThenStepEasingFunction);
		// Frame 70.
		result.InsertKeyFrame(0.875F, 2.26947999F, _cubicBezierEasingFunction_1);
		// Frame 79.
		result.InsertKeyFrame(0.987500012F, 2.25F, _cubicBezierEasingFunction_2);
		return result;
	}

	// - - - PreComp layer: Controls - 03 - Back - 02 - NormalToPressed Controls - 03 -
	// Back - 04 - PointerOverToPressed  Controls - 03 - Back - 05 - PressedToNormal
	// Controls - 03 - Back - 06 - PressedToPointerOver
	// - - Opacity for layer: Controls - 03 - Back - 02 - NormalToPressed Controls - 03 -
	// Back - 04 - PointerOverToPressed  Controls - 03 - Back - 05 - PressedToNormal
	// Controls - 03 - Back - 06 - PressedToPointerOver
	// - Layer: Round Cap 2 Round Cap 2 Round Cap 2 Round Cap 2
	// Transforms: Stem 2 Stem 2 Stem 2 Stem 2
	// Scale
	private ScalarKeyFrameAnimation ScaleYScalarAnimation_2p25_to_2p25()
	{
		// Frame 0.
		var result = CreateScalarKeyFrameAnimation(0.0F, 2.25F, _stepThenHoldEasingFunction);
		// Frame 10.
		result.InsertKeyFrame(0.125F, 2.25F, _holdThenStepEasingFunction);
		// Frame 19.
		result.InsertKeyFrame(0.237499997F, 2.25F, CubicBezierEasingFunction_3());
		// Frame 30.
		result.InsertKeyFrame(0.375F, 2.25F, _holdThenStepEasingFunction);
		// Frame 39.
		result.InsertKeyFrame(0.487500012F, 2.25F, _cubicBezierEasingFunction_3);
		// Frame 40.
		result.InsertKeyFrame(0.5F, 2.25F, _holdThenStepEasingFunction);
		// Frame 50.
		result.InsertKeyFrame(0.625F, 2.25F, _cubicBezierEasingFunction_1);
		// Frame 59.
		result.InsertKeyFrame(0.737500012F, 2.25F, _cubicBezierEasingFunction_2);
		// Frame 60.
		result.InsertKeyFrame(0.75F, 2.25F, _holdThenStepEasingFunction);
		// Frame 70.
		result.InsertKeyFrame(0.875F, 2.25F, _cubicBezierEasingFunction_1);
		// Frame 79.
		result.InsertKeyFrame(0.987500012F, 2.25F, _cubicBezierEasingFunction_2);
		return result;
	}

	private ScalarKeyFrameAnimation t0ScalarAnimation_0_to_1()
	{
		// Frame 50.
		var result = CreateScalarKeyFrameAnimation(0.62500006F, 0.0F, _stepThenHoldEasingFunction);
		result.SetReferenceParameter("_", _root);
		// Frame 59.
		result.InsertKeyFrame(0.737499952F, 1.0F, _cubicBezierEasingFunction_2);
		// Frame 70.
		result.InsertKeyFrame(0.87500006F, 0.0F, _stepThenHoldEasingFunction);
		// Frame 79.
		result.InsertKeyFrame(0.987499952F, 1.0F, _cubicBezierEasingFunction_2);
		return result;
	}

	// PreComp layer: Controls - 03 - Back - 02 - NormalToPressed Controls - 03 - Back -
	// 04 - PointerOverToPressed  Controls - 03 - Back - 05 - PressedToNormal Controls -
	// 03 - Back - 06 - PressedToPointerOver
	// Layer aggregator
	private ShapeVisual ShapeVisual_0()
	{
		var result = _c.CreateShapeVisual();
		result.Size = new Vector2(48.0F, 48.0F);
		var shapes = result.Shapes;
		// Layer: Round Cap 2 Round Cap 2 Round Cap 2 Round Cap 2
		shapes.Add(ContainerShape());
		// Layer: Round Cap 2 Round Cap 2 Round Cap 2 Round Cap 2
		shapes.Add(SpriteShape_2());
		return result;
	}

	// PreComp layer: Controls - 03 - Back - 01 - NormalToPointerOver Controls - 03 - Back
	// - 03 - PointerOverToNormal
	// Layer aggregator
	private ShapeVisual ShapeVisual_1()
	{
		var result = _c.CreateShapeVisual();
		result.Size = new Vector2(48.0F, 48.0F);
		var shapes = result.Shapes;
		// Layer: Round Cap 2 Round Cap 2
		shapes.Add(SpriteShape_3());
		// Layer: Round Cap 2 Round Cap 2
		shapes.Add(SpriteShape_4());
		// Layer: Round Cap 2 Round Cap 2
		shapes.Add(SpriteShape_5());
		return result;
	}

	private StepEasingFunction HoldThenStepEasingFunction()
	{
		var result = _holdThenStepEasingFunction = _c.CreateStepEasingFunction();
		result.IsFinalStepSingleFrame = true;
		return result;
	}

	private StepEasingFunction StepThenHoldEasingFunction()
	{
		var result = _stepThenHoldEasingFunction = _c.CreateStepEasingFunction();
		result.IsInitialStepSingleFrame = true;
		return result;
	}

	// - - PreComp layer: Controls - 03 - Back - 02 - NormalToPressed Controls - 03 - Back
	// - 04 - PointerOverToPressed  Controls - 03 - Back - 05 - PressedToNormal Controls -
	// 03 - Back - 06 - PressedToPointerOver
	// - Opacity for layer: Controls - 03 - Back - 02 - NormalToPressed Controls - 03 -
	// Back - 04 - PointerOverToPressed  Controls - 03 - Back - 05 - PressedToNormal
	// Controls - 03 - Back - 06 - PressedToPointerOver
	// Layer: Round Cap 2 Round Cap 2 Round Cap 2 Round Cap 2
	// Offset
	private Vector2KeyFrameAnimation OffsetVector2Animation_0()
	{
		// Frame 0.
		var result = CreateVector2KeyFrameAnimation(0.0F, new Vector2(24.0F, 24.0F), _stepThenHoldEasingFunction);
		result.SetReferenceParameter("_", _root);
		// Frame 10.
		result.InsertKeyFrame(0.125F, new Vector2(24.0F, 24.0F), _holdThenStepEasingFunction);
		// Frame 19.
		result.InsertKeyFrame(0.237499997F, new Vector2(24.9379997F, 24.0F), _cubicBezierEasingFunction_0);
		// Frame 30.
		result.InsertKeyFrame(0.375F, new Vector2(24.0F, 24.0F), _holdThenStepEasingFunction);
		// Frame 39.
		result.InsertKeyFrame(0.487500012F, new Vector2(24.9379997F, 24.0F), _cubicBezierEasingFunction_0);
		// Frame 40.
		result.InsertKeyFrame(0.5F, new Vector2(24.9379997F, 24.0F), _holdThenStepEasingFunction);
		// Frame 50.
		result.InsertKeyFrame(0.625F, new Vector2(20.25F, 24.0F), _cubicBezierEasingFunction_1);
		// Frame 59.
		result.InsertExpressionKeyFrame(0.737499952F, "Pow(1-_.t0,3)*Vector2(20.25,24)+(3*Square(1-_.t0)*_.t0*Vector2(20.094,24))+(3*(1-_.t0)*Square(_.t0)*Vector2(23.375,24))+(Pow(_.t0,3)*Vector2(24,24))", _stepThenHoldEasingFunction);
		// Frame 59.
		result.InsertKeyFrame(0.737500012F, new Vector2(24.0F, 24.0F), _stepThenHoldEasingFunction);
		// Frame 60.
		result.InsertKeyFrame(0.75F, new Vector2(24.9379997F, 24.0F), _holdThenStepEasingFunction);
		// Frame 70.
		result.InsertKeyFrame(0.875F, new Vector2(20.25F, 24.0F), _cubicBezierEasingFunction_1);
		// Frame 79.
		result.InsertExpressionKeyFrame(0.987499952F, "Pow(1-_.t0,3)*Vector2(20.25,24)+(3*Square(1-_.t0)*_.t0*Vector2(20.094,24))+(3*(1-_.t0)*Square(_.t0)*Vector2(23.375,24))+(Pow(_.t0,3)*Vector2(24,24))", _stepThenHoldEasingFunction);
		// Frame 79.
		result.InsertKeyFrame(0.987500012F, new Vector2(24.0F, 24.0F), _stepThenHoldEasingFunction);
		return result;
	}

	// - - PreComp layer: Controls - 03 - Back - 02 - NormalToPressed Controls - 03 - Back
	// - 04 - PointerOverToPressed  Controls - 03 - Back - 05 - PressedToNormal Controls -
	// 03 - Back - 06 - PressedToPointerOver
	// - Opacity for layer: Controls - 03 - Back - 02 - NormalToPressed Controls - 03 -
	// Back - 04 - PointerOverToPressed  Controls - 03 - Back - 05 - PressedToNormal
	// Controls - 03 - Back - 06 - PressedToPointerOver
	// Layer: Round Cap 2 Round Cap 2 Round Cap 2 Round Cap 2
	// Offset
	private Vector2KeyFrameAnimation OffsetVector2Animation_1()
	{
		// Frame 0.
		var result = CreateVector2KeyFrameAnimation(0.0F, new Vector2(24.0F, 24.0F), _stepThenHoldEasingFunction);
		// Frame 10.
		result.InsertKeyFrame(0.125F, new Vector2(24.0F, 24.0F), _holdThenStepEasingFunction);
		// Frame 19.
		result.InsertKeyFrame(0.237499997F, new Vector2(33.0F, 24.0F), _cubicBezierEasingFunction_0);
		// Frame 30.
		result.InsertKeyFrame(0.375F, new Vector2(24.0F, 24.0F), _holdThenStepEasingFunction);
		// Frame 39.
		result.InsertKeyFrame(0.487500012F, new Vector2(33.0F, 24.0F), _cubicBezierEasingFunction_0);
		// Frame 40.
		result.InsertKeyFrame(0.5F, new Vector2(33.0F, 24.0F), _holdThenStepEasingFunction);
		// Frame 50.
		result.InsertKeyFrame(0.625F, new Vector2(19.9839993F, 24.0F), CubicBezierEasingFunction_4());
		// Frame 59.
		result.InsertKeyFrame(0.737500012F, new Vector2(24.0F, 24.0F), _cubicBezierEasingFunction_2);
		// Frame 60.
		result.InsertKeyFrame(0.75F, new Vector2(33.0F, 24.0F), _holdThenStepEasingFunction);
		// Frame 70.
		result.InsertKeyFrame(0.875F, new Vector2(19.9839993F, 24.0F), _cubicBezierEasingFunction_4);
		// Frame 79.
		result.InsertKeyFrame(0.987500012F, new Vector2(24.0F, 24.0F), _cubicBezierEasingFunction_2);
		return result;
	}

	public AnimatedBackVisualSource_AnimatedVisual(
		Compositor compositor,
		CompositionPropertySet themeProperties)
	{
		_c = compositor;
		_themeProperties = themeProperties;
		_reusableExpressionAnimation = compositor.CreateExpressionAnimation();

		_ = Root();
	}

	/// <summary>Releases the underlying composition tree.</summary>
	public void Dispose()
	{
		if (_root != null)
		{
			_root.Dispose();
		}
	}

	/// <summary>Gets the duration of the animated visual.</summary>
	public TimeSpan Duration => new TimeSpan(c_durationTicks);

	/// <summary>Gets the root <see cref="Visual"/> of the animated visual.</summary>
	public Visual RootVisual => _root;

	/// <summary>Gets the natural size of the animated visual.</summary>
	public Vector2 Size => new Vector2(48.0F, 48.0F);

	internal static bool IsRuntimeCompatible()
	{
#if HAS_UNO
		// Uno's Skia composition pipeline supports the APIs this animated visual depends on.
		return true;
#else
		return ApiInformation.IsApiContractPresent("Windows.Foundation.UniversalApiContract", 7);
#endif
	}
}
