//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     LottieGen version: 7.1.0+ge1fa92580f
// </auto-generated>
//------------------------------------------------------------------------------
// MUX Reference AnimatedChevronRightDownSmallVisualSource.h, commit 5f9e85113

#nullable enable

// Name:        Controls_08_SideChevron_TreeViewExpand
// Frame rate:  60 fps
// Frame count: 220
// Duration:    3666.7 mS
// Markers and theme property tables omitted for brevity. See the source for full data.

using Microsoft.UI.Composition;
using Color = Windows.UI.Color;

namespace Microsoft.UI.Xaml.Controls.AnimatedVisuals;

partial class AnimatedChevronRightDownSmallVisualSource
{
	private CompositionPropertySet? _themeProperties;
	private Color _themeForeground = Color.FromArgb(0xFF, 0x06, 0x08, 0x08);

	// Animation duration: 3.667 seconds.
	internal const long c_durationTicks = 36666666L;

	// Marker: NormalOnToNormalOff_Start.
	public const float M_NormalOnToNormalOff_Start = 0.0F;

	// Marker: NormalOnToNormalOff_End.
	public const float M_NormalOnToNormalOff_End = 0.0411363654F;

	// Marker: NormalOnToPointerOverOn_Start.
	public const float M_NormalOnToPointerOverOn_Start = 0.0456818193F;

	// Marker: NormalOnToPointerOverOn_End.
	public const float M_NormalOnToPointerOverOn_End = 0.0865909085F;

	// Marker: NormalOnToPressedOn_Start.
	public const float M_NormalOnToPressedOn_Start = 0.0911363661F;

	// Marker: NormalOnToPressedOn_End.
	public const float M_NormalOnToPressedOn_End = 0.132045448F;

	// Marker: NormalOffToNormalOn_Start.
	public const float M_NormalOffToNormalOn_Start = 0.136590913F;

	// Marker: NormalOffToNormalOn_End.
	public const float M_NormalOffToNormalOn_End = 0.268409103F;

	// Marker: NormalOffToPointerOverOff_Start.
	public const float M_NormalOffToPointerOverOff_Start = 0.272954553F;

	// Marker: NormalOffToPointerOverOff_End.
	public const float M_NormalOffToPointerOverOff_End = 0.313863635F;

	// Marker: NormalOffToPressedOff_Start.
	public const float M_NormalOffToPressedOff_Start = 0.318409085F;

	// Marker: NormalOffToPressedOff_End.
	public const float M_NormalOffToPressedOff_End = 0.359318167F;

	// Marker: PointerOverOnToPointerOverOff_Start.
	public const float M_PointerOverOnToPointerOverOff_Start = 0.363863647F;

	// Marker: PointerOverOnToPointerOverOff_End.
	public const float M_PointerOverOnToPointerOverOff_End = 0.404772729F;

	// Marker: PointerOverOnToNormalOn_Start.
	public const float M_PointerOverOnToNormalOn_Start = 0.409318179F;

	// Marker: PointerOverOnToNormalOn_End.
	public const float M_PointerOverOnToNormalOn_End = 0.450227261F;

	// Marker: PointerOverOnToPressedOn_Start.
	public const float M_PointerOverOnToPressedOn_Start = 0.454772741F;

	// Marker: PointerOverOnToPressedOn_End.
	public const float M_PointerOverOnToPressedOn_End = 0.495681822F;

	// Marker: PointerOverOffToPointerOverOn_Start.
	public const float M_PointerOverOffToPointerOverOn_Start = 0.500227273F;

	// Marker: PointerOverOffToPointerOverOn_End.
	public const float M_PointerOverOffToPointerOverOn_End = 0.541136384F;

	// Marker: PointerOverOffToNormalOff_Start.
	public const float M_PointerOverOffToNormalOff_Start = 0.545681834F;

	// Marker: PointerOverOffToNormalOff_End.
	public const float M_PointerOverOffToNormalOff_End = 0.586590886F;

	// Marker: PointerOverOffToPressedOff_Start.
	public const float M_PointerOverOffToPressedOff_Start = 0.591136336F;

	// Marker: PointerOverOffToPressedOff_End.
	public const float M_PointerOverOffToPressedOff_End = 0.632045448F;

	// Marker: PressedOnToPressedOff_Start.
	public const float M_PressedOnToPressedOff_Start = 0.636590898F;

	// Marker: PressedOnToPressedOff_End.
	public const float M_PressedOnToPressedOff_End = 0.67750001F;

	// Marker: PressedOnToPointerOverOff_Start.
	public const float M_PressedOnToPointerOverOff_Start = 0.68204546F;

	// Marker: PressedOnToPointerOverOff_End.
	public const float M_PressedOnToPointerOverOff_End = 0.722954571F;

	// Marker: PressedOnToNormalOff_Start.
	public const float M_PressedOnToNormalOff_Start = 0.727500021F;

	// Marker: PressedOnToNormalOff_End.
	public const float M_PressedOnToNormalOff_End = 0.768409073F;

	// Marker: PressedOffToPressedOn_Start.
	public const float M_PressedOffToPressedOn_Start = 0.772954524F;

	// Marker: PressedOffToPressedOn_End.
	public const float M_PressedOffToPressedOn_End = 0.813863635F;

	// Marker: PressedOffToPointerOverOn_Start.
	public const float M_PressedOffToPointerOverOn_Start = 0.818409085F;

	// Marker: PressedOffToPointerOverOn_End.
	public const float M_PressedOffToPointerOverOn_End = 0.904772699F;

	// Marker: PressedOffToNormalOn_Start.
	public const float M_PressedOffToNormalOn_Start = 0.909318209F;

	// Marker: PressedOffToNormalOn_End.
	public const float M_PressedOffToNormalOn_End = 0.995681822F;

	// Theme property: Foreground.
	private static readonly Color c_themeForeground = Color.FromArgb(0xFF, 0x06, 0x08, 0x08);
}
