//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     LottieGen version: 7.1.0+ge1fa92580f
// </auto-generated>
//------------------------------------------------------------------------------
// MUX Reference AnimatedSettingsVisualSource.cpp, commit 5f9e85113

using System;
using System.Collections.Generic;
using System.Numerics;
using Microsoft.UI.Composition;
using Microsoft.UI.Xaml.Controls;
using Color = Windows.UI.Color;

namespace Microsoft.UI.Xaml.Controls.AnimatedVisuals;

partial class AnimatedSettingsVisualSource
{
	private static Vector4 ColorAsVector4(Color color)
	{
		return new Vector4((float)color.R, (float)color.G, (float)color.B, (float)color.A);
	}

	private CompositionPropertySet EnsureThemeProperties(Compositor compositor)
	{
		if (_themeProperties == null)
		{
			_themeProperties = compositor.CreatePropertySet();
			_themeProperties.InsertVector4("Foreground", ColorAsVector4(_themeForeground));
		}

		return _themeProperties;
	}

	/// <summary>
	/// Gets or sets the color used for the settings icon's foreground.
	/// </summary>
	/// <value>The foreground <see cref="Color"/>. The default is <c>#FF131718</c>.</value>
	public Color Foreground
	{
		get => _themeForeground;
		set
		{
			_themeForeground = value;
			if (_themeProperties != null)
			{
				_themeProperties.InsertVector4("Foreground", ColorAsVector4(_themeForeground));
			}
		}
	}

	/// <summary>
	/// Tries to create a new <see cref="IAnimatedVisual"/> for the specified compositor.
	/// </summary>
	/// <param name="compositor">The compositor that will own the created visual.</param>
	/// <returns>An <see cref="IAnimatedVisual"/> that hosts the icon's composition tree, or
	/// <c>null</c> if the runtime is not compatible.</returns>
	public IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor)
	{
		object diagnostics = null;
		return TryCreateAnimatedVisual(compositor, out diagnostics);
	}

	/// <summary>
	/// Tries to create a new <see cref="IAnimatedVisual"/> for the specified compositor.
	/// </summary>
	/// <param name="compositor">The compositor that will own the created visual.</param>
	/// <param name="diagnostics">A diagnostics object that the source can populate if creation
	/// fails. Always <c>null</c> for this lottie-generated source.</param>
	/// <returns>An <see cref="IAnimatedVisual"/> that hosts the icon's composition tree, or
	/// <c>null</c> if the runtime is not compatible.</returns>
	public IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor, out object diagnostics)
	{
		_ = EnsureThemeProperties(compositor);
		diagnostics = null;

		if (AnimatedSettingsVisualSource_AnimatedVisual.IsRuntimeCompatible())
		{
			return new AnimatedSettingsVisualSource_AnimatedVisual(
				compositor,
				_themeProperties!);
		}

		return null;
	}

	/// <summary>Gets the number of frames in the animation.</summary>
	public double FrameCount => 120.0;

	/// <summary>Gets the framerate of the animation in frames-per-second.</summary>
	public double Framerate => 60.0;

	/// <summary>Gets the duration of the animation.</summary>
	public TimeSpan Duration => new TimeSpan(20000000L);

	/// <summary>
	/// Converts a zero-based frame number to the corresponding progress value denoting the
	/// start of the frame.
	/// </summary>
	/// <param name="frameNumber">The frame number to convert.</param>
	/// <returns>A normalized progress value (0..1) corresponding to the start of the frame.</returns>
	public double FrameToProgress(double frameNumber)
	{
		return frameNumber / 120.0;
	}

	/// <summary>
	/// Gets the markers defined in the source animation, mapped to their normalized progress values.
	/// </summary>
	public IReadOnlyDictionary<string, double> Markers => s_markers;

	private static readonly IReadOnlyDictionary<string, double> s_markers = new Dictionary<string, double>
	{
		{ "NormalToPointerOver_Start", 0.0 },
		{ "NormalToPointerOver_End", 0.0754166666666667 },
		{ "NormalToPressed_Start", 0.08375 },
		{ "NormalToPressed_End", 0.15875 },
		{ "PointerOverToNormal_Start", 0.167083333333333 },
		{ "PointerOverToNormal_End", 0.242083333333333 },
		{ "PointerOverToPressed_Start", 0.250416666666667 },
		{ "PointerOverToPressed_End", 0.325416666666667 },
		{ "PressedToNormal_Start", 0.33375 },
		{ "PressedToNormal_End", 0.65875 },
		{ "PressedToPointerOver_Start", 0.667083333333333 },
		{ "PressedToPointerOver_End", 0.992083333333333 },
	};

	/// <summary>
	/// Sets the color property with the given name, or does nothing if no such property exists.
	/// </summary>
	/// <param name="propertyName">Name of the color property to set. Only "Foreground" is supported.</param>
	/// <param name="value">The new color value.</param>
	public void SetColorProperty(string propertyName, Color value)
	{
		if (propertyName == "Foreground")
		{
			_themeForeground = value;
		}
		else
		{
			return;
		}

		if (_themeProperties != null)
		{
			_themeProperties.InsertVector4(propertyName, ColorAsVector4(value));
		}
	}

	/// <summary>
	/// Sets the scalar property with the given name, or does nothing if no such property exists.
	/// </summary>
	/// <param name="propertyName">Name of the scalar property to set.</param>
	/// <param name="value">The new value.</param>
	public void SetScalarProperty(string propertyName, double value)
	{
	}
}
