//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//       LottieGen version:
//           7.1.0+ge1fa92580f
//
//       Command:
//           LottieGen -Language Cppwinrt -WinUIVersion 2.4 -InputFile AnimatedSettingsVisualSource.json
//
//       Input file:
//           AnimatedSettingsVisualSource.json (28705 bytes created 23:37-07:00 Oct 5 2021)
//
//       LottieGen source:
//           http://aka.ms/Lottie
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// MUX Reference AnimatedSettingsVisualSource.cpp/.h, commit 5f9e85113

using System;
using System.Collections.Generic;
using Microsoft.UI.Xaml.Controls;

namespace Microsoft.UI.Xaml.Controls.AnimatedVisuals;

/// <summary>
/// A settings (gear) icon represented as an animated visual that responds to the
/// <see cref="AnimatedIcon"/> states (Normal, PointerOver, Pressed).
/// </summary>
/// <remarks>
/// The animation is generated from a Lottie JSON file using the
/// <see href="https://aka.ms/Lottie">LottieGen tool</see> and exposes a single
/// theme color (<see cref="Foreground"/>) that drives the icon's color.
/// </remarks>
public partial class AnimatedSettingsVisualSource : IAnimatedVisualSource, IAnimatedVisualSource2
{
}
