//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     LottieGen version: 7.1.0+ge1fa92580f
// </auto-generated>
//------------------------------------------------------------------------------
// MUX Reference AnimatedChevronUpDownSmallVisualSource.h, commit 5f9e85113

#nullable enable

// Name:        Controls_07_DownChevron_Expand+NavView
// Frame rate:  60 fps
// Frame count: 260
// Duration:    4333.3 mS
// Markers and theme property tables omitted for brevity. See the source for full data.

using Microsoft.UI.Composition;
using Color = Windows.UI.Color;

namespace Microsoft.UI.Xaml.Controls.AnimatedVisuals;

partial class AnimatedChevronUpDownSmallVisualSource
{
	private CompositionPropertySet? _themeProperties;
	private Color _themeForeground = Color.FromArgb(0xFF, 0x00, 0x00, 0x00);

	// Animation duration: 4.333 seconds.
	internal const long c_durationTicks = 43333333L;

	// Marker: NormalOnToNormalOff_Start.
	public const float M_NormalOnToNormalOff_Start = 0.0F;

	// Marker: NormalOnToNormalOff_End.
	public const float M_NormalOnToNormalOff_End = 0.111730769F;

	// Marker: NormalOnToPointerOverOn_Start.
	public const float M_NormalOnToPointerOverOn_Start = 0.115576923F;

	// Marker: NormalOnToPointerOverOn_End.
	public const float M_NormalOnToPointerOverOn_End = 0.150192305F;

	// Marker: NormalOnToPressedOn_Start.
	public const float M_NormalOnToPressedOn_Start = 0.154038459F;

	// Marker: NormalOnToPressedOn_End.
	public const float M_NormalOnToPressedOn_End = 0.188653842F;

	// Marker: NormalOffToNormalOn_Start.
	public const float M_NormalOffToNormalOn_Start = 0.192499995F;

	// Marker: NormalOffToNormalOn_End.
	public const float M_NormalOffToNormalOn_End = 0.304038465F;

	// Marker: NormalOffToPointerOverOff_Start.
	public const float M_NormalOffToPointerOverOff_Start = 0.307884604F;

	// Marker: NormalOffToPointerOverOff_End.
	public const float M_NormalOffToPointerOverOff_End = 0.342500001F;

	// Marker: NormalOffToPressedOff_Start.
	public const float M_NormalOffToPressedOff_Start = 0.34634614F;

	// Marker: NormalOffToPressedOff_End.
	public const float M_NormalOffToPressedOff_End = 0.380961537F;

	// Marker: PointerOverOnToPointerOverOff_Start.
	public const float M_PointerOverOnToPointerOverOff_Start = 0.384807706F;

	// Marker: PointerOverOnToPointerOverOff_End.
	public const float M_PointerOverOnToPointerOverOff_End = 0.419423074F;

	// Marker: PointerOverOnToNormalOn_Start.
	public const float M_PointerOverOnToNormalOn_Start = 0.423269242F;

	// Marker: PointerOverOnToNormalOn_End.
	public const float M_PointerOverOnToNormalOn_End = 0.45788461F;

	// Marker: PointerOverOnToPressedOn_Start.
	public const float M_PointerOverOnToPressedOn_Start = 0.461730778F;

	// Marker: PointerOverOnToPressedOn_End.
	public const float M_PointerOverOnToPressedOn_End = 0.496346146F;

	// Marker: PointerOverOffToPointerOverOn_Start.
	public const float M_PointerOverOffToPointerOverOn_Start = 0.500192285F;

	// Marker: PointerOverOffToPointerOverOn_End.
	public const float M_PointerOverOffToPointerOverOn_End = 0.534807682F;

	// Marker: PointerOverOffToNormalOff_Start.
	public const float M_PointerOverOffToNormalOff_Start = 0.538653851F;

	// Marker: PointerOverOffToNormalOff_End.
	public const float M_PointerOverOffToNormalOff_End = 0.573269248F;

	// Marker: PointerOverOffToPressedOff_Start.
	public const float M_PointerOverOffToPressedOff_Start = 0.577115357F;

	// Marker: PointerOverOffToPressedOff_End.
	public const float M_PointerOverOffToPressedOff_End = 0.611730754F;

	// Marker: PressedOnToPressedOff_Start.
	public const float M_PressedOnToPressedOff_Start = 0.615576923F;

	// Marker: PressedOnToPressedOff_End.
	public const float M_PressedOnToPressedOff_End = 0.65019232F;

	// Marker: PressedOnToPointerOverOff_Start.
	public const float M_PressedOnToPointerOverOff_Start = 0.654038489F;

	// Marker: PressedOnToPointerOverOff_End.
	public const float M_PressedOnToPointerOverOff_End = 0.727115393F;

	// Marker: PressedOnToNormalOff_Start.
	public const float M_PressedOnToNormalOff_Start = 0.730961561F;

	// Marker: PressedOnToNormalOff_End.
	public const float M_PressedOnToNormalOff_End = 0.804038465F;

	// Marker: PressedOffToPressedOn_Start.
	public const float M_PressedOffToPressedOn_Start = 0.807884634F;

	// Marker: PressedOffToPressedOn_End.
	public const float M_PressedOffToPressedOn_End = 0.842499971F;

	// Marker: PressedOffToPointerOverOn_Start.
	public const float M_PressedOffToPointerOverOn_Start = 0.84634614F;

	// Marker: PressedOffToPointerOverOn_End.
	public const float M_PressedOffToPointerOverOn_End = 0.919423103F;

	// Marker: PressedOffToNormalOn_Start.
	public const float M_PressedOffToNormalOn_Start = 0.923269212F;

	// Marker: PressedOffToNormalOn_End.
	public const float M_PressedOffToNormalOn_End = 0.996346176F;

	// Theme property: Foreground.
	private static readonly Color c_themeForeground = Color.FromArgb(0xFF, 0x00, 0x00, 0x00);
}
