//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     LottieGen version: 7.1.0+ge1fa92580f
// </auto-generated>
//------------------------------------------------------------------------------
// MUX Reference AnimatedSettingsVisualSource.cpp (nested AnimatedSettingsVisualSource_AnimatedVisual class), commit 5f9e85113

// ____________________________________
// |       Object stats       | Count |
// |__________________________|_______|
// | All CompositionObjects   |    63 |
// |--------------------------+-------|
// | Expression animators     |     7 |
// | KeyFrame animators       |     6 |
// | Reference parameters     |     7 |
// | Expression operations    |     4 |
// |--------------------------+-------|
// | Animated brushes         |     1 |
// | Animated gradient stops  |     - |
// | ExpressionAnimations     |     2 |
// | PathKeyFrameAnimations   |     - |
// |--------------------------+-------|
// | ContainerVisuals         |     4 |
// | ShapeVisuals             |     3 |
// |--------------------------+-------|
// | ContainerShapes          |     - |
// | CompositionSpriteShapes  |     3 |
// |--------------------------+-------|
// | Brushes                  |     1 |
// | Gradient stops           |     - |
// | CompositionVisualSurface |     - |
// ------------------------------------

using System;
using System.Numerics;
using Microsoft.Graphics.Canvas.Geometry;
using Microsoft.UI.Composition;
using Microsoft.UI.Xaml.Controls;
using Windows.Foundation;
using Windows.Foundation.Metadata;

namespace Microsoft.UI.Xaml.Controls.AnimatedVisuals;

/// <summary>
/// The IAnimatedVisual implementation that builds the settings (gear) composition tree and
/// drives its property animations.
/// </summary>
internal sealed class AnimatedSettingsVisualSource_AnimatedVisual : IAnimatedVisual
{
	private const long c_durationTicks = 20000000L;

	private readonly Compositor _c;
	private readonly ExpressionAnimation _reusableExpressionAnimation;
	private readonly CompositionPropertySet _themeProperties;

	private CompositionColorBrush _themeColor_Foreground;
	private CompositionPathGeometry _pathGeometry;
	private ContainerVisual _root;
	private CubicBezierEasingFunction _cubicBezierEasingFunction_0;
	private CubicBezierEasingFunction _cubicBezierEasingFunction_1;
	private ExpressionAnimation _rootProgress;
	private InsetClip _insetClip_0;
	private StepEasingFunction _holdThenStepEasingFunction;
	private StepEasingFunction _stepThenHoldEasingFunction;

	private static void StartProgressBoundAnimation(
		CompositionObject target,
		string animatedPropertyName,
		CompositionAnimation animation,
		ExpressionAnimation controllerProgressExpression)
	{
		target.StartAnimation(animatedPropertyName, animation);
		var controller = target.TryGetAnimationController(animatedPropertyName);
		controller.Pause();
		controller.StartAnimation("Progress", controllerProgressExpression);
	}

	private void BindProperty(
		CompositionObject target,
		string animatedPropertyName,
		string expression,
		string referenceParameterName,
		CompositionObject referencedObject)
	{
		_reusableExpressionAnimation.ClearAllParameters();
		_reusableExpressionAnimation.Expression = expression;
		_reusableExpressionAnimation.SetReferenceParameter(referenceParameterName, referencedObject);
		target.StartAnimation(animatedPropertyName, _reusableExpressionAnimation);
	}

	private BooleanKeyFrameAnimation CreateBooleanKeyFrameAnimation(float initialProgress, bool initialValue)
	{
		var result = _c.CreateBooleanKeyFrameAnimation();
		result.Duration = new TimeSpan(c_durationTicks);
		result.InsertKeyFrame(initialProgress, initialValue);
		return result;
	}

	private ScalarKeyFrameAnimation CreateScalarKeyFrameAnimation(float initialProgress, float initialValue, CompositionEasingFunction initialEasingFunction)
	{
		var result = _c.CreateScalarKeyFrameAnimation();
		result.Duration = new TimeSpan(c_durationTicks);
		result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
		return result;
	}

	// PreComp layer: Controls - 04 - Settings - 06 - PressedToPointerOver
	private BooleanKeyFrameAnimation IsVisibleBooleanAnimation_0()
	{
		// Frame 80.
		var result = CreateBooleanKeyFrameAnimation(0.666666687F, true);
		return result;
	}

	// PreComp layer: Controls - 04 - Settings - 05 - PressedToNormal
	private BooleanKeyFrameAnimation IsVisibleBooleanAnimation_1()
	{
		// Frame 40.
		var result = CreateBooleanKeyFrameAnimation(0.333333343F, true);
		// Frame 80.
		result.InsertKeyFrame(0.666666687F, false);
		return result;
	}

	// PreComp layer: Controls - 04 - Settings - 01 - NormalToPointerOver Controls - 04 -
	// Settings - 02 - NormalToPressed Controls - 04 - Settings - 03 - PointerOverToNormal
	// Controls - 04 - Settings - 04 - PointerOverToPressed
	private BooleanKeyFrameAnimation IsVisibleBooleanAnimation_2()
	{
		// Frame 40.
		var result = CreateBooleanKeyFrameAnimation(0.333333343F, false);
		return result;
	}

	// - Path 4+Path 3+Path 2+Path 1.PathGeometry
	private CanvasGeometry Geometry_0()
	{
		var geometries = new CanvasGeometry[]
		{
			Geometry_1(),
			Geometry_2(),
			Geometry_3(),
			Geometry_4(),
		};
		return CanvasGeometry.CreateGroup(null, geometries, CanvasFilledRegionDetermination.Winding);
	}

	// - - Path 4+Path 3+Path 2+Path 1.PathGeometry
	private CanvasGeometry Geometry_1()
	{
		var builder = new CanvasPathBuilder(null);
		builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
		builder.BeginFigure(new Vector2(48.8800011F, 30.9810009F));
		builder.AddCubicBezier(new Vector2(49.1990013F, 29.9960003F), new Vector2(49.7229996F, 29.0919991F), new Vector2(50.4160004F, 28.3250008F));
		builder.AddCubicBezier(new Vector2(50.5330009F, 28.1949997F), new Vector2(50.7169991F, 28.1490002F), new Vector2(50.8810005F, 28.2080002F));
		builder.AddLine(new Vector2(52.5359993F, 28.7989998F));
		builder.AddCubicBezier(new Vector2(52.9850006F, 28.9589996F), new Vector2(53.4790001F, 28.7259998F), new Vector2(53.6389999F, 28.2770004F));
		builder.AddCubicBezier(new Vector2(53.6549988F, 28.2329998F), new Vector2(53.6669998F, 28.1879997F), new Vector2(53.6749992F, 28.1420002F));
		builder.AddLine(new Vector2(53.9900017F, 26.4109993F));
		builder.AddCubicBezier(new Vector2(54.0209999F, 26.2390003F), new Vector2(54.1539993F, 26.1019993F), new Vector2(54.3250008F, 26.066F));
		builder.AddCubicBezier(new Vector2(54.8260002F, 25.9589996F), new Vector2(55.3390007F, 25.9060001F), new Vector2(55.8590012F, 25.9060001F));
		builder.AddCubicBezier(new Vector2(56.3790016F, 25.9060001F), new Vector2(56.8919983F, 25.9599991F), new Vector2(57.3919983F, 26.066F));
		builder.AddCubicBezier(new Vector2(57.5629997F, 26.1019993F), new Vector2(57.6949997F, 26.2390003F), new Vector2(57.7260017F, 26.4109993F));
		builder.AddLine(new Vector2(58.0419998F, 28.1420002F));
		builder.AddCubicBezier(new Vector2(58.1279984F, 28.6110001F), new Vector2(58.5769997F, 28.9209995F), new Vector2(59.0460014F, 28.8360004F));
		builder.AddCubicBezier(new Vector2(59.0919991F, 28.8279991F), new Vector2(59.137001F, 28.8150005F), new Vector2(59.1809998F, 28.7989998F));
		builder.AddLine(new Vector2(60.8359985F, 28.2080002F));
		builder.AddCubicBezier(new Vector2(61.0F, 28.1490002F), new Vector2(61.1850014F, 28.1949997F), new Vector2(61.3019981F, 28.3250008F));
		builder.AddCubicBezier(new Vector2(61.9949989F, 29.0919991F), new Vector2(62.519001F, 29.9960003F), new Vector2(62.8380013F, 30.9810009F));
		builder.AddCubicBezier(new Vector2(62.8919983F, 31.1469994F), new Vector2(62.8390007F, 31.3299999F), new Vector2(62.7060013F, 31.4430008F));
		builder.AddLine(new Vector2(61.3650017F, 32.5810013F));
		builder.AddCubicBezier(new Vector2(61.0019989F, 32.8889999F), new Vector2(60.9580002F, 33.4350014F), new Vector2(61.2659988F, 33.7980003F));
		builder.AddCubicBezier(new Vector2(61.2960014F, 33.8339996F), new Vector2(61.3289986F, 33.8670006F), new Vector2(61.3650017F, 33.8969994F));
		builder.AddLine(new Vector2(62.7060013F, 35.0359993F));
		builder.AddCubicBezier(new Vector2(62.8390007F, 35.1489983F), new Vector2(62.8919983F, 35.3310013F), new Vector2(62.8380013F, 35.4970016F));
		builder.AddCubicBezier(new Vector2(62.519001F, 36.4819984F), new Vector2(61.9949989F, 37.387001F), new Vector2(61.3019981F, 38.1539993F));
		builder.AddCubicBezier(new Vector2(61.1850014F, 38.2840004F), new Vector2(61.0F, 38.3300018F), new Vector2(60.8359985F, 38.2709999F));
		builder.AddLine(new Vector2(59.1809998F, 37.6790009F));
		builder.AddCubicBezier(new Vector2(58.7319984F, 37.519001F), new Vector2(58.2389984F, 37.7519989F), new Vector2(58.0789986F, 38.2010002F));
		builder.AddCubicBezier(new Vector2(58.0629997F, 38.2449989F), new Vector2(58.0499992F, 38.2910004F), new Vector2(58.0419998F, 38.3370018F));
		builder.AddLine(new Vector2(57.7260017F, 40.0680008F));
		builder.AddCubicBezier(new Vector2(57.6949997F, 40.2400017F), new Vector2(57.5629997F, 40.3759995F), new Vector2(57.3919983F, 40.4119987F));
		builder.AddCubicBezier(new Vector2(56.8919983F, 40.5180016F), new Vector2(56.3790016F, 40.5730019F), new Vector2(55.8590012F, 40.5730019F));
		builder.AddCubicBezier(new Vector2(55.3390007F, 40.5730019F), new Vector2(54.8260002F, 40.519001F), new Vector2(54.3250008F, 40.4119987F));
		builder.AddCubicBezier(new Vector2(54.1539993F, 40.3759995F), new Vector2(54.0209999F, 40.2389984F), new Vector2(53.9900017F, 40.0670013F));
		builder.AddLine(new Vector2(53.6749992F, 38.3370018F));
		builder.AddCubicBezier(new Vector2(53.5900002F, 37.868F), new Vector2(53.1409988F, 37.5569992F), new Vector2(52.6720009F, 37.6430016F));
		builder.AddCubicBezier(new Vector2(52.6259995F, 37.651001F), new Vector2(52.5800018F, 37.6629982F), new Vector2(52.5359993F, 37.6790009F));
		builder.AddLine(new Vector2(50.8810005F, 38.2709999F));
		builder.AddCubicBezier(new Vector2(50.7169991F, 38.3300018F), new Vector2(50.5330009F, 38.2840004F), new Vector2(50.4160004F, 38.1539993F));
		builder.AddCubicBezier(new Vector2(49.7229996F, 37.387001F), new Vector2(49.1990013F, 36.4819984F), new Vector2(48.8800011F, 35.4970016F));
		builder.AddCubicBezier(new Vector2(48.8260002F, 35.3310013F), new Vector2(48.8779984F, 35.1489983F), new Vector2(49.0110016F, 35.0359993F));
		builder.AddLine(new Vector2(50.3520012F, 33.8969994F));
		builder.AddCubicBezier(new Vector2(50.7150002F, 33.5890007F), new Vector2(50.7599983F, 33.0439987F), new Vector2(50.4519997F, 32.6809998F));
		builder.AddCubicBezier(new Vector2(50.4220009F, 32.6450005F), new Vector2(50.3880005F, 32.6110001F), new Vector2(50.3520012F, 32.5810013F));
		builder.AddLine(new Vector2(49.0110016F, 31.4430008F));
		builder.AddCubicBezier(new Vector2(48.8779984F, 31.3299999F), new Vector2(48.8260002F, 31.1469994F), new Vector2(48.8800011F, 30.9810009F));
		builder.EndFigure(CanvasFigureLoop.Closed);
		return CanvasGeometry.CreatePath(builder);
	}

	// - - Path 4+Path 3+Path 2+Path 1.PathGeometry
	private CanvasGeometry Geometry_2()
	{
		var builder = new CanvasPathBuilder(null);
		builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
		builder.BeginFigure(new Vector2(49.7949982F, 30.9759998F));
		builder.AddLine(new Vector2(50.9109993F, 31.9239998F));
		builder.AddCubicBezier(new Vector2(50.9819984F, 31.9850006F), new Vector2(51.0480003F, 32.0509987F), new Vector2(51.1090012F, 32.1220016F));
		builder.AddCubicBezier(new Vector2(51.7260017F, 32.8479996F), new Vector2(51.637001F, 33.9370003F), new Vector2(50.9109993F, 34.5540009F));
		builder.AddLine(new Vector2(49.7949982F, 35.5019989F));
		builder.AddCubicBezier(new Vector2(50.0470009F, 36.1769981F), new Vector2(50.4099998F, 36.8040009F), new Vector2(50.8689995F, 37.3590012F));
		builder.AddLine(new Vector2(52.2459984F, 36.8670006F));
		builder.AddCubicBezier(new Vector2(52.3339996F, 36.8349991F), new Vector2(52.4249992F, 36.8110008F), new Vector2(52.5169983F, 36.7939987F));
		builder.AddCubicBezier(new Vector2(53.4550018F, 36.6230011F), new Vector2(54.3530006F, 37.2439995F), new Vector2(54.5239983F, 38.1819992F));
		builder.AddLine(new Vector2(54.7859993F, 39.6209984F));
		builder.AddCubicBezier(new Vector2(55.1380005F, 39.6800003F), new Vector2(55.4970016F, 39.7099991F), new Vector2(55.8590012F, 39.7099991F));
		builder.AddCubicBezier(new Vector2(56.2210007F, 39.7099991F), new Vector2(56.5789986F, 39.6800003F), new Vector2(56.9309998F, 39.6209984F));
		builder.AddLine(new Vector2(57.1940002F, 38.1819992F));
		builder.AddCubicBezier(new Vector2(57.2109985F, 38.0900002F), new Vector2(57.2340012F, 37.9990005F), new Vector2(57.2659988F, 37.9109993F));
		builder.AddCubicBezier(new Vector2(57.5870018F, 37.0139999F), new Vector2(58.5740013F, 36.5460014F), new Vector2(59.4720001F, 36.8670006F));
		builder.AddLine(new Vector2(60.848999F, 37.3590012F));
		builder.AddCubicBezier(new Vector2(61.3069992F, 36.8040009F), new Vector2(61.6710014F, 36.1769981F), new Vector2(61.9230003F, 35.5019989F));
		builder.AddLine(new Vector2(60.8069992F, 34.5540009F));
		builder.AddCubicBezier(new Vector2(60.7360001F, 34.493F), new Vector2(60.6689987F, 34.4269981F), new Vector2(60.6080017F, 34.355999F));
		builder.AddCubicBezier(new Vector2(59.9910011F, 33.6300011F), new Vector2(60.0810013F, 32.5410004F), new Vector2(60.8069992F, 31.9239998F));
		builder.AddLine(new Vector2(61.9230003F, 30.9759998F));
		builder.AddCubicBezier(new Vector2(61.6710014F, 30.3010006F), new Vector2(61.3069992F, 29.6739998F), new Vector2(60.848999F, 29.1189995F));
		builder.AddLine(new Vector2(59.4720001F, 29.6119995F));
		builder.AddCubicBezier(new Vector2(59.3839989F, 29.6439991F), new Vector2(59.2929993F, 29.6669998F), new Vector2(59.2010002F, 29.684F));
		builder.AddCubicBezier(new Vector2(58.2639999F, 29.8549995F), new Vector2(57.3650017F, 29.2339993F), new Vector2(57.1940002F, 28.2970009F));
		builder.AddLine(new Vector2(56.9309998F, 26.8570004F));
		builder.AddCubicBezier(new Vector2(56.5789986F, 26.7980003F), new Vector2(56.2210007F, 26.7679996F), new Vector2(55.8590012F, 26.7679996F));
		builder.AddCubicBezier(new Vector2(55.4970016F, 26.7679996F), new Vector2(55.1380005F, 26.7980003F), new Vector2(54.7859993F, 26.8570004F));
		builder.AddLine(new Vector2(54.5239983F, 28.2959995F));
		builder.AddCubicBezier(new Vector2(54.507F, 28.3880005F), new Vector2(54.4830017F, 28.4799995F), new Vector2(54.4510002F, 28.5680008F));
		builder.AddCubicBezier(new Vector2(54.1300011F, 29.4650002F), new Vector2(53.1430016F, 29.9330006F), new Vector2(52.2459984F, 29.6119995F));
		builder.AddLine(new Vector2(50.8689995F, 29.1189995F));
		builder.AddCubicBezier(new Vector2(50.4099998F, 29.6739998F), new Vector2(50.0470009F, 30.3010006F), new Vector2(49.7949982F, 30.9759998F));
		builder.EndFigure(CanvasFigureLoop.Closed);
		return CanvasGeometry.CreatePath(builder);
	}

	// - - Path 4+Path 3+Path 2+Path 1.PathGeometry
	private CanvasGeometry Geometry_3()
	{
		var builder = new CanvasPathBuilder(null);
		builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
		builder.BeginFigure(new Vector2(53.7019997F, 33.2389984F));
		builder.AddCubicBezier(new Vector2(53.7019997F, 32.0480003F), new Vector2(54.6679993F, 31.0820007F), new Vector2(55.8590012F, 31.0820007F));
		builder.AddCubicBezier(new Vector2(57.0499992F, 31.0820007F), new Vector2(58.0159988F, 32.0480003F), new Vector2(58.0159988F, 33.2389984F));
		builder.AddCubicBezier(new Vector2(58.0159988F, 34.4300003F), new Vector2(57.0499992F, 35.3959999F), new Vector2(55.8590012F, 35.3959999F));
		builder.AddCubicBezier(new Vector2(54.6679993F, 35.3959999F), new Vector2(53.7019997F, 34.4300003F), new Vector2(53.7019997F, 33.2389984F));
		builder.EndFigure(CanvasFigureLoop.Closed);
		return CanvasGeometry.CreatePath(builder);
	}

	// - - Path 4+Path 3+Path 2+Path 1.PathGeometry
	private CanvasGeometry Geometry_4()
	{
		var builder = new CanvasPathBuilder(null);
		builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
		builder.BeginFigure(new Vector2(54.5649986F, 33.2389984F));
		builder.AddCubicBezier(new Vector2(54.5649986F, 33.9539986F), new Vector2(55.144001F, 34.5330009F), new Vector2(55.8590012F, 34.5330009F));
		builder.AddCubicBezier(new Vector2(56.5740013F, 34.5330009F), new Vector2(57.1529999F, 33.9539986F), new Vector2(57.1529999F, 33.2389984F));
		builder.AddCubicBezier(new Vector2(57.1529999F, 32.5239983F), new Vector2(56.5740013F, 31.9449997F), new Vector2(55.8590012F, 31.9449997F));
		builder.AddCubicBezier(new Vector2(55.144001F, 31.9449997F), new Vector2(54.5649986F, 32.5239983F), new Vector2(54.5649986F, 33.2389984F));
		builder.EndFigure(CanvasFigureLoop.Closed);
		return CanvasGeometry.CreatePath(builder);
	}

	// Color bound to theme property value: Foreground
	private CompositionColorBrush ThemeColor_Foreground()
	{
		var result = _themeColor_Foreground = _c.CreateColorBrush();
		BindProperty(result, "Color", "ColorRGB(_theme.Foreground.W,_theme.Foreground.X,_theme.Foreground.Y,_theme.Foreground.Z)", "_theme", _themeProperties);
		return result;
	}

	// Path 4+Path 3+Path 2+Path 1.PathGeometry
	private CompositionPathGeometry PathGeometry()
	{
		return _pathGeometry = _c.CreatePathGeometry(new CompositionPath(Geometry_0()));
	}

	// - PreComp layer: Controls - 04 - Settings - 06 - PressedToPointerOver
	// Transforms for Controls - 04 - Settings - 06 - PressedToPointerOver Scale(1,1,0)
	// Path 4+Path 3+Path 2+Path 1
	private CompositionSpriteShape SpriteShape_0()
	{
		var result = _c.CreateSpriteShape(PathGeometry());
		result.CenterPoint = new Vector2(55.8590012F, 33.2389984F);
		result.Offset = new Vector2(-31.8590012F, -9.23899841F);
		result.Scale = new Vector2(3.0F, 3.0F);
		result.FillBrush = ThemeColor_Foreground();
		StartProgressBoundAnimation(result, "RotationAngleInDegrees", RotationAngleInDegreesScalarAnimation_0_to_360_0(), RootProgress());
		return result;
	}

	// - PreComp layer: Controls - 04 - Settings - 05 - PressedToNormal
	// Transforms for Controls - 04 - Settings - 05 - PressedToNormal Scale(1,1,0)
	// Path 4+Path 3+Path 2+Path 1
	private CompositionSpriteShape SpriteShape_1()
	{
		var result = _c.CreateSpriteShape(_pathGeometry);
		result.CenterPoint = new Vector2(55.8590012F, 33.2389984F);
		result.Offset = new Vector2(-31.8590012F, -9.23899841F);
		result.Scale = new Vector2(3.0F, 3.0F);
		result.FillBrush = _themeColor_Foreground;
		StartProgressBoundAnimation(result, "RotationAngleInDegrees", RotationAngleInDegreesScalarAnimation_0_to_360_1(), _rootProgress);
		return result;
	}

	// - PreComp layer: Controls - 04 - Settings - 01 - NormalToPointerOver Controls - 04
	// - Settings - 02 - NormalToPressed Controls - 04 - Settings - 03 -
	// PointerOverToNormal Controls - 04 - Settings - 04 - PointerOverToPressed
	// Transforms for Controls - 04 - Settings - 01 - NormalToPointerOver Controls - 04 -
	// Settings - 02 - NormalToPressed Controls - 04 - Settings - 03 - PointerOverToNormal
	// Controls - 04 - Settings - 04 - PointerOverToPressed Scale(1,1,0)
	// Path 4 Path 4 Path 4 Path 4+Path 3 Path 3 Path 3 Path 3+Path 2 Path 2 Path 2 Path
	// 2+Path 1 Path 1 Path 1 Path 1
	private CompositionSpriteShape SpriteShape_2()
	{
		var result = _c.CreateSpriteShape(_pathGeometry);
		result.CenterPoint = new Vector2(55.8590012F, 33.2389984F);
		result.Offset = new Vector2(-31.8590012F, -9.23899841F);
		result.Scale = new Vector2(3.0F, 3.0F);
		result.FillBrush = _themeColor_Foreground;
		StartProgressBoundAnimation(result, "RotationAngleInDegrees", RotationAngleInDegreesScalarAnimation_0_to_m20(), _rootProgress);
		return result;
	}

	// PreComp layer: Controls - 04 - Settings - 06 - PressedToPointerOver
	private ContainerVisual ContainerVisual_0()
	{
		var result = _c.CreateContainerVisual();
		result.Clip = InsetClip_0();
		result.IsVisible = false;
		result.Size = new Vector2(48.0F, 48.0F);
		// Scale:<1, 1> — Identity matrix.
		// Note: the WinUI-generated source applies a malformed 4x4 here with zeros on M22/M33.
		// In WinUI's column-major DComp pipeline that ends up being interpreted as identity for
		// 2D content; in Skia's row-major Matrix4x4 it would collapse the layer entirely. We
		// substitute identity which is the intended behavior.
		result.TransformMatrix = Matrix4x4.Identity;
		// Transforms for Controls - 04 - Settings - 06 - PressedToPointerOver Scale(1,1,0)
		result.Children.InsertAtTop(ShapeVisual_0());
		StartProgressBoundAnimation(result, "IsVisible", IsVisibleBooleanAnimation_0(), _rootProgress);
		return result;
	}

	// PreComp layer: Controls - 04 - Settings - 05 - PressedToNormal
	private ContainerVisual ContainerVisual_1()
	{
		var result = _c.CreateContainerVisual();
		result.Clip = _insetClip_0;
		result.IsVisible = false;
		result.Size = new Vector2(48.0F, 48.0F);
		// Scale:<1, 1> — Identity matrix (see ContainerVisual_0 for context).
		result.TransformMatrix = Matrix4x4.Identity;
		// Transforms for Controls - 04 - Settings - 05 - PressedToNormal Scale(1,1,0)
		result.Children.InsertAtTop(ShapeVisual_1());
		StartProgressBoundAnimation(result, "IsVisible", IsVisibleBooleanAnimation_1(), _rootProgress);
		return result;
	}

	// PreComp layer: Controls - 04 - Settings - 01 - NormalToPointerOver Controls - 04 -
	// Settings - 02 - NormalToPressed Controls - 04 - Settings - 03 - PointerOverToNormal
	// Controls - 04 - Settings - 04 - PointerOverToPressed
	private ContainerVisual ContainerVisual_2()
	{
		var result = _c.CreateContainerVisual();
		result.Clip = _insetClip_0;
		result.Size = new Vector2(48.0F, 48.0F);
		// Scale:<1, 1> — Identity matrix (see ContainerVisual_0 for context).
		result.TransformMatrix = Matrix4x4.Identity;
		// Transforms for Controls - 04 - Settings - 01 - NormalToPointerOver Controls - 04 -
		// Settings - 02 - NormalToPressed Controls - 04 - Settings - 03 - PointerOverToNormal
		// Controls - 04 - Settings - 04 - PointerOverToPressed Scale(1,1,0)
		result.Children.InsertAtTop(ShapeVisual_2());
		StartProgressBoundAnimation(result, "IsVisible", IsVisibleBooleanAnimation_2(), _rootProgress);
		return result;
	}

	// The root of the composition.
	private ContainerVisual Root()
	{
		var result = _root = _c.CreateContainerVisual();
		var propertySet = result.Properties;
		propertySet.InsertScalar("Progress", 0.0F);
		var children = result.Children;
		// PreComp layer: Controls - 04 - Settings - 06 - PressedToPointerOver
		children.InsertAtTop(ContainerVisual_0());
		// PreComp layer: Controls - 04 - Settings - 05 - PressedToNormal
		children.InsertAtTop(ContainerVisual_1());
		// PreComp layer: Controls - 04 - Settings - 01 - NormalToPointerOver Controls - 04 -
		// Settings - 02 - NormalToPressed Controls - 04 - Settings - 03 - PointerOverToNormal
		// Controls - 04 - Settings - 04 - PointerOverToPressed
		children.InsertAtTop(ContainerVisual_2());
		return result;
	}

	private CubicBezierEasingFunction CubicBezierEasingFunction_0()
	{
		return _cubicBezierEasingFunction_0 = _c.CreateCubicBezierEasingFunction(new Vector2(0.166999996F, 0.166999996F), new Vector2(1.0F, 1.0F));
	}

	private CubicBezierEasingFunction CubicBezierEasingFunction_1()
	{
		return _cubicBezierEasingFunction_1 = _c.CreateCubicBezierEasingFunction(new Vector2(0.0F, 0.0F), new Vector2(0.0F, 1.0F));
	}

	private ExpressionAnimation RootProgress()
	{
		var result = _rootProgress = _c.CreateExpressionAnimation("_.Progress");
		result.SetReferenceParameter("_", _root);
		return result;
	}

	private InsetClip InsetClip_0()
	{
		var result = _insetClip_0 = _c.CreateInsetClip();
		return result;
	}

	// - - PreComp layer: Controls - 04 - Settings - 06 - PressedToPointerOver
	// - Transforms for Controls - 04 - Settings - 06 - PressedToPointerOver Scale(1,1,0)
	// ShapeGroup: Group 1
	// Rotation
	private ScalarKeyFrameAnimation RotationAngleInDegreesScalarAnimation_0_to_360_0()
	{
		// Frame 0.
		var result = CreateScalarKeyFrameAnimation(0.0F, 0.0F, StepThenHoldEasingFunction());
		// Frame 70.
		result.InsertKeyFrame(0.583333313F, 0.0F, HoldThenStepEasingFunction());
		// Frame 80.
		result.InsertKeyFrame(0.666666687F, -20.0F, CubicBezierEasingFunction_0());
		// Frame 119.
		result.InsertKeyFrame(0.991666675F, 360.0F, CubicBezierEasingFunction_1());
		return result;
	}

	// - - PreComp layer: Controls - 04 - Settings - 05 - PressedToNormal
	// - Transforms for Controls - 04 - Settings - 05 - PressedToNormal Scale(1,1,0)
	// ShapeGroup: Group 1
	// Rotation
	private ScalarKeyFrameAnimation RotationAngleInDegreesScalarAnimation_0_to_360_1()
	{
		// Frame 0.
		var result = CreateScalarKeyFrameAnimation(0.0F, 0.0F, _stepThenHoldEasingFunction);
		// Frame 30.
		result.InsertKeyFrame(0.25F, 0.0F, _holdThenStepEasingFunction);
		// Frame 40.
		result.InsertKeyFrame(0.333333343F, -20.0F, _cubicBezierEasingFunction_0);
		// Frame 79.
		result.InsertKeyFrame(0.658333361F, 360.0F, _cubicBezierEasingFunction_1);
		return result;
	}

	// - - PreComp layer: Controls - 04 - Settings - 01 - NormalToPointerOver Controls -
	// 04 - Settings - 02 - NormalToPressed Controls - 04 - Settings - 03 -
	// PointerOverToNormal Controls - 04 - Settings - 04 - PointerOverToPressed
	// - Transforms for Controls - 04 - Settings - 01 - NormalToPointerOver Controls - 04
	// - Settings - 02 - NormalToPressed Controls - 04 - Settings - 03 -
	// PointerOverToNormal Controls - 04 - Settings - 04 - PointerOverToPressed
	// Scale(1,1,0)
	// ShapeGroup: Group 1 Group 1 Group 1 Group 1
	// Rotation
	private ScalarKeyFrameAnimation RotationAngleInDegreesScalarAnimation_0_to_m20()
	{
		// Frame 0.
		var result = CreateScalarKeyFrameAnimation(0.0F, 0.0F, _holdThenStepEasingFunction);
		// Frame 10.
		result.InsertKeyFrame(0.0833333358F, 0.0F, _holdThenStepEasingFunction);
		// Frame 19.
		result.InsertKeyFrame(0.158333331F, -20.0F, _cubicBezierEasingFunction_0);
		// Frame 20.
		result.InsertKeyFrame(0.166666672F, 0.0F, _holdThenStepEasingFunction);
		// Frame 30.
		result.InsertKeyFrame(0.25F, 0.0F, _holdThenStepEasingFunction);
		// Frame 39.
		result.InsertKeyFrame(0.324999988F, -20.0F, _cubicBezierEasingFunction_0);
		return result;
	}

	// PreComp layer: Controls - 04 - Settings - 06 - PressedToPointerOver
	// Shape tree root for layer: Layer 2
	private ShapeVisual ShapeVisual_0()
	{
		var result = _c.CreateShapeVisual();
		result.Size = new Vector2(48.0F, 48.0F);
		// ShapeGroup: Group 1
		result.Shapes.Add(SpriteShape_0());
		return result;
	}

	// PreComp layer: Controls - 04 - Settings - 05 - PressedToNormal
	// Shape tree root for layer: Layer 2
	private ShapeVisual ShapeVisual_1()
	{
		var result = _c.CreateShapeVisual();
		result.Size = new Vector2(48.0F, 48.0F);
		// ShapeGroup: Group 1
		result.Shapes.Add(SpriteShape_1());
		return result;
	}

	// PreComp layer: Controls - 04 - Settings - 01 - NormalToPointerOver Controls - 04 -
	// Settings - 02 - NormalToPressed Controls - 04 - Settings - 03 - PointerOverToNormal
	// Controls - 04 - Settings - 04 - PointerOverToPressed
	// Shape tree root for layer: Layer 2 Layer 2 Layer 2 Layer 2
	private ShapeVisual ShapeVisual_2()
	{
		var result = _c.CreateShapeVisual();
		result.Size = new Vector2(48.0F, 48.0F);
		// ShapeGroup: Group 1 Group 1 Group 1 Group 1
		result.Shapes.Add(SpriteShape_2());
		return result;
	}

	private StepEasingFunction HoldThenStepEasingFunction()
	{
		var result = _holdThenStepEasingFunction = _c.CreateStepEasingFunction();
		result.IsFinalStepSingleFrame = true;
		return result;
	}

	private StepEasingFunction StepThenHoldEasingFunction()
	{
		var result = _stepThenHoldEasingFunction = _c.CreateStepEasingFunction();
		result.IsInitialStepSingleFrame = true;
		return result;
	}

	public AnimatedSettingsVisualSource_AnimatedVisual(
		Compositor compositor,
		CompositionPropertySet themeProperties)
	{
		_c = compositor;
		_themeProperties = themeProperties;
		_reusableExpressionAnimation = compositor.CreateExpressionAnimation();

		_ = Root();
	}

	/// <summary>Releases the underlying composition tree.</summary>
	public void Dispose()
	{
		if (_root != null)
		{
			_root.Dispose();
		}
	}

	/// <summary>Gets the duration of the animated visual.</summary>
	public TimeSpan Duration => new TimeSpan(c_durationTicks);

	/// <summary>Gets the root <see cref="Visual"/> of the animated visual.</summary>
	public Visual RootVisual => _root;

	/// <summary>Gets the natural size of the animated visual.</summary>
	public Vector2 Size => new Vector2(48.0F, 48.0F);

	internal static bool IsRuntimeCompatible()
	{
#if HAS_UNO
		// Uno's Skia composition pipeline supports the APIs this animated visual depends on.
		return true;
#else
		return ApiInformation.IsApiContractPresent("Windows.Foundation.UniversalApiContract", 7);
#endif
	}
}
