// <auto-generated>
#pragma warning disable 108 // new keyword hiding
#pragma warning disable 114 // new keyword hiding
namespace Microsoft/* UWP don't rename */.UI.Xaml.Controls
{
#if __ANDROID__ || __IOS__ || IS_UNIT_TESTS || __WASM__ || __SKIA__ || __NETSTD_REFERENCE__ || __MACOS__
	[global::Uno.NotImplemented]
#endif
	public partial class TabViewTabTearOutWindowRequestedEventArgs
	{
#if __ANDROID__ || __IOS__ || IS_UNIT_TESTS || __WASM__ || __SKIA__ || __NETSTD_REFERENCE__ || __MACOS__
		internal TabViewTabTearOutWindowRequestedEventArgs()
		{
		}
#endif
#if __ANDROID__ || __IOS__ || IS_UNIT_TESTS || __WASM__ || __SKIA__ || __NETSTD_REFERENCE__ || __MACOS__
		[global::Uno.NotImplemented("__ANDROID__", "__IOS__", "IS_UNIT_TESTS", "__WASM__", "__SKIA__", "__NETSTD_REFERENCE__", "__MACOS__")]
		public global::Microsoft.UI.WindowId NewWindowId
		{
			get
			{
				throw new global::System.NotImplementedException("The member WindowId TabViewTabTearOutWindowRequestedEventArgs.NewWindowId is not implemented. For more information, visit https://aka.platform.uno/notimplemented#m=WindowId%20TabViewTabTearOutWindowRequestedEventArgs.NewWindowId");
			}
			set
			{
				global::Windows.Foundation.Metadata.ApiInformation.TryRaiseNotImplemented("Microsoft.UI.Xaml.Controls.TabViewTabTearOutWindowRequestedEventArgs", "WindowId TabViewTabTearOutWindowRequestedEventArgs.NewWindowId");
			}
		}
#endif
#if __ANDROID__ || __IOS__ || IS_UNIT_TESTS || __WASM__ || __SKIA__ || __NETSTD_REFERENCE__ || __MACOS__
		[global::Uno.NotImplemented("__ANDROID__", "__IOS__", "IS_UNIT_TESTS", "__WASM__", "__SKIA__", "__NETSTD_REFERENCE__", "__MACOS__")]
		public object[] Items
		{
			get
			{
				throw new global::System.NotImplementedException("The member object[] TabViewTabTearOutWindowRequestedEventArgs.Items is not implemented. For more information, visit https://aka.platform.uno/notimplemented#m=object%5B%5D%20TabViewTabTearOutWindowRequestedEventArgs.Items");
			}
		}
#endif
#if __ANDROID__ || __IOS__ || IS_UNIT_TESTS || __WASM__ || __SKIA__ || __NETSTD_REFERENCE__ || __MACOS__
		[global::Uno.NotImplemented("__ANDROID__", "__IOS__", "IS_UNIT_TESTS", "__WASM__", "__SKIA__", "__NETSTD_REFERENCE__", "__MACOS__")]
		public global::Microsoft.UI.Xaml.UIElement[] Tabs
		{
			get
			{
				throw new global::System.NotImplementedException("The member UIElement[] TabViewTabTearOutWindowRequestedEventArgs.Tabs is not implemented. For more information, visit https://aka.platform.uno/notimplemented#m=UIElement%5B%5D%20TabViewTabTearOutWindowRequestedEventArgs.Tabs");
			}
		}
#endif
		// Forced skipping of method Microsoft.UI.Xaml.Controls.TabViewTabTearOutWindowRequestedEventArgs.Items.get
		// Forced skipping of method Microsoft.UI.Xaml.Controls.TabViewTabTearOutWindowRequestedEventArgs.Tabs.get
		// Forced skipping of method Microsoft.UI.Xaml.Controls.TabViewTabTearOutWindowRequestedEventArgs.NewWindowId.get
		// Forced skipping of method Microsoft.UI.Xaml.Controls.TabViewTabTearOutWindowRequestedEventArgs.NewWindowId.set
	}
}
