namespace MU_XC_NAMESPACE
{

[WUXC_VERSION_RS4]
[webhosthidden]
enum TreeViewSelectionMode
{
    None = 0,
    Single = 1,
    Multiple = 2,
};

[WUXC_VERSION_RS4]
[webhosthidden]
[WUXC_INTERFACE_NAME("ITreeViewItemInvokedEventArgs", 472ab521-0242-4290-9363-ab4fe704527f)]
runtimeclass TreeViewItemInvokedEventArgs
{
    Object InvokedItem { get; };
    Boolean Handled { set; get; };
}

[WUXC_VERSION_RS4]
/*The bindable tag is needed for bindings in C++ apps if a class isn't being referenced in markup*/
[bindable]
[webhosthidden]
[WUXC_INTERFACE_NAME("ITreeViewNode", c04c8ed3-9af2-4e75-a329-7497a110e7a8)]
[WUXC_STATIC_NAME("ITreeViewNodeStatics", 5d8276fe-e1d1-4b61-9e81-c7fb189a2980)]
[WUXC_CONSTRUCTOR_NAME("ITreeViewNodeFactory", 6ec62d90-aa19-414a-8a45-0a5589a836f7)]
[MUX_PROPERTY_CHANGED_CALLBACK_METHODNAME("OnPropertyChanged")]
unsealed runtimeclass TreeViewNode : Windows.UI.Xaml.DependencyObject
{
    TreeViewNode();

    Object Content { get; set; };
    TreeViewNode Parent { get; };
    [MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
    Boolean IsExpanded { get; set; };
    [MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
    Boolean HasChildren { get; };
    [MUX_DEFAULT_VALUE("-1")]
    Int32 Depth { get; };
    Boolean HasUnrealizedChildren { get; set; };
    Windows.Foundation.Collections.IVector<TreeViewNode> Children { get; };

    static Windows.UI.Xaml.DependencyProperty ContentProperty { get; };
    static Windows.UI.Xaml.DependencyProperty DepthProperty { get; };
    static Windows.UI.Xaml.DependencyProperty IsExpandedProperty { get; };
    static Windows.UI.Xaml.DependencyProperty HasChildrenProperty { get; };
}

[WUXC_VERSION_RS4]
[webhosthidden]
[WUXC_INTERFACE_NAME("ITreeViewExpandingEventArgs", c5e1fa63-4154-49d2-a21f-c34176605e3a)]
runtimeclass TreeViewExpandingEventArgs
{
    TreeViewNode Node { get; };
    [WUXC_VERSION_RS5]
    {
        Object Item{ get; };
    }
}

[WUXC_VERSION_RS4]
[webhosthidden]
[WUXC_INTERFACE_NAME("ITreeViewCollapsedEventArgs", 391db3b0-1e58-4539-9e93-387978f46cce)]
runtimeclass TreeViewCollapsedEventArgs
{
    TreeViewNode Node { get; };
    [WUXC_VERSION_RS5]
    {
        Object Item{ get; };
    }
}

[WUXC_VERSION_RS5]
[webhosthidden]
runtimeclass TreeViewDragItemsStartingEventArgs
{
    Boolean Cancel{ get; set; };
    Windows.ApplicationModel.DataTransfer.DataPackage Data{ get; };
    Windows.Foundation.Collections.IVector<Object> Items{ get; };
}

[WUXC_VERSION_RS5]
[webhosthidden]
runtimeclass TreeViewDragItemsCompletedEventArgs
{
    Windows.ApplicationModel.DataTransfer.DataPackageOperation DropResult{ get; };
    Windows.Foundation.Collections.IVectorView<Object> Items{ get; };

    [WUXC_VERSION_MUXONLY]
    {
        Object NewParentItem{ get; };
    }
}

[WUXC_VERSION_RS4]
[webhosthidden]
[WUXC_INTERFACE_NAME("ITreeViewList", 0f00a54e-099a-47a5-a942-94692b01f452)]
[WUXC_CONSTRUCTOR_NAME("ITreeViewListFactory", 288f6232-41d2-46f7-b1f5-691c625264b7)]
unsealed runtimeclass TreeViewList : Windows.UI.Xaml.Controls.ListView
{
    TreeViewList();
}

[WUXC_VERSION_RS4]
[webhosthidden]
[WUXC_INTERFACE_NAME("ITreeView", 9353cc5c-dd6e-453c-aedd-0c3ac993978b)]
[WUXC_STATIC_NAME("ITreeViewStatics", ef913e08-83f2-4e16-bfb1-1577b98355f5)]
[WUXC_CONSTRUCTOR_NAME("ITreeViewFactory", cc5267c3-6c69-49ce-b445-753acee7948b)]
[MUX_PROPERTY_CHANGED_CALLBACK_METHODNAME("OnPropertyChanged")]
unsealed runtimeclass TreeView : Windows.UI.Xaml.Controls.Control
{
    TreeView();

    Windows.Foundation.Collections.IVector<TreeViewNode> RootNodes { get; };
    [MUX_DEFAULT_VALUE("winrt::TreeViewSelectionMode::Single")]
    [MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
    TreeViewSelectionMode SelectionMode { get; set; };
    Windows.Foundation.Collections.IVector<TreeViewNode> SelectedNodes { get; };
    void Expand(TreeViewNode value);
    void Collapse(TreeViewNode value);
    void SelectAll();
    event Windows.Foundation.TypedEventHandler<TreeView, TreeViewItemInvokedEventArgs> ItemInvoked;
    event Windows.Foundation.TypedEventHandler<TreeView, TreeViewExpandingEventArgs> Expanding;
    event Windows.Foundation.TypedEventHandler<TreeView, TreeViewCollapsedEventArgs> Collapsed;

    static Windows.UI.Xaml.DependencyProperty SelectionModeProperty{ get; };

    [WUXC_VERSION_RS5]
    {
        TreeViewNode NodeFromContainer(Windows.UI.Xaml.DependencyObject container);
        Windows.UI.Xaml.DependencyObject ContainerFromNode(TreeViewNode node);
        Object ItemFromContainer(Windows.UI.Xaml.DependencyObject container);
        Windows.UI.Xaml.DependencyObject ContainerFromItem(Object item);

        [MUX_DEFAULT_VALUE("true")]
        Boolean CanDragItems{ get; set; };
        [MUX_DEFAULT_VALUE("true")]
        Boolean CanReorderItems{ get; set; };
        Windows.UI.Xaml.DataTemplate ItemTemplate{ get; set; };
        Windows.UI.Xaml.Controls.DataTemplateSelector ItemTemplateSelector{ get; set; };
        Windows.UI.Xaml.Style ItemContainerStyle{ get; set; };
        Windows.UI.Xaml.Controls.StyleSelector ItemContainerStyleSelector{ get; set; };
        Windows.UI.Xaml.Media.Animation.TransitionCollection ItemContainerTransitions{ get; set; };
        [MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
        Object ItemsSource{ get; set; };
        event Windows.Foundation.TypedEventHandler<TreeView, TreeViewDragItemsStartingEventArgs> DragItemsStarting;
        event Windows.Foundation.TypedEventHandler<TreeView, TreeViewDragItemsCompletedEventArgs> DragItemsCompleted;

        static Windows.UI.Xaml.DependencyProperty CanDragItemsProperty{ get; };
        static Windows.UI.Xaml.DependencyProperty CanReorderItemsProperty{ get; };
        static Windows.UI.Xaml.DependencyProperty ItemTemplateProperty{ get; };
        static Windows.UI.Xaml.DependencyProperty ItemTemplateSelectorProperty{ get; };
        static Windows.UI.Xaml.DependencyProperty ItemContainerStyleProperty{ get; };
        static Windows.UI.Xaml.DependencyProperty ItemContainerStyleSelectorProperty{ get; };
        static Windows.UI.Xaml.DependencyProperty ItemContainerTransitionsProperty{ get; };
        static Windows.UI.Xaml.DependencyProperty ItemsSourceProperty{ get; };
    }

    [WUXC_VERSION_MUXONLY]
    {
        TreeViewNode SelectedNode{ get; set; };
        Object SelectedItem{ get; set; };
        Windows.Foundation.Collections.IVector<Object> SelectedItems{ get; };
    }
}

[WUXC_VERSION_RS4]
[webhosthidden]
[WUXC_INTERFACE_NAME("ITreeViewItemTemplateSettings", ec323744-de31-4936-bfc2-1cb37ba1dc08)]
[WUXC_STATIC_NAME("ITreeViewItemTemplateSettingsStatics", 55c720a8-70ed-4c21-93f4-2d79c1a4a5f7)]
[WUXC_CONSTRUCTOR_NAME("ITreeViewItemTemplateSettingsFactory", 11a1953b-31b7-4f40-8633-02fc614b518c)]
unsealed runtimeclass TreeViewItemTemplateSettings : Windows.UI.Xaml.DependencyObject
{
    TreeViewItemTemplateSettings();

    [MUX_DEFAULT_VALUE("winrt::Visibility::Collapsed")]
    Windows.UI.Xaml.Visibility ExpandedGlyphVisibility { get; };
    [MUX_DEFAULT_VALUE("winrt::Visibility::Collapsed")]
    Windows.UI.Xaml.Visibility CollapsedGlyphVisibility { get; };
    Windows.UI.Xaml.Thickness Indentation { get; };
    Int32 DragItemsCount { get; };

    static Windows.UI.Xaml.DependencyProperty ExpandedGlyphVisibilityProperty { get; };
    static Windows.UI.Xaml.DependencyProperty CollapsedGlyphVisibilityProperty { get; };
    static Windows.UI.Xaml.DependencyProperty IndentationProperty { get; };
    static Windows.UI.Xaml.DependencyProperty DragItemsCountProperty { get; };
}

[WUXC_VERSION_RS4]
[webhosthidden]
[WUXC_INTERFACE_NAME("ITreeViewItem", 4e05d3e6-6167-44e7-9c74-291ddd6df6eb)]
[WUXC_STATIC_NAME("ITreeViewItemStatics", 436795be-7396-46dc-a264-21c56581c5e5)]
[WUXC_CONSTRUCTOR_NAME("ITreeViewItemFactory", 4ea32731-568d-4d0d-adfd-3d8dc5aa5d88)]
[MUX_PROPERTY_CHANGED_CALLBACK_METHODNAME("OnPropertyChanged")]
unsealed runtimeclass TreeViewItem : Windows.UI.Xaml.Controls.ListViewItem
{
    TreeViewItem();

    [MUX_DEFAULT_VALUE("1.0")]
    Double GlyphOpacity { get; set; };
    Windows.UI.Xaml.Media.Brush GlyphBrush { get; set; };
    [MUX_DEFAULT_VALUE("\uE70D")]
    String ExpandedGlyph { get; set; };
    [MUX_DEFAULT_VALUE("\uE76C")]
    String CollapsedGlyph { get; set; };
    [MUX_DEFAULT_VALUE("12.0")]
    Double GlyphSize { get; set; };
    [MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
    Boolean IsExpanded { get; set; };
    TreeViewItemTemplateSettings TreeViewItemTemplateSettings { get; };

    static Windows.UI.Xaml.DependencyProperty GlyphOpacityProperty { get; };
    static Windows.UI.Xaml.DependencyProperty GlyphBrushProperty { get; };
    static Windows.UI.Xaml.DependencyProperty ExpandedGlyphProperty { get; };
    static Windows.UI.Xaml.DependencyProperty CollapsedGlyphProperty { get; };
    static Windows.UI.Xaml.DependencyProperty GlyphSizeProperty { get; };
    static Windows.UI.Xaml.DependencyProperty IsExpandedProperty { get; };
    static Windows.UI.Xaml.DependencyProperty TreeViewItemTemplateSettingsProperty { get; };

    [WUXC_VERSION_RS5]
    {
        [MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
        Boolean HasUnrealizedChildren{ get; set; };
        [MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
        Object ItemsSource{ get; set; };

        static Windows.UI.Xaml.DependencyProperty HasUnrealizedChildrenProperty{ get; };
        static Windows.UI.Xaml.DependencyProperty ItemsSourceProperty{ get; };
    }
}

}