#nullable disable

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Uno.Globalization.NumberFormatting
{
	internal static class NumeralSystemTranslatorHelper
	{
		private static readonly char[] ArabDigits = new char[] { '\u0660', '\u0661', '\u0662', '\u0663', '\u0664', '\u0665', '\u0666', '\u0667', '\u0668', '\u0669' };
		private static readonly char[] ArabExtDigits = new char[] { '\u06F0', '\u06F1', '\u06F2', '\u06F3', '\u06F4', '\u06F5', '\u06F6', '\u06F7', '\u06F8', '\u06F9' };
		private static readonly char[] BaliDigits = new char[] { '\u1B50', '\u1B51', '\u1B52', '\u1B53', '\u1B54', '\u1B55', '\u1B56', '\u1B57', '\u1B58', '\u1B59' };
		private static readonly char[] BengDigits = new char[] { '\u09E6', '\u09E7', '\u09E8', '\u09E9', '\u09EA', '\u09EB', '\u09EC', '\u09ED', '\u09EE', '\u09EF' };
		private static readonly char[] ChamDigits = new char[] { '\uAA50', '\uAA51', '\uAA52', '\uAA53', '\uAA54', '\uAA55', '\uAA56', '\uAA57', '\uAA58', '\uAA59' };
		private static readonly char[] DevaDigits = new char[] { '\u0966', '\u0967', '\u0968', '\u0969', '\u096A', '\u096B', '\u096C', '\u096D', '\u096E', '\u096F' };
		private static readonly char[] FullWideDigits = new char[] { '\uFF10', '\uFF11', '\uFF12', '\uFF13', '\uFF14', '\uFF15', '\uFF16', '\uFF17', '\uFF18', '\uFF19' };
		private static readonly char[] GujrDigits = new char[] { '\u0AE6', '\u0AE7', '\u0AE8', '\u0AE9', '\u0AEA', '\u0AEB', '\u0AEC', '\u0AED', '\u0AEE', '\u0AEF' };
		private static readonly char[] GuruDigits = new char[] { '\u0A66', '\u0A67', '\u0A68', '\u0A69', '\u0A6A', '\u0A6B', '\u0A6C', '\u0A6D', '\u0A6E', '\u0A6F' };
		private static readonly char[] JavaDigits = new char[] { '\uA9D0', '\uA9D1', '\uA9D2', '\uA9D3', '\uA9D4', '\uA9D5', '\uA9D6', '\uA9D7', '\uA9D8', '\uA9D9' };
		private static readonly char[] KaliDigits = new char[] { '\uA900', '\uA901', '\uA902', '\uA903', '\uA904', '\uA905', '\uA906', '\uA907', '\uA908', '\uA909' };
		private static readonly char[] KhmrDigits = new char[] { '\u17E0', '\u17E1', '\u17E2', '\u17E3', '\u17E4', '\u17E5', '\u17E6', '\u17E7', '\u17E8', '\u17E9' };
		private static readonly char[] KndaDigits = new char[] { '\u0CE6', '\u0CE7', '\u0CE8', '\u0CE9', '\u0CEA', '\u0CEB', '\u0CEC', '\u0CED', '\u0CEE', '\u0CEF' };
		private static readonly char[] LanaDigits = new char[] { '\u1A80', '\u1A81', '\u1A82', '\u1A83', '\u1A84', '\u1A85', '\u1A86', '\u1A87', '\u1A88', '\u1A89' };
		private static readonly char[] LanaThamDigits = new char[] { '\u1A90', '\u1A91', '\u1A92', '\u1A93', '\u1A94', '\u1A95', '\u1A96', '\u1A97', '\u1A98', '\u1A99' };
		private static readonly char[] LaooDigits = new char[] { '\u0ED0', '\u0ED1', '\u0ED2', '\u0ED3', '\u0ED4', '\u0ED5', '\u0ED6', '\u0ED7', '\u0ED8', '\u0ED9' };
		private static readonly char[] LatnDigits = new char[] { '\u0030', '\u0031', '\u0032', '\u0033', '\u0034', '\u0035', '\u0036', '\u0037', '\u0038', '\u0039' };
		private static readonly char[] LepcDigits = new char[] { '\u1C40', '\u1C41', '\u1C42', '\u1C43', '\u1C44', '\u1C45', '\u1C46', '\u1C47', '\u1C48', '\u1C49' };
		private static readonly char[] LimbDigits = new char[] { '\u1946', '\u1947', '\u1948', '\u1949', '\u194A', '\u194B', '\u194C', '\u194D', '\u194E', '\u194F' };
		private static readonly char[] MlymDigits = new char[] { '\u0D66', '\u0D67', '\u0D68', '\u0D69', '\u0D6A', '\u0D6B', '\u0D6C', '\u0D6D', '\u0D6E', '\u0D6F' };
		private static readonly char[] MongDigits = new char[] { '\u1810', '\u1811', '\u1812', '\u1813', '\u1814', '\u1815', '\u1816', '\u1817', '\u1818', '\u1819' };
		private static readonly char[] MteiDigits = new char[] { '\uABF0', '\uABF1', '\uABF2', '\uABF3', '\uABF4', '\uABF5', '\uABF6', '\uABF7', '\uABF8', '\uABF9' };
		private static readonly char[] MymrDigits = new char[] { '\u1040', '\u1041', '\u1042', '\u1043', '\u1044', '\u1045', '\u1046', '\u1047', '\u1048', '\u1049' };
		private static readonly char[] MymrShanDigits = new char[] { '\u1090', '\u1091', '\u1092', '\u1093', '\u1094', '\u1095', '\u1096', '\u1097', '\u1098', '\u1099' };
		private static readonly char[] NkooDigits = new char[] { '\u07C0', '\u07C1', '\u07C2', '\u07C3', '\u07C4', '\u07C5', '\u07C6', '\u07C7', '\u07C8', '\u07C9' };
		private static readonly char[] OlckDigits = new char[] { '\u1C50', '\u1C51', '\u1C52', '\u1C53', '\u1C54', '\u1C55', '\u1C56', '\u1C57', '\u1C58', '\u1C59' };
		private static readonly char[] OryaDigits = new char[] { '\u0B66', '\u0B67', '\u0B68', '\u0B69', '\u0B6A', '\u0B6B', '\u0B6C', '\u0B6D', '\u0B6E', '\u0B6F' };
		private static readonly char[] SaurDigits = new char[] { '\uA8D0', '\uA8D1', '\uA8D2', '\uA8D3', '\uA8D4', '\uA8D5', '\uA8D6', '\uA8D7', '\uA8D8', '\uA8D9' };
		private static readonly char[] SundDigits = new char[] { '\u1BB0', '\u1BB1', '\u1BB2', '\u1BB3', '\u1BB4', '\u1BB5', '\u1BB6', '\u1BB7', '\u1BB8', '\u1BB9' };
		private static readonly char[] TaluDigits = new char[] { '\u19D0', '\u19D1', '\u19D2', '\u19D3', '\u19D4', '\u19D5', '\u19D6', '\u19D7', '\u19D8', '\u19D9' };
		private static readonly char[] TamlDecDigits = new char[] { '\u0BE6', '\u0BE7', '\u0BE8', '\u0BE9', '\u0BEA', '\u0BEB', '\u0BEC', '\u0BED', '\u0BEE', '\u0BEF' };
		private static readonly char[] TeluDigits = new char[] { '\u0C66', '\u0C67', '\u0C68', '\u0C69', '\u0C6A', '\u0C6B', '\u0C6C', '\u0C6D', '\u0C6E', '\u0C6F' };
		private static readonly char[] ThaiDigits = new char[] { '\u0E50', '\u0E51', '\u0E52', '\u0E53', '\u0E54', '\u0E55', '\u0E56', '\u0E57', '\u0E58', '\u0E59' };
		private static readonly char[] TibtDigits = new char[] { '\u0F20', '\u0F21', '\u0F22', '\u0F23', '\u0F24', '\u0F25', '\u0F26', '\u0F27', '\u0F28', '\u0F29' };
		private static readonly char[] VaiiDigits = new char[] { '\uA620', '\uA621', '\uA622', '\uA623', '\uA624', '\uA625', '\uA626', '\uA627', '\uA628', '\uA629' };

		// GetNumeralSystem and GetResolvedLanguage use language tags from list of language/region names supported by Windows:
		// https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-lcid/a9eac961-e77d-41a6-90a5-ce1a8b0cdb9c
		public static string GetNumeralSystem(string languageTag)
		{
			languageTag = languageTag.ToLowerInvariant();

			switch (languageTag)
			{
				case "aa":
					return "Latn";
				case "aa-dj":
					return "Latn";
				case "aa-er":
					return "Latn";
				case "aa-et":
					return "Latn";
				case "af":
					return "Latn";
				case "af-na":
					return "Latn";
				case "af-za":
					return "Latn";
				case "agq":
					return "Latn";
				case "agq-cm":
					return "Latn";
				case "ak":
					return "Latn";
				case "ak-gh":
					return "Latn";
				case "sq":
					return "Latn";
				case "sq-al":
					return "Latn";
				case "sq-mk":
					return "Latn";
				case "gsw":
					return "Latn";
				case "gsw-fr":
					return "Latn";
				case "gsw-li":
					return "Latn";
				case "gsw-ch":
					return "Latn";
				case "am":
					return "Latn";
				case "am-et":
					return "Latn";
				case "ar":
					return "Arab";
				case "ar-dz":
					return "Latn";
				case "ar-bh":
					return "Arab";
				case "ar-td":
					return "Arab";
				case "ar-km":
					return "Arab";
				case "ar-dj":
					return "Arab";
				case "ar-eg":
					return "Arab";
				case "ar-er":
					return "Arab";
				case "ar-iq":
					return "Arab";
				case "ar-il":
					return "Arab";
				case "ar-jo":
					return "Arab";
				case "ar-kw":
					return "Arab";
				case "ar-lb":
					return "Arab";
				case "ar-ly":
					return "Latn";
				case "ar-mr":
					return "Arab";
				case "ar-ma":
					return "Latn";
				case "ar-om":
					return "Arab";
				case "ar-ps":
					return "Arab";
				case "ar-qa":
					return "Arab";
				case "ar-sa":
					return "Arab";
				case "ar-so":
					return "Arab";
				case "ar-ss":
					return "Arab";
				case "ar-sd":
					return "Arab";
				case "ar-sy":
					return "Arab";
				case "ar-tn":
					return "Latn";
				case "ar-ae":
					return "Arab";
				case "ar-001":
					return "Arab";
				case "ar-ye":
					return "Arab";
				case "hy":
					return "Latn";
				case "hy-am":
					return "Latn";
				case "as":
					return "Latn";
				case "as-in":
					return "Latn";
				case "ast":
					return "Latn";
				case "ast-es":
					return "Latn";
				case "asa":
					return "Latn";
				case "asa-tz":
					return "Latn";
				case "az-cyrl":
					return "Latn";
				case "az-cyrl-az":
					return "Latn";
				case "az":
					return "Latn";
				case "az-latn":
					return "Latn";
				case "az-latn-az":
					return "Latn";
				case "ksf":
					return "Latn";
				case "ksf-cm":
					return "Latn";
				case "bm":
					return "Latn";
				case "bm-latn-ml":
					return "Latn";
				case "bn":
					return "Beng";
				case "bn-bd":
					return "Beng";
				case "bn-in":
					return "Latn";
				case "bas":
					return "Latn";
				case "bas-cm":
					return "Latn";
				case "ba":
					return "Latn";
				case "ba-ru":
					return "Latn";
				case "eu":
					return "Latn";
				case "eu-es":
					return "Latn";
				case "be":
					return "Latn";
				case "be-by":
					return "Latn";
				case "bem":
					return "Latn";
				case "bem-zm":
					return "Latn";
				case "bez":
					return "Latn";
				case "bez-tz":
					return "Latn";
				case "byn":
					return "Latn";
				case "byn-er":
					return "Latn";
				case "brx":
					return "Latn";
				case "brx-in":
					return "Latn";
				case "bs-cyrl":
					return "Latn";
				case "bs-cyrl-ba":
					return "Latn";
				case "bs-latn":
					return "Latn";
				case "bs":
					return "Latn";
				case "bs-latn-ba":
					return "Latn";
				case "br":
					return "Latn";
				case "br-fr":
					return "Latn";
				case "bg":
					return "Latn";
				case "bg-bg":
					return "Latn";
				case "my":
					return "Mymr";
				case "my-mm":
					return "Mymr";
				case "ca":
					return "Latn";
				case "ca-ad":
					return "Latn";
				case "ca-fr":
					return "Latn";
				case "ca-it":
					return "Latn";
				case "ca-es":
					return "Latn";
				case "ceb":
					return "ArabExt";
				case "ceb-latn":
					return "ArabExt";
				case "ceb-latn-ph":
					return "ArabExt";
				case "tzm-arab-ma":
					return "Latn";
				case "tzm-latn-ma":
					return "Latn";
				case "ku":
					return "Arab";
				case "ku-arab":
					return "Arab";
				case "ku-arab-iq":
					return "Arab";
				case "ccp":
					return "ArabExt";
				case "ccp-cakm":
					return "ArabExt";
				case "ccp-cakm-bd":
					return "ArabExt";
				case "ccp-cakm-in":
					return "ArabExt";
				case "ce-ru":
					return "Latn";
				case "chr":
					return "Latn";
				case "chr-cher":
					return "Latn";
				case "chr-cher-us":
					return "Latn";
				case "cgg":
					return "Latn";
				case "cgg-ug":
					return "Latn";
				case "zh-hans":
					return "Latn";
				case "zh":
					return "Latn";
				case "zh-cn":
					return "Latn";
				case "zh-sg":
					return "Latn";
				case "zh-hant":
					return "Latn";
				case "zh-hk":
					return "Latn";
				case "zh-mo":
					return "Latn";
				case "zh-tw":
					return "Latn";
				case "cu-ru":
					return "Latn";
				case "swc":
					return "ArabExt";
				case "swc-cd":
					return "Latn";
				case "kw":
					return "Latn";
				case "kw-gb":
					return "Latn";
				case "co":
					return "Latn";
				case "co-fr":
					return "Latn";
				case "hr":
					return "Latn";
				case "hr-hr":
					return "Latn";
				case "hr-ba":
					return "Latn";
				case "cs":
					return "Latn";
				case "cs-cz":
					return "Latn";
				case "da":
					return "Latn";
				case "da-dk":
					return "Latn";
				case "da-gl":
					return "Latn";
				case "prs":
					return "Arab";
				case "prs-af":
					return "Arab";
				case "dv":
					return "Latn";
				case "dv-mv":
					return "Latn";
				case "dua":
					return "Latn";
				case "dua-cm":
					return "Latn";
				case "nl":
					return "Latn";
				case "nl-aw":
					return "Latn";
				case "nl-be":
					return "Latn";
				case "nl-bq":
					return "Latn";
				case "nl-cw":
					return "Latn";
				case "nl-nl":
					return "Latn";
				case "nl-sx":
					return "Latn";
				case "nl-sr":
					return "Latn";
				case "dz":
					return "Tibt";
				case "dz-bt":
					return "Tibt";
				case "ebu":
					return "Latn";
				case "ebu-ke":
					return "Latn";
				case "en":
					return "Latn";
				case "en-as":
					return "Latn";
				case "en-ai":
					return "Latn";
				case "en-ag":
					return "Latn";
				case "en-au":
					return "Latn";
				case "en-at":
					return "Latn";
				case "en-bs":
					return "Latn";
				case "en-bb":
					return "Latn";
				case "en-be":
					return "Latn";
				case "en-bz":
					return "Latn";
				case "en-bm":
					return "Latn";
				case "en-bw":
					return "Latn";
				case "en-io":
					return "Latn";
				case "en-vg":
					return "Latn";
				case "en-bi":
					return "Latn";
				case "en-cm":
					return "Latn";
				case "en-ca":
					return "Latn";
				case "en-029":
					return "Latn";
				case "en-ky":
					return "Latn";
				case "en-cx":
					return "Latn";
				case "en-cc":
					return "Latn";
				case "en-ck":
					return "Latn";
				case "en-cy":
					return "Latn";
				case "en-dk":
					return "Latn";
				case "en-dm":
					return "Latn";
				case "en-er":
					return "Latn";
				case "en-150":
					return "Latn";
				case "en-fk":
					return "Latn";
				case "en-fi":
					return "Latn";
				case "en-fj":
					return "Latn";
				case "en-gm":
					return "Latn";
				case "en-de":
					return "Latn";
				case "en-gh":
					return "Latn";
				case "en-gi":
					return "Latn";
				case "en-gd":
					return "Latn";
				case "en-gu":
					return "Latn";
				case "en-gg":
					return "Latn";
				case "en-gy":
					return "Latn";
				case "en-hk":
					return "Latn";
				case "en-in":
					return "Latn";
				case "en-ie":
					return "Latn";
				case "en-im":
					return "Latn";
				case "en-il":
					return "Latn";
				case "en-jm":
					return "Latn";
				case "en-je":
					return "Latn";
				case "en-ke":
					return "Latn";
				case "en-ki":
					return "Latn";
				case "en-ls":
					return "Latn";
				case "en-lr":
					return "Latn";
				case "en-mo":
					return "Latn";
				case "en-mg":
					return "Latn";
				case "en-mw":
					return "Latn";
				case "en-my":
					return "Latn";
				case "en-mt":
					return "Latn";
				case "en-mh":
					return "Latn";
				case "en-mu":
					return "Latn";
				case "en-fm":
					return "Latn";
				case "en-ms":
					return "Latn";
				case "en-na":
					return "Latn";
				case "en-nr":
					return "Latn";
				case "en-nl":
					return "Latn";
				case "en-nz":
					return "Latn";
				case "en-ng":
					return "Latn";
				case "en-nu":
					return "Latn";
				case "en-nf":
					return "Latn";
				case "en-mp":
					return "Latn";
				case "en-pk":
					return "Latn";
				case "en-pw":
					return "Latn";
				case "en-pg":
					return "Latn";
				case "en-pn":
					return "Latn";
				case "en-pr":
					return "Latn";
				case "en-ph":
					return "Latn";
				case "en-rw":
					return "Latn";
				case "en-kn":
					return "Latn";
				case "en-lc":
					return "Latn";
				case "en-vc":
					return "Latn";
				case "en-ws":
					return "Latn";
				case "en-sc":
					return "Latn";
				case "en-sl":
					return "Latn";
				case "en-sg":
					return "Latn";
				case "en-sx":
					return "Latn";
				case "en-si":
					return "Latn";
				case "en-sb":
					return "Latn";
				case "en-za":
					return "Latn";
				case "en-ss":
					return "Latn";
				case "en-sh":
					return "Latn";
				case "en-sd":
					return "Latn";
				case "en-sz":
					return "Latn";
				case "en-se":
					return "Latn";
				case "en-ch":
					return "Latn";
				case "en-tz":
					return "Latn";
				case "en-tk":
					return "Latn";
				case "en-to":
					return "Latn";
				case "en-tt":
					return "Latn";
				case "en-tc":
					return "Latn";
				case "en-tv":
					return "Latn";
				case "en-ug":
					return "Latn";
				case "en-ae":
					return "Latn";
				case "en-gb":
					return "Latn";
				case "en-us":
					return "Latn";
				case "en-um":
					return "Latn";
				case "en-vi":
					return "Latn";
				case "en-vu":
					return "Latn";
				case "en-001":
					return "Latn";
				case "en-zm":
					return "Latn";
				case "en-zw":
					return "Latn";
				case "eo":
					return "Latn";
				case "eo-001":
					return "Latn";
				case "et":
					return "Latn";
				case "et-ee":
					return "Latn";
				case "ee":
					return "Latn";
				case "ee-gh":
					return "Latn";
				case "ee-tg":
					return "Latn";
				case "ewo":
					return "Latn";
				case "ewo-cm":
					return "Latn";
				case "fo":
					return "Latn";
				case "fo-dk":
					return "Latn";
				case "fo-fo":
					return "Latn";
				case "fil":
					return "Latn";
				case "fil-ph":
					return "Latn";
				case "fi":
					return "Latn";
				case "fi-fi":
					return "Latn";
				case "fr":
					return "Latn";
				case "fr-dz":
					return "Latn";
				case "fr-be":
					return "Latn";
				case "fr-bj":
					return "Latn";
				case "fr-bf":
					return "Latn";
				case "fr-bi":
					return "Latn";
				case "fr-cm":
					return "Latn";
				case "fr-ca":
					return "Latn";
				case "fr-029":
					return "Latn";
				case "fr-cf":
					return "Latn";
				case "fr-td":
					return "Latn";
				case "fr-km":
					return "Latn";
				case "fr-cg":
					return "Latn";
				case "fr-cd":
					return "Latn";
				case "fr-ci":
					return "Latn";
				case "fr-dj":
					return "Latn";
				case "fr-gq":
					return "Latn";
				case "fr-fr":
					return "Latn";
				case "fr-gf":
					return "Latn";
				case "fr-pf":
					return "Latn";
				case "fr-ga":
					return "Latn";
				case "fr-gp":
					return "Latn";
				case "fr-gn":
					return "Latn";
				case "fr-ht":
					return "Latn";
				case "fr-lu":
					return "Latn";
				case "fr-mg":
					return "Latn";
				case "fr-ml":
					return "Latn";
				case "fr-mq":
					return "Latn";
				case "fr-mr":
					return "Latn";
				case "fr-mu":
					return "Latn";
				case "fr-yt":
					return "Latn";
				case "fr-ma":
					return "Latn";
				case "fr-nc":
					return "Latn";
				case "fr-ne":
					return "Latn";
				case "fr-mc":
					return "Latn";
				case "fr-re":
					return "Latn";
				case "fr-rw":
					return "Latn";
				case "fr-bl":
					return "Latn";
				case "fr-mf":
					return "Latn";
				case "fr-pm":
					return "Latn";
				case "fr-sn":
					return "Latn";
				case "fr-sc":
					return "Latn";
				case "fr-ch":
					return "Latn";
				case "fr-sy":
					return "Latn";
				case "fr-tg":
					return "Latn";
				case "fr-tn":
					return "Latn";
				case "fr-vu":
					return "Latn";
				case "fr-wf":
					return "Latn";
				case "fy":
					return "Latn";
				case "fy-nl":
					return "Latn";
				case "fur":
					return "Latn";
				case "fur-it":
					return "Latn";
				case "ff":
					return "Latn";
				case "ff-latn":
					return "Latn";
				case "ff-latn-bf":
					return "Latn";
				case "ff-cm":
					return "Latn";
				case "ff-latn-cm":
					return "Latn";
				case "ff-latn-gm":
					return "Latn";
				case "ff-latn-gh":
					return "Latn";
				case "ff-gn":
					return "Latn";
				case "ff-latn-gn":
					return "Latn";
				case "ff-latn-gw":
					return "Latn";
				case "ff-latn-lr":
					return "Latn";
				case "ff-mr":
					return "Latn";
				case "ff-latn-mr":
					return "Latn";
				case "ff-latn-ne":
					return "Latn";
				case "ff-ng":
					return "Latn";
				case "ff-latn-ng":
					return "Latn";
				case "ff-latn-sn":
					return "Latn";
				case "ff-latn-sl":
					return "Latn";
				case "gl":
					return "Latn";
				case "gl-es":
					return "Latn";
				case "lg":
					return "Latn";
				case "lg-ug":
					return "Latn";
				case "ka":
					return "Latn";
				case "ka-ge":
					return "Latn";
				case "de":
					return "Latn";
				case "de-at":
					return "Latn";
				case "de-be":
					return "Latn";
				case "de-de":
					return "Latn";
				case "de-it":
					return "Latn";
				case "de-li":
					return "Latn";
				case "de-lu":
					return "Latn";
				case "de-ch":
					return "Latn";
				case "el":
					return "Latn";
				case "el-cy":
					return "Latn";
				case "el-gr":
					return "Latn";
				case "kl":
					return "Latn";
				case "kl-gl":
					return "Latn";
				case "gn":
					return "Latn";
				case "gn-py":
					return "Latn";
				case "gu":
					return "Latn";
				case "gu-in":
					return "Latn";
				case "guz":
					return "Latn";
				case "guz-ke":
					return "Latn";
				case "ha":
					return "Latn";
				case "ha-latn":
					return "Latn";
				case "ha-latn-gh":
					return "Latn";
				case "ha-latn-ne":
					return "Latn";
				case "ha-latn-ng":
					return "Latn";
				case "haw":
					return "Latn";
				case "haw-us":
					return "Latn";
				case "he":
					return "Latn";
				case "he-il":
					return "Latn";
				case "hi":
					return "Latn";
				case "hi-in":
					return "Latn";
				case "hu":
					return "Latn";
				case "hu-hu":
					return "Latn";
				case "is":
					return "Latn";
				case "is-is":
					return "Latn";
				case "ig":
					return "Latn";
				case "ig-ng":
					return "Latn";
				case "id":
					return "Latn";
				case "id-id":
					return "Latn";
				case "ia":
					return "Latn";
				case "ia-fr":
					return "ArabExt";
				case "ia-001":
					return "Latn";
				case "iu":
					return "Latn";
				case "iu-latn":
					return "Latn";
				case "iu-latn-ca":
					return "Latn";
				case "iu-cans":
					return "Latn";
				case "iu-cans-ca":
					return "Latn";
				case "ga":
					return "Latn";
				case "ga-ie":
					return "Latn";
				case "it":
					return "Latn";
				case "it-it":
					return "Latn";
				case "it-sm":
					return "Latn";
				case "it-ch":
					return "Latn";
				case "it-va":
					return "Latn";
				case "ja":
					return "Latn";
				case "ja-jp":
					return "Latn";
				case "jv":
					return "Latn";
				case "jv-latn":
					return "Latn";
				case "jv-latn-id":
					return "Latn";
				case "dyo":
					return "Latn";
				case "dyo-sn":
					return "Latn";
				case "kea":
					return "Latn";
				case "kea-cv":
					return "Latn";
				case "kab":
					return "Latn";
				case "kab-dz":
					return "Latn";
				case "kkj":
					return "Latn";
				case "kkj-cm":
					return "Latn";
				case "kln":
					return "Latn";
				case "kln-ke":
					return "Latn";
				case "kam":
					return "Latn";
				case "kam-ke":
					return "Latn";
				case "kn":
					return "Latn";
				case "kn-in":
					return "Latn";
				case "kr-latn-ng":
					return "Latn";
				case "ks":
					return "ArabExt";
				case "ks-arab":
					return "ArabExt";
				case "ks-arab-in":
					return "ArabExt";
				case "ks-deva-in":
					return "Latn";
				case "kk":
					return "Latn";
				case "kk-kz":
					return "Latn";
				case "km":
					return "Khmr";
				case "km-kh":
					return "Khmr";
				case "quc":
					return "Latn";
				case "quc-latn-gt":
					return "Latn";
				case "ki":
					return "Latn";
				case "ki-ke":
					return "Latn";
				case "rw":
					return "Latn";
				case "rw-rw":
					return "Latn";
				case "sw":
					return "Latn";
				case "sw-ke":
					return "Latn";
				case "sw-tz":
					return "Latn";
				case "sw-ug":
					return "Latn";
				case "kok":
					return "Latn";
				case "kok-in":
					return "Latn";
				case "ko":
					return "Latn";
				case "ko-kr":
					return "Latn";
				case "ko-kp":
					return "Latn";
				case "khq":
					return "Latn";
				case "khq-ml":
					return "Latn";
				case "ses":
					return "Latn";
				case "ses-ml":
					return "Latn";
				case "nmg":
					return "Latn";
				case "nmg-cm":
					return "Latn";
				case "ky":
					return "Latn";
				case "ky-kg":
					return "Latn";
				case "ku-arab-ir":
					return "Arab";
				case "lkt":
					return "Latn";
				case "lkt-us":
					return "Latn";
				case "lag":
					return "Latn";
				case "lag-tz":
					return "Latn";
				case "lo":
					return "Latn";
				case "lo-la":
					return "Latn";
				case "la-va":
					return "Latn";
				case "lv":
					return "Latn";
				case "lv-lv":
					return "Latn";
				case "ln":
					return "Latn";
				case "ln-ao":
					return "Latn";
				case "ln-cf":
					return "Latn";
				case "ln-cg":
					return "Latn";
				case "ln-cd":
					return "Latn";
				case "lt":
					return "Latn";
				case "lt-lt":
					return "Latn";
				case "nds":
					return "Latn";
				case "nds-de":
					return "Latn";
				case "nds-nl":
					return "Latn";
				case "dsb":
					return "Latn";
				case "dsb-de":
					return "Latn";
				case "lu":
					return "Latn";
				case "lu-cd":
					return "Latn";
				case "luo":
					return "Latn";
				case "luo-ke":
					return "Latn";
				case "lb":
					return "Latn";
				case "lb-lu":
					return "Latn";
				case "luy":
					return "Latn";
				case "luy-ke":
					return "Latn";
				case "mk":
					return "Latn";
				case "mk-mk":
					return "Latn";
				case "jmc":
					return "Latn";
				case "jmc-tz":
					return "Latn";
				case "mgh":
					return "Latn";
				case "mgh-mz":
					return "Latn";
				case "kde":
					return "Latn";
				case "kde-tz":
					return "Latn";
				case "mg":
					return "Latn";
				case "mg-mg":
					return "Latn";
				case "ms":
					return "Latn";
				case "ms-bn":
					return "Latn";
				case "ms-my":
					return "Latn";
				case "ml":
					return "Latn";
				case "ml-in":
					return "Latn";
				case "mt":
					return "Latn";
				case "mt-mt":
					return "Latn";
				case "gv":
					return "Latn";
				case "gv-im":
					return "Latn";
				case "mi":
					return "Latn";
				case "mi-nz":
					return "Latn";
				case "arn":
					return "Latn";
				case "arn-cl":
					return "Latn";
				case "mr":
					return "Latn";
				case "mr-in":
					return "Latn";
				case "mas":
					return "Latn";
				case "mas-ke":
					return "Latn";
				case "mas-tz":
					return "Latn";
				case "mzn-ir":
					return "ArabExt";
				case "mer":
					return "Latn";
				case "mer-ke":
					return "Latn";
				case "mgo":
					return "Latn";
				case "mgo-cm":
					return "Latn";
				case "moh":
					return "Latn";
				case "moh-ca":
					return "Latn";
				case "mn":
					return "Latn";
				case "mn-cyrl":
					return "Latn";
				case "mn-mn":
					return "Latn";
				case "mn-mong":
					return "Latn";
				case "mn-mong-cn":
					return "Latn";
				case "mn-mong-mn":
					return "Latn";
				case "mfe":
					return "Latn";
				case "mfe-mu":
					return "Latn";
				case "mua":
					return "Latn";
				case "mua-cm":
					return "Latn";
				case "nqo":
					return "Nkoo";
				case "nqo-gn":
					return "Nkoo";
				case "naq":
					return "Latn";
				case "naq-na":
					return "Latn";
				case "ne":
					return "Latn";
				case "ne-in":
					return "Deva";
				case "ne-np":
					return "Latn";
				case "nnh":
					return "Latn";
				case "nnh-cm":
					return "Latn";
				case "jgo":
					return "Latn";
				case "jgo-cm":
					return "Latn";
				case "lrc-iq":
					return "ArabExt";
				case "lrc-ir":
					return "ArabExt";
				case "nd":
					return "Latn";
				case "nd-zw":
					return "Latn";
				case "no":
					return "Latn";
				case "nb":
					return "Latn";
				case "nb-no":
					return "Latn";
				case "nn":
					return "Latn";
				case "nn-no":
					return "Latn";
				case "nb-sj":
					return "Latn";
				case "nus":
					return "Latn";
				case "nus-sd":
					return "Latn";
				case "nus-ss":
					return "Latn";
				case "nyn":
					return "Latn";
				case "nyn-ug":
					return "Latn";
				case "oc":
					return "Latn";
				case "oc-fr":
					return "Latn";
				case "or":
					return "Latn";
				case "or-in":
					return "Latn";
				case "om":
					return "Latn";
				case "om-et":
					return "Latn";
				case "om-ke":
					return "Latn";
				case "os":
					return "Latn";
				case "os-ge":
					return "Latn";
				case "os-ru":
					return "Latn";
				case "ps":
					return "ArabExt";
				case "ps-af":
					return "ArabExt";
				case "ps-pk":
					return "ArabExt";
				case "fa":
					return "ArabExt";
				case "fa-af":
					return "Arab";
				case "fa-ir":
					return "ArabExt";
				case "pl":
					return "Latn";
				case "pl-pl":
					return "Latn";
				case "pt":
					return "Latn";
				case "pt-ao":
					return "Latn";
				case "pt-br":
					return "Latn";
				case "pt-cv":
					return "Latn";
				case "pt-gq":
					return "Latn";
				case "pt-gw":
					return "Latn";
				case "pt-lu":
					return "Latn";
				case "pt-mo":
					return "Latn";
				case "pt-mz":
					return "Latn";
				case "pt-pt":
					return "Latn";
				case "pt-st":
					return "Latn";
				case "pt-ch":
					return "Latn";
				case "pt-tl":
					return "Latn";
				case "prg-001":
					return "Latn";
				case "qps-ploca":
					return "Latn";
				case "qps-ploc":
					return "Latn";
				case "qps-plocm":
					return "Arab";
				case "pa":
					return "Latn";
				case "pa-arab":
					return "ArabExt";
				case "pa-in":
					return "Latn";
				case "pa-arab-pk":
					return "ArabExt";
				case "quz":
					return "Latn";
				case "quz-bo":
					return "Latn";
				case "quz-ec":
					return "Latn";
				case "quz-pe":
					return "Latn";
				case "ksh":
					return "Latn";
				case "ksh-de":
					return "Latn";
				case "ro":
					return "Latn";
				case "ro-md":
					return "Latn";
				case "ro-ro":
					return "Latn";
				case "rm":
					return "Latn";
				case "rm-ch":
					return "Latn";
				case "rof":
					return "Latn";
				case "rof-tz":
					return "Latn";
				case "rn":
					return "Latn";
				case "rn-bi":
					return "Latn";
				case "ru":
					return "Latn";
				case "ru-by":
					return "Latn";
				case "ru-kz":
					return "Latn";
				case "ru-kg":
					return "Latn";
				case "ru-md":
					return "Latn";
				case "ru-ru":
					return "Latn";
				case "ru-ua":
					return "Latn";
				case "rwk":
					return "Latn";
				case "rwk-tz":
					return "Latn";
				case "ssy":
					return "Latn";
				case "ssy-er":
					return "Latn";
				case "sah":
					return "Latn";
				case "sah-ru":
					return "Latn";
				case "saq":
					return "Latn";
				case "saq-ke":
					return "Latn";
				case "smn":
					return "Latn";
				case "smn-fi":
					return "Latn";
				case "smj":
					return "Latn";
				case "smj-no":
					return "Latn";
				case "smj-se":
					return "Latn";
				case "se":
					return "Latn";
				case "se-fi":
					return "Latn";
				case "se-no":
					return "Latn";
				case "se-se":
					return "Latn";
				case "sms":
					return "Latn";
				case "sms-fi":
					return "Latn";
				case "sma":
					return "Latn";
				case "sma-no":
					return "Latn";
				case "sma-se":
					return "Latn";
				case "sg":
					return "Latn";
				case "sg-cf":
					return "Latn";
				case "sbp":
					return "Latn";
				case "sbp-tz":
					return "Latn";
				case "sa":
					return "Latn";
				case "sa-in":
					return "Latn";
				case "gd":
					return "Latn";
				case "gd-gb":
					return "Latn";
				case "seh":
					return "Latn";
				case "seh-mz":
					return "Latn";
				case "sr-cyrl":
					return "Latn";
				case "sr-cyrl-ba":
					return "Latn";
				case "sr-cyrl-me":
					return "Latn";
				case "sr-cyrl-rs":
					return "Latn";
				case "sr-cyrl-cs":
					return "Latn";
				case "sr-latn":
					return "Latn";
				case "sr":
					return "Latn";
				case "sr-latn-ba":
					return "Latn";
				case "sr-latn-me":
					return "Latn";
				case "sr-latn-rs":
					return "Latn";
				case "sr-latn-cs":
					return "Latn";
				case "nso":
					return "Latn";
				case "nso-za":
					return "Latn";
				case "tn":
					return "Latn";
				case "tn-bw":
					return "Latn";
				case "tn-za":
					return "Latn";
				case "ksb":
					return "Latn";
				case "ksb-tz":
					return "Latn";
				case "sn":
					return "Latn";
				case "sn-latn":
					return "Latn";
				case "sn-latn-zw":
					return "Latn";
				case "sd":
					return "ArabExt";
				case "sd-arab":
					return "ArabExt";
				case "sd-arab-pk":
					return "ArabExt";
				case "si":
					return "Latn";
				case "si-lk":
					return "Latn";
				case "sk":
					return "Latn";
				case "sk-sk":
					return "Latn";
				case "sl":
					return "Latn";
				case "sl-si":
					return "Latn";
				case "xog":
					return "Latn";
				case "xog-ug":
					return "Latn";
				case "so":
					return "Latn";
				case "so-dj":
					return "Latn";
				case "so-et":
					return "Latn";
				case "so-ke":
					return "Latn";
				case "so-so":
					return "Latn";
				case "st":
					return "Latn";
				case "st-za":
					return "Latn";
				case "nr":
					return "Latn";
				case "nr-za":
					return "Latn";
				case "st-ls":
					return "Latn";
				case "es":
					return "Latn";
				case "es-ar":
					return "Latn";
				case "es-bz":
					return "Latn";
				case "es-ve":
					return "Latn";
				case "es-bo":
					return "Latn";
				case "es-br":
					return "Latn";
				case "es-cl":
					return "Latn";
				case "es-co":
					return "Latn";
				case "es-cr":
					return "Latn";
				case "es-cu":
					return "Latn";
				case "es-do":
					return "Latn";
				case "es-ec":
					return "Latn";
				case "es-sv":
					return "Latn";
				case "es-gq":
					return "Latn";
				case "es-gt":
					return "Latn";
				case "es-hn":
					return "Latn";
				case "es-419":
					return "Latn";
				case "es-mx":
					return "Latn";
				case "es-ni":
					return "Latn";
				case "es-pa":
					return "Latn";
				case "es-py":
					return "Latn";
				case "es-pe":
					return "Latn";
				case "es-ph":
					return "Latn";
				case "es-pr":
					return "Latn";
				case "es-es":
					return "Latn";
				case "es-us":
					return "Latn";
				case "es-uy":
					return "Latn";
				case "zgh":
					return "Latn";
				case "zgh-tfng-ma":
					return "Latn";
				case "zgh-tfng":
					return "Latn";
				case "ss":
					return "Latn";
				case "ss-za":
					return "Latn";
				case "ss-sz":
					return "Latn";
				case "sv":
					return "Latn";
				case "sv-ax":
					return "Latn";
				case "sv-fi":
					return "Latn";
				case "sv-se":
					return "Latn";
				case "syr":
					return "Latn";
				case "syr-sy":
					return "Latn";
				case "shi":
					return "Latn";
				case "shi-tfng":
					return "Latn";
				case "shi-tfng-ma":
					return "Latn";
				case "shi-latn":
					return "Latn";
				case "shi-latn-ma":
					return "Latn";
				case "dav":
					return "Latn";
				case "dav-ke":
					return "Latn";
				case "tg":
					return "Latn";
				case "tg-cyrl":
					return "Latn";
				case "tg-cyrl-tj":
					return "Latn";
				case "tzm":
					return "Latn";
				case "tzm-latn":
					return "Latn";
				case "tzm-latn-dz":
					return "Latn";
				case "ta":
					return "Latn";
				case "ta-in":
					return "Latn";
				case "ta-my":
					return "Latn";
				case "ta-sg":
					return "Latn";
				case "ta-lk":
					return "Latn";
				case "twq":
					return "Latn";
				case "twq-ne":
					return "Latn";
				case "tt":
					return "Latn";
				case "tt-ru":
					return "Latn";
				case "te":
					return "Latn";
				case "te-in":
					return "Latn";
				case "teo":
					return "Latn";
				case "teo-ke":
					return "Latn";
				case "teo-ug":
					return "Latn";
				case "th":
					return "Latn";
				case "th-th":
					return "Latn";
				case "bo":
					return "Latn";
				case "bo-in":
					return "Latn";
				case "bo-cn":
					return "Latn";
				case "tig":
					return "Latn";
				case "tig-er":
					return "Latn";
				case "ti":
					return "Latn";
				case "ti-er":
					return "Latn";
				case "ti-et":
					return "Latn";
				case "to":
					return "Latn";
				case "to-to":
					return "Latn";
				case "ts":
					return "Latn";
				case "ts-za":
					return "Latn";
				case "tr":
					return "Latn";
				case "tr-cy":
					return "Latn";
				case "tr-tr":
					return "Latn";
				case "tk":
					return "Latn";
				case "tk-tm":
					return "Latn";
				case "uk":
					return "Latn";
				case "uk-ua":
					return "Latn";
				case "hsb":
					return "Latn";
				case "hsb-de":
					return "Latn";
				case "ur":
					return "Latn";
				case "ur-in":
					return "ArabExt";
				case "ur-pk":
					return "Latn";
				case "ug":
					return "Latn";
				case "ug-cn":
					return "Latn";
				case "uz-arab":
					return "ArabExt";
				case "uz-arab-af":
					return "ArabExt";
				case "uz-cyrl":
					return "Latn";
				case "uz-cyrl-uz":
					return "Latn";
				case "uz":
					return "Latn";
				case "uz-latn":
					return "Latn";
				case "uz-latn-uz":
					return "Latn";
				case "vai":
					return "Latn";
				case "vai-vaii":
					return "Latn";
				case "vai-vaii-lr":
					return "Latn";
				case "vai-latn-lr":
					return "Latn";
				case "vai-latn":
					return "Latn";
				case "ca-es-valencia":
					return "Latn";
				case "ve":
					return "Latn";
				case "ve-za":
					return "Latn";
				case "vi":
					return "Latn";
				case "vi-vn":
					return "Latn";
				case "vo":
					return "Latn";
				case "vo-001":
					return "Latn";
				case "vun":
					return "Latn";
				case "vun-tz":
					return "Latn";
				case "wae":
					return "Latn";
				case "wae-ch":
					return "Latn";
				case "cy":
					return "Latn";
				case "cy-gb":
					return "Latn";
				case "wal":
					return "Latn";
				case "wal-et":
					return "Latn";
				case "wo":
					return "Latn";
				case "wo-sn":
					return "Latn";
				case "xh":
					return "Latn";
				case "xh-za":
					return "Latn";
				case "yav":
					return "Latn";
				case "yav-cm":
					return "Latn";
				case "ii":
					return "Latn";
				case "ii-cn":
					return "Latn";
				case "yi-001":
					return "Latn";
				case "yo":
					return "Latn";
				case "yo-bj":
					return "Latn";
				case "yo-ng":
					return "Latn";
				case "dje":
					return "Latn";
				case "dje-ne":
					return "Latn";
				case "zu":
					return "Latn";
				case "zu-za":
					return "Latn";
				default:
					throw new ArgumentException("The parameter is incorrect.");
			}
		}

		public static string GetResolvedLanguage(string languageTag)
		{
			languageTag = languageTag.ToLowerInvariant();

			switch (languageTag)
			{
				case "aa":
					return "aa";
				case "aa-dj":
					return "aa-Latn-DJ";
				case "aa-er":
					return "aa-Latn-ER";
				case "aa-et":
					return "aa-Latn-ET";
				case "af":
					return "af";
				case "af-na":
					return "af-NA";
				case "af-za":
					return "af";
				case "agq":
					return "agq";
				case "agq-cm":
					return "agq-Latn-CM";
				case "ak":
					return "ak";
				case "ak-gh":
					return "ak-Latn-GH";
				case "sq":
					return "sq";
				case "sq-al":
					return "sq";
				case "sq-mk":
					return "sq-MK";
				case "gsw":
					return "gsw";
				case "gsw-fr":
					return "gsw-FR";
				case "gsw-li":
					return "gsw-LI";
				case "gsw-ch":
					return "gsw";
				case "am":
					return "am";
				case "am-et":
					return "am";
				case "ar":
					return "ar";
				case "ar-dz":
					return "ar-DZ";
				case "ar-bh":
					return "ar-BH";
				case "ar-td":
					return "ar-TD";
				case "ar-km":
					return "ar-KM";
				case "ar-dj":
					return "ar-DJ";
				case "ar-eg":
					return "ar-EG";
				case "ar-er":
					return "ar-ER";
				case "ar-iq":
					return "ar-IQ";
				case "ar-il":
					return "ar-IL";
				case "ar-jo":
					return "ar-JO";
				case "ar-kw":
					return "ar-KW";
				case "ar-lb":
					return "ar-LB";
				case "ar-ly":
					return "ar-LY";
				case "ar-mr":
					return "ar-MR";
				case "ar-ma":
					return "ar-MA";
				case "ar-om":
					return "ar-OM";
				case "ar-ps":
					return "ar-PS";
				case "ar-qa":
					return "ar-QA";
				case "ar-sa":
					return "ar-SA";
				case "ar-so":
					return "ar-SO";
				case "ar-ss":
					return "ar-SS";
				case "ar-sd":
					return "ar-SD";
				case "ar-sy":
					return "ar-SY";
				case "ar-tn":
					return "ar-TN";
				case "ar-ae":
					return "ar-AE";
				case "ar-001":
					return "ar-001";
				case "ar-ye":
					return "ar-YE";
				case "hy":
					return "hy";
				case "hy-am":
					return "hy";
				case "as":
					return "as";
				case "as-in":
					return "as";
				case "ast":
					return "ast";
				case "ast-es":
					return "ast-Latn-ES";
				case "asa":
					return "asa";
				case "asa-tz":
					return "asa-Latn-TZ";
				case "az-cyrl":
					return "az-Cyrl";
				case "az-cyrl-az":
					return "az-Cyrl";
				case "az":
					return "az";
				case "az-latn":
					return "az-Latn";
				case "az-latn-az":
					return "az-Latn";
				case "ksf":
					return "ksf";
				case "ksf-cm":
					return "ksf-Latn-CM";
				case "bm":
					return "bm";
				case "bm-latn-ml":
					return "bm-Latn-ML";
				case "bn":
					return "bn";
				case "bn-bd":
					return "bn-BD";
				case "bn-in":
					return "bn-IN";
				case "bas":
					return "bas";
				case "bas-cm":
					return "bas-Latn-CM";
				case "ba":
					return "ba";
				case "ba-ru":
					return "ba-Cyrl";
				case "eu":
					return "eu";
				case "eu-es":
					return "eu";
				case "be":
					return "be";
				case "be-by":
					return "be";
				case "bem":
					return "bem";
				case "bem-zm":
					return "bem-Latn-ZM";
				case "bez":
					return "bez";
				case "bez-tz":
					return "bez-Latn-TZ";
				case "byn":
					return "byn";
				case "byn-er":
					return "byn-Ethi-ER";
				case "brx":
					return "brx";
				case "brx-in":
					return "brx-Deva-IN";
				case "bs-cyrl":
					return "bs-Cyrl";
				case "bs-cyrl-ba":
					return "bs-Cyrl";
				case "bs-latn":
					return "bs";
				case "bs":
					return "bs";
				case "bs-latn-ba":
					return "bs";
				case "br":
					return "br";
				case "br-fr":
					return "br-Latn";
				case "bg":
					return "bg";
				case "bg-bg":
					return "bg";
				case "my":
					return "my";
				case "my-mm":
					return "my";
				case "ca":
					return "ca";
				case "ca-ad":
					return "ca-AD";
				case "ca-fr":
					return "ca-FR";
				case "ca-it":
					return "ca-IT";
				case "ca-es":
					return "ca";
				case "ceb":
					return "fa";
				case "ceb-latn":
					return "fa";
				case "ceb-latn-ph":
					return "fa";
				case "tzm-arab-ma":
					return "tzm-Arab-MA";
				case "tzm-latn-ma":
					return "tzm-Latn-MA";
				case "ku":
					return "ku";
				case "ku-arab":
					return "ku-Arab";
				case "ku-arab-iq":
					return "ku-Arab";
				case "ccp":
					return "fa";
				case "ccp-cakm":
					return "fa";
				case "ccp-cakm-bd":
					return "fa";
				case "ccp-cakm-in":
					return "fa";
				case "ce-ru":
					return "ce-Cyrl-RU";
				case "chr":
					return "chr";
				case "chr-cher":
					return "chr-Cher";
				case "chr-cher-us":
					return "chr-Cher";
				case "cgg":
					return "cgg";
				case "cgg-ug":
					return "cgg-Latn-UG";
				case "zh-hans":
					return "zh-Hans";
				case "zh":
					return "zh";
				case "zh-cn":
					return "zh-Hans-CN";
				case "zh-sg":
					return "zh-Hans-SG";
				case "zh-hant":
					return "zh-Hant";
				case "zh-hk":
					return "zh-Hant-HK";
				case "zh-mo":
					return "zh-Hant-MO";
				case "zh-tw":
					return "zh-Hant-TW";
				case "cu-ru":
					return "cu-Cyrl-RU";
				case "swc":
					return "fa";
				case "swc-cd":
					return "swc-CD";
				case "kw":
					return "kw";
				case "kw-gb":
					return "kw-Latn-GB";
				case "co":
					return "co";
				case "co-fr":
					return "co-Latn";
				case "hr":
					return "hr";
				case "hr-hr":
					return "hr-HR";
				case "hr-ba":
					return "hr-BA";
				case "cs":
					return "cs";
				case "cs-cz":
					return "cs";
				case "da":
					return "da";
				case "da-dk":
					return "da";
				case "da-gl":
					return "da-GL";
				case "prs":
					return "prs-Arab";
				case "prs-af":
					return "prs-Arab";
				case "dv":
					return "dv";
				case "dv-mv":
					return "dv";
				case "dua":
					return "dua";
				case "dua-cm":
					return "dua-Latn-CM";
				case "nl":
					return "nl";
				case "nl-aw":
					return "nl-AW";
				case "nl-be":
					return "nl-BE";
				case "nl-bq":
					return "nl-BQ";
				case "nl-cw":
					return "nl-CW";
				case "nl-nl":
					return "nl-NL";
				case "nl-sx":
					return "nl-SX";
				case "nl-sr":
					return "nl-SR";
				case "dz":
					return "dz";
				case "dz-bt":
					return "dz";
				case "ebu":
					return "ebu";
				case "ebu-ke":
					return "ebu-Latn-KE";
				case "en":
					return "en";
				case "en-as":
					return "en-AS";
				case "en-ai":
					return "en-AI";
				case "en-ag":
					return "en-AG";
				case "en-au":
					return "en-AU";
				case "en-at":
					return "en-AT";
				case "en-bs":
					return "en-BS";
				case "en-bb":
					return "en-BB";
				case "en-be":
					return "en-BE";
				case "en-bz":
					return "en-BZ";
				case "en-bm":
					return "en-BM";
				case "en-bw":
					return "en-BW";
				case "en-io":
					return "en-IO";
				case "en-vg":
					return "en-VG";
				case "en-bi":
					return "en-BI";
				case "en-cm":
					return "en-CM";
				case "en-ca":
					return "en-CA";
				case "en-029":
					return "en-029";
				case "en-ky":
					return "en-KY";
				case "en-cx":
					return "en-CX";
				case "en-cc":
					return "en-CC";
				case "en-ck":
					return "en-CK";
				case "en-cy":
					return "en-CY";
				case "en-dk":
					return "en-DK";
				case "en-dm":
					return "en-DM";
				case "en-er":
					return "en-ER";
				case "en-150":
					return "en-150";
				case "en-fk":
					return "en-FK";
				case "en-fi":
					return "en-FI";
				case "en-fj":
					return "en-FJ";
				case "en-gm":
					return "en-GM";
				case "en-de":
					return "en-DE";
				case "en-gh":
					return "en-GH";
				case "en-gi":
					return "en-GI";
				case "en-gd":
					return "en-GD";
				case "en-gu":
					return "en-GU";
				case "en-gg":
					return "en-GG";
				case "en-gy":
					return "en-GY";
				case "en-hk":
					return "en-HK";
				case "en-in":
					return "en-IN";
				case "en-ie":
					return "en-IE";
				case "en-im":
					return "en-IM";
				case "en-il":
					return "en-IL";
				case "en-jm":
					return "en-JM";
				case "en-je":
					return "en-JE";
				case "en-ke":
					return "en-KE";
				case "en-ki":
					return "en-KI";
				case "en-ls":
					return "en-LS";
				case "en-lr":
					return "en-LR";
				case "en-mo":
					return "en-MO";
				case "en-mg":
					return "en-MG";
				case "en-mw":
					return "en-MW";
				case "en-my":
					return "en-MY";
				case "en-mt":
					return "en-MT";
				case "en-mh":
					return "en-MH";
				case "en-mu":
					return "en-MU";
				case "en-fm":
					return "en-FM";
				case "en-ms":
					return "en-MS";
				case "en-na":
					return "en-NA";
				case "en-nr":
					return "en-NR";
				case "en-nl":
					return "en-NL";
				case "en-nz":
					return "en-NZ";
				case "en-ng":
					return "en-NG";
				case "en-nu":
					return "en-NU";
				case "en-nf":
					return "en-NF";
				case "en-mp":
					return "en-MP";
				case "en-pk":
					return "en-PK";
				case "en-pw":
					return "en-PW";
				case "en-pg":
					return "en-PG";
				case "en-pn":
					return "en-PN";
				case "en-pr":
					return "en-PR";
				case "en-ph":
					return "en-PH";
				case "en-rw":
					return "en-RW";
				case "en-kn":
					return "en-KN";
				case "en-lc":
					return "en-LC";
				case "en-vc":
					return "en-VC";
				case "en-ws":
					return "en-WS";
				case "en-sc":
					return "en-SC";
				case "en-sl":
					return "en-SL";
				case "en-sg":
					return "en-SG";
				case "en-sx":
					return "en-SX";
				case "en-si":
					return "en-SI";
				case "en-sb":
					return "en-SB";
				case "en-za":
					return "en-ZA";
				case "en-ss":
					return "en-SS";
				case "en-sh":
					return "en-SH";
				case "en-sd":
					return "en-SD";
				case "en-sz":
					return "en-SZ";
				case "en-se":
					return "en-SE";
				case "en-ch":
					return "en-CH";
				case "en-tz":
					return "en-TZ";
				case "en-tk":
					return "en-TK";
				case "en-to":
					return "en-TO";
				case "en-tt":
					return "en-TT";
				case "en-tc":
					return "en-TC";
				case "en-tv":
					return "en-TV";
				case "en-ug":
					return "en-UG";
				case "en-ae":
					return "en";
				case "en-gb":
					return "en-GB";
				case "en-us":
					return "en-US";
				case "en-um":
					return "en-UM";
				case "en-vi":
					return "en-VI";
				case "en-vu":
					return "en-VU";
				case "en-001":
					return "en-001";
				case "en-zm":
					return "en-ZM";
				case "en-zw":
					return "en-ZW";
				case "eo":
					return "eo";
				case "eo-001":
					return "eo-001";
				case "et":
					return "et";
				case "et-ee":
					return "et";
				case "ee":
					return "ee";
				case "ee-gh":
					return "ee-Latn-GH";
				case "ee-tg":
					return "ee-Latn-TG";
				case "ewo":
					return "ewo";
				case "ewo-cm":
					return "ewo-Latn-CM";
				case "fo":
					return "fo";
				case "fo-dk":
					return "fo-DK";
				case "fo-fo":
					return "fo";
				case "fil":
					return "fil-Latn";
				case "fil-ph":
					return "fil-Latn";
				case "fi":
					return "fi";
				case "fi-fi":
					return "fi";
				case "fr":
					return "fr";
				case "fr-dz":
					return "fr-DZ";
				case "fr-be":
					return "fr-BE";
				case "fr-bj":
					return "fr-BJ";
				case "fr-bf":
					return "fr-BF";
				case "fr-bi":
					return "fr-BI";
				case "fr-cm":
					return "fr-CM";
				case "fr-ca":
					return "fr-CA";
				case "fr-029":
					return "fr-029";
				case "fr-cf":
					return "fr-CF";
				case "fr-td":
					return "fr-TD";
				case "fr-km":
					return "fr-KM";
				case "fr-cg":
					return "fr-CG";
				case "fr-cd":
					return "fr-CD";
				case "fr-ci":
					return "fr-CI";
				case "fr-dj":
					return "fr-DJ";
				case "fr-gq":
					return "fr-GQ";
				case "fr-fr":
					return "fr-FR";
				case "fr-gf":
					return "fr-GF";
				case "fr-pf":
					return "fr-PF";
				case "fr-ga":
					return "fr-GA";
				case "fr-gp":
					return "fr-GP";
				case "fr-gn":
					return "fr-GN";
				case "fr-ht":
					return "fr-HT";
				case "fr-lu":
					return "fr-LU";
				case "fr-mg":
					return "fr-MG";
				case "fr-ml":
					return "fr-ML";
				case "fr-mq":
					return "fr-MQ";
				case "fr-mr":
					return "fr-MR";
				case "fr-mu":
					return "fr-MU";
				case "fr-yt":
					return "fr-YT";
				case "fr-ma":
					return "fr-MA";
				case "fr-nc":
					return "fr-NC";
				case "fr-ne":
					return "fr-NE";
				case "fr-mc":
					return "fr-MC";
				case "fr-re":
					return "fr-RE";
				case "fr-rw":
					return "fr-RW";
				case "fr-bl":
					return "fr-BL";
				case "fr-mf":
					return "fr-MF";
				case "fr-pm":
					return "fr-PM";
				case "fr-sn":
					return "fr-SN";
				case "fr-sc":
					return "fr-SC";
				case "fr-ch":
					return "fr-CH";
				case "fr-sy":
					return "fr-SY";
				case "fr-tg":
					return "fr-TG";
				case "fr-tn":
					return "fr-TN";
				case "fr-vu":
					return "fr-VU";
				case "fr-wf":
					return "fr-WF";
				case "fy":
					return "fy";
				case "fy-nl":
					return "fy";
				case "fur":
					return "fur";
				case "fur-it":
					return "fur-Latn-IT";
				case "ff":
					return "ff";
				case "ff-latn":
					return "ff-Latn";
				case "ff-latn-bf":
					return "ff-Latn-BF";
				case "ff-cm":
					return "ff-CM";
				case "ff-latn-cm":
					return "ff-Latn-CM";
				case "ff-latn-gm":
					return "ff-Latn-GM";
				case "ff-latn-gh":
					return "ff-Latn-GH";
				case "ff-gn":
					return "ff-GN";
				case "ff-latn-gn":
					return "ff-Latn-GN";
				case "ff-latn-gw":
					return "ff-Latn-GW";
				case "ff-latn-lr":
					return "ff-Latn-LR";
				case "ff-mr":
					return "ff-MR";
				case "ff-latn-mr":
					return "ff-Latn-MR";
				case "ff-latn-ne":
					return "ff-Latn-NE";
				case "ff-ng":
					return "ff-NG";
				case "ff-latn-ng":
					return "ff-Latn-NG";
				case "ff-latn-sn":
					return "ff-Latn-SN";
				case "ff-latn-sl":
					return "ff-Latn-SL";
				case "gl":
					return "gl";
				case "gl-es":
					return "gl";
				case "lg":
					return "lg";
				case "lg-ug":
					return "lg-Latn-UG";
				case "ka":
					return "ka";
				case "ka-ge":
					return "ka";
				case "de":
					return "de";
				case "de-at":
					return "de-AT";
				case "de-be":
					return "de-BE";
				case "de-de":
					return "de-DE";
				case "de-it":
					return "de-IT";
				case "de-li":
					return "de-LI";
				case "de-lu":
					return "de-LU";
				case "de-ch":
					return "de-CH";
				case "el":
					return "el";
				case "el-cy":
					return "el-CY";
				case "el-gr":
					return "el";
				case "kl":
					return "kl";
				case "kl-gl":
					return "kl";
				case "gn":
					return "gn";
				case "gn-py":
					return "gn";
				case "gu":
					return "gu";
				case "gu-in":
					return "gu";
				case "guz":
					return "guz";
				case "guz-ke":
					return "guz-Latn-KE";
				case "ha":
					return "ha";
				case "ha-latn":
					return "ha-Latn";
				case "ha-latn-gh":
					return "ha-Latn-GH";
				case "ha-latn-ne":
					return "ha-Latn-NE";
				case "ha-latn-ng":
					return "ha-Latn";
				case "haw":
					return "haw-Latn";
				case "haw-us":
					return "haw-Latn";
				case "he":
					return "he";
				case "he-il":
					return "he";
				case "hi":
					return "hi";
				case "hi-in":
					return "hi";
				case "hu":
					return "hu";
				case "hu-hu":
					return "hu";
				case "is":
					return "is";
				case "is-is":
					return "is";
				case "ig":
					return "ig";
				case "ig-ng":
					return "ig-Latn";
				case "id":
					return "id";
				case "id-id":
					return "id";
				case "ia":
					return "ia";
				case "ia-fr":
					return "fa";
				case "ia-001":
					return "ia-001";
				case "iu":
					return "iu";
				case "iu-latn":
					return "iu-Latn";
				case "iu-latn-ca":
					return "iu-Latn";
				case "iu-cans":
					return "iu-Cans";
				case "iu-cans-ca":
					return "iu-Cans";
				case "ga":
					return "ga";
				case "ga-ie":
					return "ga";
				case "it":
					return "it";
				case "it-it":
					return "it-IT";
				case "it-sm":
					return "it-SM";
				case "it-ch":
					return "it-CH";
				case "it-va":
					return "it-VA";
				case "ja":
					return "ja";
				case "ja-jp":
					return "ja";
				case "jv":
					return "jv";
				case "jv-latn":
					return "jv-Latn";
				case "jv-latn-id":
					return "jv-Latn-ID";
				case "dyo":
					return "dyo";
				case "dyo-sn":
					return "dyo-Latn-SN";
				case "kea":
					return "kea";
				case "kea-cv":
					return "kea-Latn-CV";
				case "kab":
					return "kab";
				case "kab-dz":
					return "kab-Latn-DZ";
				case "kkj":
					return "kkj";
				case "kkj-cm":
					return "kkj-Latn-CM";
				case "kln":
					return "kln";
				case "kln-ke":
					return "kln-Latn-KE";
				case "kam":
					return "kam";
				case "kam-ke":
					return "kam-Latn-KE";
				case "kn":
					return "kn";
				case "kn-in":
					return "kn";
				case "kr-latn-ng":
					return "kr-Latn-NG";
				case "ks":
					return "ks";
				case "ks-arab":
					return "ks-Arab";
				case "ks-arab-in":
					return "ks-Arab-IN";
				case "ks-deva-in":
					return "ks-Deva-IN";
				case "kk":
					return "kk";
				case "kk-kz":
					return "kk";
				case "km":
					return "km";
				case "km-kh":
					return "km";
				case "quc":
					return "quc";
				case "quc-latn-gt":
					return "quc-Latn";
				case "ki":
					return "ki";
				case "ki-ke":
					return "ki-Latn-KE";
				case "rw":
					return "rw";
				case "rw-rw":
					return "rw";
				case "sw":
					return "sw";
				case "sw-ke":
					return "sw";
				case "sw-tz":
					return "sw-TZ";
				case "sw-ug":
					return "sw-UG";
				case "kok":
					return "kok";
				case "kok-in":
					return "kok";
				case "ko":
					return "ko";
				case "ko-kr":
					return "ko";
				case "ko-kp":
					return "ko-KP";
				case "khq":
					return "khq";
				case "khq-ml":
					return "khq-Latn-ML";
				case "ses":
					return "ses";
				case "ses-ml":
					return "ses-Latn-ML";
				case "nmg":
					return "nmg";
				case "nmg-cm":
					return "nmg-Latn-CM";
				case "ky":
					return "ky";
				case "ky-kg":
					return "ky-Cyrl";
				case "ku-arab-ir":
					return "ku-Arab-IR";
				case "lkt":
					return "lkt";
				case "lkt-us":
					return "lkt-Latn-US";
				case "lag":
					return "lag";
				case "lag-tz":
					return "lag-Latn-TZ";
				case "lo":
					return "lo";
				case "lo-la":
					return "lo";
				case "la-va":
					return "la";
				case "lv":
					return "lv";
				case "lv-lv":
					return "lv";
				case "ln":
					return "ln";
				case "ln-ao":
					return "ln-AO";
				case "ln-cf":
					return "ln-CF";
				case "ln-cg":
					return "ln-CG";
				case "ln-cd":
					return "ln-CD";
				case "lt":
					return "lt";
				case "lt-lt":
					return "lt";
				case "nds":
					return "nds";
				case "nds-de":
					return "nds-DE";
				case "nds-nl":
					return "nds-NL";
				case "dsb":
					return "dsb";
				case "dsb-de":
					return "dsb";
				case "lu":
					return "lu";
				case "lu-cd":
					return "lu-Latn-CD";
				case "luo":
					return "luo";
				case "luo-ke":
					return "luo-Latn-KE";
				case "lb":
					return "lb";
				case "lb-lu":
					return "lb";
				case "luy":
					return "luy";
				case "luy-ke":
					return "luy-Latn-KE";
				case "mk":
					return "mk";
				case "mk-mk":
					return "mk";
				case "jmc":
					return "jmc";
				case "jmc-tz":
					return "jmc-Latn-TZ";
				case "mgh":
					return "mgh";
				case "mgh-mz":
					return "mgh-Latn-MZ";
				case "kde":
					return "kde";
				case "kde-tz":
					return "kde-Latn-TZ";
				case "mg":
					return "mg";
				case "mg-mg":
					return "mg-MG";
				case "ms":
					return "ms";
				case "ms-bn":
					return "ms-BN";
				case "ms-my":
					return "ms-MY";
				case "ml":
					return "ml";
				case "ml-in":
					return "ml";
				case "mt":
					return "mt";
				case "mt-mt":
					return "mt";
				case "gv":
					return "gv";
				case "gv-im":
					return "gv-IM";
				case "mi":
					return "mi-Latn";
				case "mi-nz":
					return "mi-Latn";
				case "arn":
					return "arn";
				case "arn-cl":
					return "arn-Latn";
				case "mr":
					return "mr";
				case "mr-in":
					return "mr";
				case "mas":
					return "mas";
				case "mas-ke":
					return "mas-Latn-KE";
				case "mas-tz":
					return "mas-Latn-TZ";
				case "mzn-ir":
					return "mzn-Arab-IR";
				case "mer":
					return "mer";
				case "mer-ke":
					return "mer-Latn-KE";
				case "mgo":
					return "mgo";
				case "mgo-cm":
					return "mgo-Latn-CM";
				case "moh":
					return "moh";
				case "moh-ca":
					return "moh-Latn";
				case "mn":
					return "mn";
				case "mn-cyrl":
					return "mn-Cyrl";
				case "mn-mn":
					return "mn-Cyrl";
				case "mn-mong":
					return "mn-Mong";
				case "mn-mong-cn":
					return "mn-Mong";
				case "mn-mong-mn":
					return "mn-Mong-MN";
				case "mfe":
					return "mfe";
				case "mfe-mu":
					return "mfe-Latn-MU";
				case "mua":
					return "mua";
				case "mua-cm":
					return "mua-Latn-CM";
				case "nqo":
					return "nqo";
				case "nqo-gn":
					return "nqo-GN";
				case "naq":
					return "naq";
				case "naq-na":
					return "naq-Latn-NA";
				case "ne":
					return "ne";
				case "ne-in":
					return "ne-IN";
				case "ne-np":
					return "ne-NP";
				case "nnh":
					return "nnh";
				case "nnh-cm":
					return "nnh-Latn-CM";
				case "jgo":
					return "jgo";
				case "jgo-cm":
					return "jgo-Latn-CM";
				case "lrc-iq":
					return "lrc-Arab-IQ";
				case "lrc-ir":
					return "lrc-Arab-IR";
				case "nd":
					return "nd";
				case "nd-zw":
					return "nd-ZW";
				case "no":
					return "no";
				case "nb":
					return "nb";
				case "nb-no":
					return "nb";
				case "nn":
					return "nn";
				case "nn-no":
					return "nn";
				case "nb-sj":
					return "nb-SJ";
				case "nus":
					return "nus";
				case "nus-sd":
					return "nus-SD";
				case "nus-ss":
					return "nus-Latn-SS";
				case "nyn":
					return "nyn";
				case "nyn-ug":
					return "nyn-Latn-UG";
				case "oc":
					return "oc";
				case "oc-fr":
					return "oc-Latn";
				case "or":
					return "or";
				case "or-in":
					return "or";
				case "om":
					return "om";
				case "om-et":
					return "om";
				case "om-ke":
					return "om-KE";
				case "os":
					return "os";
				case "os-ge":
					return "os-Cyrl-GE";
				case "os-ru":
					return "os-Cyrl-RU";
				case "ps":
					return "ps";
				case "ps-af":
					return "ps";
				case "ps-pk":
					return "ps";
				case "fa":
					return "fa";
				case "fa-af":
					return "fa-AF";
				case "fa-ir":
					return "fa";
				case "pl":
					return "pl";
				case "pl-pl":
					return "pl";
				case "pt":
					return "pt";
				case "pt-ao":
					return "pt-AO";
				case "pt-br":
					return "pt-BR";
				case "pt-cv":
					return "pt-CV";
				case "pt-gq":
					return "pt-GQ";
				case "pt-gw":
					return "pt-GW";
				case "pt-lu":
					return "pt-LU";
				case "pt-mo":
					return "pt-MO";
				case "pt-mz":
					return "pt-MZ";
				case "pt-pt":
					return "pt-PT";
				case "pt-st":
					return "pt-ST";
				case "pt-ch":
					return "pt-CH";
				case "pt-tl":
					return "pt-TL";
				case "prg-001":
					return "prg-Latn-001";
				case "qps-ploca":
					return "qps-ploca";
				case "qps-ploc":
					return "qps-ploc";
				case "qps-plocm":
					return "qps-plocm";
				case "pa":
					return "pa";
				case "pa-arab":
					return "pa-Arab";
				case "pa-in":
					return "pa";
				case "pa-arab-pk":
					return "pa-Arab";
				case "quz":
					return "quz-Latn";
				case "quz-bo":
					return "quz-Latn-BO";
				case "quz-ec":
					return "quz-Latn-EC";
				case "quz-pe":
					return "quz-Latn-PE";
				case "ksh":
					return "ksh";
				case "ksh-de":
					return "ksh-Latn-DE";
				case "ro":
					return "ro";
				case "ro-md":
					return "ro-MD";
				case "ro-ro":
					return "ro-RO";
				case "rm":
					return "rm";
				case "rm-ch":
					return "rm";
				case "rof":
					return "rof";
				case "rof-tz":
					return "rof-Latn-TZ";
				case "rn":
					return "rn";
				case "rn-bi":
					return "rn-BI";
				case "ru":
					return "ru";
				case "ru-by":
					return "ru-BY";
				case "ru-kz":
					return "ru-KZ";
				case "ru-kg":
					return "ru-KG";
				case "ru-md":
					return "ru-MD";
				case "ru-ru":
					return "ru";
				case "ru-ua":
					return "ru-UA";
				case "rwk":
					return "rwk";
				case "rwk-tz":
					return "rwk-Latn-TZ";
				case "ssy":
					return "ssy";
				case "ssy-er":
					return "ssy-Latn-ER";
				case "sah":
					return "sah";
				case "sah-ru":
					return "sah-Cyrl";
				case "saq":
					return "saq";
				case "saq-ke":
					return "saq-Latn-KE";
				case "smn":
					return "smn";
				case "smn-fi":
					return "smn-Latn";
				case "smj":
					return "smj";
				case "smj-no":
					return "smj-Latn-NO";
				case "smj-se":
					return "smj-Latn-SE";
				case "se":
					return "se";
				case "se-fi":
					return "se-Latn-FI";
				case "se-no":
					return "se-Latn-NO";
				case "se-se":
					return "se-Latn-SE";
				case "sms":
					return "sms";
				case "sms-fi":
					return "sms-Latn";
				case "sma":
					return "sma";
				case "sma-no":
					return "sma-Latn-NO";
				case "sma-se":
					return "sma-Latn-SE";
				case "sg":
					return "sg";
				case "sg-cf":
					return "sg-CF";
				case "sbp":
					return "sbp";
				case "sbp-tz":
					return "sbp-Latn-TZ";
				case "sa":
					return "sa";
				case "sa-in":
					return "sa-Deva";
				case "gd":
					return "gd";
				case "gd-gb":
					return "gd-Latn";
				case "seh":
					return "seh";
				case "seh-mz":
					return "seh-Latn-MZ";
				case "sr-cyrl":
					return "sr-Cyrl";
				case "sr-cyrl-ba":
					return "sr-Cyrl-BA";
				case "sr-cyrl-me":
					return "sr-Cyrl-ME";
				case "sr-cyrl-rs":
					return "sr-Cyrl-RS";
				case "sr-cyrl-cs":
					return "sr-Cyrl-CS";
				case "sr-latn":
					return "sr-Latn";
				case "sr":
					return "sr";
				case "sr-latn-ba":
					return "sr-Latn-BA";
				case "sr-latn-me":
					return "sr-Latn-ME";
				case "sr-latn-rs":
					return "sr-Latn-RS";
				case "sr-latn-cs":
					return "sr-Latn-CS";
				case "nso":
					return "nso";
				case "nso-za":
					return "nso";
				case "tn":
					return "tn";
				case "tn-bw":
					return "tn-BW";
				case "tn-za":
					return "tn-ZA";
				case "ksb":
					return "ksb";
				case "ksb-tz":
					return "ksb-Latn-TZ";
				case "sn":
					return "sn";
				case "sn-latn":
					return "sn-Latn";
				case "sn-latn-zw":
					return "sn-Latn-ZW";
				case "sd":
					return "sd";
				case "sd-arab":
					return "sd-Arab";
				case "sd-arab-pk":
					return "sd-Arab";
				case "si":
					return "si";
				case "si-lk":
					return "si";
				case "sk":
					return "sk";
				case "sk-sk":
					return "sk";
				case "sl":
					return "sl";
				case "sl-si":
					return "sl";
				case "xog":
					return "xog";
				case "xog-ug":
					return "xog-Latn-UG";
				case "so":
					return "so";
				case "so-dj":
					return "so-DJ";
				case "so-et":
					return "so-ET";
				case "so-ke":
					return "so-KE";
				case "so-so":
					return "so";
				case "st":
					return "st";
				case "st-za":
					return "st";
				case "nr":
					return "nr";
				case "nr-za":
					return "nr-ZA";
				case "st-ls":
					return "st-LS";
				case "es":
					return "es";
				case "es-ar":
					return "es-AR";
				case "es-bz":
					return "es-BZ";
				case "es-ve":
					return "es-VE";
				case "es-bo":
					return "es-BO";
				case "es-br":
					return "es-BR";
				case "es-cl":
					return "es-CL";
				case "es-co":
					return "es-CO";
				case "es-cr":
					return "es-CR";
				case "es-cu":
					return "es-CU";
				case "es-do":
					return "es-DO";
				case "es-ec":
					return "es-EC";
				case "es-sv":
					return "es-SV";
				case "es-gq":
					return "es-GQ";
				case "es-gt":
					return "es-GT";
				case "es-hn":
					return "es-HN";
				case "es-419":
					return "es-419";
				case "es-mx":
					return "es-MX";
				case "es-ni":
					return "es-NI";
				case "es-pa":
					return "es-PA";
				case "es-py":
					return "es-PY";
				case "es-pe":
					return "es-PE";
				case "es-ph":
					return "es-PH";
				case "es-pr":
					return "es-PR";
				case "es-es":
					return "es-ES";
				case "es-us":
					return "es-US";
				case "es-uy":
					return "es-UY";
				case "zgh":
					return "zgh";
				case "zgh-tfng-ma":
					return "zgh-Tfng-MA";
				case "zgh-tfng":
					return "zgh-Tfng";
				case "ss":
					return "ss";
				case "ss-za":
					return "ss-ZA";
				case "ss-sz":
					return "ss-SZ";
				case "sv":
					return "sv";
				case "sv-ax":
					return "sv-AX";
				case "sv-fi":
					return "sv-FI";
				case "sv-se":
					return "sv-SE";
				case "syr":
					return "syr";
				case "syr-sy":
					return "syr-Syrc";
				case "shi":
					return "shi";
				case "shi-tfng":
					return "shi-Tfng";
				case "shi-tfng-ma":
					return "shi-Tfng-MA";
				case "shi-latn":
					return "shi-Latn";
				case "shi-latn-ma":
					return "shi-Latn-MA";
				case "dav":
					return "dav";
				case "dav-ke":
					return "dav-Latn-KE";
				case "tg":
					return "tg";
				case "tg-cyrl":
					return "tg-Cyrl";
				case "tg-cyrl-tj":
					return "tg-Cyrl";
				case "tzm":
					return "tzm";
				case "tzm-latn":
					return "tzm-Latn";
				case "tzm-latn-dz":
					return "tzm-Latn";
				case "ta":
					return "ta";
				case "ta-in":
					return "ta-IN";
				case "ta-my":
					return "ta-MY";
				case "ta-sg":
					return "ta-SG";
				case "ta-lk":
					return "ta-LK";
				case "twq":
					return "twq";
				case "twq-ne":
					return "twq-Latn-NE";
				case "tt":
					return "tt";
				case "tt-ru":
					return "tt-Cyrl";
				case "te":
					return "te";
				case "te-in":
					return "te";
				case "teo":
					return "teo";
				case "teo-ke":
					return "teo-Latn-KE";
				case "teo-ug":
					return "teo-Latn-UG";
				case "th":
					return "th";
				case "th-th":
					return "th";
				case "bo":
					return "bo";
				case "bo-in":
					return "bo-IN";
				case "bo-cn":
					return "bo-Tibt";
				case "tig":
					return "tig";
				case "tig-er":
					return "tig-Ethi-ER";
				case "ti":
					return "ti";
				case "ti-er":
					return "ti-ER";
				case "ti-et":
					return "ti-ET";
				case "to":
					return "to";
				case "to-to":
					return "to-TO";
				case "ts":
					return "ts";
				case "ts-za":
					return "ts";
				case "tr":
					return "tr";
				case "tr-cy":
					return "tr-CY";
				case "tr-tr":
					return "tr";
				case "tk":
					return "tk";
				case "tk-tm":
					return "tk-Latn";
				case "uk":
					return "uk";
				case "uk-ua":
					return "uk";
				case "hsb":
					return "hsb";
				case "hsb-de":
					return "hsb";
				case "ur":
					return "ur";
				case "ur-in":
					return "ur-IN";
				case "ur-pk":
					return "ur-PK";
				case "ug":
					return "ug";
				case "ug-cn":
					return "ug-Arab";
				case "uz-arab":
					return "uz-Arab";
				case "uz-arab-af":
					return "uz-Arab-AF";
				case "uz-cyrl":
					return "uz-Cyrl";
				case "uz-cyrl-uz":
					return "uz-Cyrl";
				case "uz":
					return "uz";
				case "uz-latn":
					return "uz-Latn";
				case "uz-latn-uz":
					return "uz-Latn";
				case "vai":
					return "vai";
				case "vai-vaii":
					return "vai-Vaii";
				case "vai-vaii-lr":
					return "vai-Vaii-LR";
				case "vai-latn-lr":
					return "vai-Latn-LR";
				case "vai-latn":
					return "vai-Latn";
				case "ca-es-valencia":
					return "ca-ES-valencia";
				case "ve":
					return "ve";
				case "ve-za":
					return "ve-ZA";
				case "vi":
					return "vi";
				case "vi-vn":
					return "vi";
				case "vo":
					return "vo";
				case "vo-001":
					return "vo-Latn-001";
				case "vun":
					return "vun";
				case "vun-tz":
					return "vun-Latn-TZ";
				case "wae":
					return "wae";
				case "wae-ch":
					return "wae-Latn-CH";
				case "cy":
					return "cy";
				case "cy-gb":
					return "cy";
				case "wal":
					return "wal";
				case "wal-et":
					return "wal-Ethi-ET";
				case "wo":
					return "wo-Latn";
				case "wo-sn":
					return "wo-Latn";
				case "xh":
					return "xh";
				case "xh-za":
					return "xh";
				case "yav":
					return "yav";
				case "yav-cm":
					return "yav-Latn-CM";
				case "ii":
					return "ii";
				case "ii-cn":
					return "ii-Yiii";
				case "yi-001":
					return "yi";
				case "yo":
					return "yo";
				case "yo-bj":
					return "yo-BJ";
				case "yo-ng":
					return "yo-Latn";
				case "dje":
					return "dje";
				case "dje-ne":
					return "dje-Latn-NE";
				case "zu":
					return "zu";
				case "zu-za":
					return "zu";
				default:
					throw new ArgumentException("The parameter is incorrect.");
			}
		}

		public static char[] GetDigitsSource(string numeralSystem)
		{
			switch (numeralSystem)
			{
				case "Arab":
					return ArabDigits;
				case "ArabExt":
					return ArabExtDigits;
				case "Bali":
					return BaliDigits;
				case "Beng":
					return BengDigits;
				case "Cham":
					return ChamDigits;
				case "Deva":
					return DevaDigits;
				case "FullWide":
					return FullWideDigits;
				case "Gujr":
					return GujrDigits;
				case "Guru":
					return GuruDigits;
				case "Java":
					return JavaDigits;
				case "Kali":
					return KaliDigits;
				case "Khmr":
					return KhmrDigits;
				case "Knda":
					return KndaDigits;
				case "Lana":
					return LanaDigits;
				case "LanaTham":
					return LanaThamDigits;
				case "Laoo":
					return LaooDigits;
				case "Latn":
					return LatnDigits;
				case "Lepc":
					return LepcDigits;
				case "Limb":
					return LimbDigits;
				case "Mlym":
					return MlymDigits;
				case "Mong":
					return MongDigits;
				case "Mtei":
					return MteiDigits;
				case "Mymr":
					return MymrDigits;
				case "MymrShan":
					return MymrShanDigits;
				case "Nkoo":
					return NkooDigits;
				case "Olck":
					return OlckDigits;
				case "Orya":
					return OryaDigits;
				case "Saur":
					return SaurDigits;
				case "Sund":
					return SundDigits;
				case "Talu":
					return TaluDigits;
				case "TamlDec":
					return TamlDecDigits;
				case "Telu":
					return TeluDigits;
				case "Thai":
					return ThaiDigits;
				case "Tibt":
					return TibtDigits;
				case "Vaii":
					return VaiiDigits;
				default:
					throw new ArgumentException("The parameter is incorrect.");
			}
		}

		public static string ToPascalCase(string numeralSystem)
		{
			numeralSystem = numeralSystem.ToLowerInvariant();

			switch (numeralSystem)
			{
				case "arab":
					return "Arab";
				case "arabext":
					return "ArabExt";
				case "bali":
					return "Bali";
				case "beng":
					return "Beng";
				case "cham":
					return "Cham";
				case "deva":
					return "Deva";
				case "fullwide":
					return "FullWide";
				case "gujr":
					return "Gujr";
				case "guru":
					return "Guru";
				case "java":
					return "Java";
				case "kali":
					return "Kali";
				case "khmr":
					return "Khmr";
				case "knda":
					return "Knda";
				case "lana":
					return "Lana";
				case "lanatham":
					return "LanaTham";
				case "laoo":
					return "Laoo";
				case "latn":
					return "Latn";
				case "lepc":
					return "Lepc";
				case "limb":
					return "Limb";
				case "mlym":
					return "Mlym";
				case "mong":
					return "Mong";
				case "mtei":
					return "Mtei";
				case "mymr":
					return "Mymr";
				case "mymrshan":
					return "MymrShan";
				case "nkoo":
					return "Nkoo";
				case "olck":
					return "Olck";
				case "orya":
					return "Orya";
				case "saur":
					return "Saur";
				case "sund":
					return "Sund";
				case "talu":
					return "Talu";
				case "tamldec":
					return "TamlDec";
				case "telu":
					return "Telu";
				case "thai":
					return "Thai";
				case "tibt":
					return "Tibt";
				case "vaii":
					return "Vaii";
				default:
					throw new ArgumentException("The parameter is incorrect.");
			}
		}
	}
}
