using System.Threading.Tasks;
using System.Collections.Generic;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.CodeAnalysis.Testing;
using Uno.Analyzers.Tests.Verifiers;
using System.Collections.Immutable;

namespace Uno.Analyzers.Tests;

using Verify = CSharpCodeFixVerifier<UnoMissingAssemblyAnalyzer, EmptyCodeFixProvider>;

[TestClass]
public class UnoMissingAssemblyAnalyzerTests
{
#if HAS_UNO_WINUI
	private static readonly ImmutableArray<PackageIdentity> _unoPackage = [new PackageIdentity("Uno.WinUI", "5.2.161")];
	private static readonly ImmutableArray<PackageIdentity> _unoPackageWithLottie = [new PackageIdentity("Uno.WinUI", "5.2.161"), new PackageIdentity("Uno.WinUI.Lottie", "5.2.161")];
#else
	private static readonly ImmutableArray<PackageIdentity> _unoPackage = [new PackageIdentity("Uno.UI", "5.2.161")];
	private static readonly ImmutableArray<PackageIdentity> _unoPackageWithLottie = [new PackageIdentity("Uno.UI", "5.2.161"), new PackageIdentity("Uno.UI.Lottie", "5.2.161")];
#endif

	private static readonly ReferenceAssemblies _net80WithUno = ReferenceAssemblies.Net.Net80.AddPackages(_unoPackage);
	private static readonly ReferenceAssemblies _net80WithUnoAndLottie = ReferenceAssemblies.Net.Net80.AddPackages(_unoPackageWithLottie);

	private const string UnoHeadGlobalConfig = """
		is_global = true
		build_property.IsUnoHead = true
		""";

	[TestMethod]
	public async Task UseProgressRingWithLottiePackage_NoDiagnostic()
	{
		var code = """
			using Microsoft.UI.Xaml.Controls;
			public class C
			{
				public ProgressRing M() => new ProgressRing();
			}
			""";

		var test = new Verify.Test()
		{
			TestCode = code,
			FixedCode = code,
			ReferenceAssemblies = _net80WithUnoAndLottie,
		};

		test.TestState.AnalyzerConfigFiles.Add(("/.globalconfig", UnoHeadGlobalConfig));

		await test.RunAsync();
	}

	[TestMethod]
	public async Task UseProgressRingWithoutLottiePackage_Diagnostic()
	{
		var code = """
			// <auto-generated />
			using Microsoft.UI.Xaml.Controls;
			public class C
			{
				public ProgressRing M() => [|new ProgressRing()|];
			}
			""";

		var test = new Verify.Test()
		{
			TestCode = code,
			FixedCode = code,
			ReferenceAssemblies = _net80WithUno,
		};

		test.TestState.AnalyzerConfigFiles.Add(("/.globalconfig", UnoHeadGlobalConfig));

		await test.RunAsync();
	}

}
