<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <RootNamespace>MyCrossRuntimeLib</RootNamespace>
    <AssemblyName>MyCrossRuntimeLib</AssemblyName>
    <UnoRuntimeVariant>Wasm</UnoRuntimeVariant>
    <DefineConstants>$(DefineConstants);WINUI;__WASM__</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Uno.WinUI" Version="$(NBGV_SemVer2)" />
  </ItemGroup>
</Project>
