#nullable enable

using System.Text;
using Microsoft.CodeAnalysis;

namespace Uno.UI.SourceGenerators.Mixins;

[Generator]
public sealed class DependencyPropertyMixinGenerator : IIncrementalGenerator
{
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		context.RegisterPostInitializationOutput(static ctx =>
		{
			ctx.AddSource("DependencyPropertyMixins.g.cs", Generate());
		});
	}

	public static string Generate()
	{
		var sb = new StringBuilder();
		sb.AppendLine("#if UNO_MIXIN_GENERATION");
		sb.AppendLine(Header);
		sb.AppendLine();

		foreach (var ns in Namespaces)
		{
			sb.AppendLine();
			sb.AppendLine($"namespace {ns.Name}");
			sb.AppendLine("{");

			foreach (var cls in ns.Classes)
			{
				sb.AppendLine();
				if (cls.Condition != "true")
				{
					sb.AppendLine($"#if {cls.Condition}");
				}
				sb.AppendLine($"\t{cls.AccessModifier} partial class {cls.Name}");
				sb.AppendLine("\t{");

				foreach (var dp in cls.Properties)
				{
					sb.AppendLine();
					if (dp.Condition != "true")
					{
						sb.AppendLine($"#if {dp.Condition}");
					}

					sb.AppendLine($"\t\t#region {dp.Name} DependencyProperty");
					sb.AppendLine();

					// CLR property
					sb.AppendLine($"\t\t{dp.Modifier}public {dp.PropertyType} {dp.Name}");
					sb.AppendLine("\t\t{");
					sb.AppendLine($"\t\t\tget {{ return ({dp.PropertyType})this.GetValue({dp.Name}Property); }}");
					sb.AppendLine($"\t\t\tset {{ this.SetValue({dp.Name}Property, value); }}");
					sb.AppendLine("\t\t}");
					sb.AppendLine();

					// Static DP field
					sb.AppendLine($"\t\tpublic static DependencyProperty {dp.Name}Property {{ get ; }} =");
					sb.AppendLine($"\t\t\tDependencyProperty.Register(");
					sb.AppendLine($"\t\t\t\t\"{dp.Name}\",");
					sb.AppendLine($"\t\t\t\ttypeof({dp.PropertyType}),");
					sb.AppendLine($"\t\t\t\ttypeof({cls.Name}),");
					sb.AppendLine($"\t\t\t\tnew FrameworkPropertyMetadata(");
					sb.AppendLine($"\t\t\t\t\tdefaultValue: ({dp.PropertyType}){dp.DefaultValue},");
					sb.AppendLine($"\t\t\t\t\toptions: FrameworkPropertyMetadataOptions.{dp.FrameworkPropertyOption},");
					sb.AppendLine($"\t\t\t\t\tpropertyChangedCallback: (s, e) => (({cls.Name})s)?.On{dp.Name}Changed(({dp.PropertyType})e.OldValue, ({dp.PropertyType})e.NewValue)");
					sb.AppendLine($"\t\t\t\t)");
					sb.AppendLine($"\t\t\t);");
					sb.AppendLine();

					// OnChanged virtual method
					sb.AppendLine($"\t\tprotected virtual void On{dp.Name}Changed({dp.PropertyType} old{dp.Name}, {dp.PropertyType} new{dp.Name})");
					sb.AppendLine("\t\t{");
					sb.AppendLine($"\t\t\tOn{dp.Name}ChangedPartial(old{dp.Name}, new{dp.Name});");
					sb.AppendLine($"\t\t\tOn{dp.Name}ChangedPartialNative(old{dp.Name}, new{dp.Name});");
					sb.AppendLine("\t\t}");
					sb.AppendLine();

					// Partial methods
					sb.AppendLine($"\t\tpartial void On{dp.Name}ChangedPartial({dp.PropertyType} old{dp.Name}, {dp.PropertyType} new{dp.Name});");
					sb.AppendLine($"\t\tpartial void On{dp.Name}ChangedPartialNative({dp.PropertyType} old{dp.Name}, {dp.PropertyType} new{dp.Name});");
					sb.AppendLine();
					sb.AppendLine($"\t\t#endregion");

					if (dp.Condition != "true")
					{
						sb.AppendLine("#endif");
					}
				}

				sb.AppendLine("\t}");
				sb.AppendLine();
				if (cls.Condition != "true")
				{
					sb.AppendLine("#endif");
				}
			}

			sb.AppendLine("}");
		}

		sb.AppendLine();
		sb.AppendLine("#endif // UNO_MIXIN_GENERATION");

		return sb.ToString();
	}

	private const string Header = @"// <auto-generated>
// This file was generated by DependencyPropertyMixinGenerator. Do not edit manually.
// </auto-generated>

using System;
using System.Linq;
using System.Drawing;
using System.Collections;
using System.Collections.Generic;
using System.Windows.Input;
using Uno.Disposables;
using System.Runtime.CompilerServices;
using Uno.Extensions;
using Uno.Foundation.Logging;
using Uno.UI;
using Uno.UI.DataBinding;
using Windows.Foundation;
using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Data;
using Microsoft.UI.Xaml.Media;
using Microsoft.UI.Xaml.Media.Animation;
using Microsoft.UI.Xaml.Controls;
using Microsoft.UI.Xaml.Controls.Primitives;
#if __APPLE_UIKIT__
using Color = UIKit.UIColor;
using View = UIKit.UIView;
#elif __ANDROID__
using Color = Android.Resource.Color;
using View = Android.Views.View;
#elif IS_UNIT_TESTS || UNO_REFERENCE_API
using Color = System.Object;
using View = Microsoft.UI.Xaml.FrameworkElement;
#endif";

	#region Data Model

	private sealed class NamespaceDefinition
	{
		public string Name { get; }
		public ClassDefinition[] Classes { get; }

		public NamespaceDefinition(string name, ClassDefinition[] classes)
		{
			Name = name;
			Classes = classes;
		}
	}

	private sealed class ClassDefinition
	{
		public string Name { get; }
		public string Condition { get; }
		public string AccessModifier { get; }
		public PropertyDefinition[] Properties { get; }

		public ClassDefinition(string name, string condition, string accessModifier, PropertyDefinition[] properties)
		{
			Name = name;
			Condition = condition;
			AccessModifier = accessModifier;
			Properties = properties;
		}
	}

	private sealed class PropertyDefinition
	{
		public string Name { get; }
		public string PropertyType { get; }
		public string DefaultValue { get; }
		public string Condition { get; }
		public string Modifier { get; }
		public string FrameworkPropertyOption { get; }

		public PropertyDefinition(string name, string propertyType, string defaultValue, string condition = "true", string modifier = "", string frameworkPropertyOption = "None")
		{
			Name = name;
			PropertyType = propertyType;
			DefaultValue = defaultValue;
			Condition = condition;
			Modifier = string.IsNullOrEmpty(modifier) ? "" : modifier + " ";
			FrameworkPropertyOption = frameworkPropertyOption;
		}
	}

	#endregion

	#region Data — mirrors DependencyPropertyMixins.tt

	private static readonly NamespaceDefinition[] Namespaces = new[]
	{
		new NamespaceDefinition("Microsoft.UI.Xaml.Controls", new[]
		{
			new ClassDefinition("Control", "true", "public", new[]
			{
				new PropertyDefinition("HorizontalContentAlignment", "HorizontalAlignment",
					"(Uno.UI.FeatureConfiguration.Control.UseLegacyContentAlignment ? HorizontalAlignment.Left : HorizontalAlignment.Center)",
					frameworkPropertyOption: "AffectsArrange"),
				new PropertyDefinition("VerticalContentAlignment", "VerticalAlignment",
					"(Uno.UI.FeatureConfiguration.Control.UseLegacyContentAlignment ? VerticalAlignment.Top : VerticalAlignment.Center)",
					frameworkPropertyOption: "AffectsArrange"),
			}),
			new ClassDefinition("Picker", "__IOS__", "public", new[]
			{
				new PropertyDefinition("ItemsSource", "object", "null"),
				new PropertyDefinition("SelectedItem", "object", "null"),
				new PropertyDefinition("SelectedIndex", "int", "-1"),
				new PropertyDefinition("ItemTemplate", "DataTemplate", "null", frameworkPropertyOption: "ValueDoesNotInheritDataContext"),
				new PropertyDefinition("ItemContainerStyle", "Style", "null", frameworkPropertyOption: "ValueDoesNotInheritDataContext"),
				new PropertyDefinition("ItemTemplateSelector", "DataTemplateSelector", "null"),
				new PropertyDefinition("DisplayMemberPath", "string", "string.Empty"), // TODO: Move to ItemsControl
				new PropertyDefinition("Placeholder", "object", "null"),
			}),
			new ClassDefinition("ComboBox", "true", "public", new[]
			{
				new PropertyDefinition("PlaceholderText", "string", "string.Empty"),
				new PropertyDefinition("MaxDropDownHeight", "double", "double.PositiveInfinity"),
			}),
			new ClassDefinition("ItemsControl", "true", "public", new[]
			{
				new PropertyDefinition("DisplayMemberPath", "string", "string.Empty"),
			}),
			new ClassDefinition("ListViewBase", "true", "public", new[]
			{
				new PropertyDefinition("Header", "object", "null"),
				new PropertyDefinition("HeaderTemplate", "DataTemplate", "null", frameworkPropertyOption: "ValueDoesNotInheritDataContext"),
				new PropertyDefinition("Footer", "object", "null"),
				new PropertyDefinition("FooterTemplate", "DataTemplate", "null", frameworkPropertyOption: "ValueDoesNotInheritDataContext"),
				new PropertyDefinition("SelectionMode", "ListViewSelectionMode", "ListViewSelectionMode.Single"),
				new PropertyDefinition("IsItemClickEnabled", "bool", "false"),
				new PropertyDefinition("DataFetchSize", "double", "3d"),
				new PropertyDefinition("IncrementalLoadingThreshold", "double", "0d"),
				new PropertyDefinition("IncrementalLoadingTrigger", "IncrementalLoadingTrigger", "IncrementalLoadingTrigger.Edge"),
			}),
			// https://msdn.microsoft.com/library/windows/apps/windows.ui.xaml.controls.itemsstackpanel.aspx
			new ClassDefinition("ItemsStackPanel", "true", "public", new[]
			{
				new PropertyDefinition("AreStickyGroupHeadersEnabled", "bool", "true"),
				new PropertyDefinition("GroupHeaderPlacement", "GroupHeaderPlacement", "GroupHeaderPlacement.Top"),
				new PropertyDefinition("GroupPadding", "Thickness", "Thickness.Empty"),
				new PropertyDefinition("Orientation", "Orientation", "Orientation.Vertical"),
				new PropertyDefinition("CacheLength", "double", "4.0", condition: "__ANDROID__"),
			}),
			// https://msdn.microsoft.com/library/windows/apps/windows.ui.xaml.controls.itemswrapgrid.aspx
			new ClassDefinition("ItemsWrapGrid", "true", "public", new[]
			{
				new PropertyDefinition("AreStickyGroupHeadersEnabled", "bool", "true"),
				new PropertyDefinition("GroupHeaderPlacement", "GroupHeaderPlacement", "GroupHeaderPlacement.Top"),
				new PropertyDefinition("GroupPadding", "Thickness", "Thickness.Empty"),
				new PropertyDefinition("ItemHeight", "double", "Double.NaN"),
				new PropertyDefinition("ItemWidth", "double", "Double.NaN"),
				new PropertyDefinition("Orientation", "Orientation", "Orientation.Vertical"),
				new PropertyDefinition("MaximumRowsOrColumns", "int", "-1"),
				new PropertyDefinition("CacheLength", "double", "4.0", condition: "__ANDROID__"),
			}),
			new ClassDefinition("VirtualizingPanelLayout", "true", "public", new[]
			{
				new PropertyDefinition("AreStickyGroupHeadersEnabled", "bool", "true"),
				new PropertyDefinition("GroupHeaderPlacement", "GroupHeaderPlacement", "GroupHeaderPlacement.Top"),
				new PropertyDefinition("GroupPadding", "Thickness", "Thickness.Empty"),
				new PropertyDefinition("CacheLength", "double", "4.0"),
			}),
			new ClassDefinition("ItemsWrapGridLayout", "true", "internal", new[]
			{
				new PropertyDefinition("ItemHeight", "double", "Double.NaN"),
				new PropertyDefinition("ItemWidth", "double", "Double.NaN"),
				new PropertyDefinition("MaximumRowsOrColumns", "int", "-1"),
			}),
			new ClassDefinition("DatePickerSelector", "true", "public", new[]
			{
				new PropertyDefinition("Date", "DateTimeOffset", "DateTimeOffset.MinValue"),
				new PropertyDefinition("DayVisible", "bool", "true"),
				new PropertyDefinition("MonthVisible", "bool", "true"),
				new PropertyDefinition("YearVisible", "bool", "true"),
				new PropertyDefinition("MaxYear", "DateTimeOffset", "DateTimeOffset.MaxValue"),
				new PropertyDefinition("MinYear", "DateTimeOffset", "DateTimeOffset.MinValue"),
			}),
			new ClassDefinition("DatePickerFlyout", "true", "public", new[]
			{
				new PropertyDefinition("DayVisible", "bool", "true"),
				new PropertyDefinition("MonthVisible", "bool", "true"),
				new PropertyDefinition("YearVisible", "bool", "true"),
			}),
			new ClassDefinition("TimePickerSelector", "true", "public", new[]
			{
				new PropertyDefinition("Time", "TimeSpan", "DateTime.Now.TimeOfDay"),
				new PropertyDefinition("MinuteIncrement", "int", "1"),
				new PropertyDefinition("ClockIdentifier", "string", "global::Windows.Globalization.ClockIdentifiers.TwelveHour"),
			}),
		}),
		new NamespaceDefinition("Microsoft.UI.Xaml.Controls.Primitives", new[]
		{
			new ClassDefinition("SelectorItem", "true", "public", new[]
			{
				new PropertyDefinition("IsSelected", "bool", "false"),
			}),
			new ClassDefinition("Popup", "true", "public", new[]
			{
				new PropertyDefinition("IsOpen", "bool", "false"),
				new PropertyDefinition("Child", "UIElement", "null", frameworkPropertyOption: "ValueInheritsDataContext"),
				new PropertyDefinition("IsLightDismissEnabled", "bool", "false"),
			}),
		}),
		new NamespaceDefinition("Uno.UI.Controls.Legacy", new[]
		{
			new ClassDefinition("ListViewBase", "__APPLE_UIKIT__", "public", new[]
			{
				new PropertyDefinition("DisplayMemberPath", "string", "string.Empty"),
			}),
			new ClassDefinition("ListView", "__ANDROID__", "public", new[]
			{
				new PropertyDefinition("DisplayMemberPath", "string", "string.Empty"),
			}),
			new ClassDefinition("HorizontalListView", "__ANDROID__", "public", new[]
			{
				new PropertyDefinition("DisplayMemberPath", "string", "string.Empty"),
			}),
			new ClassDefinition("GridView", "__ANDROID__", "public", new[]
			{
				new PropertyDefinition("DisplayMemberPath", "string", "string.Empty"),
			}),
			new ClassDefinition("HorizontalGridView", "__ANDROID__", "public", new[]
			{
				new PropertyDefinition("DisplayMemberPath", "string", "string.Empty"),
			}),
		}),
		// The T4 ends with .Namespace("Microsoft.UI.Xaml.Controls.Primitives") which is empty — a no-op from the builder
	};

	#endregion
}
