#nullable disable


namespace Windows.Devices.Bluetooth
{
	// using order/valus from
	// https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.bluetoothminorclass?view=winrt-19041
	// (not from Generated)

	public enum BluetoothMinorClass 
	{
		NetworkFullyAvailable = 0,
		Uncategorized = 0,
		AudioVideoWearableHeadset = 1,
		ComputerDesktop = 1,
		HealthBloodPressureMonitor = 1,
		PeripheralJoystick = 1,
		PhoneCellular = 1,
		ToyRobot = 1,
		WearableWristwatch = 1,
		AudioVideoHandsFree = 2,
		ComputerServer = 2,
		HealthThermometer = 2,
		PeripheralGamepad = 2,
		PhoneCordless = 2,
		ToyVehicle = 2,
		WearablePager = 2,
		ComputerLaptop = 3,
		HealthWeighingScale = 3,
		PeripheralRemoteControl = 3,
		PhoneSmartPhone = 3,
		ToyDoll = 3,
		WearableJacket = 3,
		AudioVideoMicrophone = 4,
		ComputerHandheld = 4,
		HealthGlucoseMeter = 4,
		PeripheralSensing = 4,
		PhoneWired = 4,
		ToyController = 4,
		WearableHelmet = 4,
		AudioVideoLoudspeaker = 5,
		ComputerPalmSize = 5,
		HealthPulseOximeter = 5,
		PeripheralDigitizerTablet = 5,
		PhoneIsdn = 5,
		ToyGame = 5,
		WearableGlasses = 5,
		AudioVideoHeadphones = 6,
		ComputerWearable = 6,
		HealthHeartRateMonitor = 6,
		PeripheralCardReader = 6,
		AudioVideoPortableAudio = 7,
		ComputerTablet = 7,
		HealthHealthDataDisplay = 7,
		PeripheralDigitalPen = 7,
		AudioVideoCarAudio = 8,
		HealthStepCounter = 8,
		NetworkUsed01To17Percent = 8,
		PeripheralHandheldScanner = 8,
		AudioVideoSetTopBox = 9,
		HealthBodyCompositionAnalyzer = 9,
		PeripheralHandheldGesture = 9,
		AudioVideoHifiAudioDevice = 10,
		HealthPeakFlowMonitor = 10,
		AudioVideoVcr = 11,
		HealthMedicationMonitor = 11,
		AudioVideoVideoCamera = 12,
		HealthKneeProsthesis = 12,
		AudioVideoCamcorder = 13,
		HealthAnkleProsthesis = 13,
		AudioVideoVideoMonitor = 14,
		HealthGenericHealthManager = 14,
		AudioVideoVideoDisplayAndLoudspeaker = 15,
		HealthPersonalMobilityDevice = 15,
		AudioVideoVideoConferencing = 16,
		NetworkUsed17To33Percent = 16,
		AudioVideoGamingOrToy = 18,
		NetworkUsed33To50Percent = 24,
		NetworkUsed50To67Percent = 32,
		NetworkUsed67To83Percent = 40,
		NetworkUsed83To99Percent = 48,
		NetworkNoServiceAvailable = 56,
	}

}
