<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>$(NetSkiaPreviousAndCurrent)</TargetFrameworks>
	</PropertyGroup>

	<Import Project="../../targetframework-override-noplatform.props" />

    <PropertyGroup>
		<AssemblyName>Uno.UI.MediaPlayer.Skia.X11</AssemblyName>
		<RootNamespace>Uno.UI.MediaPlayer.Skia.X11</RootNamespace>


		<GeneratePackageOnBuild Condition="'$(Configuration)'=='Release'">true</GeneratePackageOnBuild>
		<PackageId>Uno.WinUI.MediaPlayer.X11</PackageId>
		<Description>This package provides support for MediaPlayerElement for Uno Platform X11 apps</Description>

		<UnoRuntimeVariant>Generic</UnoRuntimeVariant>
		<PlatformItemsBasePath>.\</PlatformItemsBasePath>
		<UseCommonOverridePackage>true</UseCommonOverridePackage>
    </PropertyGroup>

	<PropertyGroup>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="LibVLCSharp" />
		<PackageReference Include="Uno.Core.Extensions.Logging" />
		<PackageReference Include="Uno.Core.Extensions.Logging.Singleton" />
		
		<ProjectReference Include="..\..\Uno.UI.Runtime.Skia.X11\Uno.UI.Runtime.Skia.X11.csproj" />
		<ProjectReference Include="..\..\Uno.UI\Uno.UI.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\..\Common\uno.png" Pack="true" PackagePath="\" Visible="false"/>
		<EmbeddedResource Include="$(MSBuildThisFileDirectory)Assets\libvlc_init_sample.mp4" />
	</ItemGroup>
</Project>
