<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>$(NetPrevious);$(NetCurrent)</TargetFrameworks>
	</PropertyGroup>

	<Import Project="../targetframework-override-noplatform.props" />

	<PropertyGroup>
		<WindowsAppSdkFoundationVersion>2.3.5</WindowsAppSdkFoundationVersion>
		<WindowsSdkNetRefVersion>10.0.26100.57</WindowsSdkNetRefVersion>
		<PkgMicrosoft_WindowsAppSDK_Foundation Condition="'$(PkgMicrosoft_WindowsAppSDK_Foundation)' == ''">$(NuGetPackageRoot)microsoft.windowsappsdk.foundation\$(WindowsAppSdkFoundationVersion)</PkgMicrosoft_WindowsAppSDK_Foundation>
		<PkgMicrosoft_Windows_SDK_NET_Ref Condition="'$(PkgMicrosoft_Windows_SDK_NET_Ref)' == ''">$(NuGetPackageRoot)microsoft.windows.sdk.net.ref\$(WindowsSdkNetRefVersion)</PkgMicrosoft_Windows_SDK_NET_Ref>
		<GeneratePackageOnBuild Condition="'$(Configuration)'=='Release'">true</GeneratePackageOnBuild>
		<Description>This package provides the platform support for Skia in Uno Platform projects.</Description>

		<PackageId>Uno.WinUI.Runtime.Skia.Win32</PackageId>

		<UseCommonOverridePackage>true</UseCommonOverridePackage>

		<!-- Ignore NU5104 for net7.0 System.Drawing.Common -->
		<NoWarn>$(NoWarn);NU5104</NoWarn>

		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\Common\uno.png" Pack="true" PackagePath="\" Visible="false" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Web.WebView2" Aliases="mswebview2" PrivateAssets="all" />

		<PackageReference Include="Microsoft.Windows.CsWin32" Version="0.3.106" />
		<PackageReference Include="Microsoft.WindowsAppSDK.Foundation" Version="$(WindowsAppSdkFoundationVersion)" PrivateAssets="all" ExcludeAssets="all" GeneratePathProperty="true" />
		<PackageReference Include="Microsoft.WindowsAppSDK.InteractiveExperiences" Version="2.1.3" PrivateAssets="all" ExcludeAssets="all" />
		<PackageReference Include="Microsoft.Windows.SDK.NET.Ref" Version="$(WindowsSdkNetRefVersion)" PrivateAssets="all" ExcludeAssets="all" GeneratePathProperty="true" />
		<PackageReference Include="HarfBuzzSharp" />
		<PackageReference Include="Uno.icu-win" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="Microsoft.Windows.AppNotifications.Projection" HintPath="$(PkgMicrosoft_WindowsAppSDK_Foundation)\lib\net6.0-windows10.0.17763.0\Microsoft.Windows.AppNotifications.Projection.dll" Aliases="winappsdk" Private="true" />
		<Reference Include="Microsoft.WindowsAppRuntime.Bootstrap.Net" HintPath="$(PkgMicrosoft_WindowsAppSDK_Foundation)\lib\net6.0-windows10.0.17763.0\Microsoft.WindowsAppRuntime.Bootstrap.Net.dll" Aliases="winappsdk" Private="true" />
		<Reference Include="Microsoft.Windows.SDK.NET" HintPath="$(PkgMicrosoft_Windows_SDK_NET_Ref)\lib\net8.0\Microsoft.Windows.SDK.NET.dll" Aliases="winappsdk" Private="true" />
		<Reference Include="WinRT.Runtime" HintPath="$(PkgMicrosoft_Windows_SDK_NET_Ref)\lib\net8.0\WinRT.Runtime.dll" Aliases="winappsdk" Private="true" />
	</ItemGroup>

	<ItemGroup>
		<None Include="$(PkgMicrosoft_WindowsAppSDK_Foundation)\runtimes\win-x64\native\Microsoft.WindowsAppRuntime.Bootstrap.dll" Link="runtimes\win-x64\native\Microsoft.WindowsAppRuntime.Bootstrap.dll" CopyToOutputDirectory="PreserveNewest" Pack="true" PackagePath="runtimes\win-x64\native" />
		<None Include="$(PkgMicrosoft_WindowsAppSDK_Foundation)\runtimes\win-x86\native\Microsoft.WindowsAppRuntime.Bootstrap.dll" Link="runtimes\win-x86\native\Microsoft.WindowsAppRuntime.Bootstrap.dll" Pack="true" PackagePath="runtimes\win-x86\native" />
		<None Include="$(PkgMicrosoft_WindowsAppSDK_Foundation)\runtimes\win-arm64\native\Microsoft.WindowsAppRuntime.Bootstrap.dll" Link="runtimes\win-arm64\native\Microsoft.WindowsAppRuntime.Bootstrap.dll" Pack="true" PackagePath="runtimes\win-arm64\native" />
		<None Include="$(PkgMicrosoft_WindowsAppSDK_Foundation)\metadata\Microsoft.Windows.AppNotifications.winmd" Pack="true" PackagePath="runtimes\win\native" />
		<None Include="$(PkgMicrosoft_WindowsAppSDK_Foundation)\lib\net6.0-windows10.0.17763.0\Microsoft.Windows.AppNotifications.Projection.dll" Pack="true" PackagePath="runtimes\win\lib\$(NetPrevious)" />
		<None Include="$(PkgMicrosoft_Windows_SDK_NET_Ref)\lib\net8.0\Microsoft.Windows.SDK.NET.dll" Pack="true" PackagePath="runtimes\win\lib\$(NetPrevious)" />
		<None Include="$(PkgMicrosoft_Windows_SDK_NET_Ref)\lib\net8.0\WinRT.Runtime.dll" Pack="true" PackagePath="runtimes\win\lib\$(NetPrevious)" />
		<None Include="$(PkgMicrosoft_WindowsAppSDK_Foundation)\lib\net6.0-windows10.0.17763.0\Microsoft.WindowsAppRuntime.Bootstrap.Net.dll" Pack="true" PackagePath="runtimes\win\lib\$(NetPrevious)" />
		<None Include="$(PkgMicrosoft_WindowsAppSDK_Foundation)\lib\net6.0-windows10.0.17763.0\Microsoft.Windows.AppNotifications.Projection.dll" Pack="true" PackagePath="runtimes\win\lib\$(NetCurrent)" />
		<None Include="$(PkgMicrosoft_Windows_SDK_NET_Ref)\lib\net8.0\Microsoft.Windows.SDK.NET.dll" Pack="true" PackagePath="runtimes\win\lib\$(NetCurrent)" />
		<None Include="$(PkgMicrosoft_Windows_SDK_NET_Ref)\lib\net8.0\WinRT.Runtime.dll" Pack="true" PackagePath="runtimes\win\lib\$(NetCurrent)" />
		<None Include="$(PkgMicrosoft_WindowsAppSDK_Foundation)\lib\net6.0-windows10.0.17763.0\Microsoft.WindowsAppRuntime.Bootstrap.Net.dll" Pack="true" PackagePath="runtimes\win\lib\$(NetCurrent)" />
	</ItemGroup>

	<ItemGroup Condition="$([MSBuild]::IsTargetFrameworkCompatible($(TargetFramework), 'net10.0'))">
		<PackageReference Include="WebView2Aot" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.BannedApiAnalyzers" Version="3.3.4" PrivateAssets="All" />
		<AdditionalFiles Include="$(MSBuildThisFileDirectory)BannedSymbols.txt" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Uno.Foundation\Uno.Foundation.Skia.csproj" />
		<ProjectReference Include="..\Uno.UI.Runtime.Skia.Win32.Support\Uno.UI.Runtime.Skia.Win32.Support.csproj" PrivateAssets="all" />
		<ProjectReference Include="..\Uno.UI.Runtime.Skia\Uno.UI.Runtime.Skia.csproj" />
		<ProjectReference Include="..\Uno.UI\Uno.UI.Skia.csproj" />
		<ProjectReference Include="..\Uno.UWP\Uno.Skia.csproj" TreatAsPackageReference="false" PrivateAssets="all" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="buildTransitive/*.*">
			<Pack>true</Pack>
			<PackagePath>buildTransitive</PackagePath>
		</Content>
	</ItemGroup>

	<Target Name="_UnoUpdateAdditionalAssemblies" AfterTargets="DispatchToInnerBuilds">
		<ItemGroup>
			<Content Include="../Uno.UI.Runtime.Skia.Win32.Support/bin/$(Configuration)/$(NetPrevious)/*.dll">
				<Pack>true</Pack>
				<PackagePath>lib/$(NetPrevious)</PackagePath>
			</Content>
			<Content Include="../Uno.UI.Runtime.Skia.Win32.Support/bin/$(Configuration)/$(NetPrevious)/*.pdb">
				<Pack>true</Pack>
				<PackagePath>lib/$(NetPrevious)</PackagePath>
			</Content>
			<Content Include="../Uno.UI.Runtime.Skia.Win32.Support/bin/$(Configuration)/$(NetCurrent)/*.dll">
				<Pack>true</Pack>
				<PackagePath>lib/$(NetCurrent)</PackagePath>
			</Content>
			<Content Include="../Uno.UI.Runtime.Skia.Win32.Support/bin/$(Configuration)/$(NetCurrent)/*.pdb">
				<Pack>true</Pack>
				<PackagePath>lib/$(NetCurrent)</PackagePath>
			</Content>
		</ItemGroup>
	</Target>

</Project>
