// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.

// DO NOT EDIT! This file was generated by CustomTasks.DependencyPropertyCodeGen
#pragma once

class RatingItemImageInfoProperties
{
public:
    RatingItemImageInfoProperties();

    void DisabledImage(ImageSource & value);
    ImageSource DisabledImage();

    void Image(ImageSource & value);
    ImageSource Image();

    void PlaceholderImage(ImageSource & value);
    ImageSource PlaceholderImage();

    void PointerOverImage(ImageSource & value);
    ImageSource PointerOverImage();

    void PointerOverPlaceholderImage(ImageSource & value);
    ImageSource PointerOverPlaceholderImage();

    void UnsetImage(ImageSource & value);
    ImageSource UnsetImage();

    static DependencyProperty DisabledImageProperty() { return s_DisabledImageProperty; }
    static DependencyProperty ImageProperty() { return s_ImageProperty; }
    static DependencyProperty PlaceholderImageProperty() { return s_PlaceholderImageProperty; }
    static DependencyProperty PointerOverImageProperty() { return s_PointerOverImageProperty; }
    static DependencyProperty PointerOverPlaceholderImageProperty() { return s_PointerOverPlaceholderImageProperty; }
    static DependencyProperty UnsetImageProperty() { return s_UnsetImageProperty; }

    static GlobalDependencyProperty s_DisabledImageProperty;
    static GlobalDependencyProperty s_ImageProperty;
    static GlobalDependencyProperty s_PlaceholderImageProperty;
    static GlobalDependencyProperty s_PointerOverImageProperty;
    static GlobalDependencyProperty s_PointerOverPlaceholderImageProperty;
    static GlobalDependencyProperty s_UnsetImageProperty;

    static void EnsureProperties();
    static void ClearProperties();
};
