// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.

// DO NOT EDIT! This file was generated by CustomTasks.DependencyPropertyCodeGen
#pragma once

class RatingItemFontInfoProperties
{
public:
    RatingItemFontInfoProperties();

    void DisabledGlyph(hstring & value);
    hstring DisabledGlyph();

    void Glyph(hstring & value);
    hstring Glyph();

    void PlaceholderGlyph(hstring & value);
    hstring PlaceholderGlyph();

    void PointerOverGlyph(hstring & value);
    hstring PointerOverGlyph();

    void PointerOverPlaceholderGlyph(hstring & value);
    hstring PointerOverPlaceholderGlyph();

    void UnsetGlyph(hstring & value);
    hstring UnsetGlyph();

    static DependencyProperty DisabledGlyphProperty() { return s_DisabledGlyphProperty; }
    static DependencyProperty GlyphProperty() { return s_GlyphProperty; }
    static DependencyProperty PlaceholderGlyphProperty() { return s_PlaceholderGlyphProperty; }
    static DependencyProperty PointerOverGlyphProperty() { return s_PointerOverGlyphProperty; }
    static DependencyProperty PointerOverPlaceholderGlyphProperty() { return s_PointerOverPlaceholderGlyphProperty; }
    static DependencyProperty UnsetGlyphProperty() { return s_UnsetGlyphProperty; }

    static GlobalDependencyProperty s_DisabledGlyphProperty;
    static GlobalDependencyProperty s_GlyphProperty;
    static GlobalDependencyProperty s_PlaceholderGlyphProperty;
    static GlobalDependencyProperty s_PointerOverGlyphProperty;
    static GlobalDependencyProperty s_PointerOverPlaceholderGlyphProperty;
    static GlobalDependencyProperty s_UnsetGlyphProperty;

    static void EnsureProperties();
    static void ClearProperties();
};
