using static Uno.UI.SourceGenerators.Tests.DependencyPropertyGeneratorTests.DependencyPropertyGeneratorHarness;

namespace Uno.UI.SourceGenerators.Tests.DependencyPropertyGeneratorTests;

/// <summary>
/// Golden-output tests for representative scenarios; focused behavior is covered by the other partial files.
/// </summary>
[TestClass]
public partial class Given_DependencyPropertyGenerator
{
	private const string HintName = "Mynamespace.C.g.cs";

	[TestMethod]
	public async Task When_Instance_Properties()
	{
		var run = await RunAsync(
			"""
			using Microsoft.UI.Xaml;
			using TestHelpers;
			using Uno.UI.Xaml;

			namespace Mynamespace
			{
				public partial class C : TestDependencyObject
				{
					[GeneratedDependencyProperty(DefaultValue = 21, ChangedCallback = true, Options = FrameworkPropertyMetadataOptions.AffectsMeasure)]
					public partial int MyValue { get; set; }

					[GeneratedDependencyProperty(LocalCache = false)]
					internal partial string Text { get; private set; }

					private void OnMyValueChanged(int oldValue, int newValue)
					{
					}
				}
			}
			""");

		run.ShouldSucceed().ShouldGenerate(
			HintName,
			"""
			// <auto-generated/>
			#nullable disable

			namespace Mynamespace
			{
				partial class C
				{
					private uint __generatedDependencyPropertyFlags0;

					public static global::Microsoft.UI.Xaml.DependencyProperty MyValueProperty { get; } = CreateMyValueProperty();

					public partial int MyValue
					{
						get
						{
							if ((__generatedDependencyPropertyFlags0 & (1u << 0)) == 0)
							{
								__MyValuePropertyBackingField = (int)GetValue(MyValueProperty);
								__generatedDependencyPropertyFlags0 |= (1u << 0);
							}

							return __MyValuePropertyBackingField;
						}
						set => SetValue(MyValueProperty, value);
					}

					private int __MyValuePropertyBackingField;

					private static global::Microsoft.UI.Xaml.DependencyProperty CreateMyValueProperty()
						=> global::Microsoft.UI.Xaml.DependencyProperty.Register(
							"MyValue",
							typeof(int),
							typeof(global::Mynamespace.C),
							new global::Microsoft.UI.Xaml.FrameworkPropertyMetadata(
								defaultValue: 21,
								options: global::Microsoft.UI.Xaml.FrameworkPropertyMetadataOptions.AffectsMeasure,
								propertyChangedCallback: static (instance, args) => ((global::Mynamespace.C)instance).OnMyValueChanged((int)args.OldValue, (int)args.NewValue),
								coerceValueCallback: null,
								backingFieldUpdateCallback: OnMyValueBackingFieldUpdate));

					private static void OnMyValueBackingFieldUpdate(global::Microsoft.UI.Xaml.DependencyObject instance, object newValue)
					{
						var typedInstance = (global::Mynamespace.C)instance;
						typedInstance.__MyValuePropertyBackingField = (int)newValue;
						typedInstance.__generatedDependencyPropertyFlags0 |= (1u << 0);
					}

					internal static global::Microsoft.UI.Xaml.DependencyProperty TextProperty { get; } = CreateTextProperty();

					internal partial string Text
					{
						get => (string)GetValue(TextProperty);
						private set => SetValue(TextProperty, value);
					}

					private static global::Microsoft.UI.Xaml.DependencyProperty CreateTextProperty()
						=> global::Microsoft.UI.Xaml.DependencyProperty.Register(
							"Text",
							typeof(string),
							typeof(global::Mynamespace.C),
							new global::Microsoft.UI.Xaml.FrameworkPropertyMetadata(
								defaultValue: null,
								options: global::Microsoft.UI.Xaml.FrameworkPropertyMetadataOptions.None,
								propertyChangedCallback: null,
								coerceValueCallback: null,
								backingFieldUpdateCallback: null));
				}
			}

			""");
	}

	[TestMethod]
	public async Task When_Attached_Property_With_Backing_Field_Owner()
	{
		var run = await RunAsync(
			"""
			using Microsoft.UI.Xaml;
			using TestHelpers;
			using Uno.UI.Xaml;

			namespace Owners
			{
				public partial class Owner : TestDependencyObject
				{
				}
			}

			namespace Mynamespace
			{
				public static partial class C
				{
					[GeneratedDependencyProperty(DefaultValue = 21, AttachedBackingFieldOwner = typeof(Owners.Owner))]
					public static partial int GetMyValue(DependencyObject instance);

					public static partial void SetMyValue(DependencyObject instance, int value);

					private static void OnMyValueChanged(DependencyObject instance, DependencyPropertyChangedEventArgs args)
					{
					}
				}
			}
			""");

		run.ShouldSucceed().ShouldGenerate(
			HintName,
			"""
			// <auto-generated/>
			#nullable disable

			namespace Mynamespace
			{
				partial class C
				{
					public static global::Microsoft.UI.Xaml.DependencyProperty MyValueProperty { get; } = CreateMyValueProperty();

					public static partial int GetMyValue(global::Microsoft.UI.Xaml.DependencyObject instance) => GetMyValueValue(instance);

					public static partial void SetMyValue(global::Microsoft.UI.Xaml.DependencyObject instance, int value) => SetMyValueValue(instance, value);

					private static int GetMyValueValue(global::Microsoft.UI.Xaml.DependencyObject instance)
					{
						if (instance is global::Owners.Owner backingFieldOwner)
						{
							if (!backingFieldOwner.__Mynamespace_C_MyValuePropertyBackingFieldSet)
							{
								backingFieldOwner.__Mynamespace_C_MyValuePropertyBackingField = (int)instance.GetValue(MyValueProperty);
								backingFieldOwner.__Mynamespace_C_MyValuePropertyBackingFieldSet = true;
							}

							return backingFieldOwner.__Mynamespace_C_MyValuePropertyBackingField;
						}

						return (int)instance.GetValue(MyValueProperty);
					}

					private static void SetMyValueValue(global::Microsoft.UI.Xaml.DependencyObject instance, int value) => instance.SetValue(MyValueProperty, value);

					private static global::Microsoft.UI.Xaml.DependencyProperty CreateMyValueProperty()
						=> global::Microsoft.UI.Xaml.DependencyProperty.RegisterAttached(
							"MyValue",
							typeof(int),
							typeof(global::Mynamespace.C),
							new global::Microsoft.UI.Xaml.FrameworkPropertyMetadata(
								defaultValue: 21,
								options: global::Microsoft.UI.Xaml.FrameworkPropertyMetadataOptions.None,
								propertyChangedCallback: static (instance, args) => global::Mynamespace.C.OnMyValueChanged(instance, args),
								coerceValueCallback: null,
								backingFieldUpdateCallback: OnMyValueBackingFieldUpdate));

					private static void OnMyValueBackingFieldUpdate(global::Microsoft.UI.Xaml.DependencyObject instance, object newValue)
					{
						if (instance is global::Owners.Owner backingFieldOwner)
						{
							backingFieldOwner.__Mynamespace_C_MyValuePropertyBackingField = (int)newValue;
							backingFieldOwner.__Mynamespace_C_MyValuePropertyBackingFieldSet = true;
						}
					}
				}
			}

			namespace Owners
			{
				partial class Owner
				{
					internal int __Mynamespace_C_MyValuePropertyBackingField;
					internal bool __Mynamespace_C_MyValuePropertyBackingFieldSet;
				}
			}

			""");
	}

	[TestMethod]
	public async Task When_Boxes_Is_Accessible()
	{
		var run = await RunWithBoxesAsync(
			"""
			using Microsoft.UI.Xaml;
			using TestHelpers;
			using Uno.UI.Xaml;

			namespace Mynamespace
			{
				public partial class C : TestDependencyObject
				{
					[GeneratedDependencyProperty(DefaultValue = true)]
					public partial bool IsOn { get; set; }

					[GeneratedDependencyProperty]
					public partial double Size { get; set; }
				}
			}
			""");

		run.ShouldSucceed().ShouldGenerate(
			HintName,
			"""
			// <auto-generated/>
			#nullable disable

			namespace Mynamespace
			{
				partial class C
				{
					private uint __generatedDependencyPropertyFlags0;

					public static global::Microsoft.UI.Xaml.DependencyProperty IsOnProperty { get; } = CreateIsOnProperty();

					public partial bool IsOn
					{
						get
						{
							if ((__generatedDependencyPropertyFlags0 & (1u << 0)) == 0)
							{
								if ((bool)GetValue(IsOnProperty))
								{
									__generatedDependencyPropertyFlags0 |= (1u << 1);
								}
								else
								{
									__generatedDependencyPropertyFlags0 &= ~(1u << 1);
								}

								__generatedDependencyPropertyFlags0 |= (1u << 0);
							}

							return (__generatedDependencyPropertyFlags0 & (1u << 1)) != 0;
						}
						set => SetValue(IsOnProperty, global::Uno.UI.Helpers.Boxes.Boxer.Box(value));
					}

					private static global::Microsoft.UI.Xaml.DependencyProperty CreateIsOnProperty()
						=> global::Microsoft.UI.Xaml.DependencyProperty.Register(
							"IsOn",
							typeof(bool),
							typeof(global::Mynamespace.C),
							new global::Microsoft.UI.Xaml.FrameworkPropertyMetadata(
								defaultValue: global::Uno.UI.Helpers.Boxes.BoolBoxes.True,
								options: global::Microsoft.UI.Xaml.FrameworkPropertyMetadataOptions.None,
								propertyChangedCallback: null,
								coerceValueCallback: null,
								backingFieldUpdateCallback: OnIsOnBackingFieldUpdate));

					private static void OnIsOnBackingFieldUpdate(global::Microsoft.UI.Xaml.DependencyObject instance, object newValue)
					{
						var typedInstance = (global::Mynamespace.C)instance;
						if ((bool)newValue)
						{
							typedInstance.__generatedDependencyPropertyFlags0 |= (1u << 1);
						}
						else
						{
							typedInstance.__generatedDependencyPropertyFlags0 &= ~(1u << 1);
						}

						typedInstance.__generatedDependencyPropertyFlags0 |= (1u << 0);
					}

					public static global::Microsoft.UI.Xaml.DependencyProperty SizeProperty { get; } = CreateSizeProperty();

					public partial double Size
					{
						get
						{
							if ((__generatedDependencyPropertyFlags0 & (1u << 2)) == 0)
							{
								__SizePropertyBackingField = (double)GetValue(SizeProperty);
								__generatedDependencyPropertyFlags0 |= (1u << 2);
							}

							return __SizePropertyBackingField;
						}
						set => SetValue(SizeProperty, global::Uno.UI.Helpers.Boxes.Boxer.Box(value));
					}

					private double __SizePropertyBackingField;

					private static global::Microsoft.UI.Xaml.DependencyProperty CreateSizeProperty()
						=> global::Microsoft.UI.Xaml.DependencyProperty.Register(
							"Size",
							typeof(double),
							typeof(global::Mynamespace.C),
							new global::Microsoft.UI.Xaml.FrameworkPropertyMetadata(
								defaultValue: global::Uno.UI.Helpers.Boxes.DoubleBoxes.Zero,
								options: global::Microsoft.UI.Xaml.FrameworkPropertyMetadataOptions.None,
								propertyChangedCallback: null,
								coerceValueCallback: null,
								backingFieldUpdateCallback: OnSizeBackingFieldUpdate));

					private static void OnSizeBackingFieldUpdate(global::Microsoft.UI.Xaml.DependencyObject instance, object newValue)
					{
						var typedInstance = (global::Mynamespace.C)instance;
						typedInstance.__SizePropertyBackingField = (double)newValue;
						typedInstance.__generatedDependencyPropertyFlags0 |= (1u << 2);
					}
				}
			}

			""");

		var analyzerDiagnostics = await run.GetGeneratedCodeAnalyzerDiagnosticsAsync("Uno.UI.SourceGenerators.Internal.BoxingDiagnosticAnalyzer");
		analyzerDiagnostics.Should().BeEmpty();
	}

	[TestMethod]
	public async Task When_Explicit_Identifier_Declaration()
	{
		var run = await RunAsync(
			"""
			using Microsoft.UI.Xaml;
			using TestHelpers;
			using Uno.UI.Xaml;

			namespace Mynamespace
			{
				public partial class C : TestDependencyObject
				{
					/// <summary>Identifies the <see cref="MyValue"/> dependency property.</summary>
					internal static partial DependencyProperty MyValueProperty { get; }

					[GeneratedDependencyProperty(LocalCache = false)]
					public partial int MyValue { get; set; }
				}
			}
			""");

		run.ShouldSucceed().ShouldGenerate(
			HintName,
			"""
			// <auto-generated/>
			#nullable disable

			namespace Mynamespace
			{
				partial class C
				{
					private static readonly global::Microsoft.UI.Xaml.DependencyProperty __MyValueProperty = CreateMyValueProperty();

					internal static partial global::Microsoft.UI.Xaml.DependencyProperty MyValueProperty { get => __MyValueProperty; }

					public partial int MyValue
					{
						get => (int)GetValue(MyValueProperty);
						set => SetValue(MyValueProperty, value);
					}

					private static global::Microsoft.UI.Xaml.DependencyProperty CreateMyValueProperty()
						=> global::Microsoft.UI.Xaml.DependencyProperty.Register(
							"MyValue",
							typeof(int),
							typeof(global::Mynamespace.C),
							new global::Microsoft.UI.Xaml.FrameworkPropertyMetadata(
								defaultValue: 0,
								options: global::Microsoft.UI.Xaml.FrameworkPropertyMetadataOptions.None,
								propertyChangedCallback: null,
								coerceValueCallback: null,
								backingFieldUpdateCallback: null));
				}
			}

			""");
	}
}
