//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//       Command:
//           LottieGen -GenerateColorBindings -Language CSharp -Namespace Microsoft.UI.Xaml.Controls.AnimatedVisuals -Public -WinUIVersion 3.0 -InputFile ProgressRingIntdeterminate.json
//       
//       Input file:
//           ProgressRingIntdeterminate.json (14427 bytes created 18:51+02:00 Jul 3 2026)
//       
//       LottieGen source:
//           http://aka.ms/Lottie
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ____________________________________
// |       Object stats       | Count |
// |__________________________|_______|
// | All CompositionObjects   |    39 |
// |--------------------------+-------|
// | Expression animators     |     4 |
// | KeyFrame animators       |     2 |
// | Reference parameters     |     4 |
// | Expression operations    |     8 |
// |--------------------------+-------|
// | Animated brushes         |     2 |
// | Animated gradient stops  |     - |
// | ExpressionAnimations     |     4 |
// | PathKeyFrameAnimations   |     - |
// |--------------------------+-------|
// | ContainerVisuals         |     1 |
// | ShapeVisuals             |     1 |
// |--------------------------+-------|
// | ContainerShapes          |     1 |
// | CompositionSpriteShapes  |     2 |
// |--------------------------+-------|
// | Brushes                  |     2 |
// | Gradient stops           |     - |
// | CompositionVisualSurface |     - |
// ------------------------------------
using Microsoft.Graphics;
using Microsoft.Graphics.Canvas.Geometry;
using Microsoft.UI.Composition;
using System;
using System.Collections.Generic;
using System.Numerics;
using Windows.UI;

namespace Microsoft.UI.Xaml.Controls.AnimatedVisuals
{
    // Name:        pregression-ring
    // Frame rate:  30 fps
    // Frame count: 140
    // Duration:    4666.7 mS
    // _______________________________________________________
    // | Theme property |  Accessor  | Type  | Default value |
    // |________________|____________|_______|_______________|
    // | Background     | Background | Color |   #FFCCCCCC   |
    // | Foreground     | Foreground | Color |   #FF296ACA   |
    // -------------------------------------------------------
    public sealed class ProgressRingIntdeterminate
        : Microsoft.UI.Xaml.Controls.IAnimatedVisualSource
        , Microsoft.UI.Xaml.Controls.IAnimatedVisualSource2
    {
        // Animation duration: 4.667 seconds.
        internal const long c_durationTicks = 46666666;

        // Theme property: Background.
        internal static readonly Color c_themeBackground = Color.FromArgb(0xFF, 0xCC, 0xCC, 0xCC);

        // Theme property: Foreground.
        internal static readonly Color c_themeForeground = Color.FromArgb(0xFF, 0x29, 0x6A, 0xCA);

        CompositionPropertySet _themeProperties;
        Color _themeBackground = c_themeBackground;
        Color _themeForeground = c_themeForeground;

        // Theme properties.
        public Color Background
        {
            get => _themeBackground;
            set
            {
                _themeBackground = value;
                if (_themeProperties != null)
                {
                    _themeProperties.InsertVector4("Background", ColorAsVector4((Color)_themeBackground));
                }
            }
        }

        public Color Foreground
        {
            get => _themeForeground;
            set
            {
                _themeForeground = value;
                if (_themeProperties != null)
                {
                    _themeProperties.InsertVector4("Foreground", ColorAsVector4((Color)_themeForeground));
                }
            }
        }

        static Vector4 ColorAsVector4(Color color) => new Vector4(color.R, color.G, color.B, color.A);

        CompositionPropertySet EnsureThemeProperties(Compositor compositor)
        {
            if (_themeProperties == null)
            {
                _themeProperties = compositor.CreatePropertySet();
                _themeProperties.InsertVector4("Background", ColorAsVector4((Color)Background));
                _themeProperties.InsertVector4("Foreground", ColorAsVector4((Color)Foreground));
            }
            return _themeProperties;
        }

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor)
        {
            object ignored = null;
            return TryCreateAnimatedVisual(compositor, out ignored);
        }

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor, out object diagnostics)
        {
            diagnostics = null;
            EnsureThemeProperties(compositor);

            var res = 
                new ProgressRingIntdeterminate_AnimatedVisual(
                    compositor,
                    _themeProperties
                    );
                res.CreateAnimations();
                return res;
        }

        /// <summary>
        /// Gets the number of frames in the animation.
        /// </summary>
        public double FrameCount => 140d;

        /// <summary>
        /// Gets the frame rate of the animation.
        /// </summary>
        public double Framerate => 30d;

        /// <summary>
        /// Gets the duration of the animation.
        /// </summary>
        public TimeSpan Duration => TimeSpan.FromTicks(46666666);

        /// <summary>
        /// Converts a zero-based frame number to the corresponding progress value denoting the
        /// start of the frame.
        /// </summary>
        public double FrameToProgress(double frameNumber)
        {
            return frameNumber / 140d;
        }

        /// <summary>
        /// Returns a map from marker names to corresponding progress values.
        /// </summary>
        public IReadOnlyDictionary<string, double> Markers =>
            new Dictionary<string, double>
            {
            };

        /// <summary>
        /// Sets the color property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetColorProperty(string propertyName, Color value)
        {
            if (propertyName == "Background")
            {
                _themeBackground = value;
            }
            else if (propertyName == "Foreground")
            {
                _themeForeground = value;
            }
            else
            {
                return;
            }

            if (_themeProperties != null)
            {
                _themeProperties.InsertVector4(propertyName, ColorAsVector4(value));
            }
        }

        /// <summary>
        /// Sets the scalar property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetScalarProperty(string propertyName, double value)
        {
        }

        sealed class ProgressRingIntdeterminate_AnimatedVisual
            : Microsoft.UI.Xaml.Controls.IAnimatedVisual
            , Microsoft.UI.Xaml.Controls.IAnimatedVisual2
        {
            const long c_durationTicks = 46666666;
            readonly Compositor _c;
            readonly ExpressionAnimation _reusableExpressionAnimation;
            readonly CompositionPropertySet _themeProperties;
            AnimationController _animationController_0;
            AnimationController _animationController_1;
            CompositionColorBrush _themeColor_Background;
            CompositionColorBrush _themeColor_Foreground;
            CompositionContainerShape _containerShape;
            CompositionPathGeometry _pathGeometry_1;
            ContainerVisual _root;
            CubicBezierEasingFunction _cubicBezierEasingFunction_0;
            StepEasingFunction _holdThenStepEasingFunction;

            void BindProperty(
                CompositionObject target,
                string animatedPropertyName,
                string expression,
                string referenceParameterName,
                CompositionObject referencedObject)
            {
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = expression;
                _reusableExpressionAnimation.SetReferenceParameter(referenceParameterName, referencedObject);
                target.StartAnimation(animatedPropertyName, _reusableExpressionAnimation);
            }

            ScalarKeyFrameAnimation CreateScalarKeyFrameAnimation(float initialProgress, float initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateScalarKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            CompositionSpriteShape CreateSpriteShape(CompositionGeometry geometry, Matrix3x2 transformMatrix)
            {
                var result = _c.CreateSpriteShape(geometry);
                result.TransformMatrix = transformMatrix;
                return result;
            }

            // - - - Layer aggregator
            // - ShapeGroup: Groupe 1 Offset:<18, 10.75>
            AnimationController AnimationController_0()
            {
                if (_animationController_0 != null) { return _animationController_0; }
                var result = _animationController_0 = _c.CreateAnimationController();
                result.Pause();
                BindProperty(_animationController_0, "Progress", "_.Progress*0.9722222", "_", _root);
                return result;
            }

            // - Layer aggregator
            AnimationController AnimationController_1()
            {
                if (_animationController_1 != null) { return _animationController_1; }
                var result = _animationController_1 = _c.CreateAnimationController();
                result.Pause();
                BindProperty(_animationController_1, "Progress", "_.Progress*0.7777778", "_", _root);
                return result;
            }

            // - - - Layer aggregator
            // - - ShapeGroup: Groupe 1 Offset:<18, 18>
            CanvasGeometry Geometry_0()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.BeginFigure(new Vector2(14.5F, 0F));
                    builder.AddCubicBezier(new Vector2(14.5F, 8.00800037F), new Vector2(8.00800037F, 14.5F), new Vector2(0F, 14.5F));
                    builder.AddCubicBezier(new Vector2(-8.00800037F, 14.5F), new Vector2(-14.5F, 8.00800037F), new Vector2(-14.5F, 0F));
                    builder.AddCubicBezier(new Vector2(-14.5F, -8.00800037F), new Vector2(-8.00800037F, -14.5F), new Vector2(0F, -14.5F));
                    builder.AddCubicBezier(new Vector2(8.00800037F, -14.5F), new Vector2(14.5F, -8.00800037F), new Vector2(14.5F, 0F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Layer aggregator
            // - - ShapeGroup: Groupe 1 Offset:<18, 10.75>
            CanvasGeometry Geometry_1()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.BeginFigure(new Vector2(-14.5F, 7.25F));
                    builder.AddCubicBezier(new Vector2(-14.5F, -0.758000016F), new Vector2(-8.00800037F, -7.25F), new Vector2(0F, -7.25F));
                    builder.AddCubicBezier(new Vector2(8.00800037F, -7.25F), new Vector2(14.5F, -0.758000016F), new Vector2(14.5F, 7.25F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - Layer aggregator
            // ShapeGroup: Groupe 1 Offset:<18, 18>
            // Color bound to theme property value: Background
            CompositionColorBrush ThemeColor_Background()
            {
                if (_themeColor_Background != null) { return _themeColor_Background; }
                var result = _themeColor_Background = _c.CreateColorBrush();
                BindProperty(_themeColor_Background, "Color", "ColorRGB(_theme.Background.W,_theme.Background.X,_theme.Background.Y,_theme.Background.Z)", "_theme", _themeProperties);
                return result;
            }

            // - - Layer aggregator
            // ShapeGroup: Groupe 1 Offset:<18, 10.75>
            // Color bound to theme property value: Foreground
            CompositionColorBrush ThemeColor_Foreground()
            {
                if (_themeColor_Foreground != null) { return _themeColor_Foreground; }
                var result = _themeColor_Foreground = _c.CreateColorBrush();
                BindProperty(_themeColor_Foreground, "Color", "ColorRGB(_theme.Foreground.W,_theme.Foreground.X,_theme.Foreground.Y,_theme.Foreground.Z)", "_theme", _themeProperties);
                return result;
            }

            // Layer aggregator
            CompositionContainerShape ContainerShape()
            {
                if (_containerShape != null) { return _containerShape; }
                var result = _containerShape = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(18F, 18F);
                // ShapeGroup: Groupe 1 Offset:<18, 10.75>
                result.Shapes.Add(SpriteShape_1());
                return result;
            }

            // - Layer aggregator
            // ShapeGroup: Groupe 1 Offset:<18, 18>
            CompositionPathGeometry PathGeometry_0()
            {
                return _c.CreatePathGeometry(new CompositionPath(Geometry_0()));
            }

            // - - Layer aggregator
            // ShapeGroup: Groupe 1 Offset:<18, 10.75>
            CompositionPathGeometry PathGeometry_1()
            {
                if (_pathGeometry_1 != null) { return _pathGeometry_1; }
                var result = _pathGeometry_1 = _c.CreatePathGeometry(new CompositionPath(Geometry_1()));
                return result;
            }

            // Layer aggregator
            // Tracé 1
            CompositionSpriteShape SpriteShape_0()
            {
                // Offset:<18, 18>
                var result = CreateSpriteShape(PathGeometry_0(), new Matrix3x2(1F, 0F, 0F, 1F, 18F, 18F));;
                result.StrokeBrush = ThemeColor_Background();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeStartCap = CompositionStrokeCap.Round;
                result.StrokeEndCap = CompositionStrokeCap.Round;
                result.StrokeMiterLimit = 5F;
                result.StrokeThickness = 3F;
                return result;
            }

            // - Layer aggregator
            // Tracé 1
            CompositionSpriteShape SpriteShape_1()
            {
                // Offset:<18, 10.75>
                var result = CreateSpriteShape(PathGeometry_1(), new Matrix3x2(1F, 0F, 0F, 1F, 18F, 10.75F));;
                result.StrokeBrush = ThemeColor_Foreground();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeStartCap = CompositionStrokeCap.Round;
                result.StrokeEndCap = CompositionStrokeCap.Round;
                result.StrokeMiterLimit = 5F;
                result.StrokeThickness = 3F;
                return result;
            }

            // The root of the composition.
            ContainerVisual Root()
            {
                if (_root != null) { return _root; }
                var result = _root = _c.CreateContainerVisual();
                var propertySet = result.Properties;
                propertySet.InsertScalar("Progress", 0F);
                // Layer aggregator
                result.Children.InsertAtTop(ShapeVisual_0());
                return result;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_0()
            {
                return (_cubicBezierEasingFunction_0 == null)
                    ? _cubicBezierEasingFunction_0 = _c.CreateCubicBezierEasingFunction(new Vector2(0.166999996F, 0.166999996F), new Vector2(0.833000004F, 0.833000004F))
                    : _cubicBezierEasingFunction_0;
            }

            // - Layer aggregator
            // Rotation
            ScalarKeyFrameAnimation RotationAngleInDegreesScalarAnimation_0_to_3240()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 0F, HoldThenStepEasingFunction());
                // Frame 140.
                result.InsertKeyFrame(1F, 3240F, CubicBezierEasingFunction_0());
                return result;
            }

            // - - - Layer aggregator
            // - ShapeGroup: Groupe 1 Offset:<18, 10.75>
            // TrimStart
            ScalarKeyFrameAnimation TrimStartScalarAnimation_0_to_0()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 0F, HoldThenStepEasingFunction());
                // Frame 35.
                result.InsertKeyFrame(0.25F, 0.949999988F, CubicBezierEasingFunction_0());
                // Frame 70.
                result.InsertKeyFrame(0.5F, 0F, CubicBezierEasingFunction_0());
                // Frame 105.
                result.InsertKeyFrame(0.75F, 0.949999988F, CubicBezierEasingFunction_0());
                // Frame 140.
                result.InsertKeyFrame(1F, 0F, CubicBezierEasingFunction_0());
                return result;
            }

            // Layer aggregator
            ShapeVisual ShapeVisual_0()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(36F, 36F);
                var shapes = result.Shapes;
                // ShapeGroup: Groupe 1 Offset:<18, 18>
                shapes.Add(SpriteShape_0());
                shapes.Add(ContainerShape());
                return result;
            }

            StepEasingFunction HoldThenStepEasingFunction()
            {
                if (_holdThenStepEasingFunction != null) { return _holdThenStepEasingFunction; }
                var result = _holdThenStepEasingFunction = _c.CreateStepEasingFunction();
                result.IsFinalStepSingleFrame = true;
                return result;
            }

            internal ProgressRingIntdeterminate_AnimatedVisual(
                Compositor compositor,
                CompositionPropertySet themeProperties
                )
            {
                _c = compositor;
                _themeProperties = themeProperties;
                _reusableExpressionAnimation = compositor.CreateExpressionAnimation();
                Root();
            }

            public Visual RootVisual => _root;
            public TimeSpan Duration => TimeSpan.FromTicks(c_durationTicks);
            public Vector2 Size => new Vector2(36F, 36F);
            void IDisposable.Dispose() => _root?.Dispose();

            public void CreateAnimations()
            {
                _containerShape.StartAnimation("RotationAngleInDegrees", RotationAngleInDegreesScalarAnimation_0_to_3240(), AnimationController_1());
                _pathGeometry_1.StartAnimation("TrimStart", TrimStartScalarAnimation_0_to_0(), AnimationController_0());
            }

            public void DestroyAnimations()
            {
                _containerShape.StopAnimation("RotationAngleInDegrees");
                _pathGeometry_1.StopAnimation("TrimStart");
            }

        }
    }
}
