name: Update UWP Generated Branch

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency: 
  group: ${{github.workflow}} - ${{github.ref}}
  cancel-in-progress: true
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  UnoCheck_Version: '1.27.0-dev.8'

jobs:
  build:
    if: github.repository == 'unoplatform/uno'
    name: update-uwp-branch
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      with:
        fetch-depth: 0

    - name: Pin .NET Version
      run: |
        cp build/ci/net9/global.json global.json

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@3447fd6a9f9e57506b15f895c5b76d3b197dc7c2 # v3
      with:
        global-json-file: global.json
      env:
        DOTNET_INSTALL_DIR: ${{ runner.temp }}\dotnet
        DOTNET_ROOT: ${{ runner.temp }}\dotnet


    - name: Setup GitVersion
      uses: gittools/actions/gitversion/setup@31b3198b2de324472547fecec2c0f721b70c38e2 # v0.9.15
      with:
        versionSpec: '5.10.3'

    - name: GitVersion
      id: gitversion
      uses: gittools/actions/gitversion/execute@31b3198b2de324472547fecec2c0f721b70c38e2 # v0.9.15
      with:
        useConfigFile: true
        configFilePath: gitversion.yml

    - name: setup git username
      run: git config user.name "GitHub Actions Bot"

    - name: Setup git email
      run: git config user.email "<>"

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@34cfbaee7f672c76950673338facd8a73f637506 # v1.1

    - run: echo "JAVA_HOME=$env:JAVA_HOME_11_X64" >> $env:GITHUB_ENV
      name: Select JDK 11 (Java home)

    - run: echo "JavaSdkDirectory=$env:JAVA_HOME_11_X64" >> $env:GITHUB_ENV
      name: Select JDK 11 (Java sdk directory)

    - run: |
        & dotnet tool update --global uno.check --version $env:UnoCheck_Version --add-source https://api.nuget.org/v3/index.json
      name: Install Uno Check
    - run: | 
        & uno-check -v --ci --non-interactive --fix --skip androidemulator --skip xcode --skip gtk3 --skip vswin --skip vsmac --pre-major
      name: Run uno-check

    - name: Convert source tree to UWP
      run: |
        cd $env:GITHUB_WORKSPACE\src\Uno.WinUIRevert
        dotnet run "$env:GITHUB_WORKSPACE"

    - name: Workloads list
      run: |
        dotnet workload list

    - name: Run API Sync Tool
      run: |
        cd $env:GITHUB_WORKSPACE\build
        msbuild Uno.UI.Build.csproj /v:m "/p:CombinedConfiguration=Release|AnyCPU" /m /t:RunAPISyncTool /bl:$env:GITHUB_WORKSPACE\artifacts-logs\msbuild.binlog

    - name: Turn script debugging on
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      run: Set-PSDebug -Trace 1
    
    - name: Stage all new/changed files
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      run: git add .

    - name: Commit to repository
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      run: git commit -a -m "Update UWP Autoconvert from $env:GITHUB_SHA"
    - name: Push to repository
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      run: git push origin $env:GITHUB_REF_NAME`:generated/$env:GITHUB_REF_NAME/uwp-autoconvert -f

    - name: Upload Logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: logs
        path: .\artifacts-logs
