global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using Windows.UI.Xaml;
global using Windows.UI.Xaml.Controls;
global using Windows.UI.Xaml.Media;
global using Windows.UI.Xaml.Navigation;
global using System;
global using System.Collections.Generic;
global using System.Collections.Immutable;
global using System.Linq;
global using System.Net.Http;
global using System.Threading;
global using System.Threading.Tasks;
global using Windows.ApplicationModel;
global using Application = Windows.UI.Xaml.Application;
global using ApplicationExecutionState = Windows.ApplicationModel.Activation.ApplicationExecutionState;
